### ISSUE TITLE
通过TextInfo设置标题 、确定、 取消按钮不加粗 不生效

### ISSUE THREAD

**Issue by sceneren** [kongzue/DialogX#1]
1、通过TextInfo设置标题 、确定、 取消按钮不加粗 不生效，
2、MessageDialog.show(null,"内容,"确定","取消")
内容顶到dialog的顶部去了，
3、无法设置MessageDialog标题和内容的边距
4、其他style能否上传到jcenter，通过gradle来引用

**Comment by kongzue** [comment]
回复：

**Comment by kongzue** [comment]
回复：
1.Material主题风格的标题、按钮本身就是粗体的；

**Comment by kongzue** [comment]
回复：
1.Material主题风格的标题、按钮本身就是粗体的；
2.布局结构限制，此次布局结构是参考了原生的布局实现，确实存在此问题。
3.不支持此功能，如果需要，可以手动制作自定义主题，稍后会更新主题制作教程。
4.jC审核不通过，做不到。

**Comment by kongzue** [comment]
关于第二条其实还有一个原因是，如果用户选择完全自定义布局的情况下，若上方存在边距也是一个问题，所以当设置标题为null时是会直接去掉标题布局的可见性，而顶部也不会设置额外的边距

**Comment by sceneren** [comment]
1、jcenter 审核不过，可以添加你自己的地址到repositories，类似：https://dl.bintray.com/xxx/maven,手动引用aar确实太不方便了。
2、关于粗体问题，我使用的是ios样式，我看了下代码，是你在MessageDialog里面写死了

**Comment by kongzue** [comment]
回复：
1.主要问题发生在DialogX已经使用了地址：https://github.com/kongzue/DialogX/ ，而其他主题再使用此地址无法通过审核；
2.MessageDialog.java的228-231行设置了粗体，但TextInfo是在refreshView()方法的403-407行才会生效，后者的优先级是大于前者的。

**Comment by sceneren** [comment]
你直接推到bintray就行了啊，然后配置 https://dl.bintray.com/myzchh/maven 不就能引用了吗？不同步到jcenter 就不需要审核的

**Comment by kongzue** [comment]
这样的话需要额外配置maven库地址，还是挺麻烦...我会考虑的

**Comment by kongzue** [comment]
通过maven仓库引入/更新主题方式已经支持，请查阅文档：https://github.com/kongzue/DialogX/wiki/%E4%BD%BF%E7%94%A8%E5%85%B6%E4%BB%96-DialogX%E4%B8%BB%E9%A2%98

**Comment by kongzue** [comment]
暂时关闭此问题，如有疑问可以继续留言
