### ISSUE TITLE
InputDialog弹出键盘遮挡的问题

### ISSUE THREAD

**Issue by StoneCodingg** [kongzue/DialogX#101]
下载Demo，选择 window 和 DialogFragment 模式弹出输入对话框，会出现遮挡的问题，点击旁边位置也无法关闭Dialog，输入法会关闭，而Dilaog会升高位置。Demo中的View模式未出现此现象，但是我按照Demo和wiki接入后（AndroidManifest.xml 中windowSoftInputMode/configChanges和Demo保持一致），在view模式下弹出输入对话框也会出现遮挡的问题。

测试机： Mi Note 3
系统版本：MiUI 10.3
android版本：8.1

![screenshot1](https://user-images.githubusercontent.com/18752810/130460058-aba64f41-0377-495b-ac34-89718935db19.png)
![screenshot2](https://user-images.githubusercontent.com/18752810/130460096-a9e8f737-043a-4038-9934-f2d1f9c5599a.png)
![screenshot3](https://user-images.githubusercontent.com/18752810/130460145-29780e48-6f08-4a02-a50e-053787dcb689.png)

**Comment by kongzue** [comment]
您好，不清楚您的设备系统是否存在无视 Activity 的 windowSoftInputMode=adjustResize 的情况，这可能是由厂商定制系统或输入法键盘引发的，因为我未能在标准 AOSP 以及测试设备 Pixel5 上复现此问题。
请告知您的系统版本以便于我进行更详细的测试。
DialogX 默认使用“非安全区”适配方案，即当输入法弹出时，且当前 Activity 允许按照 adjustResize 进行界面高度的调整，那么输入法弹出高度会被算作底部非安全区，这意味着软件内的“安全区”高度将被上移并缩小，此时 DialogX 将会对对话框上移并调整为合适的位置，以下是在 Pixel5(Android 12)上的测试截图：
![Pixel5(Android 12)上的测试截图](https://user-images.githubusercontent.com/10115359/130774361-d494755d-043e-4efa-aebd-844bd114ec97.png)

**Comment by StoneCodingg** [comment]
感谢您抽出时间对问题耐心的排查。
目前我也测试了多款真机测试机都未出现此种情况，只有在 Mi Note 3 8.1上出现此问题。
下载 Demo 运行问题依旧，查看系统和Demo的log输出也并未查看出有用的信息。
暂时关闭此Issues。
