### ISSUE TITLE
dialog的位置问题

### ISSUE THREAD

**Issue by wzg-githome** [kongzue/DialogX#104]
我在Android 9的pda设备使用了您的dialogX,出现了一个问题（其他设备没有出现问题，比如手机）：
dialog和软件盘的冲突问题，键盘显示dialog会上移，但是隐藏键盘dialog不会回到原来的位置。

**Comment by kongzue** [comment]
请尝试运行Demo看是否能复现此问题，若可以请告诉我，若不可以请参考[常见问题](https://github.com/kongzue/DialogX/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)

**Comment by kongzue** [comment]
长时间未收到回复，暂时关闭此问题，如有疑问请继续回复
