### ISSUE TITLE
androidx.appcompat:appcompat:1.2.0+ 获取不到

### ISSUE THREAD

**Issue by shooe** [kongzue/DialogX#105]
![微信截图_20210831193224](https://user-images.githubusercontent.com/13506395/131495328-dd2315d7-fe41-468f-8093-0be2f8c6f058.png)

Downloade工程到本地修改版本号就可以了，不知道是什么原因。昨天还好着
![微信截图_20210831193317](https://user-images.githubusercontent.com/13506395/131495456-cef7328d-8ded-4b74-8e84-c1e72896038c.png)

**Comment by kongzue** [comment]
暂时关闭此问题，如有疑问请继续回复
