### ISSUE TITLE
空指针

### ISSUE THREAD

**Issue by MikeVoy** [kongzue/DialogX#106]
bugly上报的日志 不太清楚具体如何复现的
Attempt to invoke virtual method 'android.content.res.Resources android.content.Context.getResources()' on a null object reference
android.view.animation.AnimationUtils.loadAnimation(AnimationUtils.java:155)
com.kongzue.dialogx.dialogs.WaitDialog$DialogImpl$4.run(WaitDialog.java:466)
android.os.Handler.handleCallback(Handler.java:883)
android.os.Handler.dispatchMessage(Handler.java:100)
android.os.Looper.loop(Looper.java:230)
android.app.ActivityThread.main(ActivityThread.java:7991)
java.lang.reflect.Method.invoke(Native Method)
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:526)
com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1034)

版本0.0.42
请问有什么方法可以尽量规避这种问题吗

**Comment by kongzue** [comment]
请更新最新版本后再试

**Comment by MikeVoy** [comment]
使用了  0.0.43.beta7 版本还是会上报这个错误

**Comment by MikeVoy** [comment]
Attempt to invoke virtual method 'android.view.View android.view.View.findViewById(int)' on a null object reference
com.kongzue.dialogx.dialogs.WaitDialog$DialogImpl.lazyCreate(WaitDialog.java:259)  还有这个错误,我感觉我的使用应该是正常的,之前还用过你的v3也没报过这种错(枯了

**Comment by kongzue** [comment]
V3和DialogX是完全不同的两个体系，DialogX是重做的

**Comment by kongzue** [comment]
您上下所描述的错误日志看起来是完全不同的两个错误

**Comment by kongzue** [comment]
在使用前，是否有完成初始化操作？

**Comment by MikeVoy** [comment]
是的,因为是线上抓到的我这边也复现不出来,所以挺疑惑的,  初始化已经在application里很靠前了

**Comment by kongzue** [comment]
目前能观察到的，在未进行使用自定义主题的情况下，只可能出现因为 [BaseDialog(311)](https://github.com/kongzue/DialogX/blob/0d7a1e41c7b08787591bae7eb9caa06502aaff68/DialogX/src/main/java/com/kongzue/dialogx/interfaces/BaseDialog.java#L311) 中， context 为空导致无法初始化主题的情况发生，请尽量确保 DialogX 完成初始化，就不会存在此问题了

**Comment by kongzue** [comment]
两个问题原因类似，都是 context 为空了

**Comment by kongzue** [comment]
但是正常情况下，DialogX会使用init的context.getApplicationContext，然后使用 ActivityLifecycleImpl 注册Application的ActivityLifecycleCallbacks获取当前最新Activity显示对话框操作。但为了避免内存泄漏，DialogX使用弱引用来关联Activity
会导致这里为空的原因猜测为系统进行了额外的gc导致context被回收，若此问题频繁出现且您能确保 activity 是非空的，此时建议使用:
```
WaitDialog.show(activity, "message");
```

**Comment by kongzue** [comment]
针对上述问题我会做额外处理避免因此导致崩溃，但很可能出现 WaitDialog 在这种异常状态下无法启动的情况。

**Comment by MikeVoy** [comment]
好,我这边先加上当前activity的引用

**Comment by kongzue** [comment]
已在最新版本修复此问题。0.0.43.beta10
