### ISSUE TITLE
BottomMenu在自定义视图中无法正常滑动

### ISSUE THREAD

**Issue by HelloJerryC** [kongzue/DialogX#107]
#68 你好，发现该问题在0.0.41.beta1版本得到修复，不过在0.0.43.beta8和0.0.42版本中又复现了该问题。

**Comment by HelloJerryC** [comment]
BottomMenu在自定义视图如设置多项（测试用的10项）以上，则会出现不能正常滑动。

**Comment by kongzue** [comment]
可以提供测试用例代码么，暂时未能明确原因

**Comment by HelloJerryC** [comment]
`
// init dialogx
DialogX.init(app);
DialogX.implIMPLMode= DialogX.IMPL_MODE.VIEW;
DialogX.globalTheme = DialogX.THEME.LIGHT;
DialogX.globalStyle = MIUIStyle.style();
DialogX.onlyOnePopTip = false;
`

`
BottomMenu bottomMenu = BottomMenu.build()
                .setMenuList(new String[]{"添加", "查看", "编辑", "删除", "分享", "评论", "下载", "收藏", "赞！", "不喜欢", "所属专辑", "复制链接", "类似推荐"})
                .setOnMenuItemClickListener(new OnMenuItemClickListener<BottomMenu>() {
                    @Override
                    public boolean onClick(BottomMenu dialog, CharSequence text, int index) {
                        return false;
                    }
                }).setCancelButton("关闭");
bottomMenu.show();
`

**Comment by HelloJerryC** [comment]
// Dialog
        DialogX.init(app);
        DialogX.implIMPLMode= DialogX.IMPL_MODE.VIEW;
        DialogX.globalTheme = DialogX.THEME.LIGHT;
        DialogX.globalStyle = MIUIStyle.style();
        DialogX.onlyOnePopTip = false;

**Comment by HelloJerryC** [comment]
> 可以提供测试用例代码么，暂时未能明确原因

// init dialogx
DialogX.init(app);
DialogX.implIMPLMode= DialogX.IMPL_MODE.VIEW;
DialogX.globalTheme = DialogX.THEME.LIGHT;
DialogX.globalStyle = MIUIStyle.style();
DialogX.onlyOnePopTip = false;

// bottom menu
BottomMenu bottomMenu = BottomMenu.build()
        .setMenuList(new String[]{"添加", "查看", "编辑", "删除", "分享", "评论", "下载", "收藏", "赞！", "不喜欢", "所属专辑", "复制链接", "类似推荐"})
        .setOnMenuItemClickListener(new OnMenuItemClickListener<BottomMenu>() {
            @Override
            public boolean onClick(BottomMenu dialog, CharSequence text, int index) {
                return false;
            }
        }).setCancelButton("关闭");
bottomMenu.show();

**Comment by HelloJerryC** [comment]
Theme在Material的情况下没问题，MIUI就会出现这个问题了

**Comment by kongzue** [comment]
收到，已确认问题原因，将在下一个版本修复

**Comment by kongzue** [comment]
请更新至版本：[0.0.43.beta11](https://github.com/kongzue/DialogX/releases/tag/0.0.43.beta11)

**Comment by HelloJerryC** [comment]
已解决，Good Job!!
