### ISSUE TITLE
WaitDialog会被DialogFragment遮挡

### ISSUE THREAD

**Issue by wjsir** [kongzue/DialogX#108]
首先展示了一个DialogFragment，在DialogFragment中有一个按钮会展示一个WaitDialog，但是WaitDialog展示之后被DialogFragment遮挡了，有什么解决方法吗？

**Comment by kongzue** [comment]
这事正常的，DialogX默认使用View方式构建对话框，个人建议使用CustomDialog或其他组件替代DialogFragment实现。

**Comment by wjsir** [comment]
> 这事正常的，DialogX默认使用View方式构建对话框，个人建议使用CustomDialog或其他组件替代DialogFragment实现。

好的，感谢🌹
