### ISSUE TITLE
0.0.43.beta10版本拉取不了

### ISSUE THREAD

**Issue by whosmyqueen** [kongzue/DialogX#109]
![Uploading image.png…]()

**Comment by kongzue** [comment]
请检查您的网络。
您可以在这里查看 jitpack 的版本信息：https://jitpack.io/#kongzue/DialogX/0.0.43.beta10
您可以在这里直接下载 aar 包文件：https://jitpack.io/com/github/kongzue/DialogX/DialogX/0.0.43.beta10/DialogX-0.0.43.beta10.aar
编译日志：https://jitpack.io/com/github/kongzue/DialogX/0.0.43.beta10/build.log
对应的主题文件：
com/github/kongzue/DialogX/DialogXMIUIStyle/0.0.43.beta10/DialogXMIUIStyle-0.0.43.beta10.aar
com/github/kongzue/DialogX/DialogXIOSStyle/0.0.43.beta10/DialogXIOSStyle-0.0.43.beta10.aar
com/github/kongzue/DialogX/DialogXKongzueStyle/0.0.43.beta10/DialogXKongzueStyle-0.0.43.beta10.aar
