### ISSUE TITLE
waitdialog单例模式会出现dismiss不调问题

### ISSUE THREAD

**Issue by whosmyqueen** [kongzue/DialogX#110]

**Comment by kongzue** [comment]
不理解您的意思

**Comment by whosmyqueen** [comment]
<img width="384" alt="image" src="https://user-images.githubusercontent.com/14005139/132821027-bec81207-a3d9-423d-a1fa-f6e076784af9.png">
这个没有做线程安全处理，多线程操作会出现问题

**Comment by whosmyqueen** [comment]
@kongzue

**Comment by kongzue** [comment]
运行会在主线程进行，请勿担心这里

**Comment by whosmyqueen** [comment]
我这边试了下，网络请求完成后，调用dismiss，等待框未隐藏。但打断点的话，就会隐藏

**Comment by kongzue** [comment]
好的，下一版会换成CopyOnWriteArrayList

**Comment by whosmyqueen** [comment]
我看底层是用的CopyOnWriteArrayList，目前没排查出问题，一会重新跟进看下

**Comment by kongzue** [comment]
暂时关闭了此问题，如有需要请继续留言回复。
