### ISSUE TITLE
CustomDialog返回键事件穿透

### ISSUE THREAD

**Issue by wjsir** [kongzue/DialogX#112]
版本：0.43.beta11
在显示一个CustomDialog的情况下，再弹出一个WaitDialog，WaitDialog执行dismiss之后，再按返回键时CustomDialog不会消失，返回事件传递到了上一层。
推测应该是View实现方式监听返回是使用View.addKeyListener()，所以会出现这个问题。
请问有什么解决办法吗？

**Comment by kongzue** [comment]
mark，待验证

**Comment by kongzue** [comment]
请更新至最新版本：[0.0.43.beta12](https://jitpack.io/#kongzue/DialogX/0.0.43.beta12)，已修复此问题

**Comment by wjsir** [comment]
> 请更新至最新版本：[0.0.43.beta12](https://jitpack.io/#kongzue/DialogX/0.0.43.beta12)，已修复此问题

好的，感谢🌹
