### ISSUE TITLE
 Failed to transform DialogX-0.0.43.beta11-0.0.43.beta11.jar (com.github.kongzue.DialogX:DialogX:0.0.43.beta11) to match attributes

### ISSUE THREAD

**Issue by cikichen** [kongzue/DialogX#113]
https://jitpack.io/com/github/kongzue/DialogX/DialogX/0.0.43.beta11/DialogX-0.0.43.beta11-0.0.43.beta11.jar

not found

**Comment by cikichen** [comment]
文档得更新了，最新的
implementation 'com.github.kongzue:dialogx:0.0.43.beta11'
替换
implementation 'com.github.kongzue.DialogX:DialogX:0.0.43.beta11'

**Comment by cikichen** [comment]
DialogX?Style样式的路径也变了，但是我没找到具体地址，现在都无法拉取到。
因为AS的缓存问题，用老版本的别更新版本没问题，但是一旦版本更新出现问题就会导致旧版本也失效

**Comment by kongzue** [comment]
目前wiki文档是正常的
![image](https://user-images.githubusercontent.com/10115359/133192409-f69e73c1-4fba-4da6-b588-8f88b623663b.png)
麻烦问下，是哪个页面还有疏漏

**Comment by cikichen** [comment]
> 目前wiki文档是正常的
> ![image](https://user-images.githubusercontent.com/10115359/133192449-9b668d57-50a7-4a5e-9cff-3ec48ac2a298.png)
> 麻烦问下，是哪个页面还有疏漏

Could not find com.github.kongzue.DialogX:DialogXMIUIStyle:0.0.43.

**Comment by kongzue** [comment]
请前往jitpack查看具体仓库内容：
https://jitpack.io/#kongzue/DialogX/0.0.43.beta12
