### ISSUE TITLE
Dialog3、DialogX连点创建多个Dialog对象问题

### ISSUE THREAD

**Issue by EarlJiRH** [kongzue/DialogX#114]
Dialog3和DialogX的演示的时候如果Dialog创建的动画时间比较长，页面上创建dialog的逻辑方法被多次重复执行(控件连点),页面就会弹出多个Dialog层，如果仅仅使用一个dialog去接收每次创建的Dialog，又会导致之前弹出的Dialog的自定义代码逻辑失效，但是BaseDialog中也没有准确的方法判断当前Dialog的实例对象是否已经显示过了，导致目前仅仅只能在dialog.show()之前先执行一次dialog.doDissmiss() 交互效果比较差。

**Comment by kongzue** [comment]
请使用防连点的方式处理Click事件，此问题并非DialogX的bug。
