### ISSUE TITLE
DialogX.Theme 在WaitDialog中的错误

### ISSUE THREAD

**Issue by Dormxb** [kongzue/DialogX#116]
WaitDialog的DialogX.Theme颜色显示LIGHT与DARK相反，希望修复一下

**Comment by Dormxb** [comment]
WaitDialog的 refreshView()方法，在410行

**Comment by kongzue** [comment]
这并不是bug，就是这样设计的，历代kongzueDialog均是亮色模式下WaitDialog为黑色显示
________________________________
发件人: Solitarily ***@***.***>
发送时间: Saturday, September 18, 2021 4:38:20 PM
收件人: kongzue/DialogX ***@***.***>
抄送: Subscribed ***@***.***>
主题: Re: [kongzue/DialogX] DialogX.Theme 在WaitDialog中的错误 (#116)


WaitDialog的 refreshView()方法，在410行

―

**Comment by kongzue** [comment]
你可以通过设置修改它![image](https://user-images.githubusercontent.com/10115359/133917668-9ad20ccd-8264-4dc5-a9a9-59888e29e581.png)

具体请查看wiki

**Comment by Dormxb** [comment]
ok，了解了，感谢
