### ISSUE TITLE
对话框点击取消确定偶尔会跳动（重复显示后消失）

### ISSUE THREAD

**Issue by Er-Dong-Chen** [kongzue/DialogX#120]

**Comment by kongzue** [comment]
未能复现你所描述的问题，请尝试最新Demo，若遇到相同现象，请告知你的设备机型及Android版本，若无法复现，请检查是否使用最新版本或参阅常见问题。

**Comment by whosmyqueen** [comment]
我这边也会偶尔出现，鸿蒙2.0系统

**Comment by kongzue** [comment]
@1291862631 @Er-Dong-Chen 是否有在Demo中测试能否复现？

**Comment by kongzue** [comment]
长时间未收到回复，暂时关闭了此问题，若有疑问请继续回复。
