### ISSUE TITLE
输入对话框怎么更改下面线的颜色

### ISSUE THREAD

**Issue by Er-Dong-Chen** [kongzue/DialogX#121]

**Comment by kongzue** [comment]
请参阅 [Wiki](https://github.com/kongzue/DialogX/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98#q%E5%A6%82%E4%BD%95%E4%BF%AE%E6%94%B9%E8%BE%93%E5%85%A5%E6%A1%86%E5%85%89%E6%A0%87%E9%A2%9C%E8%89%B2)

**Comment by Er-Dong-Chen** [comment]
demo就有设置Wiki里的 但那个好像是设置光标颜色吧
![image](https://user-images.githubusercontent.com/49261544/134631966-a8cf3ee5-f53e-4d03-921f-a03bdec1d7d7.png)

**Comment by kongzue** [comment]
刚刚查了下代码，为避免冲突，DialogX修改了默认使用的style，请在你的values/styles.xml添加以下代码：
```
<style name="DialogXCompatThemeLight" parent="Theme.AppCompat.Light.NoActionBar">
    <item name="colorPrimary">@color/colorPrimary</item>
    <item name="colorPrimaryDark">@color/colorPrimaryDark</item>
    <item name="colorAccent">@color/colorAccent</item>
</style>

<style name="DialogXCompatThemeDark" parent="Theme.AppCompat.NoActionBar">
    <item name="colorPrimary">@color/colorPrimary</item>
    <item name="colorPrimaryDark">@color/colorPrimaryDark</item>
    <item name="colorAccent">@color/colorAccent</item>
</style>
```
其中设置颜色colorAccent即可。

**Comment by kongzue** [comment]
经过测试，颜色可以正常修改。
![test](https://user-images.githubusercontent.com/10115359/134799708-00f57630-baa0-4f80-a5b2-f756c3440158.jpg)
DialogX默认Material主题使用的是系统标准的AppCompatEditText组件，其颜色由Google定义根据style的colorAccent配置显示

**Comment by kongzue** [comment]
暂时关闭了此问题，如有需要请继续留言回复。
