### ISSUE TITLE
PopTip不支持主题切换吗？

### ISSUE THREAD

**Issue by Er-Dong-Chen** [kongzue/DialogX#122]

**Comment by kongzue** [comment]
请参阅 Wiki。
![](https://user-images.githubusercontent.com/10115359/134511488-34e182c1-f572-43c1-b054-4c8957df255a.jpg)

**Comment by Er-Dong-Chen** [comment]
那个时候用demo时不管怎么切换轻消息提示一直都是白色的 可能是我总是在亮色主题点击的吧

**Comment by kongzue** [comment]
未能在最新的Demo中复现您所描述的问题。

**Comment by kongzue** [comment]
暂时关闭了此问题，如有需要请继续留言回复。
