### ISSUE TITLE
iOS的轻提示点击多个时消失会有点问题

### ISSUE THREAD

**Issue by Er-Dong-Chen** [kongzue/DialogX#123]
![image](https://user-images.githubusercontent.com/49261544/134631580-37ba9f34-c126-40b2-93ec-e63c4a674e74.png)

**Comment by kongzue** [comment]
请不要这样做。默认情况下（DialogX.onlyOnePopTip = false）时，PopTip会按照现实新的自动位移旧的来保证所有提示都可以正常显示，若您有频繁修改显示内容的需要，可以设置`DialogX.onlyOnePopTip = true`即显示下一个时自动销毁之前的，或者在PopTip显示时获得其对象，使用：
```
PopTip popTip =  PopTip.show("点击确定按钮");
popTip.setMessage(...);
```
这样来修改内容。

**Comment by kongzue** [comment]
此问题已在 0.0.43.beta15 版本修复。
