### ISSUE TITLE
null object reference

### ISSUE THREAD

**Issue by MikeVoy** [kongzue/DialogX#125]
更新了
com.github.kongzue.DialogX:DialogX:0.0.43.beta10  
的版本线上还是偶发报空指针 java.lang.NullPointerException
Attempt to invoke virtual method 'android.content.res.Resources android.content.Context.getResources()' on a null object reference com.kongzue.dialogx.dialogs.WaitDialog$DialogImpl$4.run(WaitDialog.java:466)
流程就是 照片或者视频回调到此页面 --上传--压缩进度弹窗--上传进度弹窗
可能是因为带进度引起的?  
之前说的尝试加入此页面activity引用就不能更新进度了

**Comment by kongzue** [comment]
请确认您是否使用最新的测试版本0.0.43.beta12。
在早前已对这里进行修改，当前最新版本代码 [WaitDialog.java:466](https://github.com/kongzue/DialogX/blob/514886755e0d55e92af825bd1f9e129812174f3e/DialogX/src/main/java/com/kongzue/dialogx/dialogs/WaitDialog.java#L466) 已无类似逻辑。

在 WaitDialog.java:465 已经对 context 为空进行了处理。
