### ISSUE TITLE
Maven Central Style无法使用

### ISSUE THREAD

**Issue by qiushui95** [kongzue/DialogX#13]
![image](https://user-images.githubusercontent.com/22932494/108335400-dc3c1b00-720d-11eb-862f-0307b3937644.png)
 未指定依赖版本

**Comment by kongzue** [comment]
Maven Central这边暂时还没完全搞定依赖问题，先暂时用jCenter的源吧，修复好后会发一个新版本出来

**Comment by kongzue** [comment]
暂时去掉了Maven Central 源，目前正在寻找其他解决方案
