### ISSUE TITLE
在我自己创建的dialog基础上启动BottomMenu，BottomMenu会被我的dialog覆盖遮挡

### ISSUE THREAD

**Issue by WuZ3** [kongzue/DialogX#133]
在我启动了自己创建的dialog的基础上再创建BottomMenu，BottomMenu是在我创建的dialog的后面启动的，也就是被我创建的dialog覆盖了，要把我创建的dialog关闭了才能看见BottomMenu，请问这个问题如何解决

**Comment by kongzue** [comment]
此问题暂时关闭，若有疑问请继续留言
