### ISSUE TITLE
BottomDialog样式问题

### ISSUE THREAD

**Issue by coolyunyun** [kongzue/DialogX#135]
BottomDialog除了IOS样式（但IOS样式两边并不撑满屏幕），其他样式标题栏的文字 并不是居中，上下不对称，希望能改成居中，否则影响美观，谢谢。

**Comment by coolyunyun** [comment]
MaterialStyle 样式由于有个小点看上去还比较对撑，但需求是不能进行下滑关闭，所以只能采用MIUIStyle，但标题栏文字并未居中

**Comment by kongzue** [comment]
您好，为避免已上线的产品出现差异，现有主题样式不会进行修改，要自定义样式，请参阅[Wiki](https://github.com/kongzue/DialogX/wiki)

**Comment by kongzue** [comment]
![image](https://user-images.githubusercontent.com/10115359/140287424-954f0491-97cb-42b5-b30b-d55864c48d68.png)
![image](https://user-images.githubusercontent.com/10115359/140287447-16cf1526-9c74-4f07-bc31-5b8a72f41275.png)
![image](https://user-images.githubusercontent.com/10115359/140287519-3255ed73-2e13-47ee-9a8d-a733ed01481d.png)
