### ISSUE TITLE
BottomDialog样式问题

### ISSUE THREAD

**Issue by coolyunyun** [kongzue/DialogX#136]
BottomDialog除了IOS样式（但IOS样式两边并不撑满屏幕），其他样式标题栏的文字 并不是居中，上下不对称，希望能改成居中，否则影响美观，谢谢。

如下图：

<a href="https://sm.ms/image/19qdIoak2c5UV6l" target="_blank"><img src="https://i.loli.net/2021/11/04/19qdIoak2c5UV6l.png" ></a>

代码：
 BottomDialog.build().setStyle(MIUIStyle.style()).setBackgroundColor(Color.RED).setCustomView(...).show();

会莫名多出一块红色区域，即使采用自定义标题栏也无法消除，白色区域是我自定义的view，红色区域是多出来的，请问这块区域如何消除。   望作者大大能优化下。

**Comment by coolyunyun** [comment]
我是自定义布局，没传入tilte,和内容信息，直接显示自定义布局，会多出一块区域。MIUIStyle和KongzueStyle都有这问题

**Comment by coolyunyun** [comment]
期望：不显示红色区域，因为没传入标题栏信息，按理说自定义布局就撑满了BottomDialog

**Comment by coolyunyun** [comment]
猜测：layout_dialogx_bottom_material.xml  自定义布局的时候  哪个控件没隐藏掉或padding magin之类的还存在。

**Comment by kongzue** [comment]
经过检查，这是主题为了规避圆角区域设计的。
测试代码：
```
RelativeLayout.LayoutParams rLp = new RelativeLayout.LayoutParams(
        ViewGroup.LayoutParams.MATCH_PARENT,
        dip2px(200)
);
RelativeLayout relativeLayout = new RelativeLayout(me);
relativeLayout.setLayoutParams(rLp);
relativeLayout.setBackgroundColor(Color.RED);
BottomDialog.show(new OnBindView<BottomDialog>(relativeLayout) {
    @Override
    public void onBind(BottomDialog dialog, View v) {
    
    }
}).setBackgroundColor(Color.GREEN);
```
显示效果：
![image](https://user-images.githubusercontent.com/10115359/140314894-d5b72035-fd34-44ad-8c8a-14e2b079939b.png)

临时的解决方案：
```
BottomDialog.show(new OnBindView<BottomDialog>(...) {
    @Override
    public void onBind(BottomDialog dialog, View v) {
        ((ViewGroup)dialog.getDialogImpl().boxCustom.getParent().getParent().getParent())
                .setPadding(0,0,0,0);
    }
});
```
后续我会在与内测群的成员讨论后对该主题的资源进行调整。

**Comment by kongzue** [comment]
备注：DialogX中所有组件均是暴露的，你可以通过`dialog.getDialogImpl()`获取大部分组件的实例，只不过这个问题比较特殊，涉及问题的组件未设置id进行暴露，后续会对此进行修改。

**Comment by kongzue** [comment]
此问题暂时关闭，若有疑问可继续留言
