### ISSUE TITLE
kongzue无法在最上层

### ISSUE THREAD

**Issue by xfjxfj** [kongzue/DialogX#138]
自定义控件中，在我们自己弹出dialog中再次弹出kongzue。但是点击取消 发现kongzue不是在最上层，请问调用什么方法可以让kongzue在最上层。用了另外一款是可以达到效果的，但是ui达不到要求。还是希望使用kongzue

**Comment by kongzue** [comment]
请参考[常见问题](https://github.com/kongzue/DialogX/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98#qdialogx-%E6%97%A0%E6%B3%95%E8%A6%86%E7%9B%96%E5%9C%A8-dialogfragmentalertdialog-%E4%B9%8B%E4%B8%8A)
