### ISSUE TITLE
能在对话框消失前加一个回调接口

### ISSUE THREAD

**Issue by zorro0799** [kongzue/DialogX#139]
因为需要在对话框上加广告view,但这个view是static的，每次设置custom view时在onbind时把广告加上，但当对话框删除时，可能这个view也被回收了，希望在回收前先从paret view中删除，所以希望有一个地方可以做这个事

**Comment by kongzue** [comment]
不建议这样做，View不应该在任何情况下被设置为静态的。
你可以通过自定义View，重写其`onDetachedFromWindow()`方法得知View从界面上解绑的事件。
另外你也可以通过Dialog的`.setDialogLifecycleCallback(...)`方法来设置一个回调，当Dialog关闭时会触发`onDismiss()`事件

**Comment by zorro0799** [comment]
谢谢
