### ISSUE TITLE
等待＋提示对话框  返回键处理异常

### ISSUE THREAD

**Issue by qiushui95** [kongzue/DialogX#14]
将demo等待时间延长，按一次返回键，PopTip弹出，立即再按返回键，会执行返回键操作。（这个操作待讨论）。
按一次返回键，PopTip弹出，等PopTip消失再按返回键，也会执行返回键操作，这个操作估计不科学。

**Comment by kongzue** [comment]
已知问题。这个原因是因为PopTip在启动后焦点转移到了PopTip组件上，焦点对Back指令的判断至关重要，而PopTip在关闭后焦点并未自动回到WaitDialog中，因此无法拦截Back指令

________________________________
发件人: 杨朝旭 <notifications@github.com>
发送时间: Thursday, February 18, 2021 9:00:23 PM
收件人: kongzue/DialogX <DialogX@noreply.github.com>
抄送: Subscribed <subscribed@noreply.github.com>
主题: [kongzue/DialogX] 等待＋提示对话框 返回键处理异常 (#14)


将demo等待时间延长，按一次返回键，PopTip弹出，立即再按返回键，会执行返回键操作。（这个操作待讨论）。
按一次返回键，PopTip弹出，等PopTip消失再按返回键，也会执行返回键操作，这个操作估计不科学。

―

**Comment by kongzue** [comment]
此问题会在后续版本修复

________________________________
发件人: zhang chao <myzcxhh@live.cn>
发送时间: Thursday, February 18, 2021 9:17:51 PM
收件人: kongzue/DialogX <reply@reply.github.com>; kongzue/DialogX <DialogX@noreply.github.com>
抄送: Subscribed <subscribed@noreply.github.com>
主题: Re: [kongzue/DialogX] 等待＋提示对话框 返回键处理异常 (#14)

已知问题。这个原因是因为PopTip在启动后焦点转移到了PopTip组件上，焦点对Back指令的判断至关重要，而PopTip在关闭后焦点并未自动回到WaitDialog中，因此无法拦截Back指令

________________________________
发件人: 杨朝旭 <notifications@github.com>
发送时间: Thursday, February 18, 2021 9:00:23 PM
收件人: kongzue/DialogX <DialogX@noreply.github.com>
抄送: Subscribed <subscribed@noreply.github.com>
主题: [kongzue/DialogX] 等待＋提示对话框 返回键处理异常 (#14)


将demo等待时间延长，按一次返回键，PopTip弹出，立即再按返回键，会执行返回键操作。（这个操作待讨论）。
按一次返回键，PopTip弹出，等PopTip消失再按返回键，也会执行返回键操作，这个操作估计不科学。

―

**Comment by kongzue** [comment]
此问题将在0.0.31版本修复，预计1天内发版。

**Comment by qiushui95** [comment]
好的。
