### ISSUE TITLE
window、dialogfragment模式下 底部弹出框会遮盖底部导航栏

### ISSUE THREAD

**Issue by chenhao1041661180** [kongzue/DialogX#141]
![image](https://user-images.githubusercontent.com/9623182/141742613-36eb3d1f-2f67-4cf4-9a6c-d7f222b798ad.png)
![Uploading image.png…]()
大佬有时间的话可以优化下

**Comment by kongzue** [comment]
我们已经测试过大部分AOSP，从Android 5-12均未发现此问题。DialogX会根据“非安全区”自动适配底部高度，若你的设备出现问题，请告知型号及系统版本

**Comment by chenhao1041661180** [comment]
红米6Pro / Android 9 、 红米Note8Pro / Android11

**Comment by kongzue** [comment]
稍后会进行测试

**Comment by kongzue** [comment]
你好，经过测试未发现在红米6Pro上存在问题。
系统版本：MIUI12.0.1
软件版本：最新源码编译0.0.43.beta19
测试截图：
![image](https://user-images.githubusercontent.com/10115359/141747525-450a162d-d422-4256-bab7-5dc3273db657.png)
 红米Note8Pro暂时无法进行测试，等待设备空闲会进行。

**Comment by chenhao1041661180** [comment]
选Window 和Dialogfragment 方式，View的方式没问题

**Comment by kongzue** [comment]
不推荐使用其他方案，文档里也有说明，尚存在bug

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: chenhao1041661180 ***@***.***>
发送时间: Monday, November 15, 2021 4:37:45 PM
收件人: kongzue/DialogX ***@***.***>
抄送: Kongzue ***@***.***>; Comment ***@***.***>
主题: Re: [kongzue/DialogX] window、dialogfragment模式下 底部弹出框会遮盖底部导航栏 (Issue #141)


选Window 和Dialogfragment 方式，View的方式没问题

―

**Comment by chenhao1041661180** [comment]
好的

**Comment by kongzue** [comment]
暂时关闭了此问题，如有疑问请继续回复
