### ISSUE TITLE
BottomDialog 不能横向铺满屏幕，怎么调整可以呢？

### ISSUE THREAD

**Issue by feisher** [kongzue/DialogX#143]
如题

**Comment by feisher** [comment]
IOS主题下，想要IOS的MessageDialog是核心诉求

**Comment by kongzue** [comment]
很抱歉我无法复现你所描述的问题。
BottomDialog在经过测试是可以横向全屏显示的，无论在默认的Material主题下还是IOS主题下。
![image](https://user-images.githubusercontent.com/10115359/142572572-b4cc86c5-9579-4f12-9262-8f0806c705d8.png)
![image](https://user-images.githubusercontent.com/10115359/142572582-e56e6e75-5e4f-4e56-855b-2015be4852ee.png)
请检查你是否使用最新版本，或进行过一些设置，例如`DialogX.dialogMaxWidth（设置对话框最大宽度）`，详情请[参阅 Wiki](https://github.com/kongzue/DialogX/wiki)

**Comment by kongzue** [comment]
> IOS主题下，想要IOS的MessageDialog是核心诉求

无法理解这句话的意思，DialogX 在任何主题下都支持显示 MessageDialog

**Comment by kongzue** [comment]
暂时关闭了此问题，若有疑问请继续回复
