### ISSUE TITLE
activity关闭后  希望能和toast一样的效果。

### ISSUE THREAD

**Issue by coolyunyun** [kongzue/DialogX#144]
activity关闭后   PopTip会立即消失， 能否支持类似Toast一样的效果，关闭后，到时间才会自动关闭。
例如目前有一个场景：
提交成功后，进行toast提示成功并关闭页面， 目前PopTip无法满足。
有解决方案么？

**Comment by kongzue** [comment]
您好，做不到，Google现在越发的限制悬浮窗的可能，除了基于Window的需要额外用户手动开启悬浮窗权限外是没有其他办法的，PopTip是基于View制作，基于Activity进行显示，本身不支持悬浮到Activity外，如有需要可参考单Activity使用多Fragment实现子界面的方案。

**Comment by coolyunyun** [comment]
好的，谢谢

**Comment by kongzue** [comment]
暂时关闭了此问题，如有疑问可继续回复。
