### ISSUE TITLE
WaitDialog无法关闭

### ISSUE THREAD

**Issue by zhubinsheng** [kongzue/DialogX#146]
I/>>>: WaitDialog(5761b5d).show
I/>>>: WaitDialog(5761b5d).show
D/CompatibilityChangeReporter: Compat change id reported: 147798919; UID 10153; state: ENABLED
I/>>>: WaitDialog(5761b5d).dismiss
W/System: A resource failed to call close.

**Comment by kongzue** [comment]
请执行对应 WaitDialog 的 dismiss() 方法。

**Comment by zhubinsheng** [comment]
> 请执行对应 WaitDialog 的 dismiss() 方法。 未在 Demo 中发现问题。

I/>>>: WaitDialog(bce7152).show
D/ForceDarkHelper: updateByCheckExcludeList: pkg: com.cantoop.lawyer activity: com.cantoop.lawyer.ui.activity.LawyerActivity@57e625c
I/chatty: uid=11503(com.cantoop.lawyer) identical 6 lines
D/ForceDarkHelper: updateByCheckExcludeList: pkg: com.cantoop.lawyer activity: com.cantoop.lawyer.ui.activity.LawyerActivity@57e625c
I/>>>: WaitDialog(bce7152).show
请求前

W/RenderInspector: QueueBuffer time out on com.cantoop.lawyer/com.cantoop.lawyer.ui.activity.LawyerActivity, count=1, avg=17 ms, max=17 ms.
I/>>>: WaitDialog(bce7152).dismiss
I/chatty: uid=11503(com.cantoop.lawyer) identical 2 lines
I/>>>: WaitDialog(bce7152).dismiss
请求后
未关闭

**Comment by whosmyqueen** [comment]
我也出现这个问题,目前最新版本还是不行

**Comment by whosmyqueen** [comment]
可以了

**Comment by xiansenxuan** [comment]
implementation 'com.github.kongzue.DialogX:DialogX:0.0.50.beta14'
最新版这个问题又出现了 包括0.0.49

已测试0.0.47版本正常

**Comment by kongzue** [comment]
> implementation 'com.github.kongzue.DialogX:DialogX:0.0.50.beta14' 最新版这个问题又出现了 包括0.0.49
> 
> 已测试0.0.47版本正常

请尝试在 Demo 代码中是否能够复现，如果能，请提交一个新是 issues，已经关闭的 issues 不再回复。
