### ISSUE TITLE
WaitDialog.dismiss不会关闭之前打开的所有的WaitDialog吗

### ISSUE THREAD

**Issue by zhubinsheng** [kongzue/DialogX#147]
I/>>>: WaitDialog(50eb5a8).show
I/>>>: WaitDialog(9e710f6).dismiss

**Comment by zhubinsheng** [comment]
会考虑增加dismissall这样的方法吗

**Comment by kongzue** [comment]
WaitDialog 理论上是单利的，只要你启动时没有使用 activity 参数。
若你指定了 activity 启动，那么，请直接获取 WaitDialog 句柄，执行其对应的 dismiss() 方法。
例如：
```
WaitDialog wd = WaitDialog.show(...);
//...
wd.dismiss();
```

**Comment by zhubinsheng** [comment]
目前我只是简单的使用，要做到开箱即用建议增加dismissall这样的方法
