### ISSUE TITLE
CustomDialog后台弹出回到前台崩溃

### ISSUE THREAD

**Issue by kagurasansan** [kongzue/DialogX#148]
java.lang.IllegalStateException: The specified child already has a parent. You must call removeView() on the child's parent first.
--
19812-07 14:05:44.020 6504 6504 E AndroidRuntime: at android.view.ViewGroup.addViewInner(ViewGroup.java:5377)
19912-07 14:05:44.020 6504 6504 E AndroidRuntime: at android.view.ViewGroup.addView(ViewGroup.java:5192)
20012-07 14:05:44.020 6504 6504 E AndroidRuntime: at android.view.ViewGroup.addView(ViewGroup.java:5132)
20112-07 14:05:44.020 6504 6504 E AndroidRuntime: at android.view.ViewGroup.addView(ViewGroup.java:5104)
20212-07 14:05:44.020 6504 6504 E AndroidRuntime: at com.kongzue.dialogx.interfaces.BaseDialog$3.run(BaseDialog.java:162)
20312-07 14:05:44.020 6504 6504 E AndroidRuntime: at android.os.Handler.handleCallback(Handler.java:938)
20412-07 14:05:44.020 6504 6504 E AndroidRuntime: at android.os.Handler.dispatchMessage(Handler.java:99)
20512-07 14:05:44.020 6504 6504 E AndroidRuntime: at android.os.Looper.loop(Looper.java:264)
20612-07 14:05:44.020 6504 6504 E AndroidRuntime: at android.app.ActivityThread.main(ActivityThread.java:8263)
20712-07 14:05:44.020 6504 6504 E AndroidRuntime: at java.lang.reflect.Method.invoke(Native Method)
20812-07 14:05:44.020 6504 6504 E AndroidRuntime: at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:632)
20912-07 14:05:44.020 6504 6504 E AndroidRuntime: at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1049)

**Comment by kongzue** [comment]
不清楚您具体执行的代码，但这个问题会尝试性的在下一个版本修复。

**Comment by kongzue** [comment]
请尝试 0.0.44.beta3 版本，已修复此问题。

**Comment by kagurasansan** [comment]
升级了试了几次不再复现了
