### ISSUE TITLE
dialog.isShow方法无效

### ISSUE THREAD

**Issue by wohelu666** [kongzue/DialogX#149]
dialog.isShow方法无效，无法判断Messagedialog 是否已经弹出，每次都会弹出新的dialog.

**Comment by kongzue** [comment]
请确认您是对已实例化的对象执行的此方法。
范例代码：
```
MessageDialog messageDialog = MessageDialog.show("标题", "这里是正文内容。", "确定").setOkButton(new OnDialogButtonClickListener<MessageDialog>() {
    @Override
    public boolean onClick(MessageDialog baseDialog, View v) {
        PopTip.show("点击确定按钮");
        return false;
    }
});
//模拟延迟 2000 毫秒后执行
new Handler(Looper.getMainLooper()).postDelayed(new Runnable() {
    @Override
    public void run() {
        log("isShow: "+(messageDialog.isShow()));
    }
}, 2000);
```
在您每次执行`MessageDialog.show(...)` 时都是重新创建的新对象，而并不是之前启动的对话框。MessageDialog并非单例的，要对以往的对象进行判断，请自行获取其句柄，例如：`MessageDialog messageDialog = MessageDialog.show(...)`亦或者`MessageDialog messageDialog = MessageDialog.build()`

**Comment by wohelu666** [comment]
dialog = DialogUtils.showMessageDialog("提示", "已经扫描过此货物,确认重新提交吗？", "确定提交", "取消")
                dialog?.setOkButton(object : OnDialogButtonClickListener<MessageDialog> {
                    override fun onClick(baseDialog: MessageDialog?, v: View?): Boolean {
//
                        dialog = null
                        return false
                    }
                })?.setCancelButton(object : OnDialogButtonClickListener<MessageDialog> {
                    override fun onClick(baseDialog: MessageDialog?, v: View?): Boolean {
                        dialog = null
                        return false
                    }
                })?.show()

class DialogUtils {

    companion object{

        fun  showMessageDialog(title:String,message:String,okText:String,cancelText:String):MessageDialog{
            val messageDialog = MessageDialog.build().setTitle(title).setMessage(message).setOkButton(okText).setCancelButton(cancelText)
                .setButtonOrientation(LinearLayout.VERTICAL)
                .setCancelable(false)
            return messageDialog
        }
    }


}

我是这样调用的，结果判断 isShow方法每次都是false，只能自己判空操作了。

**Comment by kongzue** [comment]
在对话框未完成启动时执行isShow必然会返回false。
原因是对话框是需要在主线程执行的，DialogX之所以能允许您在异步线程启动对话框的原理是操作UI的操作会post到UI线程去执行，这个过程会需要一小段时间（通常不会被察觉）的十几毫秒，若您使用上述代码执行，那必然会是false，要监控对话框何时真正启动，请使用`setDialogLifecycleCallback(...)`来设置生命周期监听器，具体请参考wiki。

**Comment by wohelu666** [comment]
假如messageDialog 已经show 成功， 为啥isShow方法还是返回false？

**Comment by wohelu666** [comment]
如何让messageDialog 只显示一次，而不是重复显示，请提供解决方案谢谢。

**Comment by kongzue** [comment]
你所描述的情况不存在。你可以根据我第一个回复的代码进行验证


获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: wohelu666 ***@***.***>
发送时间: Wednesday, December 8, 2021 1:33:13 PM
收件人: kongzue/DialogX ***@***.***>
抄送: Kongzue ***@***.***>; Comment ***@***.***>
主题: Re: [kongzue/DialogX] dialog.isShow方法无效 (Issue #149)


假如messageDialog 已经show 成功， 为啥isShow方法还是返回false？

―

**Comment by wohelu666** [comment]
第一个代码，在messageDialog 已经show 的情况下，再去判断ishow 为true 已经毫无意义了。

**Comment by kongzue** [comment]
isShow方法代表的是当前现实状态，并不是“已经显示过了”，您需要明确清楚。若您希望直显示一次，请自行设置一个boolean标记判断

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: wohelu666 ***@***.***>
发送时间: Wednesday, December 8, 2021 1:53:37 PM
收件人: kongzue/DialogX ***@***.***>
抄送: Kongzue ***@***.***>; Comment ***@***.***>
主题: Re: [kongzue/DialogX] dialog.isShow方法无效 (Issue #149)


第一个代码，在messageDialog 已经show 的情况下，再去判断ishow 为true 已经毫无意义了。

―

**Comment by wohelu666** [comment]
好的，谢谢您的回复，希望后续能改善这个问题。

**Comment by kongzue** [comment]
这并不是个问题啊

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: wohelu666 ***@***.***>
发送时间: Wednesday, December 8, 2021 1:58:11 PM
收件人: kongzue/DialogX ***@***.***>
抄送: Kongzue ***@***.***>; Comment ***@***.***>
主题: Re: [kongzue/DialogX] dialog.isShow方法无效 (Issue #149)


好的，谢谢您的回复，希望后续能改善这个问题。

―

**Comment by wohelu666** [comment]
原生的dialog 可以根据isShowing 这样判断的，不需要自行写逻辑。

**Comment by kongzue** [comment]
但据我所知，AlertDialog在dismiss()后，isShowing也是会返回false的，这与isShow是逻辑基本一致

**Comment by kongzue** [comment]
如果您希望不要等待主线程处理，自行处理线程问题可以通过'DialogX.autoRunOnUIThread = false'来修改相关设置

**Comment by kongzue** [comment]
![image](https://user-images.githubusercontent.com/10115359/145157037-e866c8c1-18e8-40ab-80a6-76cb57cba134.png)

**Comment by wohelu666** [comment]
我讲的重点是：isShowing 会在dialog显示的时候返回为true ,在dissmiss 之后返回为false ,这个是正常的，而不是，在show之后，isshowing 依旧为 false ,这与我的业务不符。

**Comment by wohelu666** [comment]
还是谢谢的您的回复，我后面自行理解，谢谢。

**Comment by kongzue** [comment]
> 我讲的重点是：isShowing 会在dialog显示的时候返回为true ,在dissmiss 之后返回为false ,这个是正常的，而不是，在show之后，isshowing 依旧为 false ,这与我的业务不符。

请参考
![image](https://user-images.githubusercontent.com/10115359/145157702-74cce39b-3e7b-445f-acda-5b2b74af2e65.png)

**Comment by kongzue** [comment]
上边给出的方案将关闭自动在主线程运行，而是会直接执行显示，那么isShow的状态会在执行show(...)方法后立即变成true。

**Comment by kongzue** [comment]
正常情况下，执行show后，你就可以理解成对话框已经启动，不清楚您的实际业务为什么一定要对刚刚执行的流程进行判断和质疑，一般情况下DialogX并不会出现在执行了show后不启动的清空

**Comment by kongzue** [comment]
长时间未收到回复，暂时关闭了此问题，若有疑问清继续回复。
