### ISSUE TITLE
TipDialog builder模式

### ISSUE THREAD

**Issue by qiushui95** [kongzue/DialogX#15]
TipDialog 没有builder模式，只能TipDialog.show(*,*);
产生的影响，不能show（activity）;

**Comment by kongzue** [comment]
这个原因是因为WaitDialog和TipDialog为了做到能够衔接，是具备单例的特性，也就意味着内存中一次只会有一个WaitDialog在运行，因此WaitDialog和TipDialog无法预创建

________________________________
发件人: 杨朝旭 <notifications@github.com>
发送时间: Friday, February 19, 2021 8:58:02 PM
收件人: kongzue/DialogX <DialogX@noreply.github.com>
抄送: Subscribed <subscribed@noreply.github.com>
主题: [kongzue/DialogX] TipDialog builder模式 (#15)


TipDialog 没有builder模式，只能TipDialog.show(,);
产生的影响，不能show（activity）;

―

**Comment by kongzue** [comment]
此问题将在0.0.31版本修复，预计1天内发版
