### ISSUE TITLE
自定义弹窗，关闭反复显示。

### ISSUE THREAD

**Issue by 1291862631** [kongzue/DialogX#151]
自定义弹窗，点击关闭时的时候，反复点击屏幕，自定义布局对话框会重复出现

**Comment by 1291862631** [comment]
提供Demo 验证“完全自定义对话框”也有同样的问题。

**Comment by kongzue** [comment]
很抱歉，未能复现您所描述的问题。
测试步骤：在开启CustomDialog后快速重复点击遮罩区域，CustomDialog并未重复显示。
测试环境：DialogX:0.0.44.beta4；Pixel5 with Android 12；
测试录屏：

https://user-images.githubusercontent.com/10115359/145665129-f4824116-91e1-49f5-bc62-78c46da26ec3.mp4

**Comment by kongzue** [comment]
补充测试：您所描述的应该是指对话框内，通过按钮执行了 'dismiss()' 方法导致关闭过程被重复执行吧？
这个问题会在下个版本中修复。

**Comment by kongzue** [comment]
请更新至 0.0.44.beta5 版本，此问题已被修复。https://jitpack.io/#kongzue/DialogX/0.0.44.beta5

**Comment by 1291862631** [comment]
点击自定义弹窗，点击”我知道啦“然后快速重复点击屏幕，屏幕就会出现。

**Comment by kongzue** [comment]
> 点击自定义弹窗，点击”我知道啦“然后快速重复点击屏幕，屏幕就会出现。

请更新版本，在最新版本中不存在此问题

**Comment by kongzue** [comment]
长时间未收到回复，暂时关闭此问题，如有疑问可继续回复
