### ISSUE TITLE
PopMenu弹出窗口大小位置计算不准确

### ISSUE THREAD

**Issue by zorro0799** [kongzue/DialogX#152]
列表项布局最右上角有一个可点击按钮，希望点击能弹出一个菜单，这个可点按钮大小不大，点出的菜单希望左边是图标右边是文字，但实际用DialogX发现弹出的菜单就只有可点击按钮大小，只能显示部分图标，文字部分完全没有，看源码弹出菜单的大小是根据可点击View的大小确定的，这样使用的情况在手机布局上太少了，希望菜单大小能根据图标和文字计算出来，并且在手机左，右，上，下屏上能都能准确弹出(计算位置时请考虑父窗口的margin)

**Comment by kongzue** [comment]
请更新至 0.0.44.beta9 版本已修复此问题：https://github.com/kongzue/DialogX/releases

**Comment by kongzue** [comment]
已在最新版本中对PopMenu进行了完善，请参考 release 日志：https://github.com/kongzue/DialogX/releases/tag/0.0.44.beta15
