### ISSUE TITLE
PopMenu 无法设置宽度

### ISSUE THREAD

**Issue by CPC-Coder** [kongzue/DialogX#154]

**Comment by CPC-Coder** [comment]
横屏的app不友好

**Comment by CPC-Coder** [comment]
而且无法设置 文字居中

**Comment by kongzue** [comment]
请注意，PopMenu尚处于测试阶段，并未正式发布。
该组件的宽度是根据源布局宽度自动适应的，当设置`.setWidth(...)`后，是可以调整宽度的：
![image](https://user-images.githubusercontent.com/10115359/146859652-cbdc73a9-d040-47d4-944b-025b9e5afb5e.png)

**Comment by CPC-Coder** [comment]
0.0.43  设置宽度没有效果

**Comment by CPC-Coder** [comment]
这个功能使用频率还是蛮高   在activity中间显示           文字无法居中也是个麻烦

**Comment by kongzue** [comment]
> 0.0.43 设置宽度没有效果

请更新版本，我会逐步针对以往的问题进行修复。
