### ISSUE TITLE
底部自定义滑动布局 RecycleView 滑动问题

### ISSUE THREAD

**Issue by hzxlelp** [kongzue/DialogX#155]
将RecycleView的Item高度改为wrap_content或改成固定高度，将RecycleView滑动到底部，然后向下滑动RecycleView时会滑动到BottomDialog，从而关闭了BottomDialog。

**Comment by kongzue** [comment]
已列入待测试

**Comment by kongzue** [comment]
大致上能确定问题在于：RecycleView 的 layoutManager.findFirstVisibleItemPosition 在子布局设置高度为 wrap_content 时，返回恒等于0。
尚不清楚此问题是 RecycleView 的 bug 还是其他原因导致，理论上该方法应当返回当前在屏幕内首位显示的子布局的索引position，它会影响已滑动距离的计算导致 DialogX 无法正确判断已滚动的距离。

此问题暂时无法解决，它并非 DialogX 的错误。我也将继续寻找能替代解决的方案。

**Comment by kongzue** [comment]
长时间未收到回复，暂时关闭了此问题，如有疑问可继续回复。
