### ISSUE TITLE
DialogFragment中 弹出MessageDialog，显示层级在dialogFragment下面怎么处理

### ISSUE THREAD

**Issue by h-zhouwenjun** [kongzue/DialogX#156]
DialogFragment中 弹出MessageDialog，显示层级在dialogFragment下面怎么处理

**Comment by kongzue** [comment]
建议将 DialogFragment 的事务更改为 DialogX 实现。
或者使用 DialogX 的其他实现方法，方法在 [wiki 文档](https://github.com/kongzue/DialogX/wiki#%E5%AE%9E%E7%8E%B0%E6%A8%A1%E5%BC%8F)中有。但我不建议这么设置，因为其他实现方式均为测试版，依然存在 bug。
