### ISSUE TITLE
关于自定义view，并且连续显示dialog的问题

### ISSUE THREAD

**Issue by Sky0202** [kongzue/DialogX#159]
WaitDialog.show("正在登录")
                .setCustomView(object : OnBindView<WaitDialog>(R.layout.layout_wait_dialog) {
                    override fun onBind(dialog: WaitDialog?, v: View?) {
                        val load = v?.findViewById<ImageView>(R.id.iv_load)
                        val animation = RotateAnimation(
                            0f, 360f,
                            Animation.RELATIVE_TO_SELF, 0.5f, Animation.RELATIVE_TO_SELF, 0.5f
                        )
                        animation.duration = 1000
                        animation.repeatCount = -1
                        animation.interpolator = LinearInterpolator() //旋转效果
                        load?.animation = animation
                    }
                })
            Handler(Looper.getMainLooper()).postDelayed({
                // TipDialog.show("登录成功", WaitDialog.TYPE.SUCCESS)   // 只用这一句的话，不会自动消失
                WaitDialog.dismiss()
                TipDialog.show("登录成功")
                    .setCustomView(object : OnBindView<WaitDialog>(R.layout.layout_success_dialog) {
                        override fun onBind(dialog: WaitDialog?, v: View?) {
                        }
                    })
            }, 1500)

我这是一个模拟登陆的过程，这样写，第一个动画会跟第二个自定义view 重合显示，然后再消失，我尝试了好多种方式都不行，无奈给作者提个issue，想问问您有没有这种情况，版本就是用的最新的

**Comment by kongzue** [comment]
未遇到过任何问题，我这边只能提供一些建议给你。
1. WaitDialog 和 TipDialog 是同一个组件的不同表现形式，在同一个 Activity 实例下显示时，是使用同一主体的；
2. 要关掉 WaitDialog 并显示 TipDialog，无需对 WaitDialog.dismiss()，请直接执行 TipDialog.show(...) 它会直接取代 WaitDialog 显示。
3. 请勿频繁的执行 WaitDialog 和 TipDialog 的启停，DialogX 所有组件均会自动到主线程执行，需要等待主线程消费消息，频繁执行，特别是在异步线程频繁执行可能出现消息乱掉的情况，如果你需要自己处理，可以通过 `DialogX.autoRunOnUIThread = false`来关闭自动到主线程执行的功能。

**Comment by Sky0202** [comment]
> 
这个动画是去掉了 WaitDialog.dismiss()    但是自己不会自动消失，还会重叠显示
![83964414-a375-441a-b84b-2092ed0d6700](https://user-images.githubusercontent.com/9075467/148496332-162388e7-16f7-4fe5-a2fb-bd380efc7d46.gif)

**Comment by kongzue** [comment]
麻烦确定下是否在同一个Activity上执行的显示，DialogX会自动获取顶层Activity实例，若Activity实例不一致会创建新的对话框实例，或者您可以通过 .show(activity) 指定在要显示的 activity 实例上创建对话框。

**Comment by Sky0202** [comment]
> 

![image](https://user-images.githubusercontent.com/9075467/148500404-b1debca0-0f19-4f9a-a158-6cda0cec8e15.png)
我是在fragment 中调用的，全局只有一个activity ，现在加了 activity，可以自动消失了，但是还会重叠

**Comment by kongzue** [comment]
DialogX与Fragment无关，因为Fragment是无法独立承载Window的，DialogX实际上是在当前Activity中插入一个View来实现显示的，对于WaitDialog和TipDialog而言，因为是阻断式等待提示，会根据当前Activity生成单例的对话框实例进行显示，目前在已上线的产品中未发现存在问题，暂时无法确定原因

**Comment by Sky0202** [comment]
> DialogX与Fragment无关，因为Fragment是无法独立承载Window的，DialogX实际上是在当前Activity中插入一个View来实现显示的，对于WaitDialog和TipDialog而言，因为是阻断式等待提示，会根据当前Activity生成单例的对话框实例进行显示，目前在已上线的产品中未发现存在问题，暂时无法确定原因

![image](https://user-images.githubusercontent.com/9075467/148505593-e1294b1f-72d4-4c98-bbe0-f5e2c0ce735f.png)
.setCustomView(new OnBindView<WaitDialog>(R.layout.layout_custom_view) {
                    @Override
                    public void onBind(WaitDialog dialog, View v) {
                        ImageView img = v.findViewById(R.id.img_ico);
                        RotateAnimation animation = new RotateAnimation(
                                0f, 360f,
                                Animation.RELATIVE_TO_SELF, 0.5f, Animation.RELATIVE_TO_SELF, 0.5f
                        );
                        animation.setDuration(1000);
                        animation.setRepeatCount(-1);
                        img.setAnimation(animation);
                    }
                });
这是在demo中直接改的，你可以试试，dialog不会自动消失，成功的动画也没出现

**Comment by kongzue** [comment]
感谢反馈，明白了，因为使用自定义布局，无法判断动画衔接进行结束导致无法完全切换到 TipDialog 状态，此问题将在下一个版本修复。
但依然未能发现重叠的问题。

**Comment by kongzue** [comment]
请更新至 0.0.44.beta10 版本已修复此问题：https://github.com/kongzue/DialogX/releases

**Comment by Sky0202** [comment]
if (!closeFlag) runDelayed(new Runnable() {
                    @Override
                    public void run() {
                        if (!closeFlag) TipDialog.show("完成！", WaitDialog.TYPE.SUCCESS)
                                .setCustomView(new OnBindView(R.layout.layout_custom_dialog) {
                                    @Override
                                    public void onBind(Object dialog, View v) {
                                    }
                                });
                    }
                }, 2000);
用这个就能看见重叠了，再把layout_custom_dialog 中第一个 imageview 删掉就看见了，他是覆盖在动画之上了。我刚才用了最新的版本，dialog是关掉了

**Comment by Sky0202** [comment]
你好，重叠是否复现了呢？有什么解决方案吗

**Comment by kongzue** [comment]
我这边测试结果是并未覆盖在动画之上，而是以正常逻辑，TipDialog取代了WaitDialog显示。
代码：
```
closeFlag = false;
WaitDialog.show("Please Wait!")
        .setOnBackPressedListener(new OnBackPressedListener() {
    @Override
    public boolean onBackPressed() {
        PopTip.show("按下返回", "关闭").setButton(new OnDialogButtonClickListener<PopTip>() {
            @Override
            public boolean onClick(PopTip baseDialog, View v) {
                closeFlag = true;
                WaitDialog.dismiss();
                return false;
            }
        });
        return false;
    }
});
if (!closeFlag) runDelayed(new Runnable() {
    @Override
    public void run() {
        if (!closeFlag) TipDialog.show("完成！", WaitDialog.TYPE.SUCCESS)
                .setCustomView(new OnBindView<WaitDialog>(R.layout.layout_custom_dialog) {
                    @Override
                    public void onBind(WaitDialog dialog, View v) {
                    }
                });
    }
}, 2000);
```
额外的为了方便验证，修改了WaitDialog的BlurView透明的为0.5f。
执行结果：
![image](https://user-images.githubusercontent.com/10115359/149081626-70c8c805-3f61-48cc-aaa0-27fb7111ca4b.png)
如图，并没有出现TipDialog覆盖着WaitDialog动画的情况出现。

**Comment by Sky0202** [comment]
使用自定义view 就会出现，您可以用我上边那段代码试试，就是在demo里直接改的

**Comment by Sky0202** [comment]
waitDialog 和 tipDialog都用自定义view

**Comment by kongzue** [comment]
说实话这种情况更建议直接自定义主题了，既方便也合适

**Comment by kongzue** [comment]
代码如下：

**Comment by kongzue** [comment]
长时间未收到回复，暂时关闭了此问题，如有疑问请继续回复。
