### ISSUE TITLE
java.lang.NullPointerException

### ISSUE THREAD

**Issue by 1825492258** [kongzue/DialogX#160]
![image](https://user-images.githubusercontent.com/16134482/148480626-e0ca1f8e-64d5-495c-9cb9-ad7bdc365bdb.png)
bugly里面报的这个异常

**Comment by kongzue** [comment]
是否在关闭对话框后执行了设置的相关操作

**Comment by kongzue** [comment]
此问题将在下一个版本修复。

**Comment by feisher** [comment]
同样碰到这个问题，发生了1717次（10w+用户）

**Comment by kongzue** [comment]
@feisher  目前跟踪代码显示是自定义 View 的外层组件默认 LayoutParams 为空导致的，此问题将在下一个版本修复。

**Comment by kongzue** [comment]
@feisher @1825492258 请更新至 0.0.44.beta10 版本已修复此问题：https://github.com/kongzue/DialogX/releases

**Comment by 1825492258** [comment]
好的
