### ISSUE TITLE
用DialogX中里面含有EditTextView  每次弹出都会有个收缩  能不能取消这个收缩  

### ISSUE THREAD

**Issue by strongerzzx** [kongzue/DialogX#162]

**Comment by kongzue** [comment]
不理解您的意思，这不是DialogX控制的，请检查您的Activity的`android:windowSoftInputMode`设置，在AndroidManifest.xml里

**Comment by kongzue** [comment]
各属性介绍如下：
![image](https://user-images.githubusercontent.com/10115359/149860950-f78d02cc-474a-43b7-8709-5236e29e0d33.png)

**Comment by strongerzzx** [comment]
好的，感谢回复。 顺便一说框架很好用哦。



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年1月18日(星期二) 上午10:34
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [kongzue/DialogX] 用DialogX中里面含有EditTextView  每次弹出都会有个收缩  能不能取消这个收缩   (Issue #162)





 
各属性介绍如下：
 
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by kongzue** [comment]
不客气，有需要也可以加群获得更及时的沟通590498789
