### ISSUE TITLE
想问下BottomMenu底部菜单没有没有办法设置最后一个menu的字体颜色等textInfo属性。

### ISSUE THREAD

**Issue by amosxb** [kongzue/DialogX#163]
同标题

**Comment by kongzue** [comment]
如果你说的是取消按钮，它实际上是遵循取消按钮设置的，可以单独设置也可以全局设置
________________________________
发件人: aubooo ***@***.***>
发送时间: Tuesday, January 18, 2022 11:51:34 AM
收件人: kongzue/DialogX ***@***.***>
抄送: Subscribed ***@***.***>
主题: [kongzue/DialogX] 想问下BottomMenu底部菜单没有没有办法设置最后一个menu的字体颜色等textInfo属性。 (Issue #163)


同标题

―

**Comment by amosxb** [comment]
我记得IOS取消按钮是和menu分开的。

**Comment by kongzue** [comment]
对啊，它就是取消按钮，你可以试试下边的代码：
```
BottomMenu.show(new String[]{"新标签页中打开", "稍后阅读", "复制链接网址"})
        .setMessage("http://www.kongzue.com/DialogX")
        .setOnMenuItemClickListener(new OnMenuItemClickListener<BottomMenu>() {
            @Override
            public boolean onClick(BottomMenu dialog, CharSequence text, int index) {
                PopTip.show(text);
                dialog.setMenuList(new String[]{"test", "test2", "test3"});
                return false;
            }
        })
.setCancelTextInfo(new TextInfo()
        .setBold(true)
        .setFontSize(30)
        .setFontColor(Color.RED)
);
```
运行效果如图：
![image](https://user-images.githubusercontent.com/10115359/150301344-90c79e4b-3992-408b-b849-c02af1627241.png)

**Comment by amosxb** [comment]
大佬，不是这个取消，是list的最后一个item，也就是取消上面的item

**Comment by kongzue** [comment]
菜单内容不支持单独修改样式，原因是本质上是个单样式的ListView，不过你可以通过获取DialogImpl来自定义布局实现更多功能

**Comment by amosxb** [comment]
![IMG_0052](https://user-images.githubusercontent.com/19277279/150302699-7f0fe58a-acd2-4f92-a36e-96fef4733994.PNG)
原生IOS是这样的。 不过也没关系，没太大的影响。

**Comment by kongzue** [comment]
请更新至 0.0.44.beta11 版本，更新说明参见 https://github.com/kongzue/DialogX/releases/tag/0.0.44.beta11
![image](https://user-images.githubusercontent.com/10115359/150641303-70694964-ed24-419b-89a4-3738033c520c.png)
使用方法范例：
```
BottomMenu.show(new String[]{"新标签页中打开", "稍后阅读", "复制链接网址"})
        .setMenuItemTextInfoInterceptor(new MenuItemTextInfoInterceptor<BottomMenu>() {
            @Override
            public TextInfo menuItemTextInfo(BottomMenu dialog, int index, String menuText) {
                if (index==2){
                    return new TextInfo()
                            .setFontColor(Color.RED)
                            .setBold(true);
                }
                return null;
            }
        });
```
