### ISSUE TITLE
如何设置ios风格dialog的圆角弧度

### ISSUE THREAD

**Issue by coolyunyun** [kongzue/DialogX#164]
如何设置ios风格dialog的圆角弧度
.setDialogLifecycleCallback(new DialogLifecycleCallback<MessageDialog>() {
                    @Override
                    public void onShow(MessageDialog dialog) {
方法中怎么设置

**Comment by kongzue** [comment]
这个需要自定义主题了，并不支持直接修改

**Comment by kongzue** [comment]
请尝试自定义主题并重写overrideWaitTipRes#overrideRadiusPx返回值单位为像素。
长时间未收到回复，暂时关闭了此问题，如有疑问请继续回复。
