### ISSUE TITLE
0.0.44.beta11测试版 关闭所有弹窗时崩溃

### ISSUE THREAD

**Issue by bobolover** [kongzue/DialogX#166]
收集到的崩溃信息如下 是更新了0.0.44.beta11测试版之后出现的 麻烦您帮忙看下

1
io.reactivex.exceptions.UndeliverableException:android.util.AndroidRuntimeException: Animators may only be run on Looper threads
2
io.reactivex.plugins.RxJavaPlugins.onError(RxJavaPlugins.java:367)
3
......
4
Caused by:
5
android.util.AndroidRuntimeException:Animators may only be run on Looper threads
6
android.animation.ValueAnimator.start(ValueAnimator.java:1052)
7
android.animation.ValueAnimator.start(ValueAnimator.java:1106)
8
com.kongzue.dialogx.dialogs.MessageDialog$DialogImpl.doDismiss(MessageDialog.java:694)
9
com.kongzue.dialogx.dialogs.MessageDialog.dismiss(MessageDialog.java:713)
10
com.kongzue.dialogx.dialogs.MessageDialog.shutdown(MessageDialog.java:1098)
11
com.kongzue.dialogx.interfaces.BaseDialog.cleanAll(BaseDialog.java:643)
12
com.lixun.lib.utils.DialogUtils.cancelAllDialog(DialogUtils.java:71)

**Comment by kongzue** [comment]
此问题将在下一个版本修复。
