### ISSUE TITLE
FullScreenDialog布局内包含RecyclerView，下拉关闭的手势没了！

### ISSUE THREAD

**Issue by shooe** [kongzue/DialogX#167]
OnBindView<FullScreenDialog> onBindView;

        onBindView = new OnBindView<FullScreenDialog>(R.layout.user_list) {
            。。。
            。。。
};

只能使用BottomDialog嘛？
FullScreenDialog  怎么处理这里的逻辑。RecyclerView滑动到顶部后，Dialog也可以下拉关闭这样。。。求教

**Comment by kongzue** [comment]
是的，这个需要手动处理

**Comment by kongzue** [comment]
长时间未收到回复，暂时关闭了此问题，如有疑问请继续回复。
