### ISSUE TITLE
一个 NullPointerException

### ISSUE THREAD

**Issue by bobolover** [kongzue/DialogX#169]
DialogX:0.0.44.beta5 bugly收集到的线上崩溃 app处在后台
# main(2)

java.lang.NullPointerException

Attempt to invoke virtual method 'com.kongzue.dialogx.util.views.MaxRelativeLayout com.kongzue.dialogx.util.views.MaxRelativeLayout.setMaxWidth(int)' on a null object reference

解析原始
1
com.kongzue.dialogx.dialogs.MessageDialog$DialogImpl.refreshView(MessageDialog.java:470)
2
com.kongzue.dialogx.dialogs.MessageDialog$1.run(MessageDialog.java:234)
3
android.os.Handler.handleCallback(Handler.java:938)
4
android.os.Handler.dispatchMessage(Handler.java:99)
5
android.os.Looper.loop(Looper.java:263)
6
android.app.ActivityThread.main(ActivityThread.java:8283)
7
java.lang.reflect.Method.invoke(Native Method)
8
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:612)
9
com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1006)

**Comment by kongzue** [comment]
收到，下一版本修复

**Comment by kongzue** [comment]
已修复，请更新最新版本
