### ISSUE TITLE
为什么不持有独立的 Window 呢

### ISSUE THREAD

**Issue by KunMinX** [kongzue/DialogX#17]
不持有独立的 Window，将会对宿主 Window 造成过度绘制，
弹窗时的背景遮罩算一层（绿色），对话框的背景算一层（浅红），这时候再布置些内容，就已经触及性能的红线了。

如果坚持通过这种方式来显示对话框，倒是有一种办法可以尽可能减少过度绘制，是通过 canvas.clipRect 的方式，使对话框遮住的部分不再绘制。

不过这种方式的实现只适合底栏和顶栏。

![](https://flomo.oss-cn-shanghai.aliyuncs.com/file/2021-02-22/35479/cf35485e8716eae41b602b609bd0398b.png)

![](https://flomo.oss-cn-shanghai.aliyuncs.com/file/2021-02-22/35479/aa9672f1f27c74eee4d01e3e846f0608.png)

![](https://flomo.oss-cn-shanghai.aliyuncs.com/file/2021-02-22/35479/78eae2b56651ebde090f61ef122aba39.png)

**Comment by kongzue** [comment]
因为创建Window则会导致在Activity先于Dialog被关闭时发生WindowLeaked错误，我认为这反而不符合常识理解，按照正常理解，宿主Activity关闭相关联的基于宿主创建的组件理应自动卸载，但显然Google并未考虑这种问题，而开发APP的过程中因需要执行费时操作显示一个例如WaitDialog等待提示而在事务执行完毕后直接关闭Activity是一种常见操作，为避免这里出现问题通常不得不额外的在onDestroy时需要对Dialog进行dismiss我认为过于麻烦。

经过测试目前大部分设备性能并不会因为这层DialogX创建的布局发生卡顿，感谢你的建议但很抱歉基于减少开发过程中遇到麻烦的设计目的我无法采纳。

________________________________
发件人: KunMinX <notifications@github.com>
发送时间: Monday, February 22, 2021 12:40:11 AM
收件人: kongzue/DialogX <DialogX@noreply.github.com>
抄送: Subscribed <subscribed@noreply.github.com>
主题: [kongzue/DialogX] 为什么不持有独立的 Window 呢 (#17)


不持有独立的 Window，将会对宿主 Window 造成过度绘制，
弹窗时的背景遮罩算一层（绿色），对话框的背景算一层（浅红），这时候再布置些内容，就已经触及性能的红线了。

如果坚持通过这种方式来显示对话框，倒是有一种办法可以尽可能减少过度绘制，是通过 canvas.clipRect 的方式，使对话框遮住的部分不再绘制。

不过这种方式的实现只适合底栏和顶栏。

―

**Comment by KunMinX** [comment]
那么 DialogV3 后续会保持基于 DialogFragment 的设计吗

**Comment by kongzue** [comment]
暂时关闭了此问题，如有疑问可继续回复。

**Comment by FreeLoopC** [comment]
对于这种过度绘制做法我也不能认同

监听Activity的LifeCycle是否可以解决<通常不得不额外的在onDestroy时需要对Dialog进行dismiss我认为过于麻烦。>这个问题

**Comment by kongzue** [comment]
@FreeLoopC 事实上，Kongzue Dialog前几代作品（例如DialogV3）都是基于AlertDialog或DialogFragment的Window体系制作的，但存在大量的不可避免的问题，诸如受到Window限制，无法做到底部导航栏自由沉浸式处理的问题，DialogFragment依然存在无法处理的内存泄漏问题，以及由Window引发的WindowLeaked泄露问题，另外经过我们测试，使用非Window改用View渲染模式实际上在Dialog UI显示和关闭时动画会更流畅而不是更卡顿，创建Window事务事实上开销成本并不低。目前DialogX已经应用于我们已上架应用和即将上架的测试版本，诸如《给未来写封信》、《花哪儿记账X》、《密码键盘》等，实际效果都非常不错。至于担心渲染层级多导致卡顿的问题，我们也做过实际试验，Android的Activity在同一界面同时渲染上千个View是不存在问题的，至于复杂场景，我更建议去考虑从UI设计上简化界面结构，而不是担心DialogX会增加很多负担，另外在dismiss后，DialogX会从当前界面完全remove掉，并不会增加太多性能持续消耗的开销。
