### ISSUE TITLE
编译出错

### ISSUE THREAD

**Issue by shooe** [kongzue/DialogX#171]
Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not resolve androidx.appcompat:appcompat:1.2.0+.
     Required by:
         project :app > com.github.kongzue.DialogX:DialogX:0.0.44.beta10
      > Failed to list versions for androidx.appcompat:appcompat.

**Comment by kongzue** [comment]
请升级你的gradle版本
________________________________
发件人: Hash1 ***@***.***>
发送时间: Tuesday, February 15, 2022 2:16:51 PM
收件人: kongzue/DialogX ***@***.***>
抄送: Subscribed ***@***.***>
主题: [kongzue/DialogX] 编译出错 (Issue #171)


Could not resolve all files for configuration ':app:debugRuntimeClasspath'.

Could not resolve androidx.appcompat:appcompat:1.2.0+.
Required by:
project :app > com.github.kongzue.DialogX:DialogX:0.0.44.beta10
> Failed to list versions for androidx.appcompat:appcompat.

―

**Comment by kongzue** [comment]
此问题大概率是网络问题。
appcompat是Android 的基础包，DialogX依赖此包实现UI，请确保你的网络可以正常加载它。

**Comment by bachan111** [comment]
我也遇到这个问题了，还报502，我在找找原因

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:checkDebugAarMetadata'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not resolve androidx.appcompat:appcompat:1.2.0+.
     Required by:
         project :app
         project :app > project :base-lib
         project :app > project :base-lib > com.github.kongzue.DialogX:DialogX:0.0.45.beta23
      > Failed to list versions for androidx.appcompat:appcompat.
         > Unable to load Maven meta-data from https://dl.bintray.com/cjt/maven/androidx/appcompat/appcompat/maven-metadata.xml.
            > Could not get resource 'https://dl.bintray.com/cjt/maven/androidx/appcompat/appcompat/maven-metadata.xml'.
               > Could not GET 'https://dl.bintray.com/cjt/maven/androidx/appcompat/appcompat/maven-metadata.xml'. Received status code 502 from server: Bad Gateway
   > Could not resolve androidx.constraintlayout:constraintlayout:2.0.4+.
     Required by:
         project :app > project :base-lib > com.github.kongzue.DialogX:DialogX:0.0.45.beta23
      > Skipped due to earlier error
      > Failed to list versions for androidx.constraintlayout:constraintlayout.
         > Unable to load Maven meta-data from https://dl.bintray.com/madchan/maven/androidx/constraintlayout/constraintlayout/maven-metadata.xml.
            > Could not get resource 'https://dl.bintray.com/madchan/maven/androidx/constraintlayout/constraintlayout/maven-metadata.xml'.
               > Could not GET 'https://dl.bintray.com/madchan/maven/androidx/constraintlayout/constraintlayout/maven-metadata.xml'. Received status code 502 from server: Bad Gateway

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

**Comment by kongzue** [comment]
> 我也遇到这个问题了，还报502，我在找找原因
> 
> FAILURE: Build failed with an exception.
> 
> * What went wrong:
>   Execution failed for task ':app:checkDebugAarMetadata'.
> 
> > Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
> > Could not resolve androidx.appcompat:appcompat:1.2.0+.
> > Required by:
> > project :app
> > project :app > project :base-lib
> > project :app > project :base-lib > com.github.kongzue.DialogX:DialogX:0.0.45.beta23
> > > Failed to list versions for androidx.appcompat:appcompat.
> > > Unable to load Maven meta-data from https://dl.bintray.com/cjt/maven/androidx/appcompat/appcompat/maven-metadata.xml.
> > > Could not get resource 'https://dl.bintray.com/cjt/maven/androidx/appcompat/appcompat/maven-metadata.xml'.
> > > Could not GET 'https://dl.bintray.com/cjt/maven/androidx/appcompat/appcompat/maven-metadata.xml'. Received status code 502 from server: Bad Gateway
> > Could not resolve androidx.constraintlayout:constraintlayout:2.0.4+.
> > Required by:
> > project :app > project :base-lib > com.github.kongzue.DialogX:DialogX:0.0.45.beta23
> > > Skipped due to earlier error
> > > Failed to list versions for androidx.constraintlayout:constraintlayout.
> > > Unable to load Maven meta-data from https://dl.bintray.com/madchan/maven/androidx/constraintlayout/constraintlayout/maven-metadata.xml.
> > > Could not get resource 'https://dl.bintray.com/madchan/maven/androidx/constraintlayout/constraintlayout/maven-metadata.xml'.
> > > Could not GET 'https://dl.bintray.com/madchan/maven/androidx/constraintlayout/constraintlayout/maven-metadata.xml'. Received status code 502 from server: Bad Gateway
> 
> * Try:
>   Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
> * Get more help at https://help.gradle.org

请注意，jCenter源服务商bintray已经停止运行，我已经在文档中注明的很清楚了。请切换至 jitpack 源。
![image](https://user-images.githubusercontent.com/10115359/178182001-4fc02d34-76e5-4870-841e-1bd682524872.png)
