### ISSUE TITLE
0.044.beta14版本会出现内存泄漏问题

### ISSUE THREAD

**Issue by amosxb** [kongzue/DialogX#172]
操作步骤：demo的MainActivity跳转到另一个Activity，在另一个Activity上打开MessageDialog或者任一类型的Dialog，点击关闭dialog,再返回MainActivity。

- > 
![IMG_0024](https://user-images.githubusercontent.com/19277279/154878169-bbdd6d00-e054-435f-9698-711574d3b1d8.JPG)

**Comment by kongzue** [comment]
DialogXBaseRelativeLayout 中的 mContext 来自于继承的父类：View#mContext 此问题并非是 DialogXBaseRelativeLayout 持有上下文，不清楚 Google 在设计 View 时，当 Context（Activity）销毁后，View 为何没有自动解绑依然持有，此问题需要进一步确认原因。

**Comment by amosxb** [comment]
嗯，大佬，好好查下哪里出的问题，我这边凡是用到dialog的地方基本上都有内存泄漏的问题，不清楚你那边具体的实现逻辑。

**Comment by kongzue** [comment]
> 嗯，大佬，好好查下哪里出的问题，我这边凡是用到dialog的地方基本上都有内存泄漏的问题，不清楚你那边具体的实现逻辑。

主要问题是，我无法帮Google去处理View中的逻辑，也无法对系统底层组件进行修改，目前我这边已经上线的项目均未发现任何问题，此问题已列入待观察，但暂时无法处理。

DialogX 默认是基于 View 实现的，如果你没有强行使用其他实验性的实现方式，理论上是不存在问题是，在Activity销毁时，其中的View应当自动解绑，也不存在持续持有Context的可能。

**Comment by amosxb** [comment]
![BBT3M{73MZD@JOKC$IG JL6](https://user-images.githubusercontent.com/19277279/154881501-a9caa053-8173-455d-a1a7-25dff1f22145.png)


大佬，看下我使用有啥问题么。

**Comment by kongzue** [comment]
OKButton的事件中无需手动dismiss，另外请检查是否设置过DialogX.dialogImpl，若没有就不应该有问题

**Comment by kongzue** [comment]
长时间未收到回复，暂时关闭了此问题，如有疑问请继续回复。
