### ISSUE TITLE
PopMenu  setCustomView无效

### ISSUE THREAD

**Issue by CPC-Coder** [kongzue/DialogX#177]

**Comment by kongzue** [comment]
PopMenu 尚不支持自定义布局，该组件依然处于开发状态，并非上线的组件

**Comment by CPC-Coder** [comment]
这个功能挺常用的 希望早点上线 麻烦 空神

**Comment by kongzue** [comment]
请更新至最新版本：0.0.44.beta15
更新日志：https://github.com/kongzue/DialogX/releases/tag/0.0.44.beta15
