### ISSUE TITLE
BottomDialog setCustomView后，调用dismiss没有动画效果

### ISSUE THREAD

**Issue by Molzx** [kongzue/DialogX#178]
`
                
                         BottomDialog.build()
                        .setCustomView(new OnBindView<BottomDialog>(R.layout.dialog_bottom_normal) {
                            @Override
                            public void onBind(BottomDialog dialog, View v) {
                                List<ItemType2Adapter.ItemType2> adapterData = new ArrayList<>();
                                for (String titleData : data) {
                                    adapterData.add(new ItemType2Adapter.ItemType2(titleData));
                                }

                                DialogBottomNormalBinding binding = DialogBottomNormalBinding.bind(v);

                                binding.tvTitle.setText(title);

                                RecyclerView recyclerView = binding.recycleView;
                                LinearLayoutManager layoutManager = new LinearLayoutManager(context);
                                recyclerView.setLayoutManager(layoutManager);

                                int padding = SizeUtils.dp2px(15);
                                DividerDecoration.builder(context)
                                        .insets(padding, padding)
                                        .showFirstDivider()
                                        .size(1)
                                        .colorRes(R.color.divier_color_bottom_dialog_item)
                                        .build()
                                        .addTo(recyclerView);

                                ItemType2Adapter adapter = new ItemType2Adapter(adapterData);
                                adapter.setSelectedIndex(selectMenuIndex);
                                adapter.setOnItemClickListener(new OnItemClickListener() {
                                    @Override
                                    public void onItemClick(@androidx.annotation.NonNull BaseQuickAdapter<?, ?> adapter, @androidx.annotation.NonNull View view, int position) {
                                        XLog.i(position + "");
                                        ((ItemType2Adapter) adapter).setSelectedIndex(position);
                                    }
                                });
                                recyclerView.setAdapter(adapter);

                                binding.tvDone.setOnClickListener(new View.OnClickListener() {
                                    @Override
                                    public void onClick(View view) {

                                        if (selectMenuIndex != adapter.getSelectedIndex()) {
                                            int selectedIndex = adapter.getSelectedIndex();
                                            if (!emitter.isDisposed()) {
                                                emitter.onSuccess(selectedIndex);
                                            }
                                        }
                                        dialog.dismiss();
                                    }
                                });
                            }
                        })
                        .show();
`

调用dismiss没有动画效果，直接就消失了，又或者稍微有效果？就是很突兀的消失了。但是点击对话框外面，还是有消失动画的

**Comment by kongzue** [comment]
很抱歉，未能在Demo中复现你所描述的问题。
测试代码：
```
new BottomDialog("标题", "这里是对话框内容。\n" + s + "。\n底部对话框也支持自定义布局扩展使用方式。",
        new OnBindView<BottomDialog>(R.layout.layout_custom_view) {
            @Override
            public void onBind(BottomDialog dialog, View v) {
                if (dialog.getDialogImpl().imgTab != null) {
                    ((ViewGroup) dialog.getDialogImpl().imgTab.getParent()).removeView(dialog.getDialogImpl().imgTab);
                }
                v.setOnClickListener(new View.OnClickListener() {
                    @Override
                    public void onClick(View v) {
                        dialog.dismiss();
                        PopTip.show("Click Custom View");
                    }
                });
            }
        })
        .show();
```

**Comment by kongzue** [comment]
长时间未收到回复，暂时关闭了此问题，如有疑问请继续回复。
