### ISSUE TITLE
Dialog 无法 dismiss问题

### ISSUE THREAD

**Issue by QIMOU** [kongzue/DialogX#180]
短时间内调用了两次WaitDialog(“加载中”) ----->TipDialog或者 dismiss或者dismiss(activity)，结果是dismiss不管用无法取消dialog，tipdialog会加载一次，动画结束后紧接着 WaitDialog(“加载中”)  ，且 OnBackPressedListener {    true  } 无效

**Comment by kongzue** [comment]
### 测试过程
很抱歉未能未能复现你所描述的问题。以下代码均在最新版本的Demo中进行。
#### 测试用例1：
直接测试多次启动WaitDialog后等待两秒对其dismiss。
```
WaitDialog.show("Please Wait!");
WaitDialog.show("Please Wait2!");
runDelayed(new Runnable() {
    @Override
    public void run() {
        WaitDialog.dismiss();
    }
}, 2000);
```
结果：两秒对话框正常关闭。
#### 测试用例2：
测试立即重复启动WaitDialog都对其立即dismiss
```
WaitDialog.show("Please Wait!");
WaitDialog.show("Please Wait2!");
WaitDialog.dismiss();
```
结果：无任何反应，符合预期。
#### 测试用例3：
测试设置OnBackPressedListener->true后是否可以正常使用返回键关闭
```
WaitDialog.show("Please Wait!").setOnBackPressedListener(new OnBackPressedListener() {
    @Override
    public boolean onBackPressed() {
        return true;
    }
});
WaitDialog.show("Please Wait2!");
```
结果：显示文本“Please Wait2!”，按下返回键关闭WaitDialog，因WaitDialog是单例的，结果符合预期。

### 原因猜测
你可能是在异步线程执行了WaitDialog的启停操作。异步线程中要操作UI，是需要等待UI线程完成响应的，而多次重复启动WaitDialog可能会将message移交给mainHandler等待处理，这可能造成之前启动的WaitDialog未能实际创建实例造成后续构建WaitDialog时无法得知之前已经创建过WaitDialog，造成重复创建实例的情况，这种情况建议优化程序逻辑，不要多次使用`WaitDialog.show()`方法，可以在第一次构建后使用`.setMessage(string)`设置其他内容。

**Comment by QIMOU** [comment]
好的 感谢能这么快回复问题，辛苦了，我梳理梳理逻辑问题

**Comment by kongzue** [comment]
好的，有疑问也可以加反馈群随时讨论：590498789

**Comment by QIMOU** [comment]
好的

**Comment by kongzue** [comment]
长时间未收到回复，暂时关闭了此问题，如有疑问请继续回复。
