### ISSUE TITLE
BottomMenu启动很慢是怎么回事，0.4版本不会

### ISSUE THREAD

**Issue by JefferyLei** [kongzue/DialogX#183]
点击后要等几百毫秒才弹出对话框，体验真受不了

**Comment by kongzue** [comment]
猜测是菜单数量过多导致的
________________________________
发件人: mxlei ***@***.***>
发送时间: Tuesday, March 29, 2022 10:24:28 AM
收件人: kongzue/DialogX ***@***.***>
抄送: Subscribed ***@***.***>
主题: [kongzue/DialogX] BottomMenu启动很慢是怎么回事，0.4版本不会 (Issue #183)


点击后要等几百毫秒才弹出对话框，体验真受不了

―

**Comment by kongzue** [comment]
暂时关闭了此问题，若有疑问请继续回复
