### ISSUE TITLE
项目整体上移，被状态栏给遮住一部分了

### ISSUE THREAD

**Issue by ylmyg** [kongzue/DialogX#187]
为什么加入依赖以后，界面整体向上移动，被状态栏遮住了？

**Comment by ylmyg** [comment]
而且为什么对话框显示以后，整个界面背景都是黑色了。已经设置类背景颜色了。搞不懂

**Comment by kongzue** [comment]
我也搞不懂，有试过Demo么？是否有遇到类似问题

**Comment by kongzue** [comment]
请尝试 0.0.45.beta4 版本看是否还存在问题

**Comment by kongzue** [comment]
长时间未收到回复，暂时关闭此问题，若有疑问请继续回复。
