### ISSUE TITLE
【BUG反馈】customDialog 被挡住

### ISSUE THREAD

**Issue by sceneren** [kongzue/DialogX#189]
### 问题描述：
tablayout+viewpager2,在MainActivity里面显示一个CustomDialog,结果Dialog显示在了最底层

**Comment by kongzue** [comment]
请确认你以看过文档。
![image](https://user-images.githubusercontent.com/10115359/165251618-fa8f3886-2d8a-4406-98c3-71a65624cc7a.png)

**Comment by sceneren** [comment]
我知道的，默认view方式，也应该是显示在add在layout的最上层吧

**Comment by kongzue** [comment]
AlertDialog基于Window的层级是高于Activity的Window的

**Comment by kongzue** [comment]
你无法使一个被AlertDialog的Window遮挡的Activity的Window上创建的View置于AlertDialog的Window前
其结构大致类似于：
![image](https://user-images.githubusercontent.com/10115359/165253460-7a0b72ae-3b99-4680-90f4-86c141c669c3.png)

**Comment by sceneren** [comment]
<img width="254" alt="image" src="https://user-images.githubusercontent.com/6612998/165252839-695aa9e7-7b48-47f6-a3ea-09f6aa926b28.png">
<img width="395" alt="WX20220426-160702@2x" src="https://user-images.githubusercontent.com/6612998/165252889-8a193471-8fe2-4d18-b9a0-ae6d43fc0bf4.png">

第一张图是dialog的样式
第二张是显示的样子，
确实是显示在了fragment最下面

`
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:orientation="vertical">

    <include
        android:id="@+id/title_layout"
        layout="@layout/app_main_title_bar" />

    <View
        android:layout_width="match_parent"
        android:layout_height="1dp"
        android:background="@drawable/m_assets_bg_main_tab_line" />

    <androidx.viewpager2.widget.ViewPager2
        android:id="@+id/viewPager"
        android:layout_width="match_parent"
        android:layout_height="0dp"
        android:layout_weight="1" />

    <View
        android:layout_width="match_parent"
        android:layout_height="1dp"
        android:background="@drawable/m_assets_bg_main_tab_line" />

    <com.flyco.tablayout.CommonTabLayout
        android:id="@+id/tab_layout"
        android:layout_width="match_parent"
        android:layout_height="54dp"
        android:background="#201C36"
        app:tl_iconHeight="24dp"
        app:tl_iconWidth="24dp"
        app:tl_indicator_color="#03EAA6"
        app:tl_indicator_height="0dp"
        app:tl_textSelectColor="#03EAA6"
        app:tl_textSelectSize="10sp"
        app:tl_textUnselectColor="#888888"
        app:tl_textsize="10sp" />


</LinearLayout>


`

MainActivity的布局代码

**Comment by kongzue** [comment]
这跟你使用什么布局无关，请明确了解Window和View的层级关系
