### ISSUE TITLE
为什么我使用你的代码，显示的和你的软件显示的不一样呢？

### ISSUE THREAD

**Issue by ytxyyt** [kongzue/DialogX#19]
按键大小不对，和你的不一样

**Comment by kongzue** [comment]
请运行Demo尝试。
Demo是基于原生项目进行开发的，显示方式和原生渲染方式完全一致，但如果您自行使用了第三方的适配框架、响应/沉浸式框架，例如头条适配方案，请根据第三方适配方案自行进行处理，DialogX仅保证在原生运行方式的情况下显示正常。

**Comment by ytxyyt** [comment]
可是我什么也没有添加啊
![Screenshot_2021-02-25-17-13-46-53](https://user-images.githubusercontent.com/76242879/109130562-d786e200-778c-11eb-8cfc-dd2010bf6cd5.png)
![Screenshot_2021-02-25-17-13-27-26](https://user-images.githubusercontent.com/76242879/109130566-d950a580-778c-11eb-8565-93c87500a91a.png)
显示的是这样

**Comment by kongzue** [comment]
看截图大概明白了，这是某几个版本的Android系统（AOSP）存在BUG，导致系统属性`android:paddingVertical`和`android:paddingHorizontal`不生效，更新至新版本系统可解决此问题。
但为避免类似的问题出现，在下一个版本中我也会在源代码中使用`paddingTop`、`paddingBottom`和`paddingLeft`、`paddingRight`逐一替换掉`android:paddingVertical`和`android:paddingHorizontal`，更新后会通知你。

**Comment by ytxyyt** [comment]
哦，谢谢😘😚😗😙

**Comment by kongzue** [comment]
请更新至测试版：0.0.32.beta1，已处理此问题。
