### ISSUE TITLE
弱引用出现空指针异常  java.lang.NullPointerException

### ISSUE THREAD

**Issue by yinbiaos** [kongzue/DialogX#190]
## BUG 反馈
收到广播后，在广播中 使用 WaitDialog.show(mContext, "加载中，请稍候...");   出现空指针异常。

### 问题描述：
1	java.lang.RuntimeException:Error receiving broadcast Intent { act=android.provider.JWS.REQUEST_RESPONSE_NFC_ID flg=0x20000010 (has extras) } in com.qz.arcface.ui.FaceActivity$1@760de26
2	android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:1132)
3	......
4	Caused by:
5	java.lang.NullPointerException:Attempt to invoke virtual method 'com.kongzue.dialogx.DialogX$IMPL_MODE com.kongzue.dialogx.interfaces.BaseDialog.getDialogImplMode()' on a null object reference
6	com.kongzue.dialogx.util.views.DialogXBaseRelativeLayout.setParentDialog(DialogXBaseRelativeLayout.java:283)
7	com.kongzue.dialogx.dialogs.WaitDialog$DialogImpl.init(WaitDialog.java:312)
8	com.kongzue.dialogx.dialogs.WaitDialog$DialogImpl.lazyCreate(WaitDialog.java:277)
9	com.kongzue.dialogx.dialogs.WaitDialog$2.run(WaitDialog.java:233)
10	com.kongzue.dialogx.interfaces.BaseDialog.runOnMain(BaseDialog.java:663)
11	com.kongzue.dialogx.dialogs.WaitDialog.show(WaitDialog.java:224)
12	com.kongzue.dialogx.dialogs.WaitDialog.showWithInstance(WaitDialog.java:945)
13	com.kongzue.dialogx.dialogs.WaitDialog.show(WaitDialog.java:101)
14	com.qz.arcface.ui.FaceActivity.payOrderByFace(FaceActivity.java:318)
15	com.qz.arcface.ui.FaceActivity.access$400(FaceActivity.java:88)
16	com.qz.arcface.ui.FaceActivity$1.onReceive(FaceActivity.java:201)
17	android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:1122)
18	android.os.Handler.handleCallback(Handler.java:755)
19	android.os.Handler.dispatchMessage(Handler.java:95)
20	android.os.Looper.loop(Looper.java:154)

### 设备信息：
Android 7.1.2,level 25
armeabi-v7a

### 是否在 Demo 中能复现此问题？
未尝试

### 问题截图/视频

![image](https://user-images.githubusercontent.com/12043685/165423198-967f6874-32de-4b6a-a02d-c8a25dbe8223.png)

**Comment by kongzue** [comment]
正在验证问题并处理

**Comment by kongzue** [comment]
请更新至 **0.0.45.beta3** 版本，已尝试修复此问题。

**Comment by kongzue** [comment]
长时间未收到回复，暂时关闭此问题，若有疑问请继续回复。
