### ISSUE TITLE
自定义弹窗居中弹出时顶部有间距

### ISSUE THREAD

**Issue by BigKingQY** [kongzue/DialogX#191]
使用自定义布局弹出时，如果设置居中弹出，顶部会有间距，如果把CENTER改成TOP时，间距就没了。想要居中弹出，顶部没有间距的效果，能否修复一下，谢谢。
CustomDialog.setAlign(CustomDialog.ALIGN.CENTER)

**Comment by kongzue** [comment]
是不是因为安全区的问题。
默认情况下对话框自定义布局会被限制到安全区范围内，即，刨除掉顶部状态栏高度和底部导航栏高度之后的可用范围，若需要解除这个限制，请参考 wiki 文档：https://github.com/kongzue/DialogX/wiki/%E8%87%AA%E5%AE%9A%E4%B9%89%E5%AF%B9%E8%AF%9D%E6%A1%86-CustomDialog#%E6%B2%89%E6%B5%B8%E5%BC%8F

```
.setAutoUnsafePlacePadding(false)
```

**Comment by kongzue** [comment]
长时间未收到回复，暂时关闭此问题，若有疑问请继续回复。
