### ISSUE TITLE
你好，给BottomDialog进行列表渲染，初始化大量数据的时候，弹窗卡顿

### ISSUE THREAD

**Issue by zhanghuibiao** [kongzue/DialogX#194]
## BUG 反馈

请先确认您已阅读[《常见问题》](https://github.com/kongzue/DialogX/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)

### 问题描述：
每次显示BottomDialog，会初始化列表数据，数据量一旦变大，弹窗显示就会卡顿

### 设备信息：
请在此说明您使用的设备型号、Android 版本等信息以协助我们排查问题

### 是否在 Demo 中能复现此问题？
是

### 问题截图/视频
![image](https://user-images.githubusercontent.com/19171770/168717632-cb4dca86-51a5-4930-8c73-11bce272ae11.png)

**Comment by kongzue** [comment]
事实上BottomMenu的应用场景并不适合大量菜单的选择，这种情况建议使用PopMenu或者FullScreenDialog完成。
例如：
```
List<CharSequence> a=new ArrayList<>();
for (int i=0;i<200;i++){
    a.add("Test "+i);
}
PopMenu.show(a);
```
BottomMenu主要适用于简单的选项业务场景，考虑到滑动的兼容，并不是利用ListView拆东墙补西墙的原理去实现的。

**Comment by zhanghuibiao** [comment]
那比如说很多常见的业务场景需要在底部弹窗里展示列表的话，是不是这个框架就不支持了哈

**Comment by kongzue** [comment]
或者请使用固定高度，自定义ListView为CustomView来实现，BottomMenu默认情况下是根据内容进行高度扩展高度的，同时要兼顾继承滑动列表和下滑关闭对话框。

**Comment by zhanghuibiao** [comment]
嗯嗯，好的，谢谢了
