### ISSUE TITLE
【BUG反馈】按钮字体样式消失，无颜色

### ISSUE THREAD

**Issue by zhuxu1** [kongzue/DialogX#195]
### 问题描述：
按钮字体样式消失，无颜色

### 设备信息：
APP安装的所有手机，Android11

代码环境：
minSdkVersion 19
targetSdkVersion 29
compileSdkVersion 29
implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.4.0"
implementation 'androidx.appcompat:appcompat:1.3.1'
implementation 'androidx.core:core-ktx:1.6.0'

### 是否在 Demo 中能复现此问题？
否

### 问题截图/视频

![01bb919b68f77867259d677fdacc1ca](https://user-images.githubusercontent.com/12688562/169189260-a56e7913-afe9-45ee-a96d-822aca23d79f.jpg)

`    implementation "com.github.kongzue.DialogX:DialogX:0.0.45.beta13"`

未对DialogX样式进行任何修改
切换IOS样式问题依旧
按钮可点击，点击有效果，但文字不显示

`MessageDialog.show("提示", "确定切换为该账号吗?", "切换", "点错了")
                                .setOkButtonClickListener(new OnDialogButtonClickListener<MessageDialog>() {
                                    @Override
                                    public boolean onClick(MessageDialog baseDialog, View v) {
                                        return false;
                                    }
                                });`
![image](https://user-images.githubusercontent.com/12688562/169189502-3cb8f93d-6718-40be-aa62-934baff69eb0.png)

**Comment by kongzue** [comment]
很抱歉无法确定原因，已尝试在Demo中使用相同代码进行测试未能复现此问题。
请尝试开启系统设置-开发者选项-显示布局边界确定按钮布局为何没有正常显示，以及使用Android Studio的Layout Inspector来确认布局情况，例如：
![image](https://user-images.githubusercontent.com/10115359/169189835-307df702-6025-40dc-8d6b-b23d5bb403f0.png)

**Comment by zhuxu1** [comment]
> 

布局显示正常，按下有正常点击阴影效果。
![129c36b60d41c430d880d270520cbd7](https://user-images.githubusercontent.com/12688562/169190272-291e2901-6b5b-4c13-946b-a41f364c944b.jpg)
![image](https://user-images.githubusercontent.com/12688562/169191044-143f8549-d4ff-4602-b62e-384af68c4920.png)

**Comment by kongzue** [comment]
猜测可能由系统暗色模式或其他因素导致的文字颜色反色。
请尝试设置：
```
//指定所有按钮文字样式
DialogX.buttonTextInfo = new TextInfo().setFontColor(Color.RED);
//单独制定ok按钮文字样式
DialogX.okButtonTextInfo = new TextInfo().setFontColor(Color.RED);
```
来设置按钮文字颜色

**Comment by kongzue** [comment]
默认情况下无定义是按照布局中定义的，你可以 [在这里](https://github.com/kongzue/DialogX/blob/3a1033c3ad78205d4cd2f7d6c232cb4bd40f8693/DialogX/src/main/res/layout/layout_dialogx_material.xml#L23) 找到默认对话框的布局文件中的按钮定义。

默认情况下文字使用颜色样式 `android:textColor="@color/black70"` 不排除您的项目中有其他框架或者同名的资源 `black70` 被覆盖定义了
