### ISSUE TITLE
系统权限申请弹窗大概率触发 onDetachedFromWindow 导致弹窗被关闭

### ISSUE THREAD

**Issue by j2yych** [kongzue/DialogX#196]
## BUG 反馈

请先确认您已阅读[《常见问题》](https://github.com/kongzue/DialogX/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)

### 问题描述：
请在此详细描述问题。

### 设备信息：
请在此说明您使用的设备型号、Android 版本等信息以协助我们排查问题

### 是否在 Demo 中能复现此问题？
是/否/未尝试

### 问题截图/视频
请在此插入佐证问题的截图和视频。

**Comment by kongzue** [comment]
无法理解你的意思，DialogX并不需要权限。

**Comment by j2yych** [comment]
进入应用展示一个更新弹窗。此刻当用户是初次安装时,提示用户授权定位等一系列权限。此刻在多个权限弹窗点击过程中会触发DialogXBaseRelativeLayout类的onDetachedFromWindow

**Comment by kongzue** [comment]
还是没理解你的意思，DialogXBaseRelativeLayout#onDetachedFromWindow 的触发并不是由 DialogX 主动发起的，当Activity被关闭，或者对话框关闭时，需要将对话框 UI 从当前界面卸载掉，此时会触发 DialogXBaseRelativeLayout#onDetachedFromWindow 是正常的，请检查你的代码逻辑。

**Comment by j2yych** [comment]
CustomDialog.show()的同时也弹出了系统权限申请弹窗,在定位权限申请dismiss后紧跟着申请语音权限,此刻触发了onDetachedFromWindow. 修改成CustomDialog.build().show(activity)后正常

**Comment by kongzue** [comment]
DialogX默认情况下是自动获取顶层topActivity的，根据你的描述应该是你的申请权限触发了新的Activity建立导致DialogX错误的在新Activity上显示了对话框，此时可以使用`.show(activity)`指定要显示在的Activity上。
此问题并非 DialogX 的问题，请检查你的业务逻辑。

**Comment by j2yych** [comment]
是的 理解了，感谢解答
