### ISSUE TITLE
当前页面dialog跑到上个页面显示

### ISSUE THREAD

**Issue by fuys123** [kongzue/DialogX#197]
SwipeBack侧滑返回，在当前页面想右滑返回，但是未返回上个页面的情况下，去点击当前页面的dialog发现在当前页面不显示，而是跑到上个页面显示了，系统的dialog则不会出现，请问是什么原因？ 依赖是最新版的。

**Comment by fuys123** [comment]
我手上 android10的会出现这种情况，而android12不会 品牌为小米

**Comment by kongzue** [comment]
请使用 `.show(activity)` 来启动 DialogX
DialogX默认情况下是自动获取当前的 topActivity，这依赖于 ActivityLifecycle 的回调，若有需要请自行指定要显示 Dialog 的 Activity 实例。
