### ISSUE TITLE
WaitDialog会影响webview渲染

### ISSUE THREAD

**Issue by zaceeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee** [kongzue/DialogX#199]
在一个webview页面，webview有一个列表，请求之前弹出WaitDialog，请求完成后dismissdialog，列表不会出来，换回dialogV3没有这个问题

**Comment by kongzue** [comment]
无法理解你的问题，请检查自己的代码是否存在问题。
DialogX 本质上就是个插入在 Activity 的前层 View，并不会对 webView 做任何操作，目前也尚未收到任何类似问题的反馈，建议自行排查问题的原因。

**Comment by zaceeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee** [comment]
以打开百度为例吧，新建一个最简单的webview页面，如果在loadurl之前调用WaitDialog.show("..")的话，那么搜索框下面那幅图就加载不出来（或者只能显示一半，有时候也能加载，但百分之80是出不来的），不加WaitDialog的话，显示是没问题的
![微信图片_20220530142414](https://user-images.githubusercontent.com/17674440/170929901-0d1d53c0-681b-44dd-9bba-e11cda7772dd.jpg)
![微信图片_20220530142419](https://user-images.githubusercontent.com/17674440/170929986-1d3492ac-5203-414e-9066-fe447015b349.jpg)

。

**Comment by kongzue** [comment]
很抱歉未能复现你所描述的问题，请检查是否存在其他可能影响渲染的情况。
测试设备：Google Pixel5(Android 13 beta2)、WebView版本101.0.4951.15
测试截图：
![image](https://user-images.githubusercontent.com/10115359/170933066-2eb08e59-1374-4f5b-bbad-7fe4f66c5185.png)

**Comment by kongzue** [comment]
长时间未回复暂时关闭了此问题，若有疑问请继续回复。
