### ISSUE TITLE
还是不一样

### ISSUE THREAD

**Issue by ytxyyt** [kongzue/DialogX#20]
![Screenshot_2021-02-25-22-00-37-80](https://user-images.githubusercontent.com/76242879/109164194-1d57a080-77b5-11eb-837f-dfcb006c7a48.png)
![Screenshot_2021-02-25-20-55-16-14](https://user-images.githubusercontent.com/76242879/109164202-1f216400-77b5-11eb-9f89-1c3832df2475.png)
和你软件还是不一样，宽度对了，长度不对啊？

**Comment by kongzue** [comment]
感觉你这个版本的安卓系统问题挺大啊，这可能是margin相关的属性也有问题

________________________________
发件人: ytxyyt <notifications@github.com>
发送时间: Thursday, February 25, 2021 10:03:25 PM
收件人: kongzue/DialogX <DialogX@noreply.github.com>
抄送: Subscribed <subscribed@noreply.github.com>
主题: [kongzue/DialogX] 还是不一样 (#20)


[Screenshot_2021-02-25-22-00-37-80]<https://apac01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F76242879%2F109164194-1d57a080-77b5-11eb-837f-dfcb006c7a48.png&data=04%7C01%7C%7C95f52640cc524aeadb2c08d8d9961fe6%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637498586082480707%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=Tw9g4nKMyzSHkMpNVcY7vA9SABb6us7yRJOR6ADdfBM%3D&reserved=0>
[Screenshot_2021-02-25-20-55-16-14]<https://apac01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F76242879%2F109164202-1f216400-77b5-11eb-9f89-1c3832df2475.png&data=04%7C01%7C%7C95f52640cc524aeadb2c08d8d9961fe6%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637498586082480707%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=7B3NaBwQYDa%2FdTMitWt8O3Osaucp3eLfbIbLjRDJcE4%3D&reserved=0>
和你软件还是不一样，宽度对了，长度不对啊？

―

**Comment by ytxyyt** [comment]
怎么解决啊？

**Comment by kongzue** [comment]
其实最正确的方法是让厂商去更新至最新版本的AOSP，但这不太现实。我再改一版吧

**Comment by ytxyyt** [comment]
谢谢

**Comment by ytxyyt** [comment]
辛苦你们了

**Comment by kongzue** [comment]
麻烦检查下你的AndroidManifest.xml是否包含了android:supportsRtl="true"，这也可能导致这个属性失效

**Comment by ytxyyt** [comment]
没有

**Comment by kongzue** [comment]
请更新至0.0.32.beta2版本。

**Comment by ytxyyt** [comment]
正常了，谢谢，辛苦你们了
