### ISSUE TITLE
【BUG反馈】WeakReference.get()空指针

### ISSUE THREAD

**Issue by yinli155** [kongzue/DialogX#201]
06-05 17:59:17.275 27858 27858 E AndroidRuntime: Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object java.lang.ref.WeakReference.get()' on a null object reference
06-05 17:59:17.275 27858 27858 E AndroidRuntime: 	at com.kongzue.dialogx.interfaces.BaseDialog.show(BaseDialog.java:152)
06-05 17:59:17.275 27858 27858 E AndroidRuntime: 	at com.kongzue.dialogx.dialogs.MessageDialog.show(MessageDialog.java:214)
06-05 17:59:17.275 27858 27858 E AndroidRuntime: 	at com.mubei.android.activity.MainActivity.onCreate(MainActivity.java:79)
06-05 17:59:17.275 27858 27858 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:8129)
06-05 17:59:17.275 27858 27858 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:8109)
06-05 17:59:17.275 27858 27858 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1344)
06-05 17:59:17.275 27858 27858 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3750)
06-05 17:59:17.275 27858 27858 E AndroidRuntime: 	... 12 more

**Comment by kongzue** [comment]
是否有按照文档进行初始化，另外请问正在使用的版本是否为最新？

**Comment by yinli155** [comment]
> 是否有按照文档进行的初始版本，另外要求正在使用的是否为最新？

抱歉，我忘记初始化了，现在没问题了

**Comment by kongzue** [comment]
理论上有防呆设计，如果没有初始化会自动尝试反射获取顶层Activity完成初始化，但如果一进入界面立即要显示对话框可能就糟了...初始化的需要过程的可能反应不及

**Comment by yinli155** [comment]
> 

原来如此

**Comment by kongzue** [comment]
先关闭此问题了，如有疑问可继续回复，或者加反馈群随时沟通。
