### ISSUE TITLE
能加将加载成功或失败的动画加快速度

### ISSUE THREAD

**Issue by StriveForLaity** [kongzue/DialogX#204]
![image](https://user-images.githubusercontent.com/56580749/172517884-b3ab238c-1af2-4dae-860d-19cf1ab44330.png)

**Comment by kongzue** [comment]
https://github.com/kongzue/DialogX/wiki/%E7%AD%89%E5%BE%85%E6%A1%86-WaitDialog-%E5%92%8C%E6%8F%90%E7%A4%BA%E6%A1%86-TipDialog
![image](https://user-images.githubusercontent.com/10115359/172517973-51620222-d3ca-436c-9620-fbe9ae899590.png)

**Comment by StriveForLaity** [comment]
万分感谢
