### ISSUE TITLE
【BUG反馈】您好 请问, CustomDialog.show() 的布局中含有EditTextView的时候, 为什么弹出没有自动获取到焦点并弹出软键盘?

### ISSUE THREAD

**Issue by VihanTest** [kongzue/DialogX#205]

**Comment by kongzue** [comment]
因为我不可能预知你的输入框对象

________________________________
发件人: VihanTest ***@***.***>
发送时间: Friday, June 10, 2022 2:10:26 PM
收件人: kongzue/DialogX ***@***.***>
抄送: Subscribed ***@***.***>
主题: [kongzue/DialogX] 【BUG反馈】您好 请问, CustomDialog.show() 的布局中含有EditTextView的时候, 为什么弹出没有自动获取到焦点并弹出软键盘? (Issue #205)


―

**Comment by VihanTest** [comment]
感谢您对我愚蠢问题的快速回复,在您的源代码中我看到了相关的解决代码, 非常感谢!
