### ISSUE TITLE
【功能建议】请填写标题

### ISSUE THREAD

**Issue by KunMinX** [kongzue/DialogX#209]
### 需求描述：
请详细描述你的需求。

目前 popMenu 难实现自定义样式，因背景强制白框，且如未提供 menulist 则报错。

```java
PopMenu.build()
        .setCustomView(new OnBindView<PopMenu>(R.layout.layout_custom_view) {
            @Override
            public void onBind(PopMenu dialog, View v) {
                
            }
        })
        //.setMenuList(new String[]{"选项1", "选项2", "选项3"})
        .show();

```

需求：popMenu 同 customDialog 使用，只是多一 align 某 View

**Comment by KunMinX** [comment]
通过继承重写 MaterialStyle 解决了。
各种 DialogRes 和 settings 接口方法建议 java 8 default 声明，如此开发者实现接口时可仅修改所选。

**Comment by kongzue** [comment]
未预料到的用法。
正在尝试对PopMenu进行无菜单内容显示支持，以及为CustomDialog添加Align支持

**Comment by kongzue** [comment]
将于下一版本更新：
- PopMenu 不限制是否设置 list；
- CustomDialog 支持 `setAlignBaseViewGravity(...)` 可绑定一个 baseView 并基于其四周对齐，也可设置相对于 baseView 的四周间距（margin）；
预览图如下：
![image](https://user-images.githubusercontent.com/10115359/175777740-01e1e306-7ca9-4d34-8259-8eb64c2d8351.png)
目前正在进行接口设计、debug和收尾工作，预计两天内更新。

**Comment by kongzue** [comment]
请更新至0.0.45.beta19
- CustomDialog 增加 setAlignBaseViewGravity(...) 相关设置以绑定围绕一个 view 周围显示对话框；
- CustomDialog 增加 setBaseViewMargin(...) 及相关单独设置，以设置围绕 view 周围显示时的间距；
- CustomDialog 增加 setWidth(...) 和 setHeight(...) 相关设置可直接设置对话框内容布局的宽度和高度；
- PopMenu 支持设置空菜单；
