### ISSUE TITLE
无法在onBackPressed中关闭WaitDialog

### ISSUE THREAD

**Issue by 1849323938** [kongzue/DialogX#21]
@Override
    public void onBackPressed() {
        super.onBackPressed();
        WaitDialog.dismiss();
    }

此处调用WaitDialog无法消失

**Comment by kongzue** [comment]
虽然问题已关闭，但还是说明一下比较好。
要让WaitDialog可以在按返回键时关闭，如果是全局的需求可以这样设置：
```
DialogX.cancelableTipDialog=true;
```
但如果针对单独的一个WaitDialog，请勿在Activity中重写`onBackPressed()`进行处理，因此此事件在WaitDialog显示时是无法触达的，请按照以下方式处理：
```
WaitDialog.show("Please Wait!").setOnBackPressedListener(new OnBackPressedListener() {
    @Override
    public boolean onBackPressed() {
        //返回值为false则不处理，返回值为true则允许关闭
        return true;
    }
});
```
