### ISSUE TITLE
【BUG反馈】等待+对话框提示 最后屏幕会闪烁一下

### ISSUE THREAD

**Issue by SillyBoy93** [kongzue/DialogX#210]
### 问题描述：
在0.0.45.beta18之后的版本，等待+对话框提示 最后屏幕会闪烁一下

### 设备信息：
OPPO R15 ，Android 10

### 是否在 Demo 中能复现此问题？
是

**Comment by kongzue** [comment]
很抱歉未能在0.0.45.beta19中复现你所描述的问题。
测试设备：Google Pixel5(Android 12 beta2)
测试视频：

https://user-images.githubusercontent.com/10115359/176337589-cac7571a-be42-4c17-aede-ef9f4ed30317.mp4

**Comment by kongzue** [comment]
已确定在WaitDialog切换状态时会触发问题，正在寻找解决方案

**Comment by kongzue** [comment]
已确认将在下一个版本修复。此问题触发的原因是为了解决 [issues:207](https://github.com/kongzue/DialogX/issues/207)

**Comment by kongzue** [comment]
请更新至版本 [0.0.45.beta20](https://github.com/kongzue/DialogX/releases/tag/0.0.45.beta20)

**Comment by SillyBoy93** [comment]
感谢
