### ISSUE TITLE
调佣拍照返回等待对话框不显示

### ISSUE THREAD

**Issue by ruoLing-0115** [kongzue/DialogX#212]
## BUG 反馈

请先确认您已阅读[《常见问题》](https://github.com/kongzue/DialogX/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)

### 问题描述：
调佣拍照返回等待对话框不显示，控制台有显示WaitDialog show

### 设备信息：
小米6

### 是否在 Demo 中能复现此问题？
未尝试

### 问题截图/视频
![image](https://user-images.githubusercontent.com/75604491/176809375-25ea6753-06ef-4ed7-89ff-f86dbff519f8.png)

**Comment by kongzue** [comment]
拍照界面是否为自己软件内的实现？
若是，请尝试指定要对话框显示的activity：
```
WaitDialog.show(activity, "message");
```
此问题原因是 DialogX 本身会自动侦测当前的顶部界面 topActivity，来显示对话框，但在关闭界面后立即显示对话框可能存在 ActivityLifecycleCallbacks 回调未能及时告知 DialogX 界面发生变化导致对话框在已经处于待 destroy 的 activity 上显示，此时只需要指定要显示在的界面即可。

**Comment by ruoLing-0115** [comment]
关闭时也需要带上 
activity 吗

**Comment by ruoLing-0115** [comment]
WaitDialog.dismiss(activity);

**Comment by kongzue** [comment]
不需要，dismiss没有context参数。
