### ISSUE TITLE
【功能建议】BottomDialog 能否支持设置圆角大小

### ISSUE THREAD

**Issue by shejishi** [kongzue/DialogX#214]
## 功能建议

`BottomDialog` 能否支持设置圆角大小

### 需求描述：

在使用`BottomDialog`的时候使用自定义`layout`， 发现设计稿出现圆角大小和框架不符的情况，在查看源码后发现 `MaxRelativeLayout # bkg`这个`view` 设置了固定的 `rect_dialogx_material_bottom_bkg_light`  `drawable`，希望可以有方法在 `DialogXStyle.BottomDialogRes` 接口中实现修改弹窗的圆角`上` 、`下`、`左`、`右`大小

**Comment by shejishi** [comment]
因为大部分设计稿弹窗样式差不多，目前解决方案是复制了`rect_dialogx_material_bottom_bkg_light `这个文件到`app`项目中，修改了圆角的大小

**Comment by kongzue** [comment]
圆角并非通过代码控制，目前建议还是通过覆写背景资源来实现。

**Comment by shejishi** [comment]
> 圆角并非通过代码控制，目前建议还是通过覆写背景资源来实现。

但是这样的可扩展性不是很强，设计稿都必须要做到统一才行

**Comment by kongzue** [comment]
针对有强设计要求的情况，个人建议定制主题，DialogX提供了丰富的主体定制接口，如有需要也可以联系我进行定做。
________________________________
发件人: shejishi ***@***.***>
发送时间: 2022年7月4日 12:49
收件人: kongzue/DialogX ***@***.***>
抄送: Kongzue ***@***.***>; Comment ***@***.***>
主题: Re: [kongzue/DialogX] 【功能建议】BottomDialog 能否支持设置圆角大小 (Issue #214)


圆角并非通过代码控制，目前建议还是通过覆写背景资源来实现。

但是这样的可扩展性不是很强，设计稿都必须要做到统一才行

―
