### ISSUE TITLE
兼容问题

### ISSUE THREAD

**Issue by Ag-gu** [kongzue/DialogX#215]
请问兼容Android 4.4吗？

**Comment by kongzue** [comment]
最低支持到API-19
________________________________
发件人: Ag ***@***.***>
发送时间: 2022年7月6日 10:26
收件人: kongzue/DialogX ***@***.***>
抄送: Subscribed ***@***.***>
主题: [kongzue/DialogX] 兼容问题 (Issue #215)


请问兼容Android 4.4吗？

―

**Comment by kongzue** [comment]
setCancelable(false)
________________________________
发件人: Ag ***@***.***>
发送时间: Wednesday, July 6, 2022 11:23:56 PM
收件人: kongzue/DialogX ***@***.***>
抄送: Kongzue ***@***.***>; Mention ***@***.***>
主题: Re: [kongzue/DialogX] 兼容问题 (Issue #215)


@kongzue<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fkongzue&data=05%7C01%7C%7C018fe8d054264785f1df08da5f638b0d%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637927178438482460%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=sXxI1mEcZcAks4PXR858Y%2F074EFUJ1DCIftJ%2FYaXS4c%3D&reserved=0> 谢谢，还有一个问题就是自定义的dialog没有方法设置点击其他区域不要消亡dialog吗？我想实现的操作是 只有当点击dialog上的按钮才会触发关闭，看了一下文档并没有这方面的说明

―

**Comment by Ag-gu** [comment]
我自己在代码找到了， 不过还是非常感谢，很好用的组件！！
