### ISSUE TITLE
【BUG反馈】dismiss动画的时候还可以点击

### ISSUE THREAD

**Issue by super-cc** [kongzue/DialogX#216]
### 问题描述：
我在使用PopMenu.show()方法时，然后进行了PopMenu的dismiss，PopMenu几乎已经全部消失，但在没有完全消失的时候，依然可以点击到Menu，应该在dismiss的时候，不进行点击回调，或增加开关。

### 设备信息：
此问题和设备无关。

### 是否在 Demo 中能复现此问题？
是

### 问题截图/视频
暂无截图/视频

**Comment by kongzue** [comment]
将会进行验证，预计在下一版本处理
________________________________
发件人: Super丶C ***@***.***>
发送时间: 2022年7月7日 7:30
收件人: kongzue/DialogX ***@***.***>
抄送: Subscribed ***@***.***>
主题: [kongzue/DialogX] 【BUG反馈】dismiss动画的时候还可以点击 (Issue #216)


BUG 反馈
问题描述：

我在使用PopMenu.show()方法时，然后进行了PopMenu的dismiss，PopMenu几乎已经全部消失，但在没有完全消失的时候，依然可以点击到Menu，应该在dismiss的时候，不进行点击回调，或增加开关。

设备信息：

此问题和设备无关。

是否在 Demo 中能复现此问题？

是

问题截图/视频

暂无截图/视频

―

**Comment by kongzue** [comment]
请更新至 0.0.45.beta22，版本日志详见：https://github.com/kongzue/DialogX/releases/tag/0.0.45.beta22

**Comment by super-cc** [comment]
@kongzue 其实还有个问题，不知道你那边能复现不能，我在PopMenu.show()的时候，这个PopMenu会先展示在左上角，很快啊，很快会展示到正确位置。会有闪的一下，而且偶而还会展示不到正确的位置，偶而。

**Comment by kongzue** [comment]
很抱歉未能复现，我们有在 Google Pixel5(Android 13) 测试绑定或非绑定 view 的PopMenu菜单均未发现问题

**Comment by super-cc** [comment]
@kongzue 刚才我说的问题，demo没有复现，有一个重要的点，我用的是Fragment，不知道有没有影响。

**Comment by kongzue** [comment]
应该没有影响，因为Dialog X实际上是在activity上显示的
________________________________
发件人: Super丶C ***@***.***>
发送时间: Friday, July 8, 2022 7:20:17 PM
收件人: kongzue/DialogX ***@***.***>
抄送: Kongzue ***@***.***>; Mention ***@***.***>
主题: Re: [kongzue/DialogX] 【BUG反馈】dismiss动画的时候还可以点击 (Issue #216)


@kongzue<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fkongzue&data=05%7C01%7C%7C126f04cfbb744bdd35dd08da60d3d643%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637928760237164191%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=5v5iXR7JkZYBYjZIxC6Ox41YTUQPKw352T5my8NfroA%3D&reserved=0> 刚才我说的问题，demo没有复现，有一个重要的点，我用的是Fragment，不知道有没有影响。

―

**Comment by super-cc** [comment]
找到复现的方法了，DialogX.IMPL_MODE.VIEW 不会出现这种情况，当使用 DialogX.IMPL_MODE.DIALOG_FRAGMENT 时，就会出现我所说的情况，使用Demo也可以复现。

**Comment by kongzue** [comment]
> DialogX.IMPL_MODE.VIEW 不会出现这种情况，当使用 DialogX.IMPL_MODE.DIALOG_FRAGMENT 时，就会出现我所说的情况，使用Demo也可以复现。

实现方式不同可能出现未知的问题，请注意除了 View 模式，其他模式目前都处于测试阶段。

**Comment by super-cc** [comment]
在代码中我发现，如果是 DIALOG_FRAGMENT 模式会直接进行 show() ，而 View 模式的话则不会.

**Comment by kongzue** [comment]
除了View模式，其他模式均是基于Window的，这也可能有影响，因为PopMenu依赖于绑定的View获取其屏幕位置

**Comment by super-cc** [comment]
根据我的观察，位置的计算是放在了 addOnPreDrawListener，但很多情况是传进来的时候，就可以直接拿到了 baseView 的位置。能讲讲你把位置计算放到 addOnPreDrawListener 的原因吗？我之前也是这么做的，不过现在忘了当时是为什么了。

**Comment by kongzue** [comment]
因为有概率存在绑定的view不一定处于已显示状态，或者activity刚刚构建，view的位置还未确定的情况，因此需要等待其被绘制再进行获取。事实上也可以使用 addOnGlobalLayoutListener，我也忘记当时怎么选择的 addOnPreDrawListener  了。
