### ISSUE TITLE
WaitDialog 如何设置id:bkg的背景颜色呢？

### ISSUE THREAD

**Issue by Fun-Pepper** [kongzue/DialogX#217]
WaitDialog 如何设置id:bkg的背景颜色呢？一直没有找到设置的入口

**Comment by Fun-Pepper** [comment]
![5111657507028_ pic](https://user-images.githubusercontent.com/83764156/178178574-3091c9b9-28b6-4d50-955e-b83f20ef5a5f.jpg)

**Comment by kongzue** [comment]
请尝试 `.setBackgroundColor(colotInt)`
例如：
```
WaitDialog.show("Please Wait!").setBackgroundColor(Color.RED)
```
