### ISSUE TITLE
【BUG反馈】

### ISSUE THREAD

**Issue by super-cc** [kongzue/DialogX#218]
### 问题描述：
在使用 PopMenu 进行展示时，我可能会随时修改传入的 menuList，所以在 PopMenu 进行初始化的时候，应该是将 menuList 进行一次重新的add添加，否则当我在外部修改 menuList 的时候，就会发生闪退，闪退的日志如下：
``` log
java.lang.IllegalStateException: The content of the adapter has changed but ListView did not receive a notification. Make sure the content of your adapter is not modified from a background thread, but only from the UI thread. Make sure your adapter calls notifyDataSetChanged() when its content changes. [in ListView(2131231193, class com.kongzue.dialogx.util.views.PopMenuListView) with Adapter(class com.kongzue.dialogx.util.PopMenuArrayAdapter)]
```
希望可以尽快修复一下，感谢。

**Comment by kongzue** [comment]
没理解你的意思，根据错误日志是没有在主线程执行。

**Comment by super-cc** [comment]
我重新整理一下语言，log 报的是你的库中在使用ListView的时候的问题，可以这样复现，我将 menuList 传入到 PopMenu 中，然后我在外部将 menuList 进行了修改，在这时，就会发生闪退，因为对于 ListView 来讲，数据发生了变化，但又没有进行 notifyDataSetChanged，这时数据和 UI 就对不上了，然后发生的闪退，所以库中 PopMenu 应将我传入的 menuList 进行addAll 到库中自己的 List 当中，这样就可以避免这样的闪退。

**Comment by super-cc** [comment]
不知道这次我有没有描述清楚。

**Comment by kongzue** [comment]
是使用`setMenuList(...)`进行的设置么？正在排查

**Comment by super-cc** [comment]
不是，是使用 PopMenu.show(view, items) ，随后我对 items 进行了修改。对于我的代码来讲，items 是共用的，而且是会变化的。

**Comment by kongzue** [comment]
是需要在 `setMenuList(...)` 时更新 menu 列表么？

**Comment by super-cc** [comment]
不是，是我在改了要传入的 menuList 的时候，会闪退。

**Comment by super-cc** [comment]
因为随后我对传入的 menuList 进行了修改。对于我的代码来讲，menuList 是共用的，而且是会变化的。

**Comment by kongzue** [comment]
很抱歉我这边未能在Demo中复现，目前版本Demo的表现是`setMenuList(...)`执行后不刷新界面上的列表，这与预期表现不符，此问题会在下一版本修复，但你所提到的menuList 进行了修改，需要重新执行`setMenuList(...)`才能刷新PopMenu，PopMenu并不包含DataWatcher功能，需要手动执行方法刷新界面。

**Comment by super-cc** [comment]
我再换一种描述方式，对于 ListView 来讲，传入 ListView 的 List 数据是可以修改的，不过如果修改了数据，必须要进行 notifyDataSetChanged，不然就会出现数据和 UI 对不上的情况，就会导致闪退。 PopMenu 使用了 ListView，对于现在的 PopMenu 来讲传入的 List 是不可以修改，不然就会造成我刚才讲的闪退，但是我现在的需求是外面的 List 是可变的，我需要修改他，在下次 show PopMenu 的时候，列表的数据是需要不一样的，所以内部不应该直接使用我传入的 List ，也就是不要用赋值的操作，而应该 new 一个 List 然后使用 addAll 的方式。

**Comment by super-cc** [comment]
复现很容易，我给你写段伪代码。
``` java
List<CharSequence> items = new ArrayList();
items.add("选项1");
items.add("选项2");
items.add("选项3");
PopMenu.show(view, items);

//会造成闪退的代码
items.add("选项4");
```

**Comment by kongzue** [comment]
很抱歉未能复现此错误，上述代码在最新版本的Demo中执行正常，没有发生崩溃

**Comment by super-cc** [comment]
复现很容易，我给你写段伪代码，刚才写的代码不够全面。
``` java
List<CharSequence> items = new ArrayList();
items.add("选项1");
items.add("选项2");
items.add("选项3");
PopMenu.show(view, items);

//会造成闪退的代码
new Thread(new Runable{
    for(int i = 0; i < 10000; i++) {
        items.clear();
        items.add("选项4");
    }
}).start()
```

**Comment by super-cc** [comment]
原因我刚才描述错了，重新梳理一下，就是当 ListView 在使用传入的 List 的时候，同时数据也在发生变化，这样就会造成闪退，因为 ListView 拿数据的时候会有点晕。

**Comment by kongzue** [comment]
很抱歉依然未能复现你所描述的问题。
在Google Pixel5(Android 13 beta2)上调试通过，运行结果如图：
![image](https://user-images.githubusercontent.com/10115359/178708953-d4bd7a8a-e8a1-4479-a740-bd91d8ab7569.png)

**Comment by kongzue** [comment]
发现问题，在 thread 中加入 sleep 后发生 crash

**Comment by super-cc** [comment]
我这边不需要 sleep，你加上循环久一些，可能是时间不够久。这个时机就是 ListView 正在使用 List 数据的时候，刚好 List 也在发生变化，产生的闪退，所以只需要不直接使用我传入的 List 数据，而是在 PopMenu 里复制一份自己用的，就好了，不要使用同一个 List 对象。

**Comment by kongzue** [comment]
这个应该是ListView本身的问题。目前我的解决方案是在 ListView 中重写：
```
@Override
protected void layoutChildren() {
    try{
        super.layoutChildren();
    }catch (IllegalStateException e){
        ((BaseAdapter)getAdapter()).notifyDataSetChanged();
        super.layoutChildren();
    }
}
```
其表现为，当数据发生变化后只要触发此问题，会强制刷新列表后继续执行。

**Comment by super-cc** [comment]
我认为 try catch 不是好的解决方式，而是去防止数据随意发生变化，比如我一直有在提到的解决方案。

**Comment by kongzue** [comment]
但也存在在 PopMenu 运行中需要对菜单进行修改的需求，此时若对于 menuList 直接进行 newArray 可能造成 adapter 无法关联并刷新菜单的问题，我正在思考合理的解决方案。

**Comment by kongzue** [comment]
做不到，原因是 DialogX 必须等待主线程执行

**Comment by super-cc** [comment]
大佬，你听我的试一下，保证不会闪退，我打包票。

**Comment by kongzue** [comment]
这种情况下只按照你的想法去处理会导致菜单无法刷新

**Comment by kongzue** [comment]
预期的合理方案为：
1.`setMenuList(...)` 必 newArray 来承载需要设置的数据内容；
2.当用户在 PopMenu 已经处于运行状态中使用 `setMenuList(...)` 修改数据的情况，当 `DialogImpl#refreshUI()` 检测到当前 listView 的 adapter 中的 menuList 内存指针和当前 PopMenu 的 menuList 不一致时，强行重新创建 adapter

**Comment by super-cc** [comment]
如果你还会担心有人在使用的时候在子线程进行 setMenuList 的话，你可以在 setMenuList 上加上注解 @MainThread ，这样也能避免问题。

**Comment by kongzue** [comment]
DialogX 必须尽可能的自己考虑线程，而不是要求用户去处理线程问题。

**Comment by kongzue** [comment]
按照上述预期的合理方案，既能满足你的想法，也能兼顾需要更新菜单内容的用户。

**Comment by super-cc** [comment]
那你可以自己去 post 到主线程呀，而且你本身如果传入的是 CharSequence[] 类型，你就是会去 new 一个呀，所以有什么区别呢？

**Comment by kongzue** [comment]
对啊，请仔细阅读我刚刚发的预期的合理方案

**Comment by kongzue** [comment]
我没否认你的修改建议，但我必须兼顾需要更新菜单内容的用户，这两者并不冲突

**Comment by super-cc** [comment]
而我所说的解决方案，很简单，并不需要影响到老用户。只需要 public PopMenu setMenuList(List<CharSequence> menuList) 里和 public PopMenu setMenuList(String[] menuList) 一样，都是 new ArrayList<>() ，然后再 addAll() ，就解决了。

**Comment by kongzue** [comment]
是这样的啊

**Comment by kongzue** [comment]
![image](https://user-images.githubusercontent.com/10115359/178713779-90d5063c-2128-4991-8376-35842d56533a.png)
我没否认你的建议

**Comment by kongzue** [comment]
只是额外的：

**Comment by super-cc** [comment]
了解了，要不这样，你更新一版，我看一下代码得了。可能在这交流不是很好描述。

**Comment by super-cc** [comment]
我懂了，你只是将 notifyDataSetChanged 的时机改到了其它地方，了解了。

**Comment by super-cc** [comment]
更新好新的一版请发我哦，谢谢了，我这边今天需要发版，感谢。

**Comment by super-cc** [comment]
大佬之前是写 c/c++ 的吗？经常用指针这样的词，其实不是指针发生变化，是数据发生变化 。

**Comment by kongzue** [comment]
请更新至 0.0.45.beta24 版本，更新日志在：https://github.com/kongzue/DialogX/releases/tag/0.0.45.beta24

**Comment by super-cc** [comment]
好的，谢谢了，已更新。

**Comment by kongzue** [comment]
新版本已经处理了，全部会在设置 list 的时候转移到一个新的 list 拷贝，这样不会出现问题了

**Comment by super-cc** [comment]
大佬请确认一下aar包没问题，我这边看aar包中的代码没有更新，是不是upload失败了。

**Comment by kongzue** [comment]
提交日志在这里：https://github.com/kongzue/DialogX/commit/8103602f2105240dcf1571605e1f439a83c0b550

**Comment by super-cc** [comment]
我这里显示的还不是对，要不大佬在demo里看一下。
![image](https://user-images.githubusercontent.com/26076424/178717761-35ffe712-aef8-40b4-b957-19492a93e270.png)

**Comment by super-cc** [comment]
一共还有3处使用的 this.menuList = menuList;

**Comment by kongzue** [comment]
好的，稍等

**Comment by super-cc** [comment]
麻烦了。

**Comment by kongzue** [comment]
我这边刚刚调试没有用 view参数

**Comment by super-cc** [comment]
赞
