### ISSUE TITLE
【功能建议】底部对话框滑动关闭阙值

### ISSUE THREAD

**Issue by lantee** [kongzue/DialogX#219]
## 功能建议
希望可以自定义设置滑动关闭的阙值（目前代码里看到是35dp）
### 需求描述：
可能觉得过于敏感希望可以自定义..

**Comment by kongzue** [comment]
收到，会考虑合理的修改方式
________________________________
发件人: lantee ***@***.***>
发送时间: 2022年7月14日 8:38
收件人: kongzue/DialogX ***@***.***>
抄送: Subscribed ***@***.***>
主题: [kongzue/DialogX] 【功能建议】底部对话框滑动关闭阙值 (Issue #219)


功能建议

希望可以自定义设置滑动关闭的阙值（目前代码里看到是35dp）

需求描述：

可能觉得过于敏感希望可以自定义..

―

**Comment by kongzue** [comment]
请更新至 [0.0.45](https://github.com/kongzue/DialogX/releases/tag/0.0.45) 版本：
- 新增设置 DialogX.touchSlideTriggerThreshold = (int) 影响触摸滑动触发阈值，影响 BottomDialog、FullScreenDialog 下滑关闭触发距离，单位：像素；
