### ISSUE TITLE
怎么实现网易云这种效果

### ISSUE THREAD

**Issue by AndyYw** [kongzue/DialogX#220]
![lQDPJxaBmJTm91vNBgrNAsyw0V521wKkUN0C1WV8EIBPAA_716_1546](https://user-images.githubusercontent.com/21366609/179437126-8802f6b6-7606-4f70-be0d-54fd72dab819.jpg)

**Comment by AndyYw** [comment]
顶部是固定的。下面是可以滚动的列表。滚动到顶部才可以拖拽dialog.试过setCustomView方法 ，但还没有滚动到顶部就可以托拽dialog。

**Comment by kongzue** [comment]
请使用bottomdialog配合自定义布局实现。dialogx不提供具体实现，请自行完成开发，如有定制需求可加群询问
________________________________
发件人: AndyYw ***@***.***>
发送时间: Monday, July 18, 2022 10:32:02 AM
收件人: kongzue/DialogX ***@***.***>
抄送: Subscribed ***@***.***>
主题: [kongzue/DialogX] 怎么实现网易云这种效果 (Issue #220)


[lQDPJxaBmJTm91vNBgrNAsyw0V521wKkUN0C1WV8EIBPAA_716_1546]<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F21366609%2F179437126-8802f6b6-7606-4f70-be0d-54fd72dab819.jpg&data=05%7C01%7C%7C80a55b7989194efb4c1008da6865b349%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637937083263357365%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=e6jeiL6e%2B9poPqMgN9ZUeatUbQ5e765yFyRErIiI4Ks%3D&reserved=0>

―

**Comment by kongzue** [comment]
没理解你的意思，可以参考drmo，dialogx是支持自定义布局的触控操作的，如果你要实现兼容滑动，请参阅wiki文档中关于滑动处理相关部分
________________________________
发件人: AndyYw ***@***.***>
发送时间: Monday, July 18, 2022 10:33:49 AM
收件人: kongzue/DialogX ***@***.***>
抄送: Kongzue ***@***.***>; Comment ***@***.***>
主题: Re: [kongzue/DialogX] 怎么实现网易云这种效果 (Issue #220)


顶部是固定的。下面是可以滚动的列表。滚动到顶部才可以拖拽dialog.试过setCustomView方法 ，但还没有滚动到顶部就可以托拽dialog。

―

**Comment by AndyYw** [comment]
好的 我看看 谢谢

**Comment by kongzue** [comment]
刚刚在室外不太好直接帮你找，你可以在这里看到解决方案：[DialogX Wiki](https://github.com/kongzue/DialogX/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98#q%E5%9C%A8-bottomdialog-%E5%92%8C-fullscreendialog-%E5%AF%B9%E8%AF%9D%E6%A1%86%E4%B8%AD%E8%AE%A9%E8%87%AA%E5%B7%B1%E7%9A%84%E6%BB%91%E5%8A%A8%E5%B8%83%E5%B1%80%E6%94%AF%E6%8C%81%E6%BB%91%E5%8A%A8%E7%BB%A7%E6%89%BF)
![image](https://user-images.githubusercontent.com/10115359/179443108-1600f5ae-21a6-47cd-867f-563980f66bc0.png)

**Comment by AndyYw** [comment]
非常感谢大佬。
