### ISSUE TITLE
【功能建议】PopMenu文字显示优化

### ISSUE THREAD

**Issue by super-cc** [kongzue/DialogX#221]
### 需求描述：
在使用 PopMenu 的时候，菜单和宽度和传入的 View 的宽度一样，这样会导致有些文字就显示不全了，这令我比较苦恼，自己业务层去计算宽度也是一件比较麻烦的事，所以不知道大佬有没有什么优化方案。

**Comment by kongzue** [comment]
请使用 `.setWidth(int)`，例如：
```
PopMenu.show(v,new String[]{"添加", "编辑", "删除", "分享"})
        .setWidth(dip2px(200));    //单位：像素
```
运行情况如图：
![image](https://user-images.githubusercontent.com/10115359/179746070-4a02d77c-b1f6-46b6-85c7-266d8aa006e6.png)

**Comment by super-cc** [comment]
是因为有一些数据是来自网络，所以我并不知道宽度是多少，除非自己计算，自己计算的话又不知道menu里文字的字号以及pading的大小。

**Comment by kongzue** [comment]
你可以在这里找到布局文件：DialogX/layout_dialogx_popmenu_material.xml (github.com)<https://github.com/kongzue/DialogX/blob/master/DialogX/src/main/res/layout/layout_dialogx_popmenu_material.xml>
________________________________
发件人: Super丶C ***@***.***>
发送时间: 2022年7月27日 9:58
收件人: kongzue/DialogX ***@***.***>
抄送: Kongzue ***@***.***>; Comment ***@***.***>
主题: Re: [kongzue/DialogX] 【功能建议】PopMenu文字显示优化 (Issue #221)


是因为有一些数据是来自网络，所以我并不知道宽度是多少，除非自己计算，自己计算的话又不知道menu里文字的字号以及pading的大小。

―

**Comment by kongzue** [comment]
长时间无回复暂时关闭了此问题，若有疑问请继续回复
