### ISSUE TITLE
可以加一个自定义PopTip的主题的功能吗

### ISSUE THREAD

**Issue by cwuom** [kongzue/DialogX#222]
我比较喜欢KongzueStyle样式的PopTip 但是只能全局设置 能不能单独设置一个组件的样式呢

**Comment by kongzue** [comment]
很抱歉该样式会在下一版被修改，预期的修改结果如下：
![image](https://user-images.githubusercontent.com/10115359/179878374-b057540c-000a-4ce4-a521-8f9174e26c71.png)
设计变更说明
Kongzue主题的PopTip组件表现形式将会在下一个版本中，更换为新的样式，修改原因为 PopTip 组件将保持以类似于吐司的简单提示为目标进行设计，“通知”功能应当交由更专注的新组件完成，下一版本中还会增加 PopNotification 的组件用于完成类似于系统通知样式的消息提示，会从屏幕顶端向下滑出进行展示，与 PopTip 类似，不会打断用户操作。
上述变更不涉及 iOS 主题，iOS主题的 PopTip 依然与现在保持不变。

我们会新增新组件 PopNotification，它会完成，默认样式如下：
![image](https://user-images.githubusercontent.com/10115359/179878521-6f9d1e8e-ab5b-4f6c-a7fd-b29539304c83.png)
此功能和PopTip类似，但默认可点击，从屏幕上方滑出/小消失，拥有更大的图片，且支持设置 Bitmap 以及 Drawable（PopTip 不支持），你也可以选择一句话的提示
![image](https://user-images.githubusercontent.com/10115359/179878583-0faa92d7-785a-4158-a8f4-10877e6050d4.png)


与系统 Notification 的区别在于易用性更高，且不需要申请通知渠道，但缺点在于：与 PopTip 一样，无法跨界面显示，无法在后台使用（并非真正意义上的悬浮窗），建议只在软件内，处于前台情况下，需要类似于通知的提示时使用。

额外的，与 PopTip 一样，支持多条消息叠加弹出
![image](https://user-images.githubusercontent.com/10115359/179878601-9989b034-251a-4296-a331-0114c75994b0.png)

**Comment by kongzue** [comment]
Kongzue 主题也会在 PopNotification 中保持与现在一致的展示效果。

**Comment by kongzue** [comment]
新的主题和功能已更新至版本 [0.0.46.beta1](https://github.com/kongzue/DialogX/releases/tag/0.0.46.beta1)
