### ISSUE TITLE
【小问题】关于线程阻塞

### ISSUE THREAD

**Issue by Joslyn-Chen** [kongzue/DialogX#223]
## BUG 反馈
不属于BUG，常见问题里面提到过。

### 问题描述：
我在dismiss中用EventBus通知Application进行第三方库的初始化，初始化耗时在2s左右，导致调用dismiss后2s窗口才关掉。
我尝试用Handler、livedata、flow、coroutines等切换线程都不能解决，我就是想关掉窗口后再通知初始化。

**Comment by kongzue** [comment]
是否有尝试过 Thread:
```
new Thread(){
    @Override
    public void run() {
        //init SDKs
        super.run();
    }
}.start();
```

**Comment by Joslyn-Chen** [comment]
> 是否有尝试过 Thread:
> 
> ```
> new Thread(){
>     @Override
>     public void run() {
>         //init SDKs
>         super.run();
>     }
> }.start();
> ```

@kongzue 尝试过了，初始化后，窗口会处于半透明化，初始化结束后才会完全关闭

**Comment by Joslyn-Chen** [comment]
@kongzue 我找到原因了，之前dismiss是在自定义界面的一个按钮事件中，初始化卡住了主线程，导致dialog一直关不了。我把初始化放在DialogLifecycleCallback的onDismiss就正常了
