### ISSUE TITLE
CustomDialog 中含有EditText，dialog未上移

### ISSUE THREAD

**Issue by Fun-Pepper** [kongzue/DialogX#224]
自定义dialog布局如下：
![5181658546860_ pic_hd](https://user-images.githubusercontent.com/83764156/180588926-3b362463-8c1a-4d7f-818c-3ed741ae004d.jpg)

dialog展示调用代码如下：
CustomDialog.show(this, CustomDialog.ALIGN.CENTER)
            .setMaskColor(Color.parseColor("#4D000000"))
            .isAutoUnsafePlacePadding = true

也已经设置isAutoUnsafePlacePadding为true，但是dialog还是没有被输入框顶起来

**Comment by kongzue** [comment]
请参考[issues:131](https://github.com/kongzue/DialogX/issues/131)

**Comment by Fun-Pepper** [comment]
嗯 我参考过这个issue，按照里面的步骤配置之后 也是一样的结果

**Comment by kongzue** [comment]
这种问题多半跟布局设计或原 Activity 的设置有关，我能确保的是在 Demo 和正常的 Activity 上是运行正常的，因为 DialogX 默认采用 View 模式实现，这意味着需要依赖的 Activity 也同样支持在软键盘弹起时发生布局上的调整，请参阅[《常见问题Q2：输入法键盘弹出后遮挡对话框/输入法无法顶起对话框》](https://github.com/kongzue/DialogX/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98#q%E8%BE%93%E5%85%A5%E6%B3%95%E9%94%AE%E7%9B%98%E5%BC%B9%E5%87%BA%E5%90%8E%E9%81%AE%E6%8C%A1%E5%AF%B9%E8%AF%9D%E6%A1%86%E8%BE%93%E5%85%A5%E6%B3%95%E6%97%A0%E6%B3%95%E9%A1%B6%E8%B5%B7%E5%AF%B9%E8%AF%9D%E6%A1%86) 看看能否帮助到你。
