### ISSUE TITLE
使用CustomDialog无法监听布局里元素的点击事件

### ISSUE THREAD

**Issue by sdjwj1118** [kongzue/DialogX#227]
## BUG 反馈

请先确认您已阅读[《常见问题》](https://github.com/kongzue/DialogX/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)

### 问题描述：
请在此详细描述问题。
使用CustomDialog无法监听布局里元素的点击事件
![image](https://user-images.githubusercontent.com/33438073/183329590-f64a0633-b7cf-4827-ac0b-ac077d7445db.png)

### 设备信息：
请在此说明您使用的设备型号、Android 版本等信息以协助我们排查问题
android12 小米10Ultra

### 是否在 Demo 中能复现此问题？
是/否/未尝试

### 问题截图/视频
请在此插入佐证问题的截图和视频。
![image](https://user-images.githubusercontent.com/33438073/183329676-3619f7e1-ebf5-4977-8f41-fb2ffc3dd758.png)

**Comment by kongzue** [comment]
很抱歉未能在Demo中复现你所描述的问题，请检查是否因其他原因导致。
测试设备：Google Pixel5(Android 13 beta4)
测试代码：
```
CustomDialog.build(new OnBindView<CustomDialog>(R.layout.layout_custom_dialog) {
            @Override
            public void onBind(final CustomDialog dialog, View v) {
                ImageView btnOk;
                btnOk = v.findViewById(R.id.btn_ok);
                btnOk.setOnClickListener(new View.OnClickListener() {
                    @Override
                    public void onClick(View v) {
                        Toast.makeText(me,"测试",Toast.LENGTH_LONG).show();
                    }
                });
            }
        })
        .setMaskColor(getResources().getColor(R.color.black30))
        .show();
```
测试结果：
代码运行符合预期，结果正常。

测试截图：
![image](https://user-images.githubusercontent.com/10115359/183330590-3e8aaf3e-57bc-4000-b49c-a1e5cdc4116e.png)

**Comment by sdjwj1118** [comment]
看起来是使用了databinding的问题                         val itemBinding = DialogCarRentalPickBinding.bind(v!!) 这行代码注释掉后就可以监听事件了

**Comment by kongzue** [comment]
我这边很少用其他组件，onBindView 是在对话框启动后才会执行的，不排除 databinding 可能存在提前获取组件但未能绑定组件的可能性。

**Comment by sdjwj1118** [comment]
奇怪的是我自定义页面里两个RecyclerView 通过databinding能正常显示数据 唯独点击事件的监听不行

**Comment by kongzue** [comment]
长时间未回复暂时关闭此问题，若有疑问请继续评论。
