### ISSUE TITLE
您好怎么在PopMenu上将文字添加"marquee"

### ISSUE THREAD

**Issue by DDGRCF** [kongzue/DialogX#229]
如题

**Comment by kongzue** [comment]
**步骤一：**
在 app 的 res/layout 中添加一个 xml 文件，命名为“item_dialogx_material_context_menu_normal_text.xml”
**步骤二：**
在其中编写代码：
```xml
<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="wrap_content">

    <LinearLayout
        android:layout_width="match_parent"
        android:layout_height="48dp"
        android:gravity="center_vertical"
        android:paddingLeft="15dp"
        android:paddingRight="15dp">

        <ImageView
            android:id="@+id/img_dialogx_menu_icon"
            android:layout_width="35dp"
            android:layout_height="35dp"
            android:layout_marginRight="8dp"
            android:padding="5dp" />

        <TextView
            android:id="@+id/txt_dialogx_menu_text"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:layout_weight="1"
            android:gravity="left|center_vertical"
            android:maxLines="1"
            android:text=""
            android:textColor="@color/black90"
            android:textSize="16dp" />

        <Space
            android:id="@+id/space_dialogx_right_padding"
            android:layout_width="35dp"
            android:layout_height="35dp"
            android:layout_marginLeft="8dp"
            android:visibility="gone" />

    </LinearLayout>

</RelativeLayout>
```
**步骤三：**
其中 id 为“txt_dialogx_menu_text”的 TextView 的添加属性：
```xml
android:ellipsize="marquee"
android:focusable="true"
android:marqueeRepeatLimit="marquee_forever"
android:maxLines="1"
android:scrollbars="none"
```

**Comment by DDGRCF** [comment]
> **步骤一：** 在 app 的 res/layout 中添加一个 xml 文件，命名为“item_dialogx_material_context_menu_normal_text.xml” **步骤二：** 在其中编写代码：
> 
> ```
> <RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
>     android:layout_width="match_parent"
>     android:layout_height="wrap_content">
> 
>     <LinearLayout
>         android:layout_width="match_parent"
>         android:layout_height="48dp"
>         android:gravity="center_vertical"
>         android:paddingLeft="15dp"
>         android:paddingRight="15dp">
> 
>         <ImageView
>             android:id="@+id/img_dialogx_menu_icon"
>             android:layout_width="35dp"
>             android:layout_height="35dp"
>             android:layout_marginRight="8dp"
>             android:padding="5dp" />
> 
>         <TextView
>             android:id="@+id/txt_dialogx_menu_text"
>             android:layout_width="match_parent"
>             android:layout_height="wrap_content"
>             android:layout_weight="1"
>             android:gravity="left|center_vertical"
>             android:maxLines="1"
>             android:text=""
>             android:textColor="@color/black90"
>             android:textSize="16dp" />
> 
>         <Space
>             android:id="@+id/space_dialogx_right_padding"
>             android:layout_width="35dp"
>             android:layout_height="35dp"
>             android:layout_marginLeft="8dp"
>             android:visibility="gone" />
> 
>     </LinearLayout>
> 
> </RelativeLayout>
> ```
> 
> **步骤三：** 其中 id 为“txt_dialogx_menu_text”的 TextView 的添加属性：
> 
> ```
> android:ellipsize="marquee"
> android:focusable="true"
> android:marqueeRepeatLimit="marquee_forever"
> android:maxLines="1"
> android:scrollbars="none"
> ```

好的，感谢
