### ISSUE TITLE
DialogX.onlyOnePopTip = false; 好像没效果

### ISSUE THREAD

**Issue by libern** [kongzue/DialogX#23]
```
DialogX.onlyOnePopTip = false;

PopTip.show("点击确定按钮1")
PopTip.show("点击确定按钮2")
PopTip.show("点击确定按钮3")
```

只会显示`"点击确定按钮3"`

**Comment by kongzue** [comment]
因为叠在一起了。DialogX.onlyOnePopTip = false;的含义是不阻止同时多次弹出，但并不会影响弹出的位置

**Comment by kongzue** [comment]
将在下一个版本提供如下效果（GIF图加载缓慢请见谅）：
![screen-20210303-160507](https://user-images.githubusercontent.com/10115359/109774852-bebe7680-7c3b-11eb-835e-bd60a4dd8897.gif)
当设置`DialogX.onlyOnePopTip = false;`时，弹出新的PopTip时使老的PopTip动画位移至空白区域，当`DialogX.onlyOnePopTip = true;`时则一次只显示一个PopTip。

**Comment by kongzue** [comment]
暂时关闭了此问题，如有疑问请继续留言。

**Comment by libern** [comment]
谢谢大哥
