### ISSUE TITLE
popmenu如果挂点的view在边缘的话，弹出来的popmenu会变形

### ISSUE THREAD

**Issue by AreYReady** [kongzue/DialogX#231]
## BUG 反馈

请先确认您已阅读[《常见问题》](https://github.com/kongzue/DialogX/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)

### 问题描述：

我在demo里加了个靠近屏幕边缘的view，用来挂载点击选项菜单的popmenu，弹出来的变形了。
### 设备信息：
请在此说明您使用的设备型号、Android 版本等信息以协助我们排查问题

### 是否在 Demo 中能复现此问题？
是

### 问题截图/视频
<img width="500" alt="image" src="https://user-images.githubusercontent.com/13625746/185340588-7a3e29cd-c4d2-436b-a3fd-f3a9d15700b5.png">

**Comment by kongzue** [comment]
是这样的，所以建议你配合 .setWidth 设置一个指定宽度值

**Comment by AreYReady** [comment]
好的。加上width正常。
