### ISSUE TITLE
FullScreenDialog

### ISSUE THREAD

**Issue by me-sendy** [kongzue/DialogX#232]
## BUG 反馈

FullScreenDialog.show() 设置了layout。但还是显示空白。请问是怎么回事 ？

### 问题描述：
使用show() 和 setCustomView() 方式都试了。 都显示白屏。

**Comment by kongzue** [comment]
很抱歉，未能在Demo中复现你所描述的问题。
测试设备：Google Pixel5（Android 13）
测试代码（Demo中的测试样例）：
```
FullScreenDialog.build(new OnBindView<FullScreenDialog>(R.layout.layout_full_webview) {
            @Override
            public void onBind(final FullScreenDialog dialog, View v) {
                btnClose = v.findViewById(R.id.btn_close);
                webView = v.findViewById(R.id.webView);
                
                btnClose.setOnClickListener(new View.OnClickListener() {
                    @Override
                    public void onClick(View v) {
                        dialog.dismiss();
                    }
                });
                
                WebSettings webSettings = webView.getSettings();
                webSettings.setJavaScriptEnabled(true);
                webSettings.setLoadWithOverviewMode(true);
                webSettings.setUseWideViewPort(true);
                webSettings.setSupportZoom(false);
                webSettings.setAllowFileAccess(true);
                webSettings.setJavaScriptCanOpenWindowsAutomatically(true);
                webSettings.setLoadsImagesAutomatically(true);
                webSettings.setDefaultTextEncodingName("utf-8");
                
                webView.setWebViewClient(new WebViewClient() {
                    @Override
                    public boolean shouldOverrideUrlLoading(WebView view, String url) {
                        try {
                            Intent intent = new Intent(Intent.ACTION_VIEW, Uri.parse(url));
                            startActivity(intent);
                        } catch (ActivityNotFoundException e) {
                            e.printStackTrace();
                        }
                        return true;
                    }
                    
                    @Override
                    public void onPageFinished(WebView view, String url) {
                        super.onPageFinished(view, url);
                    }
                });
                
                webView.loadUrl("https://github.com/kongzue/DialogX");
            }
        })
        .show();
```
测试结果：
正常显示，符合预期。
![image](https://user-images.githubusercontent.com/10115359/185531006-5de9070d-979b-4596-bfec-2ce523df86ac.png)

**Comment by kongzue** [comment]
备注，测试代码修改为 `FullScreenDialog.show(onBindView)` 也正常显示。

**Comment by me-sendy** [comment]
kotlin 代码？
<img width="812" alt="image" src="https://user-images.githubusercontent.com/87748811/185531595-cd95c49f-b81d-499e-bf00-235cdf971dd6.png">

**Comment by kongzue** [comment]
跟语言无关。
经过分析代码，不太理解你在 DialogLifecycle#onShow 里对对话框 dismiss 的原因是什么。

**Comment by me-sendy** [comment]
我也觉得和语言无关。奇怪 在我设备上白屏。pixel 4xl。
这个是。希望dialog显示一段时间后自动关闭。

**Comment by kongzue** [comment]
目前已上线的所有产品均为收到过类似问题的报告

**Comment by me-sendy** [comment]
用java代码显示正常。

但在显示时画面会抖动一下。
我的流程是
1. activity1 加载layout1布局， 延时2S 跳转到activity2 。
2. activity2 显示启动后 加载fullscreenDialog.show() layout1布局。延时一定时间关闭fullscreenDialog。
现在是从activity1到activity2时 layout1 布局会抖动一下。

https://user-images.githubusercontent.com/87748811/185537145-cde27119-990f-4ad4-9bbf-a53c56937aeb.mp4

**Comment by kongzue** [comment]
不清楚原因，目前demo测试没有发现任何问题
________________________________
发件人: sendy ***@***.***>
发送时间: Friday, August 19, 2022 11:33:09 AM
收件人: kongzue/DialogX ***@***.***>
抄送: Kongzue ***@***.***>; Comment ***@***.***>
主题: Re: [kongzue/DialogX] FullScreenDialog (Issue #232)


用java代码显示正常。

但在显示时画面会抖动一下。
我的流程是

  1.  activity1 加载layout1布局， 延时2S 跳转到activity2 。
  2.  activity2 显示启动后 加载fullscreenDialog.show() layout1布局。延时一定时间关闭fullscreenDialog。
现在是从activity1到activity2时 layout1 布局会抖动一下。

https://user-images.githubusercontent.com/87748811/185537145-cde27119-990f-4ad4-9bbf-a53c56937aeb.mp4<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F87748811%2F185537145-cde27119-990f-4ad4-9bbf-a53c56937aeb.mp4&data=05%7C01%7C%7C3d4716bb72834628ba5208da819389bf%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637964767933360421%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=qmXaa4WJjQS948d%2BGTEu4eevinI61HO8gmYzl9lf03s%3D&reserved=0>

―

**Comment by kongzue** [comment]
尝试一下在show方法中使用带参数的形式，例如：`.show(activity)` 
看您的视频这种场景更建议使用 CustomDialog，FullScreenDialog 更适用于在一个界面上显示背景下沉式的悬浮层，而不是作为闪屏展示的场景，具体应用场景请参阅 wiki：[全屏对话框 FullScreenDialog](https://github.com/kongzue/DialogX/wiki/%E5%85%A8%E5%B1%8F%E5%AF%B9%E8%AF%9D%E6%A1%86-FullScreenDialog)

**Comment by me-sendy** [comment]
好的。 谢谢。 我再研究下

**Comment by kongzue** [comment]
长时间未回复暂时关闭此问题，若有疑问请继续评论。
