### ISSUE TITLE
BottomDialog设置MaxWidth不生效

### ISSUE THREAD

**Issue by Bruce8hou** [kongzue/DialogX#233]
BottomDialog.build()
            .setDialogLifecycleCallback(object : DialogLifecycleCallback<BottomDialog>() {

                override fun onShow(dialog: BottomDialog?) {
                    dialog?.setMaxWidth(dp2px(480f))
                    super.onShow(dialog)
                }
}

**Comment by kongzue** [comment]
请直接使用 `BottomDialog.build().setMaxWidth(...)` 而不是使用内部方法。

**Comment by cxf910714** [comment]
> 
WaitDialog.build()
            .setMaxWidth((screenWidth() * 0.4f).toInt())
            .setMessageContent(msg)
            .setTipType(WaitDialog.TYPE.WARNING)
            .show()

setMaxWidth方法设置不起作用
