### ISSUE TITLE
DialogFragment中看不见

### ISSUE THREAD

**Issue by BaiMingxu** [kongzue/DialogX#234]
在DialogFragment中使用被弹窗遮挡看不见toast，我想让它在弹窗上面显示怎么办？

**Comment by kongzue** [comment]
没理解你的意思。你是使用的DialogFragment实现模式，还是toast使用了PopTip，请具体描述你的问题。

**Comment by kongzue** [comment]
另外，是否有查阅 [《常见问题》](https://github.com/kongzue/DialogX/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)

**Comment by BaiMingxu** [comment]
使用了PopTip作为吐司，其他地方显示正常，但是在我的DialogFragment上面是不显示的，盖住了，他是在fragment层级显示的。

**Comment by kongzue** [comment]
请确认已经阅读  [《常见问题》](https://github.com/kongzue/DialogX/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)，其中《Q：DialogX 无法覆盖在 DialogFragment、AlertDialog 之上》章节有解释原因。

**Comment by BaiMingxu** [comment]
谢谢
