### ISSUE TITLE
BottomDialog 遮罩色

### ISSUE THREAD

**Issue by Bruce8hou** [kongzue/DialogX#235]
BottomDialog  设置了遮罩色 （setMaskColor(Color.parseColor("#4D000000"))后
当使用setAllowInterceptTouch来切换触控拦截时候 遮罩色丢失。
比如：在fragment上有一个button切换BottomDialog 是否拦截touch， 当把setAllowInterceptTouch（true）后 遮罩色就直接丢失看不见了。即使把setAllowInterceptTouch（false）后遮罩色也没有再显示。总之，只要调用setAllowInterceptTouch函数切换 之前设置的遮罩层的颜色都看不见了

另外：
BottomDialog  在调用setCustomView自定义layout后 在向上滑动的时候 自定义layout会超过 imgTab

**Comment by kongzue** [comment]
很抱歉你所反馈的问题在Demo中未能复现。测试代码使用的是：
```java
BottomDialog.show("标题", "这里是对话框内容。\n" + s + "。\n底部对话框也支持自定义布局扩展使用方式。",
        new OnBindView<BottomDialog>(R.layout.layout_custom_view) {
            @Override
            public void onBind(BottomDialog dialog, View v) {
                if (dialog.getDialogImpl().imgTab != null) {
                    ((ViewGroup) dialog.getDialogImpl().imgTab.getParent()).removeView(dialog.getDialogImpl().imgTab);
                }
                v.setOnClickListener(new View.OnClickListener() {
                    @Override
                    public void onClick(View v) {
                        dialog.dismiss();
                        PopTip.show("Click Custom View");
                    }
                });
            }
        })
        .setMaskColor(Color.parseColor("#4D000000"))
        .setAllowInterceptTouch(false);
```
反复调整 `.setAllowInterceptTouch(ture/false)` 未发现背景遮罩发生异常，其次在 `.setAllowInterceptTouch(true)` 时向上滑动，也未发现任何异常。

测试设备：Google Pixel5(Android 13)

**Comment by Bruce8hou** [comment]
当构建BottomDialog的时候 使用build，不设置title和Message的时候 布局会出现问题，滑动的时候自定义layout会超过 imgTab

setAllowInterceptTouch在构建的时候设置没有问题，如您这样使用，完全是没有问题的，但是当在自定义的layout里面有一个button可以通过点击此button动态设置setAllowInterceptTouch(ture/false)就会出现问题。遮罩层会丢失。

**Comment by kongzue** [comment]
很抱歉经过测试依然未能发现任何问题。
测试代码：
```java
BottomDialog.build(new OnBindView<BottomDialog>(R.layout.layout_custom_view) {
            @Override
            public void onBind(BottomDialog dialog, View v) {
                if (dialog.getDialogImpl().imgTab != null) {
                    ((ViewGroup) dialog.getDialogImpl().imgTab.getParent()).removeView(dialog.getDialogImpl().imgTab);
                }
                v.setOnClickListener(new View.OnClickListener() {
                    @Override
                    public void onClick(View v) {
                        dialog.dismiss();
                        PopTip.show("Click Custom View");
                    }
                });
            }
        })
        .setMaskColor(Color.parseColor("#4D000000"))
        .setAllowInterceptTouch(false)
        .show();
```
测试设备：Google Pixel5(Android 13)
测试录屏：
当设置 `.setAllowInterceptTouch(true)` 时：
https://user-images.githubusercontent.com/10115359/185795526-06864f5e-50d1-4367-a1bc-e0bf195c3752.mp4

当设置 `.setAllowInterceptTouch(false)` 时：
https://user-images.githubusercontent.com/10115359/185795542-a8abd528-fa1b-4e5e-b2d8-c3810b29ef73.mp4

**Comment by Bruce8hou** [comment]
这样调用哈
BottomDialog.build(new OnBindView<BottomDialog>(R.layout.layout_custom_view) {
            @Override
            public void onBind(BottomDialog dialog, View v) {
                if (dialog.getDialogImpl().imgTab != null) {
                    ((ViewGroup) dialog.getDialogImpl().imgTab.getParent()).removeView(dialog.getDialogImpl().imgTab);
                }
                v.setOnClickListener(new View.OnClickListener() {
                    @Override
                    public void onClick(View v) {
			dialog.setAllowInterceptTouch(!dialog.isAllowInterceptTouch)
                    }
                });
            }
        })
        .setMaskColor(Color.parseColor("#4D000000"))
        .show();

**Comment by Bruce8hou** [comment]
这样调用哈

BottomDialog.build(new OnBindView<BottomDialog>(R.layout.layout_custom_view) {
            @Override
            public void onBind(BottomDialog dialog, View v) {
                if (dialog.getDialogImpl().imgTab != null) {
                    ((ViewGroup) dialog.getDialogImpl().imgTab.getParent()).removeView(dialog.getDialogImpl().imgTab);
                }
                v.setOnClickListener(new View.OnClickListener() {
                    @Override
                    public void onClick(View v) {
                      dialog.setAllowInterceptTouch(!dialog.isAllowInterceptTouch)
                    }
                });
            }
        })
        .setMaskColor(Color.parseColor("#4D000000"))
        .setAllowInterceptTouch(false)
        .show();

**Comment by Bruce8hou** [comment]
这样调用哈，通过button动态修改
`BottomDialog.build(new OnBindView<BottomDialog>(R.layout.layout_custom_view) {
            @Override
            public void onBind(BottomDialog dialog, View v) {
                if (dialog.getDialogImpl().imgTab != null) {
                    ((ViewGroup) dialog.getDialogImpl().imgTab.getParent()).removeView(dialog.getDialogImpl().imgTab);
                }
                v.setOnClickListener(new View.OnClickListener() {
                    @Override
                    public void onClick(View v) {
                 dialog.setAllowInterceptTouch(!dialog.isAllowInterceptTouch)
                    }
                });
            }
        })
        .setMaskColor(Color.parseColor("#4D000000"))
        .setAllowInterceptTouch(false)
        .show();`

**Comment by kongzue** [comment]
明白了，这是未曾设想过的应用场景。
但此问题会在下一个版本修复，感谢反馈。

**Comment by Bruce8hou** [comment]
好的 谢谢。关于自定义layout会超过 imgTab是因为没有设置title和massage，我已经测试了，只要设置了title就没有问题了 应该是布局方面的问题

**Comment by kongzue** [comment]
请更新 [0.0.46.beta8](https://github.com/kongzue/DialogX/releases/tag/0.0.46.beta8) 版本已修复此问题

**Comment by Bruce8hou** [comment]
您好，遮罩层丢失的问题已经解决了。但是关于自定义layout 没有设置title和massage时候滑动会超过imgTab这个问题没有修复哦，我再描述一下使用场景哈：
     比如在自定义layout的高度大于屏幕高度的时候 BottomDialog可以上下滑动，在滑动的时候 layout会覆盖imgTab，我刚刚看了源码 应该是在没有设置title和massage的时候 直接gone了。导致布局可以上滑到BottomDialog顶端了。

**Comment by kongzue** [comment]
还是没能理解你的意思，根据上述描述我尝试创建了一个800dp的自定义布局，未发现任何问题，测试代码如下：
```java
new BottomDialog(
        new OnBindView<BottomDialog>(R.layout.layout_custom_view) {
            @Override
            public void onBind(BottomDialog dialog, View v) {
                
            }
        })
        .show();
```
布局代码如下：
```xml
<?xml version="1.0" encoding="utf-8"?>
<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="800dp"
    android:background="#72DC6A6A">

    <LinearLayout
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:gravity="center_horizontal"
        android:orientation="vertical"
        android:paddingBottom="15dp"
        android:paddingTop="15dp">

        <ImageView
            android:id="@+id/img_ico"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:src="@mipmap/img_logo" />

        <TextView
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:layout_marginTop="10dp"
            android:text="这里是自定义Layout测试"
            android:textColor="#878787"
            android:textSize="12dp" />

    </LinearLayout>

</RelativeLayout>
```
测试设备：
Google Pixel5(Android 13)
测试视频如下：

https://user-images.githubusercontent.com/10115359/185883837-27b65bdf-b0af-46a9-a622-d105e6a6158d.mp4

**Comment by Bruce8hou** [comment]
最新修复的遮罩层虽然没有丢失，但是只要自定义了遮罩层颜色（setMaskColor(Color.parseColor("#4D000000"))）的时候弹出会先闪烁一下。麻烦再测试一下哦  ，

**Comment by kongzue** [comment]
反复确认了下应该是底层走了这个代码分支导致的 background 的 alpha 初始化未生效：
![image](https://user-images.githubusercontent.com/10115359/185895490-d8973c50-e394-494b-b540-27b323598787.png)
此问题会在下一个版本修复，但上述 layout会覆盖 imgTab 的问题未能复现，需要提供测试样例我这边才能查找具体原因

**Comment by Bruce8hou** [comment]
我把您的代码拷贝到我的工程里 还是出现超过imgTab 的情况 
![8228d55ff2142da96571adc3d629fc0](https://user-images.githubusercontent.com/20390458/185896765-20e3723e-21cc-4f07-aa6b-b1b2a89cbaf4.jpg)

**Comment by kongzue** [comment]
如果你担心的是圆角部分的裁剪问题可以尝试使用 `..setRadius(px)` 来设置圆角，会直接裁切内容的显示

**Comment by kongzue** [comment]
猜测你使用的是 MaterialYou 主题。
要处理此问题需要修改主题，待评估后会答复你

**Comment by Bruce8hou** [comment]
是主题原因。DialogX.globalStyle = MaterialYouStyle() 把这个注销了问题解决了。
![LOWQ{ZGLA}P~B} 3575XLQV](https://user-images.githubusercontent.com/20390458/185898538-7cc7e2e3-ce69-4798-a657-c51c8565a566.png)
这个地方是超过了。应该是主题配置的问题了

**Comment by kongzue** [comment]
对的，我刚刚也发现了，但修改主题是需要评估方案的，目前最优解是对 MaterialYou主题的内容部分向下移动2dp，还需要评估可能受影响的其他软件，会不会造成其他问题，预计后天前完成评估。

**Comment by Bruce8hou** [comment]
好的。谢谢

**Comment by kongzue** [comment]
请更新至版本 [0.0.46.beta9](https://github.com/kongzue/DialogX/releases/tag/0.0.46.beta9)
