### ISSUE TITLE
关于隐藏初始化方法

### ISSUE THREAD

**Issue by stars-one** [kongzue/DialogX#236]
### 需求描述：
用的时候，需要进行初始化，其实可以通过官方给的appstartup库进行优化，在后台默认进行初始化，这样更方便使用

可以参考下这篇文章[Jetpack新成员，App Startup一篇就懂](https://mp.weixin.qq.com/s?__biz=MzA5MzI3NjE2MA==&mid=2650251523&idx=1&sn=3409d80cc6c4252cbd4fb0e327eb3dcc&chksm=8863506cbf14d97aa6b640b6794395a158137e97b9db5804e2718b204affa3bb5c2aba8f6676&scene=178&cur_album_id=1455589563531214850#rd)

**Comment by kongzue** [comment]
这个跟我没有关系，DialogX 只专注于框架层面上的功能开发，应用层面上应由 App 开发者决定采用何种技术完成自己的项目。
如果你有修改建议欢迎提交分支合并请求，我很乐意并欢迎对优秀的修改进行合并。

**Comment by AreYReady** [comment]
这个好像真跟这个库无关，就是不写在application里面，写在Initializer 里面而已，就是一个初始化放在哪里的选择而已。
