### ISSUE TITLE
customDialog 可配置去掉退出 属性动画虚化的建议

### ISSUE THREAD

**Issue by AreYReady** [kongzue/DialogX#237]
## 功能建议
希望能可选择的去掉库写死的退出虚化动画。
### 需求描述：

使用customDialog 定制底部弹出栏A 在A的基础上再弹出底部栏B，使用right_bottom的方式。在退出的时候，库源代码写死会虚化，设置自定义动画，也无法规避。翻看源码，代码写死，没办法可选择的去掉这个虚化动画。

**Comment by kongzue** [comment]
你是指背景遮罩层的渐变么？即 [CustomDialog.java:451](https://github.com/kongzue/DialogX/blob/c96f9f0c2be927ecb99605dec74a578444041e76/DialogX/src/main/java/com/kongzue/dialogx/dialogs/CustomDialog.java#L451)

**Comment by AreYReady** [comment]
是的，我看了下，大部分消失代码都是监听这个到0之后，进行view的Gone隐藏。我无法在引用层去调配它。这样无法保持进入退出动画的一致性。

**Comment by kongzue** [comment]
我在思考这种问题怎么处理比较合理...

**Comment by AreYReady** [comment]
干巴跌

**Comment by kongzue** [comment]
目前计划是提供一个 DialogXAnimInterface 接口，其中可实现 `doShowAnim(Dialog dialog, ObjectRunnable<Float> animProgress)` 和 `doExitAnim(Dialog dialog, ObjectRunnable<Float> animProgress)` 两个方法，dialog 提供完整的对话框实例，例如 CustomDialog 的实现，你可以使用 `dialog.getDialogImpl().boxCustom` 访问内容布局实例，animProgress 用于汇报进度，例如进入动画，当进度为 1f 时意味着动画结束，关闭动画中，当进度为 0f 时意味着动画结束，此时会自动执行销毁流程。
目前编写了一个实现样例供参考：
```java
CustomDialog.show(new OnBindView<CustomDialog>(R.layout.layout_custom_dialog) {
            @Override
            public void onBind(final CustomDialog dialog, View v) {
                ImageView btnOk;
                btnOk = v.findViewById(R.id.btn_ok);
                btnOk.setOnClickListener(new View.OnClickListener() {
                    @Override
                    public void onClick(View v) {
                        dialog.dismiss();
                    }
                });
            }
        })
        .setMaskColor(getResources().getColor(R.color.black30))
        //实现完全自定义动画效果
        .setDialogXAnimImpl(new DialogXAnimInterface<CustomDialog>() {
            @Override
            public void doShowAnim(CustomDialog customDialog, ObjectRunnable<Float> animProgress) {
                Animation enterAnim;
                int enterAnimResId = com.kongzue.dialogx.R.anim.anim_dialogx_top_enter;
                enterAnim = AnimationUtils.loadAnimation(me, enterAnimResId);
                enterAnim.setInterpolator(new DecelerateInterpolator(2f));
                long enterAnimDurationTemp = enterAnim.getDuration();
                enterAnim.setDuration(enterAnimDurationTemp);
                customDialog.getDialogImpl().boxCustom.setVisibility(View.VISIBLE);
                customDialog.getDialogImpl().boxCustom.startAnimation(enterAnim);
                customDialog.getDialogImpl().boxRoot.setBackgroundColor(customDialog.getMaskColor());
                ValueAnimator bkgAlpha = ValueAnimator.ofFloat(0f, 1f);
                bkgAlpha.setDuration(enterAnimDurationTemp);
                bkgAlpha.addUpdateListener(new ValueAnimator.AnimatorUpdateListener() {
                    @Override
                    public void onAnimationUpdate(ValueAnimator animation) {
                        animProgress.run((Float) animation.getAnimatedValue());
                    }
                });
                bkgAlpha.start();
            }
            @Override
            public void doExitAnim(CustomDialog customDialog, ObjectRunnable<Float> animProgress) {
                int exitAnimResIdTemp = com.kongzue.dialogx.R.anim.anim_dialogx_default_exit;
                Animation exitAnim = AnimationUtils.loadAnimation(me, exitAnimResIdTemp);
                customDialog.getDialogImpl().boxCustom.startAnimation(exitAnim);
                ValueAnimator bkgAlpha = ValueAnimator.ofFloat(1f, 0f);
                bkgAlpha.setDuration(exitAnim.getDuration());
                bkgAlpha.addUpdateListener(new ValueAnimator.AnimatorUpdateListener() {
                    @Override
                    public void onAnimationUpdate(ValueAnimator animation) {
                        animProgress.run((Float) animation.getAnimatedValue());
                    }
                });
                bkgAlpha.start();
            }
        })
;
```
因为修改难度还是比较大的，已完成对 CustomDialog 的支持，目前还在考虑是否对其他对话框进行支持。

**Comment by AreYReady** [comment]
了解，感觉可以接受。这种需求理论上是较小众的。我本身也没想到库主会修改这么快。辛苦了。

**Comment by kongzue** [comment]
还没提交，等细节完善完毕了预计两天内更新

**Comment by kongzue** [comment]
其实是还在考虑是否对其他对话框进行支持......如果需要，要改的地方太多了

**Comment by AreYReady** [comment]
好的。

**Comment by kongzue** [comment]
请更新版本：[0.0.46.beta12](https://github.com/kongzue/DialogX/releases/tag/0.0.46.beta12)
以下是更新日志：
- BottomDialog、BottomMenu、CustomDialog、FullScreenDialog、GuideDialog、InputDialog、MessageDialog、PopMenu、PopNotification、PopTip、TipDialog、WaitDialog 新增 `.setDialogXAnimImpl(DialogXAnimInterface)` 用于完全自定义启动和关闭动画；
- PopMenu 增加 `.hideWithExitAnim()` 方法用于模拟关闭菜单动画的隐藏功能；
文档可能需要延后一段时间完成更新，参考用例请参照[MainActivity.java:944](https://github.com/kongzue/DialogX/blob/e79fdad7a540ce6c0a93d7895a670f82ddfbf821/app/src/main/java/com/kongzue/dialogxdemo/activity/MainActivity.java#L944)

**Comment by kongzue** [comment]
文档已更新，请参阅 [完全自定义开启、关闭动画](https://github.com/kongzue/DialogX/wiki#%E5%AE%8C%E5%85%A8%E8%87%AA%E5%AE%9A%E4%B9%89%E5%BC%80%E5%90%AF%E5%85%B3%E9%97%AD%E5%8A%A8%E7%94%BB)

**Comment by AreYReady** [comment]
<img width="843" alt="image" src="https://user-images.githubusercontent.com/13625746/188773444-4539d0d7-a93e-49ae-9806-2dc3a76a2f3d.png">
不确定是11还是12出现的bug，在10的时候还正常。使用hideWithExitAnim 再show出不来。

**Comment by kongzue** [comment]
未发现异常，测试代码如下：
```java
CustomDialog.show(new OnBindView<CustomDialog>(R.layout.layout_custom_dialog) {
            @Override
            public void onBind(final CustomDialog dialog, View v) {
                ImageView btnOk;
                btnOk = v.findViewById(R.id.btn_ok);
                btnOk.setOnClickListener(new View.OnClickListener() {
                    @Override
                    public void onClick(View v) {
                        dialog.hideWithExitAnim();
                        
                        runOnMainDelayed(new Runnable() {
                            @Override
                            public void run() {
                                dialog.show();
                            }
                        },1000);
                    }
                });
            }
        });
```

**Comment by AreYReady** [comment]
按照你的写法没问题，但如果按照我的写法会有问题。部分情况弹不出，部分情况第二次弹出闪消失

https://user-images.githubusercontent.com/13625746/188777351-e571b0ea-26e8-469a-a3e8-714d9ee01192.mp4

**Comment by kongzue** [comment]
检查了一下，出现了一个很奇怪的事情，当对话框被隐藏后（CstomDialog#hideWithExitAnim）已经确认 `.setVisibility(View.GONE)` 执行成功，但不清楚为何，触摸事件依然被传达到 dialogView，导致界面上实际存在一个已经隐藏显示了的对话框，目前推断是系统 bug，因为如果我开启 Layout Inspector，它又会恢复正常

**Comment by AreYReady** [comment]
进入进一步尝试，录像了第二次闪现的，嗯，我加了个日志，我发现第二次并没有进入点击事件，而是调用了dialog的dismiss，我怀疑根本原因是因为view使用了hideWithExitAnim之后并没有真正的隐藏，所以第二次点击等同于点了dialog的背景触发消失，两种现象仅是完全自定义按钮的位置是否在dialog内外的关系。【由于demo不能直接引用远程源切成10，有些资源没有。所以我没法再演示10的，在我项目上，0.0.46.beta10不会出现这个问题。12会】
<img width="1339" alt="image" src="https://user-images.githubusercontent.com/13625746/188779463-f9884145-cb5f-4a83-b7f3-ab68d31ce61f.png">

https://user-images.githubusercontent.com/13625746/188779675-28297fd8-7853-4430-b8a3-534c2d19180f.mp4

**Comment by kongzue** [comment]
排查了一下，确认是系统 bug。Android 的 View 当 alpha 处于 0 时，对其执行 `.setVisibility(View.GONE)` 会出现异常，即界面并不会真正的消失，而只是不渲染，若其依然接收 touch 事件就依然能拦截触摸事件，这是不正常的

**Comment by kongzue** [comment]
我注释掉 CustomDialog:529 到 534 行关于 boxRoot 的 alpha 动画后就没有这个问题了
![image](https://user-images.githubusercontent.com/10115359/188779986-fa22b5e6-2e6e-4ce5-8486-84ab3e98190a.png)

**Comment by kongzue** [comment]
目前的方案是取消关于 CustomDialog 的 overrideMaskEnterAnimRes 和 overrideMaskExitAnimRes 两个可定义属性，因为其可能导致使用 boxRoot 的动画导致界面无法正常隐藏和显示

**Comment by AreYReady** [comment]
哈哈，嗯，你从源头找，我只能从现象去推测。能方案合适解决吗？没有的话，12的完全自定义动画能解决这个问题吗？

**Comment by AreYReady** [comment]
懂了。做好小板凳，等群主新版本。

**Comment by kongzue** [comment]
可以，重写关闭时的动画并不要对 boxRoot 进行 alpha→0 的操作就可以了

**Comment by kongzue** [comment]
因为 CustomDialog 其实分为主体和背景两个层的动画效果，主体即 boxCustom 的动画，背景即遮罩层的动画，这两个动画是分离的，boxRoot 的动画是对整个对话框界面的动画，它实际上是遗留问题，事实上也没必要，所以可以取消掉这个功能

**Comment by kongzue** [comment]
代码已经提交了，你可以拉取源代码先试一下看还有没有问题

**Comment by AreYReady** [comment]
了解。

**Comment by AreYReady** [comment]
正常了。

**Comment by kongzue** [comment]
ok，稍后看下还有没其他需要更新的功能后合并更新版本

**Comment by AreYReady** [comment]
好的。

**Comment by kongzue** [comment]
请更新至 0.0.46.beta13 版本：https://github.com/kongzue/DialogX/releases/tag/0.0.46.beta13

**Comment by AreYReady** [comment]
升级了13，准确说是10正常，但从12 或者13 在我的项目都存在这个问题，但在demo中，我无法复现。我暂时无法排除是什么干扰了这个库的正常使用。

```
if(mBuild!=null){
            mBuild.show();
            return;
        }
        mBuild = BottomDialog.build(new OnBindView<BottomDialog>(R.layout.v_bottom_shop_manage) {
            @Override
            public void onBind(BottomDialog dialog, View v) {

            }
        }).show();
```

https://user-images.githubusercontent.com/13625746/188842841-bba7631b-eb3f-4603-9e2a-aca272f3943a.mp4

**Comment by kongzue** [comment]
不清楚，请给出完整测试代码样例，我这边测试机是 Google Pixel5(Android 13)未能发现任何问题。

**Comment by AreYReady** [comment]
了解，我在排除干扰。尝试复现。

**Comment by AreYReady** [comment]
我复现了，但没找打干扰源是啥。我测试项目私发给你。

**Comment by AreYReady** [comment]
emmmm。最终确定问题，是写法的问题。如果是0.0.46.beta10的话，可以在dismiss(),使用同一个dialog再show。0.0.46.beta10以上的版本不能这样写，需要再创建个新的dialog，不然就需要用dialog.hideWithExitAnim() 来隐藏dialog，才可以。
```
if(mBuild!=null){
            mBuild.show();
            return;
        }
        mBuild = BottomDialog.build(new OnBindView<BottomDialog>(R.layout.v_bottom_shop_manage) {
            @Override
            public void onBind(BottomDialog dialog, View v) {

            }
        }).show();
```
这是错误的写法
