### ISSUE TITLE
shape_textPressedColor 问题

### ISSUE THREAD

**Issue by Bruce8hou** [kongzue/DialogX#238]
当一个layout 有几个ShapeTextView都设置了shape_textPressedColor颜色后 不管点击哪一个 另外一个ShapeTextView 也会变色 有的时候点击layout的空白处也会触发text变色

**Comment by kongzue** [comment]
此问题应该转交给Google处理，请尝试为 ShapeTextView 设置 clickable，或：https://btfy.eu.org/?q=U2hhcGVUZXh0VmlldyDkuI3nrqHngrnlh7vlk6rkuIDkuKog5Y+m5aSW5LiA5LiqU2hhcGVUZXh0VmlldyDkuZ/kvJrlj5joibI=

**Comment by Bruce8hou** [comment]
谢谢，解决了
