### ISSUE TITLE
CustomDialog使用id和fragment作为OnBindView的参数，表现不一致

### ISSUE THREAD

**Issue by AreYReady** [kongzue/DialogX#239]
## BUG 反馈

请先确认您已阅读[《常见问题》](https://github.com/kongzue/DialogX/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)

### 问题描述：
使用官网demo改造一下，做了个自定义底部弹出框俄罗斯套娃弹出。一个用layoutid，一个用fragment传入OnBindView
用id是一直弹出新的底部框符合预期
用fragment是替换，无动画效果，不符合预期，【且】。请看视频
### 设备信息：
请在此说明您使用的设备型号、Android 版本等信息以协助我们排查问题

### 是否在 Demo 中能复现此问题？
是/否/未尝试

### 问题截图/视频
id:

https://user-images.githubusercontent.com/13625746/188605201-7c1ed18d-4c6e-4ca5-9a7e-af24a1977c0b.mp4

fragment:

https://user-images.githubusercontent.com/13625746/188605640-1998b75a-0487-45d9-9655-47dff3af5e43.mp4

相应代码图：
<img width="768" alt="image" src="https://user-images.githubusercontent.com/13625746/188605407-cfe55a03-bef7-4a8b-a67b-9dcab8b8b377.png">

**Comment by kongzue** [comment]
因为fragment的显示是必须基于一个已存在于资源中的id进行显示的，当一个activity内尝试弹出多个相同id的fragment，这种操作是无法进行的，本质上是FragmentManager限制了这件事，而fragment又无法脱离FragmentManager单独显示，此问题需要上报Google对系统底层进行修改。
建议使用自定义布局实现功能。

**Comment by AreYReady** [comment]
你说的多个相同id的fragment 是指同一个fragment吗，我这里是为了简单展示才这样写。我换成套娃弹不同的fragment还一样,这里的这个id指的是什么。

**Comment by kongzue** [comment]
id是指容器布局的id，此问题无解，需要Google修改fragment manager的逻辑，如果你有使用过feagment manager就很清楚我在说什么
________________________________
发件人: AreYReady ***@***.***>
发送时间: Tuesday, September 6, 2022 6:11:45 PM
收件人: kongzue/DialogX ***@***.***>
抄送: Kongzue ***@***.***>; State change ***@***.***>
主题: Re: [kongzue/DialogX] CustomDialog使用id和fragment作为OnBindView的参数，表现不一致 (Issue #239)


你说的多个相同id的fragment 是指同一个fragment吗，我这里是为了简单展示才这样写。我换成套娃弹不同的fragment还一样,这里的这个id指的是什么。

―

**Comment by AreYReady** [comment]
好的。

**Comment by kongzue** [comment]
因为我这边框架层是没办法去动态创建资源id的，如果必须使用fragment建议还是使用自定义布局，放一个framelayout，然后手动绑定fragment显示到framelayout里，注意弹出的新对话框里的framelayout的id一定要与之前的不同，因为fragmentmanager是基于activiry的，如果id相同依然会这样显示不出来
________________________________
发件人: AreYReady ***@***.***>
发送时间: Tuesday, September 6, 2022 6:13:57 PM
收件人: kongzue/DialogX ***@***.***>
抄送: Kongzue ***@***.***>; State change ***@***.***>
主题: Re: [kongzue/DialogX] CustomDialog使用id和fragment作为OnBindView的参数，表现不一致 (Issue #239)


好的。

―

**Comment by AreYReady** [comment]
这样说我就理解了。我明白你说的是什么了。【ps我刚才机智的尝试了下，第二次弹模式为dialogFragment，不行，有问题，不能搭配。】抱歉啊， 我对源码理解不深，胡乱尝试。确实用id自定义view的话是可以解决我的需求的。

**Comment by kongzue** [comment]
没事，这种事本质上还是google的历史遗留问题，事实上直接使用自定义布局的话会方便很多，还是google早期没考虑设计完善的view生命周期所导致的问题，我这边也会继续寻找更合适的解决方案
________________________________
发件人: AreYReady ***@***.***>
发送时间: Tuesday, September 6, 2022 6:33:14 PM
收件人: kongzue/DialogX ***@***.***>
抄送: Kongzue ***@***.***>; State change ***@***.***>
主题: Re: [kongzue/DialogX] CustomDialog使用id和fragment作为OnBindView的参数，表现不一致 (Issue #239)


这样说我就理解了。我明白你说的是什么了。【ps我刚才机智的尝试了下，第二次弹模式为dialogFragment，不行，有问题，不能搭配。】抱歉啊， 我对源码理解不深，胡乱尝试。确实用id自定义view的话是可以解决我的需求的。

―

**Comment by AreYReady** [comment]
这几天在想，如果使用fragment的缺陷是框架无法动态创建资源id，由调用者自己去在布局里放入frameLayou，然后将id作为参数传入onbindView里面。取代id_frame_layout_custom。我简单在demo了改造了下，能显示，但没有相对应的动画,已经其他一些功能，我并不理解其中的缘由。

**Comment by kongzue** [comment]
我已经在考虑自己实现一套替代FragmentManager的组件了，不过这需要时间去验证可行性
________________________________
发件人: AreYReady ***@***.***>
发送时间: Friday, September 9, 2022 4:41:59 PM
收件人: kongzue/DialogX ***@***.***>
抄送: Kongzue ***@***.***>; State change ***@***.***>
主题: Re: [kongzue/DialogX] CustomDialog使用id和fragment作为OnBindView的参数，表现不一致 (Issue #239)


这几天在想，如果使用fragment的缺陷是框架无法动态创建资源id，由调用者自己去在布局里放入frameLayou，然后将id作为参数传入onbindView里面。取代id_frame_layout_custom。我简单在demo了改造了下，能显示，但没有相对应的动画,已经其他一些功能，我并不理解其中的缘由。

―

**Comment by AreYReady** [comment]
叹为观止啊，大佬。你对源码是有多了解啊。要不要方案都是这么高级的。

**Comment by kongzue** [comment]
很不幸失败了，很多东西都被private掉了，FragmentManagerImpl 也无法自己创建，Google限制太多了

**Comment by AreYReady** [comment]
了解，胳膊拧不过大腿。如果自我创建做不到，那是否能以参数的形式让调用者传入frameLayout的id，一遍拓展。

**Comment by kongzue** [comment]
别着急，我在想别的办法，刚刚试验的结果是，我可以自己模拟Fragment的全生命周期过程，但对于内部所使用到的Hosts等元素无法hook，这会导致 Fragment 是无法真的完整使用，模拟这条路应该是不通的，在尝试别的办法

**Comment by kongzue** [comment]
请更新至 0.0.46.beta15 版本，已经对同一 activity 显示多个 fragment 的问题进行了处理，最终使用的方案为动态创建未使用的 id

**Comment by AreYReady** [comment]
啥意思，一开始多创建几个id放着，然后同页面按顺序去使用吗。

**Comment by kongzue** [comment]
不是，搞定动态生成id了
________________________________
发件人: AreYReady ***@***.***>
发送时间: Tuesday, September 13, 2022 3:48:58 PM
收件人: kongzue/DialogX ***@***.***>
抄送: Kongzue ***@***.***>; State change ***@***.***>
主题: Re: [kongzue/DialogX] CustomDialog使用id和fragment作为OnBindView的参数，表现不一致 (Issue #239)


啥意思，一开始多创建几个id放着，然后同页面按顺序去使用吗。

―

**Comment by shejishi** [comment]
动态生成id会导致使用fragment弹不出来，报错信息：
`
java.lang.IllegalArgumentException: No view found for id 0xbe3df20a (unknown) for fragment FarmBackpackFragment{e908fb6} (655e4e8a-2500-4d30-920e-93007be62832 id=0xbe3df20a)
	at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:514)
	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:261)
	at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1890)
	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1808)
	at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1751)
	at androidx.fragment.app.FragmentManager$5.run(FragmentManager.java:538)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:148)
	at android.app.ActivityThread.main(ActivityThread.java:5647)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:745)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:635)
`

**Comment by kongzue** [comment]
> 动态生成id会导致使用fragment弹不出来，报错信息：
> 
> ```
> java.lang.IllegalArgumentException: No view found for id 0xbe3df20a (unknown) for fragment FarmBackpackFragment{e908fb6} (655e4e8a-2500-4d30-920e-93007be62832 id=0xbe3df20a)
> 	at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:514)
> 	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:261)
> 	at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1890)
> 	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1808)
> 	at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1751)
> 	at androidx.fragment.app.FragmentManager$5.run(FragmentManager.java:538)
> 	at android.os.Handler.handleCallback(Handler.java:739)
> 	at android.os.Handler.dispatchMessage(Handler.java:95)
> 	at android.os.Looper.loop(Looper.java:148)
> 	at android.app.ActivityThread.main(ActivityThread.java:5647)
> 	at java.lang.reflect.Method.invoke(Native Method)
> 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:745)
> 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:635)
> ```

请确认你的堆栈信息中存在 DialogX 的错误信息，我这边无法处理非 DialogX 框架的问题。
