### ISSUE TITLE
弱弱的问一句pr里那个小bug什么时候发

### ISSUE THREAD

**Issue by Zhao-Yan-Yan** [kongzue/DialogX#24]
今天项目要发版

**Comment by kongzue** [comment]
不太理解您是指哪个问题

**Comment by Zhao-Yan-Yan** [comment]
就是那个默认动画 透明度的问题

**Comment by kongzue** [comment]
稍等，一会给你一个beta版

________________________________
发件人: ZhaoYanDev <notifications@github.com>
发送时间: Tuesday, March 2, 2021 5:24:52 PM
收件人: kongzue/DialogX <DialogX@noreply.github.com>
抄送: Kongzue <myzcxhh@live.cn>; Comment <comment@noreply.github.com>
主题: Re: [kongzue/DialogX] 弱弱的问一句pr里那个小bug什么时候发 (#24)


就是那个默认动画 透明度的问题

―

**Comment by Zhao-Yan-Yan** [comment]
🙏

**Comment by kongzue** [comment]
请更新至0.0.32.beta3版本，已修复此问题。
