### ISSUE TITLE
【BUG反馈】BottomMenu.setAllowInterceptTouch(false)列表展示不全

### ISSUE THREAD

**Issue by super-cc** [kongzue/DialogX#240]
## BUG 反馈

请先确认您已阅读[《常见问题》](https://github.com/kongzue/DialogX/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)

### 问题描述：
BottomMenu.setAllowInterceptTouch(false)列表展示不全。

### 是否在 Demo 中能复现此问题？
是

**Comment by super-cc** [comment]
@kongzue 大佬，今天能解决吗？我要用。嘿嘿

**Comment by kongzue** [comment]
急着用的话先加一个：
```java
.setBottomDialogMaxHeight(0.99f)
```
可以凑合用，下一个版本修复问题。

**Comment by kongzue** [comment]
修复更新代码已提交 github，等待合并提交版本

**Comment by super-cc** [comment]
@kongzue 好的大佬，等你就行，不是特别急。

**Comment by super-cc** [comment]
@kongzue 还有一个小问题，如果我使用了setAllowInterceptTouch(false)，那么我在recyclerView滑动到顶的时候，再向下滑动就不能收起dialog了，是否可以优化一下呢？

**Comment by kongzue** [comment]
setAllowInterceptTouch 本身就是关闭：触摸关闭对话框 这个功能的啊，需要怎么优化

**Comment by super-cc** [comment]
像我之前用BottomSheetDialogFragment就可以做到。

**Comment by kongzue** [comment]
那你就不应该关闭 setAllowInterceptTouch 啊，setAllowInterceptTouch(false) 本身的目的就是由你自己的布局处理所有触摸事件，Demo里也有说怎么做滑动继承，你也可以参考下 wiki

**Comment by super-cc** [comment]
我的目的是弹出的时候是一个半屏，向上滑动的时候，不要变成全屏，一直是半屏的状态。

**Comment by kongzue** [comment]
> 我的目的是弹出的时候是一个半屏，向上滑动的时候，不要变成全屏，一直是半屏的状态。

我知道，这个会在下一版更新后修复，代码已经提交了，等待和其他更新内容合并发版

**Comment by kongzue** [comment]
请更新至 0.0.46.beta13 版本：https://github.com/kongzue/DialogX/releases/tag/0.0.46.beta13

**Comment by super-cc** [comment]
好的。

**Comment by super-cc** [comment]
大佬在哪发财呢。

**Comment by kongzue** [comment]
![image](https://user-images.githubusercontent.com/10115359/188799363-818f7429-b1d3-4d7e-8928-7f5704fd9a79.png)

**Comment by super-cc** [comment]
我还有一个小需求，就是我希望是一个固定高度的，现在如果我的列表只有少量数据的话，会很低，固定高度用户体验会好一些。

**Comment by kongzue** [comment]
这个不难，你把自定义布局使用固定高度就可以了

**Comment by super-cc** [comment]
这个我刚才也想到了，这样的话想要设置会屏幕大小的百分比高度的话，就需要在代码中写比较多的内容，比如现在可以设置的最大高度为setBottomDialogMaxHeight(0.6f)。希望可以优化。

**Comment by super-cc** [comment]
并且我在使用你所说的方法之后，recycleView第一条不能点击了。

**Comment by super-cc** [comment]
不对，是不管怎样，我RecyclerView第一条都不能点击了。

**Comment by kongzue** [comment]
不清楚，BottomMenu、FullScreenDialog 也是这么处理的，没有发现触摸事件存在问题

**Comment by kongzue** [comment]
请排查一下具体原因，我这边也不好做复现

**Comment by super-cc** [comment]
点击和我这边用的另一个框架有关系，我找一下原因。

**Comment by super-cc** [comment]
不过将adapter里的item的layout里，根布局从match改为wrap的话，滑动会卡顿。

**Comment by super-cc** [comment]
请问，你那边有复现我最后讲的一个问题吗？

**Comment by kongzue** [comment]
目前已上线的项目没有发现类似的问题

**Comment by super-cc** [comment]
我用你写的demo也是可以复现的。不过我下载demo的时间比较早。

**Comment by super-cc** [comment]
我使用的是这个dialog。
![image](https://user-images.githubusercontent.com/26076424/188820856-dbf727f8-7009-4e18-ab97-b63a74504e6c.png)

**Comment by super-cc** [comment]
我描述有点小问题，不是滑动卡顿，而是没有了滑动惯性。

**Comment by kongzue** [comment]
已尝试但未发现任何问题。
测试设备：Google Pixel5(Android 13)骁龙765G
测试代码：
```java
List<CustomRecycleViewAdapter.Data> dataArrayList = new ArrayList<>();
dataArrayList.add(new CustomRecycleViewAdapter.Data("Item Text 1"));
dataArrayList.add(new CustomRecycleViewAdapter.Data("Item Text 2"));
dataArrayList.add(new CustomRecycleViewAdapter.Data("Item Text 3"));
dataArrayList.add(new CustomRecycleViewAdapter.Data("Item Text 4"));
dataArrayList.add(new CustomRecycleViewAdapter.Data("Item Text 5"));
dataArrayList.add(new CustomRecycleViewAdapter.Data("Item Text 6"));
dataArrayList.add(new CustomRecycleViewAdapter.Data("Item Text 7"));
dataArrayList.add(new CustomRecycleViewAdapter.Data("Item Text 8"));
dataArrayList.add(new CustomRecycleViewAdapter.Data("Item Text 9"));
dataArrayList.add(new CustomRecycleViewAdapter.Data("Item Text 10"));
dataArrayList.add(new CustomRecycleViewAdapter.Data("Item Text 11"));
dataArrayList.add(new CustomRecycleViewAdapter.Data("Item Text 12"));
dataArrayList.add(new CustomRecycleViewAdapter.Data("Item Text 13"));
dataArrayList.add(new CustomRecycleViewAdapter.Data("Item Text 14"));
BottomDialog.build()
        .setCustomView(new OnBindView<BottomDialog>(R.layout.layout_custom_recycleview) {
            @Override
            public void onBind(BottomDialog dialog, View v) {
                RecyclerView recyclerView = (RecyclerView) v;
                LinearLayoutManager linearLayoutManager = new LinearLayoutManager(me);
                recyclerView.setLayoutManager(linearLayoutManager);
                CustomRecycleViewAdapter adapter = new CustomRecycleViewAdapter(dataArrayList);
                adapter.setOnItemClickListener(new AdapterView.OnItemClickListener() {
                    @Override
                    public void onItemClick(AdapterView<?> parent, View view, int position, long id) {
                        PopTip.show("点击 position："+position);
                    }
                });
                recyclerView.setAdapter(adapter);
            }
        })
        .setBottomDialogMaxHeight(0.6f)
        .setAllowInterceptTouch(false)
        .show();
```
子布局：
```xml
<?xml version="1.0" encoding="utf-8"?>
<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="wrap_content">

    <TextView
        android:id="@+id/txt_item"
        android:layout_width="match_parent"
        android:layout_height="100dp"
        android:gravity="center"
        android:textSize="20dp" />

</RelativeLayout>
```
![image](https://user-images.githubusercontent.com/10115359/188825952-dbabdb9d-f8a5-44d4-9d7d-1ea034792924.png)

**Comment by super-cc** [comment]
滑动有惯性吗？点击是没问题的。

**Comment by kongzue** [comment]
滑动惯性正常。
测试视频：

https://user-images.githubusercontent.com/10115359/188826874-28d54046-ad6e-4e67-af2f-fda39b7d22b3.mp4

**Comment by super-cc** [comment]
我这换了几台国产手机都是必现的，你那边有国产手机没有，我这试过小米和华为。
![image](https://user-images.githubusercontent.com/26076424/188863822-cb5674b8-ccbe-4870-b53e-0859b10f1334.png)
![image](https://user-images.githubusercontent.com/26076424/188863885-6c86b897-4d18-4ce3-b90e-cc5cfd09759c.png)
就修改这两处就必现。

**Comment by kongzue** [comment]
已在小米12SU 上进行测试（Android 12）未发现任何问题：

https://user-images.githubusercontent.com/10115359/188870875-2d08274f-bc62-4278-be8c-41be7e028bde.mp4

**Comment by super-cc** [comment]
那就奇了怪了昂，哈哈

**Comment by kongzue** [comment]
因为牵扯到几个测试用的小布局的修改，我把最新的测试代码提交 Github 了，你可以拉取测试看看

**Comment by super-cc** [comment]
好的。

**Comment by kongzue** [comment]
长时间未回复，暂时关闭了此问题，若有疑问请继续回复。
