### ISSUE TITLE
【BUG反馈】PopTip setAlign(DialogXStyle.PopTipSettings.ALIGN.CENTER)  未起作用

### ISSUE THREAD

**Issue by Lumberjack100** [kongzue/DialogX#242]
## BUG 反馈

请先确认您已阅读[《常见问题》](https://github.com/kongzue/DialogX/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)

### 问题描述：
     PopTip.show("测试!").setAlign(DialogXStyle.PopTipSettings.ALIGN.CENTER).autoDismiss(3500).iconSuccess();

提示消息没有居中显示，依然在底部显示。

### 设备信息：
Build.VERSION.SDK_INT: 29
Build.MANUFACTURER: Xiaomi Mix2S

### 是否在 Demo 中能复现此问题？
是

**Comment by kongzue** [comment]
很抱歉经过查验，此 API 并非公开使用的 API，在 wiki 中也并未公开说明，虽然它设计的本意是可以定义 PopTip 所显示的位置，但事实上，PopTip 的设计改为了依赖其主题样式的设定而非通过 `setAlign(...)` 进行设置，此设置也不会生效。
如果要使  `setAlign(...)` 设置生效，可能需要对 PopTip 的显示过程进行重大调整（包括不限于入场动画方式、位移方式等），此功能暂时在下个版本会被标记为废弃，感谢你的反馈。

**Comment by kongzue** [comment]
已更新版本：https://github.com/kongzue/DialogX/releases/tag/0.0.46.beta14
