### ISSUE TITLE
优化建议

### ISSUE THREAD

**Issue by hzhdeveloper** [kongzue/DialogX#244]
使用的方式还值得进行优化，举个例子，给我你的这个库，我还需要看个半天，说句实话，如果需要实现最普通的一个dialog，你这个真有可能比我直接写还要慢，不能说我看不懂或理解能力差，因为你们这个使用教程就写的很乱。。。

**Comment by kongzue** [comment]
请具体举例。
DialogX 提供了至少两种构建方式，包含 build() 方式和直接使用静态方法构建，若你认为这很难，请列举出你认为合理的构建方式。
使用方法请参阅 [wiki](https://github.com/kongzue/DialogX/wiki)，我认为已经写的很详细了。

**Comment by hzhdeveloper** [comment]
建议为：举一反三，直接把例子写到wiki里，其实看文档的人可能不需要你的原理或者解释，只需要具体的例子即可。
感谢回复！
这样可能会对你们的工作量较大，但这个最浅显易用，而非易懂，谢谢。





&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "kongzue/DialogX"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年9月13日(星期二) 下午3:17
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [kongzue/DialogX] 优化建议 (Issue #244)





 
请具体举例。
 DialogX 提供了至少两种构建方式，包含 build() 方式和直接使用静态方法构建，若你认为这很难，请列举出你认为合理的构建方式。
 使用方法请参阅 wiki，我认为已经写的很详细了。

**Comment by kongzue** [comment]
如果需要范例代码其实可以直接拉取库代码参阅 app 相关代码，这里边全部都是 Demo 范例代码。
DialogX 只提供基础的对话框组件，我认为在 wiki 中应当给清楚所有的 API 及其释义更为合适，若全部提供范例代码将对某样功能的查找造成不便。

**Comment by hzhdeveloper** [comment]
OK，总之谢谢，同为开源人为你的开源点赞
