### ISSUE TITLE
【功能建议】可以让BottomMenu 支持显示多行吗？而不是超过1行  后面就点点点

### ISSUE THREAD

**Issue by strongerzzx** [kongzue/DialogX#247]
希望BottomMenu支持用户来选择是否单行还是多行显示

**Comment by kongzue** [comment]
这个需要修改对应主题的 layout 布局文件，请根据自己使用的主题，找到对应的 item 布局文件进行覆写或修改：
### 覆写方法
例如默认主题的是：[item_dialogx_material_context_menu_normal_text.xml](https://github.com/kongzue/DialogX/blob/master/DialogX/src/main/res/layout/item_dialogx_material_context_menu_normal_text.xml)
暗色主题是[item_dialogx_material_bottom_menu_normal_text.xml](https://github.com/kongzue/DialogX/blob/master/DialogX/src/main/res/layout/item_dialogx_material_bottom_menu_normal_text.xml)
你可以在自己的项目里 res/layout 中创建相同名称的布局文件，拷贝上述文件内容，自行进行修改。

**Comment by kongzue** [comment]
长时间未答复暂时关闭了此问题，若有疑问请继续回复。
