### ISSUE TITLE
【BUG反馈】在第一个 Activity onCreate 方法中无法显示 Dialog

### ISSUE THREAD

**Issue by julyss2019** [kongzue/DialogX#248]
## BUG 反馈

请先确认您已阅读[《常见问题》](https://github.com/kongzue/DialogX/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)

### 问题描述：
请在此详细描述问题。
`
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
            MessageDialog.show("提示", "测试", "测试");
  }`

无法在启动的（第一个加载的） Activity 中显示 Dialog，无报错。

### 设备信息：
Android 6.0.1

### 是否在 Demo 中能复现此问题？
未尝试

### 问题截图/视频
请在此插入佐证问题的截图和视频。

**Comment by kongzue** [comment]
请确认你已经提前初始化DialogX，建议在Application#onCreate中初始化。
此问题未能在正常初始化的Demo中复现，

**Comment by julyss2019** [comment]
已解决，感谢
