### ISSUE TITLE
分割线好像没有效果

### ISSUE THREAD

**Issue by libern** [kongzue/DialogX#25]
![image](https://user-images.githubusercontent.com/1830640/109943991-b5530e00-7d10-11eb-83bf-2f25d4da5bf7.png)

第一根分割线好像没效果

**Comment by kongzue** [comment]
不理解你的意思

**Comment by kongzue** [comment]
有一个简便方法，直接在你的APP中的`res/colors.xml`定义一个颜色：
```
<color name="dialogxIOSSplitLight">#2196F3</color>
```
即可直接修改所有iOS主题分割线的颜色

**Comment by libern** [comment]
> 不理解你的意思

你看图里的删除app按钮的上面分割线的颜色比较深，是ios默认的，而我设置了一个比较浅的分割线颜色了。在这个按钮下面2根线都体现出来了

**Comment by libern** [comment]
> 有一个简便方法，直接在你的APP中的`res/colors.xml`定义一个颜色：
> 
> ```
> <color name="dialogxIOSSplitLight">#2196F3</color>
> ```
> 
> 即可直接修改所有iOS主题分割线的颜色

如果想设置ios的按钮按下的颜色，有办法通过这种方式吗？

**Comment by libern** [comment]
好像没办法自定义ios主题的背景颜色，当前blurcolor一定要打开，才能使设置的生效，而不打开blurcolor就没用

**Comment by kongzue** [comment]
个人建议自定义主题，可以参考wiki中的自定义主题部分，最新版本你可以创建一个class继承IOSStyle，并修改其中的部分设定。

________________________________
发件人: Libern <notifications@github.com>
发送时间: Thursday, March 4, 2021 6:24:44 PM
收件人: kongzue/DialogX <DialogX@noreply.github.com>
抄送: Kongzue <myzcxhh@live.cn>; Comment <comment@noreply.github.com>
主题: Re: [kongzue/DialogX] 分割线好像没有效果 (#25)


有一个简便方法，直接在你的APP中的res/colors.xml定义一个颜色：

<color name="dialogxIOSSplitLight">#2196F3</color>



即可直接修改所有iOS主题分割线的颜色

如果想设置ios的按钮按下的颜色，有办法通过这种方式吗？

―

**Comment by kongzue** [comment]
在最新的0.0.34版本中对此问题进行了修复，在设置Style对分割线的着色后，对话框中的横向分割线也会着色。
先关闭了此问题，若有疑问可继续回复

**Comment by libern** [comment]
#32
