### ISSUE TITLE
自定义布局的BottomDialog中setOkButton()方法里新建对象无法获取上下文的问题

### ISSUE THREAD

**Issue by kikkichen** [kongzue/DialogX#250]
### BottomDialog中使用了自定义布局
样式如下：
![图片](https://user-images.githubusercontent.com/48638091/194811782-3ddd1bb8-7207-4d22-bbc2-3a7897183eda.png)
上述图示中有一个EditText与两个Bottom。

我定义了一个_RecyclerView_，我在为_RecyclerView_中的每个_item_都设置了一个长按监听，触发时就会弹出BottomDialog：
![图片](https://user-images.githubusercontent.com/48638091/194815247-80fb9e10-098a-4bfe-b7e3-cc83dc8d99c8.png)

在如下使用`BottomDialog.show(...)`中使用没有任何问题，`onBind(dialog, v)`里的view型参也可以获取到视图控件。
``` kotlin
BottomDialog.show("为学生添加地址信息", "${tmpStudent.id},  ${tmpStudent.name},  ${tmpStudent.className},  ${tmpStudent.score}",
    object : OnBindView<BottomDialog>(R.layout.write_student_address_layout) {

        override fun onBind(dialog: BottomDialog?, v: View?) {
            ......
         }
...... })

```
这包括了我自定义布局中的EditText控件与Button，都是能够被`v.findViewById()`找到的。

而当我在后续使用`setOkButton()`想调用对话框自身的按键监听，获取我自定义布局中的EditText输入内容时，就遇到了麻烦：
```kotlin
BottomDialog.show("为学生添加地址信息", "${tmpStudent.id},  ${tmpStudent.name},  ${tmpStudent.className},  ${tmpStudent.score}",
    object : OnBindView<BottomDialog>(R.layout.write_student_address_layout) {

        override fun onBind(dialog: BottomDialog?, v: View?) {
            ......
         }
        ... ...  
        }).apply { okButton = "确定" }
            // view 组件空指针异常位置
        .setOkButton { dialog, v ->
            CoroutineScope(Dispatchers.IO).launch {
                StudentDataBase.getInstance(parentContext).getStudentDao()
                    .updateAddress(StudentAddressEntity(
                        sid = tmpStudent.id,
                        address = v.findViewById<EditText>(R.id.edit_address).text.toString()    // 这个位置出现空指针  引用为空
                    ))
            }
            Toast.makeText(parentContext, "\uD83D\uDDFA️ 地址保存成功", Toast.LENGTH_SHORT)
                .show()
            dialog?.dismiss()
            true
        }
```
报错如下：
```Terminal
E/AndroidRuntime: FATAL EXCEPTION: DefaultDispatcher-worker-1
    Process: com.chen.kotlin_room1, PID: 4945
    java.lang.NullPointerException: Attempt to invoke virtual method 'android.text.Editable android.widget.EditText.getText()' on a null object reference
        at com.chen.kotlin_room1.adpters.StudentScoreViewAdapter$onBindViewHolder$1$2$3$1.invokeSuspend(StudentScoreViewAdapter.kt:181)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
        at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
    	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@258a80e, Dispatchers.IO]
```

上述问题，我现在是采用使用自定义Button来妥协处理，但是还是想知道`setOkButton()`中`onClick(dialog, v)`里的`View: v`有没有办法解决这个空引用的问题。

**Comment by kongzue** [comment]
因为你理解错了setOkButton回调中的 v 的含义，它表示的是OK按钮，在这里使用 v.findViewById 是无法找到自定义 view 内的布局的，请使用：
```java
dialog.getCustomView().findViewById(resId) 
```
来获取你的自定义布局内实例。

**Comment by kikkichen** [comment]
> ### BottomDialog中使用了自定义布局
> 
> 样式如下： ![图片](https://user-images.githubusercontent.com/48638091/194811782-3ddd1bb8-7207-4d22-bbc2-3a7897183eda.png) 上述图示中有一个EditText与两个Bottom。
> 
> 我定义了一个_RecyclerView_，我在为_RecyclerView_中的每个_item_都设置了一个长按监听，触发时就会弹出BottomDialog： ![图片](https://user-images.githubusercontent.com/48638091/194815247-80fb9e10-098a-4bfe-b7e3-cc83dc8d99c8.png)
> 
> 在如下使用`BottomDialog.show(...)`中使用没有任何问题，`onBind(dialog, v)`里的view型参也可以获取到视图控件。
> 
> ```kotlin
> BottomDialog.show("为学生添加地址信息", "${tmpStudent.id},  ${tmpStudent.name},  ${tmpStudent.className},  ${tmpStudent.score}",
>     object : OnBindView<BottomDialog>(R.layout.write_student_address_layout) {
> 
>         override fun onBind(dialog: BottomDialog?, v: View?) {
>             ......
>          }
> ...... })
> ```
> 
> 这包括了我自定义布局中的EditText控件与Button，都是能够被`v.findViewById()`找到的。
> 
> 而当我在后续使用`setOkButton()`想调用对话框自身的按键监听，获取我自定义布局中的EditText输入内容时，就遇到了麻烦：
> 
> ```kotlin
> BottomDialog.show("为学生添加地址信息", "${tmpStudent.id},  ${tmpStudent.name},  ${tmpStudent.className},  ${tmpStudent.score}",
>     object : OnBindView<BottomDialog>(R.layout.write_student_address_layout) {
> 
>         override fun onBind(dialog: BottomDialog?, v: View?) {
>             ......
>          }
>         ... ...  
>         }).apply { okButton = "确定" }
>             // view 组件空指针异常位置
>         .setOkButton { dialog, v ->
>             CoroutineScope(Dispatchers.IO).launch {
>                 StudentDataBase.getInstance(parentContext).getStudentDao()
>                     .updateAddress(StudentAddressEntity(
>                         sid = tmpStudent.id,
>                         address = v.findViewById<EditText>(R.id.edit_address).text.toString()    // 这个位置出现空指针  引用为空
>                     ))
>             }
>             Toast.makeText(parentContext, "\uD83D\uDDFA️ 地址保存成功", Toast.LENGTH_SHORT)
>                 .show()
>             dialog?.dismiss()
>             true
>         }
> ```
> 
> 报错如下：
> 
> ```
> E/AndroidRuntime: FATAL EXCEPTION: DefaultDispatcher-worker-1
>     Process: com.chen.kotlin_room1, PID: 4945
>     java.lang.NullPointerException: Attempt to invoke virtual method 'android.text.Editable android.widget.EditText.getText()' on a null object reference
>         at com.chen.kotlin_room1.adpters.StudentScoreViewAdapter$onBindViewHolder$1$2$3$1.invokeSuspend(StudentScoreViewAdapter.kt:181)
>         at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
>         at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
>         at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
>         at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
>         at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
>         at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
>         at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
>         at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
>     	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@258a80e, Dispatchers.IO]
> ```
>

**Comment by kikkichen** [comment]
> 因为你理解错了setOkButton回调中的 v 的含义，它表示的是OK按钮，在这里使用 v.findViewById 是无法找到自定义 view 内的布局的，请使用：
> 
> ```java
> dialog.getCustomView().findViewById(resId) 
> ```
> 
> 来获取你的自定义布局内实例。

我明白了，谢谢指正。
