### ISSUE TITLE
是否有自定義滑動條顏色的方法

### ISSUE THREAD

**Issue by Djfox936** [kongzue/DialogX#251]
我透過BottomSheet的SetBackgroundColor方法設定黑色背景，但是如此上面的滑動條在深色模式下會顯示不出來，請問有甚麼可以自定義上面滑動條顏色的方法嗎?

**Comment by kongzue** [comment]
你可以使用以下代碼獲取滑動條對象：
```java
BottomDialog.build()
        .setDialogLifecycleCallback(new DialogLifecycleCallback<BottomDialog>() {
            @Override
            public void onShow(BottomDialog dialog) {
                dialog.getDialogImpl().imgTab.setBackgroundResource(...);
            }
        })
```
事實上，DialogX 的內部成員都是通過 `.getDialogImpl()` 對外暴露的，你可以使用它來控制所有細節。
另外關於夜間模式，DialogX 以及各個主題都是直接支持夜間模式的，你可以使用以下代碼來調整它：
```java
DialogX.globalTheme = DialogX.THEME.LIGHT;  //亮色模式
DialogX.globalTheme = DialogX.THEME.DARK;   //暗色模式
DialogX.globalTheme = DialogX.THEME.AUTO;   //自動根據系統情況判斷亮暗色模式
```
如果你希望永久修改主題細節樣式，你可以通過 [自訂 DialogX 主題](https://github.com/kongzue/DialogX/wiki/%E8%87%AA%E5%AE%9A%E4%B9%89-DialogX-%E4%B8%BB%E9%A2%98) 或者手動重寫主題布局資源，例如 BottomDialog 組件的默認 Material 風格亮色主題文件是 [layout_dialogx_bottom_material.xml](https://github.com/kongzue/DialogX/blob/master/DialogX/src/main/res/layout/layout_dialogx_bottom_material.xml)，以及暗色是 [layout_dialogx_bottom_material_dark.xml](https://github.com/kongzue/DialogX/blob/master/DialogX/src/main/res/layout/layout_dialogx_bottom_material_dark.xml)，你可以在自己的 app 的 res/layout 目錄下創建相同名稱的布局資源，拷貝上述代碼進行修改，在運行時會替換 DialogX 的默認資源顯示。

**Comment by kongzue** [comment]
暫時關閉了此問題，如有疑問請繼續回復
