### ISSUE TITLE
请问在Dialog弹出后，无法获取到onKeyDown()按键事件，对这个处理有做吗？

### ISSUE THREAD

**Issue by 732275239** [kongzue/DialogX#253]
如题

**Comment by Jichensheng** [comment]
PopTip弹出后会使键盘自动缩回

**Comment by kongzue** [comment]
DialogX会拦截返回键处理，如果需要在对话康弹出时处理返回按键，请使用监听：
```java
.setOnBackPressedListener(new OnBackPressedListener<WaitDialog>() {
    @Override
    public boolean onBackPressed(WaitDialog dialog) {
        return false;
    }
});
```

**Comment by 732275239** [comment]
> DialogX会拦截返回键处理，如果需要在对话康弹出时处理返回按键，请使用监听：
> 
> ```java
> .setOnBackPressedListener(new OnBackPressedListener<WaitDialog>() {
>     @Override
>     public boolean onBackPressed(WaitDialog dialog) {
>         return false;
>     }
> });
> ```

并不仅仅是针对返回，比如我现在做了一个投屏的界面，就是通过DialogX，然后手机的音量按钮事件我接收不到

**Comment by kongzue** [comment]
> > DialogX会拦截返回键处理，如果需要在对话康弹出时处理返回按键，请使用监听：
> > ```java
> > .setOnBackPressedListener(new OnBackPressedListener<WaitDialog>() {
> >     @Override
> >     public boolean onBackPressed(WaitDialog dialog) {
> >         return false;
> >     }
> > });
> > ```
> 
> 并不仅仅是针对返回，比如我现在做了一个投屏的界面，就是通过DialogX，然后手机的音量按钮事件我接收不到

那你多半是找错人了，DialogX并不会全局拦截按键，请自行排查原因。
DialogX仅在对话框弹出且具备焦点时会进行返回键的拦截操作，具体代码在 [DialogXBaseRelativeLayout.java:123](https://github.com/kongzue/DialogX/blob/3d58e14191b847ce7c5a9a0d0394bf6e81386a77/DialogX/src/main/java/com/kongzue/dialogx/util/views/DialogXBaseRelativeLayout.java#L123)，相关代码如下：
```java
@Override
public boolean dispatchKeyEvent(KeyEvent event) {
    if (isAttachedToWindow() && event.getAction() == KeyEvent.ACTION_UP && event.getKeyCode() == KeyEvent.KEYCODE_BACK && interceptBack) {
        if (onBackPressedListener != null) {
            return onBackPressedListener.onBackPressed();
        }
    }
    return super.dispatchKeyEvent(event);
}
```
它仅会在 DialogXBaseRelativeLayout 处于焦点时生效，且只会拦截返回按键，而且当 onBackPressedListener 未设置时也会默认正常走 `super.dispatchKeyEvent(event)` 并不会拦截。

**Comment by 732275239** [comment]
> 

 好的。我再检查检查代码

**Comment by kongzue** [comment]
长时间未收到回复暂时关闭了此问题，若有疑问请继续回复。
