### ISSUE TITLE
【BUG反馈】在CustomDialog上使用WaitDialog不显示了

### ISSUE THREAD

**Issue by LiJoeAllen** [kongzue/DialogX#254]
## BUG 反馈

请先确认您已阅读[《常见问题》](https://github.com/kongzue/DialogX/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)

### 问题描述：
在CustomDialog上使用WaitDialog不显示了

### 设备信息：
ShiMeta 3568WP/Android11

### 是否在 Demo 中能复现此问题？
未尝试

### 问题截图/视频
不方便

**Comment by kongzue** [comment]
未能在Demo代码中复现你所描述的问题，请尝试拉取Github代码，在Demo app中复现，若可以重复复现问题，我会尝试寻找一台相同的设备进行测试。
