### ISSUE TITLE
【BUG反馈】您好，bottomsheet底部弹窗系列，poptip 被遮挡了 ，无法在最上层显示

### ISSUE THREAD

**Issue by Li4526330** [kongzue/DialogX#256]

**Comment by kongzue** [comment]
请确认你已经看过 [常见问题](https://github.com/kongzue/DialogX/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98#qdialogx-%E6%97%A0%E6%B3%95%E8%A6%86%E7%9B%96%E5%9C%A8-dialogfragmentalertdialog-%E4%B9%8B%E4%B8%8A)

**Comment by kongzue** [comment]
长时间未收到回复暂时关闭了此问题，若有疑问请继续回复。
