### ISSUE TITLE
【功能建议】进度提示框没有立即显示具体进度

### ISSUE THREAD

**Issue by EthanCo** [kongzue/DialogX#257]
## 功能建议
希望调用进度提示框后，能够立即显示出具体的进度，而不是先Loading一下，再显示出具体进度

### 需求描述：
第一次调用`WaitDialog.show(progress)`的时候，不会立即显示出具体的进度，而是会显示Loading。
第二次调用`WaitDialog.show(progress)`才会出现具体的进度条。  
希望能有方法第一次调用`WaitDialog.show(progress)`的时候，就可以显示出具体的进度。

当前使用的版本 : 0.0.46

**Comment by kongzue** [comment]
已确认此问题是个bug，已在最新测试版修复，请更新至 0.0.47.beta3 版本
相关更新日志：https://github.com/kongzue/DialogX/releases/tag/0.0.47.beta3

**Comment by kongzue** [comment]
长时间未收到回复暂时关闭了此问题，若有疑问请继续回复。

**Comment by Bruce8hou** [comment]
0.0.47.beta11 版本的进度不显示了

**Comment by kongzue** [comment]
> 0.0.47.beta11 版本的进度不显示了

@Bruce8hou 很抱歉未能复现你所描述的问题。
在Google Pixel5 Android 13上进行测试：
1. 直接执行：
```java
WaitDialog.show(0.5f);
```
运行结果：
![image](https://user-images.githubusercontent.com/10115359/206269360-d53a7f18-9ebd-42c1-874e-8e88462b8d29.png)
符合预期。
2. 先执行 wait 然后转为进度：
```java
WaitDialog.show("loading...");
runOnMainDelayed(new Runnable() {
    @Override
    public void run() {
        WaitDialog.show(0.5f);
    }
},1000);
```
运行结果：
![image](https://user-images.githubusercontent.com/10115359/206269664-d0bd1b23-d409-435b-922b-5ad95ac3b548.png)
符合预期
未能发现任何问题。
