### ISSUE TITLE
我用了  今日头条屏幕适配方案->AndroidAutoSize 导致尺寸改变

### ISSUE THREAD

**Issue by CPC-Coder** [kongzue/DialogX#258]
### 需求描述：
DialogFragmentImpl 想加上 implements CancelAdapt   或者自己的类 来替换   有什么办法
请详细描述你的需求。

**Comment by CPC-Coder** [comment]
但又不想改太多代码  style要动的地方比较多

**Comment by kongzue** [comment]
长时间未收到回复，暂时关闭了此问题，若有疑问请继续回复。
