### ISSUE TITLE
【功能建议】底部弹框下拉关闭没有回调

### ISSUE THREAD

**Issue by yuantang** [kongzue/DialogX#260]
### 需求描述：
底部弹框在下拉关闭得时候需要有关闭的监听

**Comment by kongzue** [comment]
已基于最新的Demo代码进行了测试，未能发现任何问题
测试设备：Google Pixel5 Android 13
测试流程：使用 Material 主题，启动 BottomDialog，下滑关闭，监听 DialogLifecycleCallback#onDismiss ，结果符合预期，测试截图如下：
![image](https://user-images.githubusercontent.com/10115359/206150229-c972b75c-7f71-4753-8ced-97c51955dcdb.png)

**Comment by kongzue** [comment]
相关代码：
```java
.setDialogLifecycleCallback(new DialogLifecycleCallback<BottomDialog>() {
    @Override
    public void onDismiss(BottomDialog dialog) {
        log("对话框关闭了");
        super.onDismiss(dialog);
    }
})
```

**Comment by yuantang** [comment]
这个全局的弹框关闭的监听，我需要针对下拉的关闭的监听通知，这个一直没有找到方法

**Comment by kongzue** [comment]
在新的版本 0.0.47.beta12 中增加了此功能，下边是详细的更新日志：
- 为 BottomDialog、BottomMenu 增加了 `.setDialogLifecycleCallback(...)` 的新实现 BottomDialogSlideEventLifecycleCallback，通过它可以监控由滑动引发的关闭事件：`BottomDialogSlideEventLifecycleCallback#onSlideClose(dialog)` 以及滑动过程：`BottomDialogSlideEventLifecycleCallback#onSlideTouchEvent(dialog, v, event)`，当返回 true 时表示拦截操作，对话框不会继续关闭或处理滑动流程，可实现触摸事件接管；
具体操作示例：
```java
.setDialogLifecycleCallback(new BottomDialogSlideEventLifecycleCallback<BottomDialog>() {
    @Override
    public boolean onSlideClose(BottomDialog dialog) {
        log("#onSlideClose");
        return super.onSlideClose(dialog);
    }
    @Override
    public boolean onSlideTouchEvent(BottomDialog dialog, View v, MotionEvent event) {
        log("#onSlideTouchEvent: action="+ event.getAction() + " y="+event.getY());
        return super.onSlideTouchEvent(dialog, v, event);
    }
})
```
