### ISSUE TITLE
【BUG反馈】CustomDialog复用时动画失效

### ISSUE THREAD

**Issue by JersonSU** [kongzue/DialogX#263]
### 问题描述：
CustomDialog第一次显示时，有动画效果，但是复用时，第二次显示就没有了动画效果

### 设备信息：
设备：华为Meta30 鸿蒙2.0系统

### 是否在 Demo 中能复现此问题？
未尝试

### 问题截图/视频
CustomDialog dialog;
if(dialog==null){
    dialog=CustomDialog.show(new OnBindView...);//有动画
}else{
    dialog.show();//无动画
}

**Comment by JersonSU** [comment]
> DialogX 建议对话框的使用是单次的，这意味着当你对一个已经显示的对话框执行 .dismiss() 方法时将完全销毁它，这是为了避免内存占用和内存泄漏，因此不建议复用任何对话框实例，如果你必须复用，可以将 OnBindView 保存下来重新创建对话框。 一定要复用对话框请参考[《常见问题-如何复用一个对话框？》](https://github.com/kongzue/DialogX/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)： ![image](https://user-images.githubusercontent.com/10115359/207219204-55233c23-eaba-4cf1-ba9d-c885d77fd32b.png)

是的，就是这样复用的，没有动画效果

**Comment by kongzue** [comment]
那么在你“关闭”对话框时，使用的是dismiss还是hideWithExitAnim？dismiss代表着“销毁”，并不支持复用

**Comment by kongzue** [comment]
感谢你的反馈，问题已测试复现。关于 CustomDialog 在 hideWithExitAnim 后重新 show 没有主布局的动画问题将在后续版本更新修复；

**Comment by kongzue** [comment]
预计一到两天内完成版本更新，修改代码已提交，敬请期待。

**Comment by kongzue** [comment]
已于0.0.47.beta13 修复：https://github.com/kongzue/DialogX/releases/tag/0.0.47.beta13
