### ISSUE TITLE
WaitDialog + TipDialog配合使用 如果先调用了WaitDialog.dismiss(),TipDialog会一闪而逝

### ISSUE THREAD

**Issue by fylw** [kongzue/DialogX#264]
## BUG 反馈

请先确认您已阅读[《常见问题》](https://github.com/kongzue/DialogX/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)

### 问题描述：
WaitDialog + TipDialog配合使用 如果在TipDialog.show()之前先调用了WaitDialog.dismiss(),TipDialog会一闪而逝

**Comment by kongzue** [comment]
请勿这样使用，如果你确信之后需要使用TipDialog请勿对之前的WaitDialog进行dismiss操作，而是直接执行 TipDialog 的show操作，你可以参考 [Demo的代码](https://github.com/kongzue/DialogX/blob/81b7aea9a5b5a4ca07a08b86c8cce5a1f8c93653/app/src/main/java/com/kongzue/dialogxdemo/activity/MainActivity.java#L533)。
这个问题的原因是DialogX的所有操作需要post到主线程执行，等待主线程响应才能刷新UI，而对于相同的activity，WaitDialog至TipDialog之间的转换是有一个过度动画的，事实上他们也是复用同一个实例执行的流程，若你执行dismiss后立即show，此时dismiss过程尚未结束（渐隐动画），show指令对于一个已经处于“显示”状态的 WaitDialog不会创建新的实例，而是进行复用，但dismiss的过程依然在进行，会造成show指令无效而dismiss继续执行的结果。

**Comment by fylw** [comment]
那么能否开放下延时dismiss方法,或者能够判断TipDialog是否显示，我再决定是否dismiss。因为我这边对该库做了二次封装,它可能有TipDialog,也可能没有。

**Comment by kongzue** [comment]
此问题将在下一个版本中处理，处理方案为，当 WaitDialog 执行 dismiss 后直接将 isShow 置空，执行启动 WaitDialog/TipDialog 时若当前 instance 的 isShow 为 false 时创建新实例。
很抱歉耽搁这么久，jitpack 源挂了这两天都在处理迁移仓库的事情，预计下个版本将在 MavenCentral 发布。

**Comment by kongzue** [comment]
请更新至 [0.0.47.beta14](https://github.com/kongzue/DialogX/tree/0.0.47.beta14) 版本，请注意由于近期 jitpack 服务不稳定此版本建议切换至 MavenCentral 源：
![image](https://user-images.githubusercontent.com/10115359/209287207-620120eb-d506-4e26-b923-2f4e643527ca.png)
