### ISSUE TITLE
Dialog支持在后台弹出吗？

### ISSUE THREAD

**Issue by 1825492258** [kongzue/DialogX#266]
支持在后台弹出Dialog吗？

**Comment by kongzue** [comment]
不支持，DialogX 是依赖 activity显示的，不过提供了 FloatingActivity 模式或 Window 模式可以实现在后台弹出，具体请参考 wiki 文档

**Comment by kongzue** [comment]
长时间未回复，暂时关闭了此问题，若有疑问请继续回复。
