### ISSUE TITLE
DialogXMaterialYou 这个主题库 下载不了

### ISSUE THREAD

**Issue by kinghom** [kongzue/DialogX#268]
## BUG 反馈

请先确认您已阅读[《常见问题》](https://github.com/kongzue/DialogX/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)

### 问题描述：
DialogXMaterialYou 这个主题库 下载不了 其他主题库可以下载

### 设备信息：
请在此说明您使用的设备型号、Android 版本等信息以协助我们排查问题

### 是否在 Demo 中能复现此问题？
是/否/未尝试

### 问题截图/视频
请在此插入佐证问题的截图和视频。

**Comment by kongzue** [comment]
请确认你的网络情况是否正常。
已确认 MavenCentral 仓库正常，最新版本是 0.0.47.beta15：
![image](https://user-images.githubusercontent.com/10115359/210682553-e55774fc-c0ff-4603-8216-088ce913fe89.png)
你可以在[这里查看详情](https://search.maven.org/artifact/com.kongzue.dialogx.style/DialogXMaterialYouStyle/0.0.47.beta15/aar)

已确认 Jitpack 仓库正常，最新版本是 0.0.47.beta20
![image](https://user-images.githubusercontent.com/10115359/210682738-cb608084-7ea1-4d33-b02a-9d1944961129.png)
你可以在[这里查看详情](https://jitpack.io/#kongzue/DialogX/0.0.47.beta20)

因为维护相当麻烦，MavenCentral 并不会完全保持最新版本同步，会在正式版发布时同步至 MavenCentral，因此 MavenCentral 的版本号相较 jitpack 仓库会有延后还请理解。

**Comment by kinghom** [comment]
![image](https://user-images.githubusercontent.com/23691629/210683645-d6f559d9-c2fe-4b1d-bce2-84956b1590d3.png)

此处 应该是 DialogXMaterialYouStyle

**Comment by kongzue** [comment]
好的，感谢反馈，已进行修改
