### ISSUE TITLE
WaitDialog、TipDialog等在暗色模式下，文字不能正常显示

### ISSUE THREAD

**Issue by smaboy** [kongzue/DialogX#269]
## BUG 反馈

请先确认您已阅读[《常见问题》](https://github.com/kongzue/DialogX/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)

### 问题描述：
WaitDialog、TipDialog等在暗色模式下，文字不能正常显示，你可以查看自己的demo。

### 设备信息：
XIAOMI 8SE

### 是否在 Demo 中能复现此问题？
是

**Comment by kongzue** [comment]
很抱歉，未能在 0.0.47 版本的 Demo 中复现你所描述的问题。
### 测试设备
Google Pixel5 Android 13 beta2
### 测试过程如下:
1) 设置 DialogX 暗色模式，启动 WaitDialog，请注意默认情况暗色模式下 WaitDialog 和 TipDialog 为白色显示（需要调整设置请参阅 wiki）：
![image](https://user-images.githubusercontent.com/10115359/211511532-a7ceaaac-c55e-48c9-860c-6713349917ed.png)

启动 TipDialog：
![image](https://user-images.githubusercontent.com/10115359/211511589-e6db4b07-f73b-44e4-933e-cbd013dcddcc.png)

未能发现任何问题，结果符合预期。

2) 尝试开启系统暗色模式，DialogX 设置为自动模式
![image](https://user-images.githubusercontent.com/10115359/211511836-c0ba55c5-fa3c-4efa-87af-2fb9790eefdb.png)

测试 WaitDialog：
![image](https://user-images.githubusercontent.com/10115359/211511898-3eb5fdee-1ec1-4ecb-bcfa-c0175cd2d0a0.png)

测试 TipDialog：
![image](https://user-images.githubusercontent.com/10115359/211511956-d5d79fdd-3bd9-417c-9c24-bf34b5bc495b.png)

未能发现任何问题，结果符合预期。

### 结论
未能发现任何问题。

请检查是否是因为国产定制系统采用了“强制反色”强行覆盖了预期颜色，如果是，请反馈给对应系统厂商，app 是无法突破系统限制的。

**Comment by kongzue** [comment]
长时间未回复，暂时关闭了此问题，若有疑问请继续回复。
