### ISSUE TITLE
主题亮色效果有问题，TipDialog情况下反了，之前3.0版的正常

### ISSUE THREAD

**Issue by feisher** [kongzue/DialogX#27]

**Comment by kongzue** [comment]
TipDialog和WaitDialog本身和其他对话框的样式是反的，这个在DialogX类的控制中也是独立的控制开关。
请检查您的手机是否具备和开启“强制暗色模式”，请注意，部分国产手机存在此选项（例如魅族、小米），若系统开启了此开关，布局样式可能会被系统强制染色，这不是真正的亮暗色模式。

在最新版本中，我们加入了`DialogX.globalTheme =THEME.AUTO`选项，这个选项可以在系统切换亮暗色主题时跟随系统进行变化，并保持了DialogX的主题不被系统强制染色的功能，具体请参考wiki。

**Comment by kongzue** [comment]
目前已确保在Pixel5（Android12 DP1）上的正常运行
