### ISSUE TITLE
WaitDialog无法设置背景透明度

### ISSUE THREAD

**Issue by licoba** [kongzue/DialogX#271]
## BUG 反馈

WaitDialog 的setBackgroundColor方法，无法设置透明度

### 问题描述：
代码段：
```
 WaitDialog.show("Please Wait!")
                        .setBackgroundColor(Color.parseColor("#44000000"))
                        .setMaskColor(Color.parseColor("#00000000")).setOnBackPressedListener(new OnBackPressedListener<WaitDialog>() {
                    @Override
                    public boolean onBackPressed(WaitDialog dialog) {
                        PopTip.show("按下返回");
                        return false;
                    }
                });
```

设置了透明背景`#44000000` 但是透明度没有起作用
 
### 设备信息：
OnePlus A600  一加6

### 是否在 Demo 中能复现此问题？
是

### 问题截图/视频
![image](https://user-images.githubusercontent.com/19327381/216934431-3ecd23d5-2a9a-49f4-bacb-00407dd391eb.png)

**Comment by kongzue** [comment]
很抱歉，这应该是一个遗留问题，在之前修改 BlurView 时，针对非模糊情况下的处理时，移除了设置的颜色的 alpha 通道，会在下一个版本修复它

**Comment by kongzue** [comment]
请更新至 jitpack 的 0.0.48.beta6 测试版本，详细的更新日志在这里查看：https://github.com/kongzue/DialogX/releases/tag/0.0.48.beta6

**Comment by licoba** [comment]
好的👌🏻
