### ISSUE TITLE
【BUG反馈】偶现空指针崩溃

### ISSUE THREAD

**Issue by licoba** [kongzue/DialogX#274]
## BUG 反馈

偶现的崩溃

### 问题描述：
Logcat日志：
```
--------- beginning of crash--
10802-10 18:36:03.284 1543 1543 E AndroidRuntime: FATAL EXCEPTION: main
10902-10 18:36:03.284 1543 1543 E AndroidRuntime: Process: com.translation666, PID: 1543
11002-10 18:36:03.284 1543 1543 E AndroidRuntime: java.lang.NullPointerException: Attempt to read from field 'com.kongzue.dialogx.util.views.MaxRelativeLayout com.kongzue.dialogx.dialogs.CustomDialog$DialogImpl.boxCustom' on a null object reference in method 'void com.kongzue.dialogx.dialogs.CustomDialog$DialogImpl$3.run()'
11102-10 18:36:03.284 1543 1543 E AndroidRuntime: at com.kongzue.dialogx.dialogs.CustomDialog$DialogImpl$3.run(CustomDialog.java:231)
11202-10 18:36:03.284 1543 1543 E AndroidRuntime: at android.os.Handler.handleCallback(Handler.java:942)
11302-10 18:36:03.284 1543 1543 E AndroidRuntime: at android.os.Handler.dispatchMessage(Handler.java:99)
11402-10 18:36:03.284 1543 1543 E AndroidRuntime: at android.os.Looper.loopOnce(Looper.java:223)
11502-10 18:36:03.284 1543 1543 E AndroidRuntime: at android.os.Looper.loop(Looper.java:324)
11602-10 18:36:03.284 1543 1543 E AndroidRuntime: at android.app.ActivityThread.main(ActivityThread.java:8386)
11702-10 18:36:03.284 1543 1543 E AndroidRuntime: at java.lang.reflect.Method.invoke(Native Method)
11802-10 18:36:03.284 1543 1543 E AndroidRuntime: at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:582)
11902-10 18:36:03.284 1543 1543 E AndroidRuntime: at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:996)


```
### 设备信息：
Android 11  机型不知道了
### 是否在 Demo 中能复现此问题？
未尝试

### 问题截图/视频
没有

**Comment by kongzue** [comment]
根据已有堆栈信息推测是系统回收导致动画过程无法正常进行，将在下一个测试版本进行处理。

**Comment by kongzue** [comment]
请更新至测试版本 0.0.48.beta7（jitpack源），详细更新日志可以在这里查看：https://github.com/kongzue/DialogX/releases/tag/0.0.48.beta7

**Comment by kongzue** [comment]
长时间未收到答复暂时关闭此问题，若有疑问请继续回复。

**Comment by xusw1024** [comment]
0.0.48.beta7版本，也会有该问题：

java.lang.NullPointerException: Attempt to read from field 'com.kongzue.dialogx.util.views.MaxRelativeLayout com.kongzue.dialogx.dialogs.CustomDialog$DialogImpl.boxCustom' on a null object reference
	at com.kongzue.dialogx.dialogs.CustomDialog$DialogImpl$3.run(CustomDialog.java:236)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:236)
	at android.app.ActivityThread.main(ActivityThread.java:8090)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:620)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1011)
Back traces end.

**Comment by xusw1024** [comment]
> 

Redmi | 28.63% | 152
vivo | 23.35% | 124
realme | 9.98% | 53



系统版本
11 | 90.40% | 480
12 | 7.91% | 42

**Comment by kongzue** [comment]
@xusw1024  xusw1024请注意，最新版本为 [0.0.48正式版](https://github.com/kongzue/DialogX/releases/tag/0.0.48)

**Comment by xusw1024** [comment]
> @xusw1024 xusw1024请注意，最新版本为 [0.0.48正式版](https://github.com/kongzue/DialogX/releases/tag/0.0.48)

很棒的轮子，深度使用，已经离不开了。

已经更新，等我反馈吧～ 

周末愉快🎉
