### ISSUE TITLE
TipDialog show不振动

### ISSUE THREAD

**Issue by yuantris** [kongzue/DialogX#276]
## BUG 反馈

请先确认您已阅读[《常见问题》](https://github.com/kongzue/DialogX/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)

### 问题描述：
请在此详细描述问题。

### 设备信息：
请在此说明您使用的设备型号、Android 版本等信息以协助我们排查问题

### 是否在 Demo 中能复现此问题？
是/否/未尝试

### 问题截图/视频
请在此插入佐证问题的截图和视频。

**Comment by kongzue** [comment]
DialogX 的振动依赖系统的 performHapticFeedback 完成，请检查系统的振动反馈设置是否开启，其次需要保持 `DialogX.useHaptic = true` 开启状态

**Comment by kongzue** [comment]
长时间未收到回复暂时关闭此问题，若有疑问请继续回复。
