### ISSUE TITLE
【BUG反馈】空指针导致的崩溃

### ISSUE THREAD

**Issue by wuhuaqing** [kongzue/DialogX#277]
## BUG 反馈

空指针导致的崩溃

### 问题描述：
Attempt to invoke virtual method 'android.view.ViewGroup$LayoutParams android.widget.RelativeLayout.getLayoutParams()' on a null object reference
com.kongzue.dialogx.dialogs.CustomDialog$DialogImpl.refreshView(CustomDialog.java:233)

### 设备信息：
系统版本 Android 11,level 30
项目依赖:com.github.kongzue.DialogX:DialogX:0.0.43

### 是否在 Demo 中能复现此问题？
 否 

### 问题截图/视频
请在此插入佐证问题的截图和视频。

**Comment by kongzue** [comment]
请确认你使用最新版本。
已验证在版本 0.0.48.beta9 的代码 [CustomDialog.java:233](https://github.com/kongzue/DialogX/blob/e0a67bff3da98095bbdbbefbcf4658a5397dc87a/DialogX/src/main/java/com/kongzue/dialogx/dialogs/CustomDialog.java#L233) 中没有存在相关问题的代码。
