### ISSUE TITLE
触摸退出BottomMenu

### ISSUE THREAD

**Issue by space-zhu** [kongzue/DialogX#278]
bottomMenu中触摸到非按钮或者其他空的地方也会退出菜单，请问改避免退出。
用的20年最有的旧版本。

**Comment by kongzue** [comment]
请更新至最新版本，使用以下代码可以单独防止通过点击背景遮罩层关闭对话框：
```java
.setOnBackgroundMaskClickListener(new OnBackgroundMaskClickListener<BottomDialog>() {
    @Override
    public boolean onClick(BottomDialog dialog, View v) {
        return true;
    }
})
```
这个方法是遮罩层的点击回调，若 return true，则代表拦截关闭操作。
早期版本也可以使用 `.setCancelable(false)` 阻止关闭操作，但它会同时阻止返回键关闭对话框以及下滑关闭对话框。
