### ISSUE TITLE
【BUG反馈】waitDialog出现的一瞬间，progressbar默认是填满的，看起来一闪而过很奇怪

### ISSUE THREAD

**Issue by 9292922** [kongzue/DialogX#279]
## BUG 反馈

请先确认您已阅读[《常见问题》](https://github.com/kongzue/DialogX/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)

### 问题描述：
waitDialog出现的一瞬间，progressbar默认是填满的，看起来一闪而过很奇怪

### 设备信息：
小米10至尊纪念版 Android12

### 是否在 Demo 中能复现此问题？
是

### 问题截图/视频
![image](https://user-images.githubusercontent.com/25112746/221348798-f6c09967-c5d4-4774-b9b4-65b5e8a1a47b.png)

**Comment by 9292922** [comment]
https://user-images.githubusercontent.com/25112746/221348853-b7c35787-b4c6-461f-a301-34ee638ef2bc.mp4

请看视频

**Comment by kongzue** [comment]
已确认此问题将在下一个测试版本修复

**Comment by kongzue** [comment]
请更新至版本 0.0.48.beta12，详细更新日志：https://github.com/kongzue/DialogX/releases/tag/0.0.48.beta12

**Comment by 9292922** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    谢谢您的跟进和修复，谢谢！
    
    
    

    

    

  
    ---- 回复的原邮件 ----
  
  
    
      
        
         发件人 
        
        
            ***@***.***>
            
        
      
      
        
         发送日期 
        
        
        2023年02月28日 13:28
        
      
      
        
         收件人 
        
        
         
          
            ***@***.***>
            
          
        
      
      
        
         抄送人 
        
        
          
            ***@***.***>
            ,
          
          
            ***@***.***>
            
          
        
      
      
        
         主题 
        
        
              Re: [kongzue/DialogX] 【BUG反馈】waitDialog出现的一瞬间，progressbar默认是填满的，看起来一闪而过很奇怪 (Issue #279)
        
      
    
  
  

请更新至版本 0.0.48.beta12，详细更新日志：https://github.com/kongzue/DialogX/releases/tag/0.0.48.beta12
