### ISSUE TITLE
自定义view中

### ISSUE THREAD

**Issue by jiaoery** [kongzue/DialogX#28]
在BottomMenu中使用自定义view带listview 最终只会显示一行的数据。感觉是BottomMenu中给cutsomview的展示面积很小
`<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="180dp"
    android:orientation="vertical">

    <RelativeLayout
        android:layout_width="match_parent"
        android:layout_height="60dp">

        <TextView
            android:id="@+id/btn_dialog_cancel"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:layout_alignParentLeft="true"
            android:layout_centerVertical="true"
            android:paddingLeft="20dp"
            android:text="@string/view_cancel"
            android:textColor="@color/textColor_iOS"
            android:textSize="@dimen/NormalTextSize" />

        <TextView
            android:id="@+id/btn_dialog_confirm"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:layout_alignParentRight="true"
            android:layout_centerVertical="true"
            android:paddingRight="20dp"
            android:text="@string/make_sure"
            android:textColor="@color/textColor_iOS"
            android:textSize="@dimen/NormalTextSize" />
    </RelativeLayout>

    <ListView
        android:id="@+id/lv_tree_menu"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:cacheColorHint="@android:color/transparent"
        android:divider="#aaa"
        android:dividerHeight="1px" />

</LinearLayout>`

**Comment by jiaoery** [comment]
OH,我的错，我发现里面转customview的container外面包裹了一层scrollview我用的是listview滑动冲突了；换了就没报错了；具体可以看layout文件 [layout_dialogx_bottom_material.xml]（ttps://github.com/kongzue/DialogX/blob/master/DialogX/src/main/res/layout/layout_dialogx_bottom_material.xml）

**Comment by kongzue** [comment]
你可以尝试使用BottomDialogListView，在包`com.kongzue.dialogx.util.views`下。
因为DialogX更多的需要考虑整体界面高度一旦超出可用大小后允许用户滑动展示其余部分的数据，所以使用外层的ScrollView代替处理，当然你如果觉得这不好用，可以在DialogLiftCycle的OnShow中使用getDialogImpl()方法获取内部组件暴露的实例，使用：
```
int layoutResId = R.layout.layout_custom;    //你的自定义布局
View 你的自定义View = LayoutInflater.from(BaseDialog.getContext()).inflate(layoutResId, new RelativeLayout(BaseDialog.getContext()),false);
((ViewGroup)dialog.getDialogImpl().scrollView).addView(你的自定义View, 1);
```
这样就可以绕过ScrollView来使用自定义布局了。
DialogX秉承着开放的设计方案进行开发，你可以几乎无障碍的修改这个组件以满足你的需求。

**Comment by jiaoery** [comment]
非常感谢大佬的回复，我现在的业务量并不大，可以使用noscrolllistview ;而且这样也保证了外部的scrollview可以滑动，效果方面也是可以达到 体界面高度一旦超出可用大小后允许用户滑动展示其余部分的数据；不过大佬提供的方法我也去试一试

**Comment by kongzue** [comment]
先关闭了此问题，若有疑问可继续回复
