### ISSUE TITLE
【BUG反馈】CustomDialog dismiss()在Android 13上闪一下

### ISSUE THREAD

**Issue by Dormxb** [kongzue/DialogX#280]
## BUG 反馈

请先确认您已阅读[《常见问题》](https://github.com/kongzue/DialogX/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)

### 问题描述：
CustomDialog 在使用自定义动画时dismiss()，画面会闪一下
Ps: 使用Android 10设备执行相同的动画代码，是正常dismiss，不会闪
自定义代码如下

anim_right_in.xml
```
<?xml version="1.0" encoding="utf-8"?>
<set xmlns:android="http://schemas.android.com/apk/res/android">
    <translate
        android:duration="200"
        android:fromXDelta="100%p"
        android:toXDelta="0"/>
    <alpha
        android:duration="200"
        android:fromAlpha="0.0"
        android:toAlpha="1.0"/>
</set>
```

anim_right_out.xml
```
<?xml version="1.0" encoding="utf-8"?>
<set xmlns:android="http://schemas.android.com/apk/res/android">
    <translate
        android:duration="200"
        android:fromXDelta="0"
        android:toXDelta="100%p"/>
    <alpha
        android:duration="200"
        android:fromAlpha="1.0"
        android:toAlpha="0.0"/>
</set>
```

调用 
```
setAnimResId(R.anim.anim_right_in, R.anim.anim_right_out)
```
### 设备信息：
Samsung S23 Ultra (Android 13)

### 是否在 Demo 中能复现此问题？
是

### 问题截图/视频
https://user-images.githubusercontent.com/34186779/222086071-4b164d2f-3d1b-44e9-8b57-2850f010ad21.mp4

**Comment by kongzue** [comment]
已测试，未能在最新版本中复现此问题，请更新至0.0.48.beta12版本后再试

https://user-images.githubusercontent.com/10115359/222873653-55f16336-829c-466d-916d-099d07e841ad.mp4

**Comment by Dormxb** [comment]
使用 0.0.48.beta13版本 问题依旧
怀疑点
1. 与系统自适应刷新率有关，更改为标准 60Hz刷新率模式，问题依旧
2. 与OneUI 5.1 本身兼容性相关
3. 使用 Google Pixel4a with Android 13 未出现以上问题

总结
与OneUI 5.1 本身兼容性有关的概率极高（但是由于我这边只有一台OneUI 5.1 Android 13的设备，无法进行其他版本OneUI的测试），可以等待OneUI后续更新，我这边再做测试

辛苦

**Comment by kongzue** [comment]
你可以尝试在自定义动画的根标签 `<set/>` 下加入设置 `android:fillAfter="true"` 看看能否解决问题。
CustomDialog 关于关闭动画的控制代码在 [CustomDialog.java:505](https://github.com/kongzue/DialogX/blob/dd79758a35441b91bc652a6aef9b8a7cd0400652/DialogX/src/main/java/com/kongzue/dialogx/dialogs/CustomDialog.java#L505) 你也可以通过自定义 DialogXAnimInterface 来控制全部的入场和出场动画流程，具体 [请参考文档《高阶扩展用法 - 完全自定义开启、关闭动画》](https://github.com/kongzue/DialogX/wiki/%E9%AB%98%E9%98%B6%E6%89%A9%E5%B1%95%E7%94%A8%E6%B3%95#%E5%AE%8C%E5%85%A8%E8%87%AA%E5%AE%9A%E4%B9%89%E5%BC%80%E5%90%AF%E5%85%B3%E9%97%AD%E5%8A%A8%E7%94%BB)

**Comment by Dormxb** [comment]
好的

**Comment by Dormxb** [comment]
通过添加 android:fillAfter="true" 解决了    \(^o^)/
感谢
