### ISSUE TITLE
【BUG反馈】FullScreenDialog 无法通过 setMaxHeight 限制最大高度

### ISSUE THREAD

**Issue by Sky-Walkrr** [kongzue/DialogX#282]
## BUG 反馈

请先确认您已阅读[《常见问题》](https://github.com/kongzue/DialogX/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)

### 问题描述：
FullScreenDialog 设置 setMaxHeight 后，如设置为屏幕高度的一半，在 dialog 里面继续上滑，dialog 仍然铺满全屏显示，无法实现 maxHeight 最大显示高度的控制

### 设备信息：
请在此说明您使用的设备型号、Android 版本等信息以协助我们排查问题

### 是否在 Demo 中能复现此问题？
未尝试

### 问题截图/视频
请在此插入佐证问题的截图和视频。

**Comment by kongzue** [comment]
请更新至 [0.0.48.beta13](https://github.com/kongzue/DialogX/releases/tag/0.0.48.beta13) 版本已修复此问题。
