### ISSUE TITLE
【BUG反馈】横屏 dialog 位置不居中  可能隐藏虚拟键盘造成

### ISSUE THREAD

**Issue by CPC-Coder** [kongzue/DialogX#283]
## BUG 反馈

请先确认您已阅读[《常见问题》](https://github.com/kongzue/DialogX/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)

### 问题描述：
横屏 dialog 位置不居中  
可能隐藏导航栏造成(项目沉浸式 无导航栏)

### 设备信息：
Date of Log        : 2023_03_04
Rom Info           : RomInfo{name=emdoor, version=20191225.101811}
Device Manufacturer: emdoor
Device Model       : RuggedPadM15
Android Version    : 9
Android SDK        : 28
App VersionName    : 1.0.0.20230304
App VersionCode    : 1

### 是否在 Demo 中能复现此问题？
未尝试

#### 有导航栏
![有1](https://user-images.githubusercontent.com/26327598/222870008-e0a00739-2b8d-4f72-99af-777cc6388e31.jpg)

![有](https://user-images.githubusercontent.com/26327598/222870002-4ba1712f-7dc1-4dca-9973-0fc7b0ccd605.jpg)

#### 无导航栏
![无1](https://user-images.githubusercontent.com/26327598/222869964-df06b4a9-3c32-4837-a7d0-f50993dcd080.jpg)

![无](https://user-images.githubusercontent.com/26327598/222869967-4f1a2d8d-79ef-4656-be7a-0eb0198922b1.jpg)

**Comment by kongzue** [comment]
经过测试，此问题系RelativeLayout在设置padding时其中wrap_content的View位置的bug，对PopTip的布局进行修改即可解决此问题：
<img width="624" alt="image" src="https://user-images.githubusercontent.com/10115359/222871545-c424c273-833a-466e-af5b-01bbc99d67e3.png">

**Comment by kongzue** [comment]
将在下一个版本更新后解决

**Comment by CPC-Coder** [comment]
tip和dialog 都要同一位置居中   希望是 全屏下居中

**Comment by kongzue** [comment]
请更新至 [0.0.48.beta13](https://github.com/kongzue/DialogX/releases/tag/0.0.48.beta13) 版本已修复此问题。

**Comment by kongzue** [comment]
长时间未收到回复暂时关闭此问题，若有疑问请继续回复。
