### ISSUE TITLE
【功能建议】BottomDialog 增加向上滑动展开更多

### ISSUE THREAD

**Issue by Xiaolangs** [kongzue/DialogX#284]
## 功能建议
BottomDialog 增加向上滑动展开更多
### 需求描述：
自定义布局时需要向上扩展显示更多 bottomDialog 好像并没有方法

**Comment by kongzue** [comment]
BottomDialog/BottomMenu拥有一个设置方法 `.setBottomDialogMaxHeight(float)` 用于设置默认显示高度，当这个值处于 0f< bottomDialogMaxHeight <1f 之间的浮点型数值时代表屏幕高度的比例，当这个值大于 1f 时为限定的高度像素值，它可以限定 BottomDialog 默认的显示高度，用户可以通过向上滑动触摸来展开对话框。

**Comment by kongzue** [comment]
以下是提供一个基于Demo源代码的范例：
layout_custom_view.xml，自定义布局，建立一个高度900dp高度大于屏幕高度会产生滑动的布局：
```xml
<?xml version="1.0" encoding="utf-8"?>
<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="900dp">

    <LinearLayout
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:gravity="center_horizontal"
        android:orientation="vertical"
        android:paddingBottom="15dp"
        android:paddingTop="15dp">

        <ImageView
            android:id="@+id/img_ico"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:src="@mipmap/img_logo" />

        <TextView
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:layout_marginTop="10dp"
            android:text="这里是自定义Layout测试"
            android:textColor="#878787"
            android:textSize="12dp" />

    </LinearLayout>

</RelativeLayout>
```
代码：
```java
new BottomDialog("标题", "这里是对话框内容。\n" + s + "。\n底部对话框也支持自定义布局扩展使用方式。",
        new OnBindView<BottomDialog>(R.layout.layout_custom_view) {
            @Override
            public void onBind(BottomDialog dialog, View v) {
                
            }
        })
        .setBottomDialogMaxHeight(0.5f)    //设置bottomDialogMaxHeight为半屏高度
        .show();
```

测试结果视频如下（设置：Google Pixel5 Android 13）：

https://user-images.githubusercontent.com/10115359/223058468-262dda80-1e86-47f6-b6a6-51cbe3460247.mp4

**Comment by Xiaolangs** [comment]
> 以下是提供一个基于Demo源代码的范例： layout_custom_view.xml，自定义布局，建立一个高度900dp高度大于屏幕高度会产生滑动的布局：
> 
> ```
> <?xml version="1.0" encoding="utf-8"?>
> <RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
>     android:layout_width="match_parent"
>     android:layout_height="900dp">
> 
>     <LinearLayout
>         android:layout_width="match_parent"
>         android:layout_height="wrap_content"
>         android:gravity="center_horizontal"
>         android:orientation="vertical"
>         android:paddingBottom="15dp"
>         android:paddingTop="15dp">
> 
>         <ImageView
>             android:id="@+id/img_ico"
>             android:layout_width="wrap_content"
>             android:layout_height="wrap_content"
>             android:src="@mipmap/img_logo" />
> 
>         <TextView
>             android:layout_width="wrap_content"
>             android:layout_height="wrap_content"
>             android:layout_marginTop="10dp"
>             android:text="这里是自定义Layout测试"
>             android:textColor="#878787"
>             android:textSize="12dp" />
> 
>     </LinearLayout>
> 
> </RelativeLayout>
> ```
> 
> 代码：
> 
> ```java
> new BottomDialog("标题", "这里是对话框内容。\n" + s + "。\n底部对话框也支持自定义布局扩展使用方式。",
>         new OnBindView<BottomDialog>(R.layout.layout_custom_view) {
>             @Override
>             public void onBind(BottomDialog dialog, View v) {
>                 
>             }
>         })
>         .setBottomDialogMaxHeight(0.5f)    //设置bottomDialogMaxHeight为半屏高度
>         .show();
> ```
> 
> 测试结果视频如下（设置：Google Pixel5 Android 13）：

我用的是动态高度

**Comment by kongzue** [comment]
必须指定一个高度，动态高度无法进行计算，当你需要展开的情况下，DialogX无法预估你的布局的展开前后的高度信息，如有需要请自行处理。
另外，DialogX 支持在运行过程中对内容高度重新调整，你可以直接调整自己的内容布局的高度，BottomDialog的高度会自动根据内容进行调整。
例如基于 Demo 的以下代码将在用户点击界面后重新调整自定义布局的高度为 900dp：
```java
new BottomDialog("标题", "这里是对话框内容。\n" + s + "。\n底部对话框也支持自定义布局扩展使用方式。",
        new OnBindView<BottomDialog>(R.layout.layout_custom_view) {
            @Override
            public void onBind(BottomDialog dialog, View v) {
                v.setOnClickListener(new View.OnClickListener() {
                    @Override
                    public void onClick(View v) {
                        ViewGroup.LayoutParams lp = v.getLayoutParams();
                        lp.height = dip2px(900);
                        v.setLayoutParams(lp);
                    }
                });
            }
        })
        .show();
```
测试结果视频如下（设置：Google Pixel5 Android 13）：

https://user-images.githubusercontent.com/10115359/223061932-8e94c7aa-9954-42b8-b44e-d83ee2a3c016.mp4
