### ISSUE TITLE
【BUG反馈】getMinHeight() 中对minWidth进行判断

### ISSUE THREAD

**Issue by Valpha** [kongzue/DialogX#286]
## BUG 反馈

请先确认您已阅读[《常见问题》](https://github.com/kongzue/DialogX/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)

### 问题描述：
BaseDialog.java里获取minHeight时，进行了判0操作，但是判0的属性用错了，用成了minWidth，应该是用minHeight

### 是否在 Demo 中能复现此问题？
未尝试

### 问题截图/视频
![image](https://user-images.githubusercontent.com/35476904/223074071-3ed4219b-d5c0-485a-80d0-741d389a589f.png)

**Comment by kongzue** [comment]
感谢反馈，将在下一个版本修复

**Comment by kongzue** [comment]
请更新至 0.0.48.beta14，此问题已处理。

**Comment by kongzue** [comment]
长时间未收到回复暂时关闭此问题，若有疑问请继续回复。
