### ISSUE TITLE
【BUG反馈】导航栏可以隐藏吗?

### ISSUE THREAD

**Issue by GCZeng** [kongzue/DialogX#287]
## BUG 反馈
我想全屏显示Dialog，但是导航栏没有隐藏。

请先确认您已阅读[《常见问题》](https://github.com/kongzue/DialogX/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)

### 问题描述：
我想全屏显示Dialog，但是导航栏没有隐藏。

### 设备信息：
Android8.0

### 是否在 Demo 中能复现此问题？
是

### 问题截图/视频
请在此插入佐证问题的截图和视频。
![微信截图_20230310171252](https://user-images.githubusercontent.com/3079863/224275018-d967ff79-319a-4319-99f1-f41484b96ada.png)

**Comment by kongzue** [comment]
默认情况下，DialogX都会保证布局处于可操作的”安全区“内显示。
要解除限制，你可以使用以下代码禁用安全区：
```java
FullScreenDialog.build(new OnBindView<FullScreenDialog>(R.layout.your_custom_layout) {
            @Override
            public void onBind(final FullScreenDialog dialog, View v) {
                dialog.getDialogImpl().boxRoot.setAutoUnsafePlacePadding(false);
                //...
            }
        })
        .show();
```
但请注意，禁用安全区设置并不会让界面全屏，要让界面全屏请对您的activity的window设置全屏flag，DialogX的布局规则依赖其显示的activity。
另外请注意，处于非全屏时，使用此设置后，DialogX的对话框将忽略非安全区的影响，非安全区的触摸操作会被系统的状态栏和导航栏（SystemUI）拦截无法触及DialogX的内容布局。

**Comment by GCZeng** [comment]
感觉你的解答，可以了。
