### ISSUE TITLE
UI旋转功能

### ISSUE THREAD

**Issue by liao00** [kongzue/DialogX#289]
建议加入UI旋转功能，通过setRotation设置旋转角度(90、180、270)，这个在固定横竖屏的APP上很有用。

**Comment by kongzue** [comment]
请自行处理，DialogX内部组件全部是对外暴露的，你可以在 `DialogLifecycle#onShow` 之后获取到他们。
举例：
```java
.setDialogLifecycleCallback(new DialogLifecycleCallback<MessageDialog>() {
    @Override
    public void onShow(MessageDialog dialog) {
        //获取到对话框布局实例：
        RelativeLayout dialogView= dialog.getDialogImpl().bkg;
        //...
        super.onShow(dialog);
    }
});
```

**Comment by liao00** [comment]
> 请自行处理，DialogX内部组件全部是对外暴露的，你可以在 `DialogLifecycle#onShow` 之后获取到他们。 举例：
> 
> ```java
> .setDialogLifecycleCallback(new DialogLifecycleCallback<MessageDialog>() {
>     @Override
>     public void onShow(MessageDialog dialog) {
>         //获取到对话框布局实例：
>         RelativeLayout dialogView= dialog.getDialogImpl().bkg;
>         //...
>         super.onShow(dialog);
>     }
> });
> ```

这样的话旋转后布局会出问题，如果你在内部处理好就很棒了
