### ISSUE TITLE
WaitDialog theme

### ISSUE THREAD

**Issue by qiushui95** [kongzue/DialogX#29]
无单独设置WaitDialog theme的接口。
我想亮色模式也是用白色框

**Comment by kongzue** [comment]
有，请仔细查看wiki

________________________________
发件人: 杨朝旭 ***@***.***>
发送时间: Wednesday, March 17, 2021 5:18:04 PM
收件人: kongzue/DialogX ***@***.***>
抄送: Subscribed ***@***.***>
主题: [kongzue/DialogX] WaitDialog theme (#29)


无单独设置WaitDialog theme的接口。
我想亮色模式也是用白色框

―

**Comment by kongzue** [comment]
请参阅：
```
//设置 TipDialog 和 WaitDialog 明暗风格，不设置则默认根据 globalTheme 定义
DialogX.tipTheme = (THEME);
```
于页面：https://github.com/kongzue/DialogX/wiki
