### ISSUE TITLE
【BUG反馈】FullScreenDialog show和dismiss时的动画问题

### ISSUE THREAD

**Issue by Dormxb** [kongzue/DialogX#292]
## BUG 反馈

请先确认您已阅读[《常见问题》](https://github.com/kongzue/DialogX/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)

### 问题描述：
FullScreenDialog show和dismiss时闪烁

### 设备信息：
设备型号 HUAWEI P30 (ELE-AL00) 
系统版本 HarmonyOS 3.0.0 (Android 10.0)

### 是否在 Demo 中能复现此问题？
是

### 问题截图/视频
请在此插入佐证问题的截图和视频。

https://user-images.githubusercontent.com/34186779/228757545-b8909e52-56b9-4d7f-8b89-61aa89be1495.mp4

**Comment by kongzue** [comment]
收到👌🏻，等待复测

**Comment by kongzue** [comment]
请更新至测试版本：[0.0.48.beta20](https://github.com/kongzue/DialogX/releases/tag/0.0.48.beta20)
已尝试修复此问题。

**Comment by Dormxb** [comment]
更新至 0.0.48.beta20，依旧出现该问题，但是我在使用demo的0.0.48.beta12版本时，在这台 HUAWEI P30 (ELE-AL00)手机上是正常的

**Comment by kongzue** [comment]
正在继续排查原因

**Comment by kongzue** [comment]
已经查到原因并正在解决，预计在明天完成版本更新。

**Comment by kongzue** [comment]
请更新至版本：[0.0.48.beta21](https://github.com/kongzue/DialogX/releases/tag/0.0.48.beta21)

**Comment by Dormxb** [comment]
经过测试，0.0.48.beta21已修复此问题，感谢
