### ISSUE TITLE
【BUG反馈】bottomdialog不会跟随输入法关闭而收缩，导致大片留白

### ISSUE THREAD

**Issue by 9292922** [kongzue/DialogX#293]
## BUG 反馈

请先确认您已阅读[《常见问题》](https://github.com/kongzue/DialogX/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)

### 问题描述：
在使用底部输入弹窗(bottomdialog)时，当手机输入法关闭时，dialog并不会自动下滑，还是停留在原处，手机输入法空出的地方成了空白。这种情况很经常出现，比如正在输入时，跳转其他操作或者返回桌面，重新返回时，就会出现。WindowsoftInputMode=adjustResize，具体情况请看GIF。

### 设备信息：
小米10至尊纪念版，Android12

### 是否在 Demo 中能复现此问题？
是

### 问题截图/视频
![Video_20230330_042551_369.gif](https://user-images.githubusercontent.com/25112746/228777494-882ad698-a0f7-423f-bfbb-549ac462a7b5.gif)

**Comment by kongzue** [comment]
此问题系系统的WindowInsets回调未正确回传正确的底部非安全区的值，DialogX的根布局没有收到调整信息因此不能正确的调整界面显示效果。
暂时没有解决方案，我这边会持续尝试寻找合适的解决方式。

**Comment by 9292922** [comment]
我想使用测试版为什么不能下载呢？ 使用0.0.47是可以正确拉取的



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年3月30日(周四) 下午4:34
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [kongzue/DialogX] 【BUG反馈】bottomdialog不会跟随输入法关闭而收缩，导致大片留白 (Issue #293)




 
此问题系系统的WindowInsets回调未正确回传正确的底部非安全区的值，DialogX的根布局没有收到调整信息因此不能正确的调整界面显示效果。
 暂时没有解决方案，我这边会持续尝试寻找合适的解决方式。

**Comment by 9292922** [comment]
> 此问题系系统的WindowInsets回调未正确回传正确的底部非安全区的值，DialogX的根布局没有收到调整信息因此不能正确的调整界面显示效果。
> 暂时没有解决方案，我这边会持续尝试寻找合适的解决方式。

我想使用测试版为什么不能下载呢？ 使用0.0.47是可以正确拉取的![mmexport1680165356442.png](https://user-images.githubusercontent.com/25112746/228779132-2a809608-6fe9-4422-9881-d36ab57d8e2b.png)

**Comment by kongzue** [comment]
请确保你拉取的是正确的包名，测试版本仅在jitpack源提供，jitpack源的包名应为 com.github.kongzue.DialogX 开头

**Comment by 9292922** [comment]
> 此问题系系统的WindowInsets回调未正确回传正确的底部非安全区的值，DialogX的根布局没有收到调整信息因此不能正确的调整界面显示效果。
> 暂时没有解决方案，我这边会持续尝试寻找合适的解决方式。

这个影响较为严重或者明显，希望可以有办法处理，可以试试把你遇到的问题问问chatgpt看看能不能从库内部来解决呢，如果通过开发者这边适配的话，可能耦合较大

**Comment by kongzue** [comment]
这个问题我清楚原因，但无法解决，最合理的方案是找Google去改系统代码，但针对老版本系统也没法再更新了

**Comment by 9292922** [comment]
那开发者这边可以监听输入法显示隐藏，然后主动调用dialog的下滑吗？感觉有点奇怪，xpopup弹窗也有类似的底部输入法贴边弹窗，他这边可以正常使用，他返回后输入法并没有关闭，不知道会不会也是一种思路呢



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年3月30日(周四) 下午4:40
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [kongzue/DialogX] 【BUG反馈】bottomdialog不会跟随输入法关闭而收缩，导致大片留白 (Issue #293)




 
这个问题我清楚原因，但无法解决，最合理的方案是找Google去改系统代码，但针对老版本系统也没法再更新了

**Comment by kongzue** [comment]
相关代码你可以在 [DialogXBaseRelativeLayout.java](https://github.com/kongzue/DialogX/blob/8f8481bd0d4e3108c56b86f14ccd9b7c6ef80ee3/DialogX/src/main/java/com/kongzue/dialogx/util/views/DialogXBaseRelativeLayout.java) 中找到

**Comment by kongzue** [comment]
Android系统并没有“输入法显示隐藏”这样的事件提供。
DialogX是依据“非安全区”进行沉浸式适配的，非安全区包含了因输入法弹起导致的界面可用高度收缩等情况。

**Comment by 9292922** [comment]
> Android系统并没有“输入法显示隐藏”这样的事件提供。 DialogX是依据“非安全区”进行沉浸式适配的，非安全区包含了因输入法弹起导致的界面可用高度收缩等情况。

![image](https://user-images.githubusercontent.com/25112746/228782306-30449658-fea5-4e8d-851d-19784dd0e59c.png)

通过如下代码可以正确监听输入法的显示或隐藏，能否通过提供一个显示或隐藏的方法来隐藏dialog的空白部分
`        binding.editReplyCommit.getViewTreeObserver().addOnGlobalLayoutListener(new ViewTreeObserver.OnGlobalLayoutListener() {
            @Override
            public void onGlobalLayout() {
                Rect r = new Rect();
                binding.editReplyCommit.getWindowVisibleDisplayFrame(r);

                int screenHeight =  binding.editReplyCommit.getRootView().getHeight();
                int keyboardHeight = screenHeight - r.bottom;

                boolean isVisible = keyboardHeight > screenHeight * 0.15;

                System.out.println("isVisible = " + isVisible);

                
            }
        });`

**Comment by kongzue** [comment]
我已经说的很清楚了，DialogX 是依据“非安全区”进行沉浸式适配的，非安全区包含了因输入法弹起导致的界面可用高度收缩等情况。
使用getViewTreeObserver#addOnGlobalLayoutListener会造成严重的性能问题一般不建议使用，DialogX不这样设计是有原因的。
我会继续寻找合理的解决方案，如果你能能够很棒的解决这个问题也欢迎提交合并代码。
https://github.com/kongzue/DialogX/blob/8f8481bd0d4e3108c56b86f14ccd9b7c6ef80ee3/DialogX/src/main/java/com/kongzue/dialogx/util/views/DialogXBaseRelativeLayout.java

**Comment by kongzue** [comment]
<img width="852" alt="image" src="https://user-images.githubusercontent.com/10115359/228791874-7bfc1655-91ba-4e19-811d-395b57ea358e.png">
经过测试，确认系统回调存在问题，返回第一个界面后立即在获取焦点处打印了底部非安全区的高度，明显存在问题，继续寻找解决方案。

**Comment by 9292922** [comment]
好嘞！！加油大神，我也在看那个代码



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年3月30日(周四) 下午5:26
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [kongzue/DialogX] 【BUG反馈】bottomdialog不会跟随输入法关闭而收缩，导致大片留白 (Issue #293)




 

 经过测试，确认系统回调存在问题，返回第一个界面后立即在获取焦点处打印了底部非安全区的高度，明显存在问题，继续寻找解决方案。

**Comment by kongzue** [comment]
请更新至测试版本：[0.0.48.beta20](https://github.com/kongzue/DialogX/releases/tag/0.0.48.beta20)
已尝试修复此问题。

**Comment by 9292922** [comment]
好的好的👌🏻



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年3月30日(周四) 晚上6:06
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [kongzue/DialogX] 【BUG反馈】bottomdialog不会跟随输入法关闭而收缩，导致大片留白 (Issue #293)




 
一点好消息，通过一些手段凑合解决了此问题，将在下一个版本更新中提供。
 修复此问题的方法并非合理的，但能够解决当前遇到的问题，但不排除可能引发其他问题，请在下个测试版本更新后谨慎测试后使用。
