### ISSUE TITLE
【功能建议】按键的焦点问题

### ISSUE THREAD

**Issue by nwhhades** [kongzue/DialogX#297]
## 功能建议
适配按键控制，添加焦点逻辑
### 需求描述：
目前的dialog没有考虑用户使用键盘或者遥控器的时候
没有加入焦点的处理  如果可以加入焦点逻辑  这个库在TV端也是可以很的使用

**Comment by nwhhades** [comment]
例如：
先在layout里面设置好焦点的传递；
再添加一个View oldView；字段
在show的时候从activity中获取之前的焦点在哪赋值给oldView，并且让dialog的按钮获取到焦点requestFocus();
在hide的时候把焦点还给oldView;

**Comment by kongzue** [comment]
mark，需求可能涉及需要修改的点有些多，开发待定
