### ISSUE TITLE
【BUG反馈】请填写标题

### ISSUE THREAD

**Issue by 9292922** [kongzue/DialogX#298]
## BUG 反馈

请先确认您已阅读[《常见问题》](https://github.com/kongzue/DialogX/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)

### 问题描述：
为什么bottomDialog设置ok按钮不会显示，cancel取消按钮可以正常显示，是设计上不允许吗

### 设备信息：
android13，小米10至尊纪念版

### 是否在 Demo 中能复现此问题？
是

### 问题截图/视频
![image](https://user-images.githubusercontent.com/25112746/230317994-cec1d8f1-c01c-4263-a9da-faf72c624211.png)

![Screenshot_2023-04-06-16-18-40-895_com magicalsto](https://user-images.githubusercontent.com/25112746/230317936-1ba30d4d-2967-4f19-9084-1b0f91bdfc6a.jpg)

**Comment by kongzue** [comment]
不是 Bug，部分主题限定罢了，有些主题的 BottomDialog 只有 Cancel 按钮，不过不影响正常使用。

**Comment by 9292922** [comment]
确实，没问题，只是问问，明白晒。很多替代方案可以实现，谢谢解答



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年4月6日(周四) 下午4:56
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [kongzue/DialogX] 【BUG反馈】请填写标题 (Issue #298)




 
不是 Bug，部分主题限定罢了，有些主题的 BottomDialog 只有 Cancel 按钮，不过不影响正常使用。

**Comment by kongzue** [comment]
如果有必要也可以加，也是当时写其他主题的时候没做ok按钮

**Comment by 9292922** [comment]
嗯，我觉得还是有点必要的，毕竟其他风格的bottomdialog也是可能用到OKbutton 看你忙不忙吧，不忙可以考虑加入ToDo list 不然用户用到时候，哈哈，设置OKbutton没出来



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年4月6日(周四) 下午5:00
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [kongzue/DialogX] 【BUG反馈】请填写标题 (Issue #298)




 
如果有必要也可以加，也是当时写其他主题的时候没做ok按钮

**Comment by kongzue** [comment]
好的，会在下一个版本处理，预计在3天内完成测试版更新。

**Comment by 9292922** [comment]
好的，close吧，谢谢大佬



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年4月6日(周四) 下午5:03
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [kongzue/DialogX] 【BUG反馈】请填写标题 (Issue #298)




 
好的，会在下一个版本处理，预计在3天内完成测试版更新。

**Comment by kongzue** [comment]
先不关，处理完了会在这里告诉你

**Comment by kongzue** [comment]
开发进度通告：已经基本实现其他主题的修改，预计周末发布测试版本更新。
![image](https://user-images.githubusercontent.com/10115359/230718426-c8d68e18-f1aa-4006-8b62-c45593cdd234.png)
![image](https://user-images.githubusercontent.com/10115359/230718433-536d5440-ad87-492e-849f-89dbf9a57475.png)
![image](https://user-images.githubusercontent.com/10115359/230718439-1cb817b9-7c2e-47d1-b22f-5277a18678e6.png)
本次更新中对 BottomDialog以及BottomMenu 在iOS主题下的高斯模糊组件和结构进行了重写设计，对于BottomDialog以及BottomMenu已经完全完成更新，但其他对话框组件因工作量巨大暂时没能来得及调整，会在后续更新中处理。

**Comment by kongzue** [comment]
请更新至测试版本：[0.0.48.beta22](https://github.com/kongzue/DialogX/releases/tag/0.0.48.beta22)

**Comment by 9292922** [comment]
好的👌🏻



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年4月9日(周日) 中午11:06
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [kongzue/DialogX] 【BUG反馈】请填写标题 (Issue #298)




 
请更新至测试版本：0.0.48.beta22
