### ISSUE TITLE
配合AndroidUtilCode PermissionUtils显示方法bug

### ISSUE THREAD

**Issue by qiushui95** [kongzue/DialogX#3]
PermissionUtils请求权限，在回调中显示MessageDialog。
PermissionUtils会启动一个UtilActivity，瞬间消失，MessageDialog.show会显示在UtilActivity上面。
由于show方法无法指定activity  ，就会出现无法show的情况

**Comment by kongzue** [comment]
正在关注此问题

**Comment by kongzue** [comment]
即将在下个版本进行解决，解决方案是提供独立的`.show(Activity)`方法可指定启动对话框的Activity

**Comment by kongzue** [comment]
已更新至版本 0.0.24，暂时关闭此问题，若有任何疑问可继续留言
