### ISSUE TITLE
提示被输入法盖住

### ISSUE THREAD

**Issue by ytxyyt** [kongzue/DialogX#30]
输入法会把PopTip盖住

**Comment by kongzue** [comment]
是的，这是已知问题，原因是DialogX的实现并不是依赖Window，而是一个View，这就会导致提示信息被IME遮挡。
目前的解决方案是在特殊情况下设置Align使其从屏幕顶端弹出显示，部分主题也提供了此功能。

**Comment by kongzue** [comment]
请尝试使用jCenter源并更新至测试版本`0.0.34.beta1`，本次修改会在下次正式版更新时同步代码

**Comment by Gxaasec** [comment]
小米8，Android10系统使用v0.0.49版本还是会被输入法挡住

**Comment by kongzue** [comment]
@Gxaasec 请尝试最新的测试版本，针对旧版可能存在的问题不再处理
