### ISSUE TITLE
【BUG反馈】关于PopNotification再次进入Activity发生内存泄漏的问题

### ISSUE THREAD

**Issue by vistar1986** [kongzue/DialogX#300]
## BUG 反馈

请先确认您已阅读[《常见问题》](https://github.com/kongzue/DialogX/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)

### 问题描述：
使用当前Activity弹出一个延时结束的PopNotification后，退出当前Activity，当再次进入的时候会出现内存泄漏。
发现内存泄漏问题不止在PopNotification中出现，其他Dialog功能也有发生
### 设备信息：
Android Studio虚拟机 android8.0/android10.0

### 是否在 Demo 中能复现此问题？
是

### 问题截图/视频

下面这个是在工业平板上出现的内存泄漏，android版本为8.0
https://user-images.githubusercontent.com/11677770/231980765-5a858994-9236-4047-92f1-62a2742a5ffd.mp4

**Comment by kongzue** [comment]
此问题已在最新版本修复。
