### ISSUE TITLE
【BUG反馈】A页面相机拍照后跳转B页面后,在跳转后的B页面点击PopMenu显示时,显示在了A页面

### ISSUE THREAD

**Issue by FOnlyJack** [kongzue/DialogX#301]
## BUG 反馈

请先确认您已阅读[《常见问题》](https://github.com/kongzue/DialogX/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)

### 问题描述：
请在此详细描述问题。

### 设备信息：
xiaomi 8 android  10 

### 是否在 Demo 中能复现此问题？
是/否/未尝试

### 问题截图/视频
请在此插入佐证问题的截图和视频。

**Comment by kongzue** [comment]
请尝试使用build方法构建，在最后执行 `.show(activity)` 使用activity参数启动对话框。
此情况属于极为特殊的情况，DialogX默认会获取当前resume的activity作为显示容器，但在频繁切换activity的一瞬间执行show可能获取到的activity不符合预期，此时请指定要显示到的activity。
