### ISSUE TITLE
FullScreenDialog 下沉

### ISSUE THREAD

**Issue by Bruce8hou** [kongzue/DialogX#302]
可否增加一个是否开启下沉效果的的属性呢？

**Comment by kongzue** [comment]
请直接使用设置：
```
.setHideZoomBackground(true)
```
此设置会关闭背景下沉缩放效果。
其实这种需求如无特殊需要最好直接使用  BottomDialog  实现。

**Comment by Bruce8hou** [comment]
BottomDialog  对于全屏适配不太方便（一般需要设置一个layout height）。FullScreenDialog 直接可以全屏  已经解决了我的需求了  谢谢

**Comment by Bruce8hou** [comment]
FullScreenDialog 布局里面ScrollView的不能滚动，是否有什么冲突呢？

**Comment by kongzue** [comment]
请查阅常见问题：[Q：在 BottomDialog 和 FullScreenDialog 对话框中让自己的滑动布局支持滑动继承
](https://github.com/kongzue/DialogX/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98#q%E5%9C%A8-bottomdialog-%E5%92%8C-fullscreendialog-%E5%AF%B9%E8%AF%9D%E6%A1%86%E4%B8%AD%E8%AE%A9%E8%87%AA%E5%B7%B1%E7%9A%84%E6%BB%91%E5%8A%A8%E5%B8%83%E5%B1%80%E6%94%AF%E6%8C%81%E6%BB%91%E5%8A%A8%E7%BB%A7%E6%89%BF)
