### ISSUE TITLE
【功能建议】建议bottomMenuDialog可以增加渐变退出动画

### ISSUE THREAD

**Issue by 9292922** [kongzue/DialogX#303]
## 功能建议
bottomMenuDialog可以增加渐变退出动画
### 需求描述：
因为目前默认的bottomMenuDialog退出动画是从上往下隐藏，这样的和弹出动画相对应蛮不错。

但是，当bottomMenDialog的menu被选中，同时要执行一些动画操作时，比如马上切换activity，就会导致出现动画不流畅，例如MIUI的默认activity切换动画是从左往右，然后bottomMenDialog隐藏动画是从上往下隐藏，这样两个动画同时执行会出现不流畅影响体验。特别是在性能不佳的手机或者新activity有比较重的初始任务时较为明显。

我建议是：bottomMenuDialog可以支持渐变消失退出动画，也就是alpha变淡，最好支持自定义动画时间。照我以往优化体验的经验知道，这样可以解决这个影响用户体验的问题。
望采纳，希望dialogX越来越好

**Comment by kongzue** [comment]
很抱歉此需求并非普遍性问题，暂时不会对框架进行调整。

但你的需求可以通过自定义动画实现，这里有一份范例：
1. 首先定义一个自定义动画实现：
```java
DialogXAnimInterface<BottomDialog> alphaDialogAnimation = new DialogXAnimInterface<BottomDialog>() {
    @Override
    //入场动画
    public void doShowAnim(BottomDialog dialog, ViewGroup dialogBodyView) {
        //设置好位置，将默认预设会在屏幕底外部恢复为屏幕内
        dialog.getDialogImpl().boxBkg.setY(dialog.getDialogImpl().boxRoot.getUnsafePlace().top);
        //创建 0f~1f 的数值动画
        ValueAnimator animator = ValueAnimator.ofFloat(0f, 1f);
        animator.addUpdateListener(new ValueAnimator.AnimatorUpdateListener() {
            @Override
            public void onAnimationUpdate(ValueAnimator animation) {
                float value = (float) animation.getAnimatedValue();
                //修改背景遮罩透明度
                dialog.getDialogImpl().boxRoot.setBkgAlpha(value);
                //修改内容透明度
                dialog.getDialogImpl().bkg.setAlpha(value);
            }
        });
        //使用真正的动画时长
        animator.setDuration(dialog.getDialogImpl().getEnterAnimationDuration());
        animator.start();
    }
    @Override
    //出场动画
    public void doExitAnim(BottomDialog dialog, ViewGroup dialogBodyView) {
        ValueAnimator animator = ValueAnimator.ofFloat(1f, 0f);
        animator.addUpdateListener(new ValueAnimator.AnimatorUpdateListener() {
            @Override
            public void onAnimationUpdate(ValueAnimator animation) {
                float value = (float) animation.getAnimatedValue();
                //这里可以直接修改整体透明度淡出
                dialog.getDialogImpl().boxRoot.setAlpha(value);
            }
        });
        animator.setDuration(dialog.getDialogImpl().getExitAnimationDuration());
        animator.start();
    }
};
```
 2. 然后设置给对话框：
```java
.setDialogXAnimImpl(alphaDialogAnimation)
```

### 修改动画时长
另外如需修改动画时长， 请勿直接修改上述动画的 Duration，请通过组件属性值覆盖的方式直接替换：
```java
BottomMenu.overrideEnterDuration = 100;  //修改为 100 毫秒
BottomMenu.overrideExitDuration = 100;
```
如果只需要单次修改而不是对整个组件生效，请使用实例的方法进行修改：
```java
.setEnterAnimDuration(100)
.setExitAnimDuration(100)
```
此方法仅针对单个实例生效，具体设置请参阅  wiki  文档。

**Comment by 9292922** [comment]
好的，谢谢解答！是我还没研究透彻，原来早已有提供解决方案，麻烦了



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年4月25日(周二) 中午12:01
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [kongzue/DialogX] 【功能建议】建议bottomMenuDialog可以增加渐变退出动画 (Issue #303)




 
很抱歉此需求并非普遍性问题，暂时不会对框架进行调整。
 
但你的需求可以通过自定义动画实现，这里有一份范例：
  
首先定义一个自定义动画实现：
  DialogXAnimInterface<BottomDialog&gt; alphaDialogAnimation = new DialogXAnimInterface<BottomDialog&gt;() {     @Override     //入场动画     public void doShowAnim(BottomDialog dialog, ViewGroup dialogBodyView) {         //设置好位置，将默认预设会在屏幕底外部恢复为屏幕内         dialog.getDialogImpl().boxBkg.setY(dialog.getDialogImpl().boxRoot.getUnsafePlace().top);         //创建 0f~1f 的数值动画         ValueAnimator animator = ValueAnimator.ofFloat(0f, 1f);         animator.addUpdateListener(new ValueAnimator.AnimatorUpdateListener() {             @Override             public void onAnimationUpdate(ValueAnimator animation) {                 float value = (float) animation.getAnimatedValue();                 //修改背景遮罩透明度                 dialog.getDialogImpl().boxRoot.setBkgAlpha(value);                 //修改内容透明度                 dialog.getDialogImpl().bkg.setAlpha(value);             }         });         //使用真正的动画时长         animator.setDuration(dialog.getDialogImpl().getEnterAnimationDuration());         animator.start();     }     @Override     //出场动画     public void doExitAnim(BottomDialog dialog, ViewGroup dialogBodyView) {         ValueAnimator animator = ValueAnimator.ofFloat(1f, 0f);         animator.addUpdateListener(new ValueAnimator.AnimatorUpdateListener() {             @Override             public void onAnimationUpdate(ValueAnimator animation) {                 float value = (float) animation.getAnimatedValue();                 //这里可以直接修改整体透明度淡出                 dialog.getDialogImpl().boxRoot.setAlpha(value);             }         });         animator.setDuration(dialog.getDialogImpl().getExitAnimationDuration());         animator.start();     } };
  
然后设置给对话框：
  .setDialogXAnimImpl(alphaDialogAnimation)
 
修改动画时长
 
另外如需修改动画时长， 请勿直接修改上述动画的 Duration，请通过组件属性值覆盖的方式直接替换：
 BottomMenu.overrideEnterDuration = 100;  //修改为 100 毫秒 BottomMenu.overrideExitDuration = 100;
 
如果只需要单次修改而不是对整个组件生效，请使用实例的方法进行修改：
 .setEnterAnimDuration(100) .setExitAnimDuration(100)
 
此方法仅针对单个实例生效，具体设置请参阅  wiki  文档。

**Comment by kongzue** [comment]
DialogXAnimInterface是可以完全实现入场出场动画完全自定义的接口，你可以通过 `getDialogImpl()` 获取对话框内容的组件进行任意调整，这也可以大大提升动画效果的可玩性

**Comment by kongzue** [comment]
你也可以参阅：https://github.com/kongzue/DialogX/wiki/%E9%AB%98%E9%98%B6%E6%89%A9%E5%B1%95%E7%94%A8%E6%B3%95 
文档有详细介绍

**Comment by 9292922** [comment]
了解，真的是太有用了



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年4月25日(周二) 中午12:04
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [kongzue/DialogX] 【功能建议】建议bottomMenuDialog可以增加渐变退出动画 (Issue #303)




 
DialogXAnimInterface是可以完全实现入场出场动画完全自定义的接口，你可以通过 getDialogImpl() 获取对话框内容的组件进行任意调整，这也可以大大提升动画效果的可玩性

**Comment by 9292922** [comment]
好的好的



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年4月25日(周二) 中午12:05
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [kongzue/DialogX] 【功能建议】建议bottomMenuDialog可以增加渐变退出动画 (Issue #303)




 
你也可以参阅：https://github.com/kongzue/DialogX/wiki/%E9%AB%98%E9%98%B6%E6%89%A9%E5%B1%95%E7%94%A8%E6%B3%95
 文档有详细介绍
