### ISSUE TITLE
【BUG反馈】

### ISSUE THREAD

**Issue by JersonSU** [kongzue/DialogX#304]
GuideDialog 不能围绕一个界面上的组件显示，实现舞台光的效果，我的代码:
xml:
<?xml version="1.0" encoding="utf-8"?>
<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="match_parent">

    <Button
        android:id="@+id/test_btn"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_centerInParent="true"
        android:gravity="center"
        android:layout_margin="5dp"
        android:text="登录"
        android:textColor="@color/white"
        android:textSize="13dp"
        android:textStyle="bold"
        android:background="@color/theme"/>

</RelativeLayout>
fragment:
public class WidgetFragment extends Fragment {
    private FragmentDashboardBinding binding;
    public View onCreateView(@NonNull LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState) {
        WidgetViewModel widgetViewModel = new ViewModelProvider(this).get(WidgetViewModel.class);
        binding = FragmentDashboardBinding.inflate(inflater, container, false);
        View root = binding.getRoot();
        **GuideDialog.show(binding.testBtn, R.drawable.ic_rem_up);**
        return root;
    }
}
截图：
![image](https://user-images.githubusercontent.com/23331765/234489423-9372a50c-2ccc-41eb-a69c-9de2ca00edc1.png)

**Comment by JersonSU** [comment]
activity:
public class WidgetFragment extends Fragment {

    private FragmentDashboardBinding binding;

    public View onCreateView(@NonNull LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState) {
        WidgetViewModel widgetViewModel = new ViewModelProvider(this).get(WidgetViewModel.class);

        binding = FragmentDashboardBinding.inflate(inflater, container, false);
        View root = binding.getRoot();

        GuideDialog.show(binding.testBtn, R.drawable.ic_rem_up);

        return root;
    }

    @Override
    public void onDestroyView() {
        super.onDestroyView();
        binding = null;
    }
}

**Comment by JersonSU** [comment]
截图：
![QQ截图20230426143535](https://user-images.githubusercontent.com/23331765/234489719-7e7baec0-667b-461d-a7c9-67b066df0c8f.png)

**Comment by kongzue** [comment]
看样子是GuideDialog在启动时未能正确获得Button的位置。请尝试在Button完成渲染后再启动，例如：
```java
button.post(new Runnable{
  @Override
  public void run() {
      GuideDialog.show(...);
  }
})
```
GuideDialog中是通过 `view.getLocationOnScreen(...)` 方法获取绑定的按钮位置的，在 activity 刚启动时可能存在 view 没有得到正确的渲染位置坐标是 0,0 的问题，这个问题系系统问题，请适当延迟后执行。
另外请参阅Demo，GuideDialog本身是没有任何问题的。
![image](https://user-images.githubusercontent.com/10115359/234490704-9033af37-1c8f-4b6b-95c2-baaad1222894.png)

**Comment by JersonSU** [comment]
> 
非常棒，使用button.post(new Runnable{});可以了。非常感谢！
