### ISSUE TITLE
【申请PBD】蓝奏云批量下载器

### ISSUE THREAD

**Issue by stars-one** [kongzue/DialogX#305]
## 申请加入 Powered By DialogX

请确认并知晓[《Powered By DialogX》](https://github.com/kongzue/DialogX/wiki/%E2%9D%A4%EF%B8%8FPowered-By-DialogX)

### App 名称:

蓝奏云批量下载器

### App 网站或商店链接：

https://stars-one.site/2020/07/20/lanzoudownloader

### 是否为公开下载的 App？
是

### DialogX 满足了你那些功能需要？（非必填）

首页的表单输入,搜索关键字输入和下载目录的选择功能

### 是否愿意参加关联推广活动？

是

### 自行上传使用 DialogX 的场景截图（可选）

![](https://img2023.cnblogs.com/blog/1210268/202304/1210268-20230427224209359-991547025.png)

![](https://img2023.cnblogs.com/blog/1210268/202304/1210268-20230427224226078-1849113159.png)

![](https://img2023.cnblogs.com/blog/1210268/202304/1210268-20230427224307015-1773865033.png)

**Comment by kongzue** [comment]
已更新至：[Powered By DialogX](https://github.com/kongzue/DialogX/wiki/%E2%9D%A4%EF%B8%8FPowered-By-DialogX)
另外，对话框中的输入框，如果需要修改其光标和底线颜色，可以参阅 [wiki 文档 - InputInfo](https://github.com/kongzue/DialogX/wiki/%E5%9F%BA%E7%A1%80%E5%AF%B9%E8%AF%9D%E6%A1%86-MessageDialog-%E5%92%8C-%E8%BE%93%E5%85%A5%E5%AF%B9%E8%AF%9D%E6%A1%86-InputDialog#inputinfo)

**Comment by stars-one** [comment]
收到

> 已更新至：[Powered By DialogX](https://github.com/kongzue/DialogX/wiki/%E2%9D%A4%EF%B8%8FPowered-By-DialogX) 另外，对话框中的输入框，如果需要修改其光标和底线颜色，可以参阅 [wiki 文档 - InputInfo](https://github.com/kongzue/DialogX/wiki/%E5%9F%BA%E7%A1%80%E5%AF%B9%E8%AF%9D%E6%A1%86-MessageDialog-%E5%92%8C-%E8%BE%93%E5%85%A5%E5%AF%B9%E8%AF%9D%E6%A1%86-InputDialog#inputinfo)
