### ISSUE TITLE
【BUG反馈】全屏对话框关闭后无法弹出

### ISSUE THREAD

**Issue by stars-one** [kongzue/DialogX#306]
## BUG 反馈

请先确认您已阅读[《常见问题》](https://github.com/kongzue/DialogX/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)

### 问题描述：

出于对重复重建对象造成的性能浪费问题,使用了lazy创建对话框,但是关闭后无法再次打开对话

对话框布局里有两个按钮,用来确定和取消,点了取消按钮之后,再次点Activity里的按钮,就无法触发对话框弹出了...

```kotlin
val inputDialog by lazy {
    FullScreenDialog.build(object :
        OnBindView<FullScreenDialog?>(R.layout.dialog_textarea) {
        override fun onBind(dialog: FullScreenDialog?, view: View?) {
            val mBtnClose = view?.findViewById<FloatingActionButton>(R.id.btnClose)
            val mBtnConfirm = view?.findViewById<MaterialButton>(R.id.btnConfirm)

            mBtnClose?.setOnClickListener {
                KeyboardUtils.hideSoftInput(this@FlashDownloadActivity)
                dialog?.dismiss()
            }
            mBtnConfirm?.setOnClickListener {
               dialog?.dismiss()
            }

        }
    })
}

在Activity中的一个按钮触发弹窗

btn.setOnClickListener{
    inputDialog.show()
}
```
### 设备信息：
谷歌模拟器 Android13

### 是否在 Demo 中能复现此问题？
未尝试

### 问题截图/视频
![GIF](https://user-images.githubusercontent.com/31400169/235289860-a83619f4-6211-477f-aee0-76f68d5a5e2e.gif)

**Comment by kongzue** [comment]
请确认你已经阅读 [《常见问题-Q：如何复用一个对话框？》](https://github.com/kongzue/DialogX/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98#q%E5%A6%82%E4%BD%95%E5%A4%8D%E7%94%A8%E4%B8%80%E4%B8%AA%E5%AF%B9%E8%AF%9D%E6%A1%86)
