### ISSUE TITLE
在Android11上阻断提示等待对话框的没有动画效果

### ISSUE THREAD

**Issue by jinfupi** [kongzue/DialogX#307]
## BUG 反馈

请先确认您已阅读[《常见问题》](https://github.com/kongzue/DialogX/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)

### 问题描述：
在Android11上阻断提示等待对话框的没有动画效果

### 设备信息：
定制设备，是Android11的版本

### 是否在 Demo 中能复现此问题？
已经用Demo尝试，同样的我呢提

https://user-images.githubusercontent.com/48344102/236684479-6c2b5a2a-8b81-4d47-b5d7-86d869752ea3.mp4

### 问题截图/视频

> `请在此插入佐证问题的截图和视频。

**Comment by kongzue** [comment]
请检查设备系统问题。如果无法在大部分设备上复现的问题不属于bug，根据变量排除法请先排查设备系统是否存在问题。
