### ISSUE TITLE
【BUG反馈】onActivityResult回调里PopTip不能显示，但是控制台有log

### ISSUE THREAD

**Issue by CharlesWWT** [kongzue/DialogX#309]
机型：小米8.Android版本：10 dialogx版本：    def dialogx_version = "0.0.47"
implementation "com.kongzue.dialogx.style:DialogXIOSStyle:${dialogx_version}"，只引用了IOSStyle
`@Override
    protected void onActivityResult(final int requestCode, int resultCode, Intent data) {
        super.onActivityResult(requestCode, resultCode, data);
        if (requestCode == PC && resultCode == RESULT_OK) {
            PopTip.show(R.mipmap.ic_launcher, "test").showShort().setButton(new OnDialogButtonClickListener<PopTip>() {
                @Override
                public boolean onClick(PopTip popTip, View v) {
                    popTip.dismiss();
                    return false;
                }
            });
}`
控制台log为
_2023-05-11 15:17:01.439 15313-15313/com.cotte.xinyuan I/>>>: PopTip(201d6b9).show
2023-05-11 15:17:03.784 15313-15313/com.cotte.xinyuan I/>>>: PopTip(201d6b9).dismiss_

**Comment by kongzue** [comment]
请参阅 wiki 《Q：对话框通过 log 可以看到显示了，但实际上在界面上不显示》：https://github.com/kongzue/DialogX/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98#q%E5%AF%B9%E8%AF%9D%E6%A1%86%E9%80%9A%E8%BF%87-log-%E5%8F%AF%E4%BB%A5%E7%9C%8B%E5%88%B0%E6%98%BE%E7%A4%BA%E4%BA%86%E4%BD%86%E5%AE%9E%E9%99%85%E4%B8%8A%E5%9C%A8%E7%95%8C%E9%9D%A2%E4%B8%8A%E4%B8%8D%E6%98%BE%E7%A4%BA
