### ISSUE TITLE
【BUG反馈】PopMenu dismiss导致异常滚动

### ISSUE THREAD

**Issue by bwmgd** [kongzue/DialogX#312]
### 问题描述：
在源码中的dismiss函数如下,`dialogImpl.doDismiss(null);`传入null会导致界面中的NestedScrollView异常向上滚动
```java
public void dismiss() {
        closing = true;
        runOnMain(new Runnable() {
            @Override
            public void run() {
                if (dialogImpl == null) {
                    return;
                }
                dialogImpl.doDismiss(null);
            }
        });
    }
```
而点击背景消失的函数如下,传入了`dialogImpl.boxRoot`,此时不会导致滚动异常
```java
boxRoot.setOnClickListener(new View.OnClickListener() {
                        @Override
                        public void onClick(View v) {
                            if (onBackgroundMaskClickListener == null || !onBackgroundMaskClickListener.onClick(me, v)) {
                                doDismiss(v);
                            }
                        }
                    });
```
此外如果使用`hideWithExitAnim()`进行隐藏弹窗也不会导致异常滚动,但是会有新问题:
在第一次隐藏之后, 再次显示时, 需要点击两次背景才能消失, 并且返回键会导致界面的返回, 而不是隐藏弹窗

**Comment by kongzue** [comment]
很抱歉没能理解您所描述的内容，PopMenu中本身没有NestedScrollView，且 dialogImpl#doDismiss 方法并不会操作滑动相关事务。
另外基于即用即走防止内存泄露的原则，DialogX 并不建议重复启动一个对话框，建议每次创建新的实例进行使用，`hideWithExitAnim()` 也仅建议在特殊情况下使用，若期望隐藏但不关闭对话框，使用 `hideWithExitAnim()` 相关的事务逻辑，例如点击背景遮罩等事项也需要自行处理。

**Comment by bwmgd** [comment]
> 

抱歉没有描述清楚, 我的fragment中包含一个NestedScrollView,其中包含触发PopMenu的界面和RecyclerView,在使用`dismiss()`方法的时候就会导致NestedScrollView向上滑动一段距离, 而使用`dialogImpl.doDismiss(dialogImpl.boxRoot)`方法就不会发生该现象

**Comment by kongzue** [comment]
那就需要断点排查原因了，目前我这边已上线的项目没有发现类似的问题。
