### ISSUE TITLE
【BUG反馈】full screendialog 高度问题

### ISSUE THREAD

**Issue by DavidMGT** [kongzue/DialogX#314]
## BUG 反馈

请先确认您已阅读[《常见问题》](https://github.com/kongzue/DialogX/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)

### 问题描述：
创建了一个fragment。但是frgamnt高度适中都是wrapcontent  
  var fragment= EditPrjInfoFragment()
        FullScreenDialog.show(object : OnBindView<FullScreenDialog>(fragment) {
            override fun onBind(dialog: FullScreenDialog?, v: View?) {

            }
        })
运行显示效果始终有问题不知道何解释，用的最新的 0.47

### 设备信息：
请在此说明您使用的设备型号、Android 版本等信息以协助我们排查问题

### 是否在 Demo 中能复现此问题？
是/否/未尝试

### 问题截图/视频
![image](https://github.com/kongzue/DialogX/assets/12042191/2ce4e696-6e28-4093-b872-35172e62cc7b)
![image](https://github.com/kongzue/DialogX/assets/12042191/7508144a-2444-44cb-ac6b-a2ff6bea956f)

**Comment by DavidMGT** [comment]
如果我给一个空布局
<layout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools">

    <LinearLayout
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:orientation="vertical"
        android:background="@color/accent">

    </LinearLayout>
</layout>
则始终在最底部
我如果只是传递id FullScreenDialog.show(object : OnBindView<FullScreenDialog>(R.layout.dialog_fragment_edit_info) {
            override fun onBind(dialog: FullScreenDialog?, v: View?) {

            }
        }) 则高度显示正常我感觉是跟databingding的兼容问题

**Comment by kongzue** [comment]
很抱歉未能理解你所描述的问题，我这边刚刚做了测试是没有问题的。

**Comment by kongzue** [comment]
测试的基于Demo app进行的，使用最新版本代码进行测试，测试设备为 Google Pixel5 Android 14 beta2

**Comment by DavidMGT** [comment]
我知道问题在哪里了你按照我的布局写就会有问题的  我在你们demo运行了 你如果布局只是我下面这样没有其他item就会有问题 我设置的背景色之类的就没用 我设置背景色就毫无效果


<?xml version="1.0" encoding="utf-8"?>
<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:layout_width="match_parent"
    android:background="@color/colorAccent"
    android:layout_height="match_parent">







































</RelativeLayout>

**Comment by DavidMGT** [comment]
<?xml version="1.0" encoding="utf-8"?>
<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:layout_width="match_parent"
    android:background="@color/colorAccent"
    android:layout_height="match_parent">







































</RelativeLayout>

**Comment by DavidMGT** [comment]
<?xml version="1.0" encoding="utf-8"?>
<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:layout_width="match_parent"
    android:background="@color/colorAccent"
    android:layout_height="match_parent">

</RelativeLayout>

**Comment by DavidMGT** [comment]
> 测试的基于Demo app进行的，使用最新版本代码进行测试，测试设备为 Google Pixel5 Android 14 beta2

我按照你们的demo那样布局也是没问题的，我是说当我只有一个空布局的时候，或者其他

**Comment by kongzue** [comment]
大致上明白您的意思了，当自定义布局外层高度使用match_parent设定，且以Fragment实现作为FullScreenDialog的内容布局时可能存在高度被压缩的问题。

经查证，此问题系使用 Fragment 为自定义布局容器时不得不额外嵌套一个FrameLayout导致的，原因是在Google的设定下，要将一个Fragment显示在界面上时必须指定一个FrameLayout且使用id进行绑定，交由FragmentManager完成显示流程，而这个过程中的FrameLayout，默认是没有LayoutParams的，其LayoutParams会在显示时因为缺失被定义为默认的 (match_parent, wrap_content)。

我这边正在寻找合理的解决方案，预计在下一个测试版本修复此问题。

**Comment by kongzue** [comment]
遇到的困难在于，在 Fragment 未显示到界面上之前是无法得知其布局高度设定的（LayoutParams.height），此时OnBindView通过传入的 fragment 获取其 getView() 返回是 null，Fragment也没有提供其他方法或接口以预获取其内容布局，因此容器无法正确继承其内容的LayoutParams设定，目前正在寻找解决方案。

**Comment by kongzue** [comment]
请更新至版本：[0.0.48.beta32](https://github.com/kongzue/DialogX/releases/tag/0.0.48.beta32)，此问题已被修复。

**Comment by DavidMGT** [comment]
> 请更新至版本：[0.0.48.beta32](https://github.com/kongzue/DialogX/releases/tag/0.0.48.beta32)，此问题已被修复。

太棒了，给你们点赞👍
