### ISSUE TITLE
【BUG反馈】空指针问题，对于弱引用没有判断引用对象是否为null

### ISSUE THREAD

**Issue by lonelee** [kongzue/DialogX#315]
## BUG 反馈

请先确认您已阅读[《常见问题》](https://github.com/kongzue/DialogX/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)

### 问题描述：
会有情况报空指针，看源码应该是缺少判断弱引用的对象是否为空
BaseDialog.getTopActivity只判断了activityWeakReference==null，应该加上activityWeakReference.get()==null的判断

### 设备信息：
跟设备和平台无关

### 是否在 Demo 中能复现此问题？
未尝试

### 问题截图/视频
![image](https://github.com/kongzue/DialogX/assets/2596436/646360ba-ec76-4d5b-9b1b-559b09f0a6d0)

**Comment by kongzue** [comment]
请确认使用的版本是最新的测试版本，未能在最新版本的代码中找到类似问题的位置。

**Comment by lonelee** [comment]
我用的是0.0.47版本，但是看了最新的代码也是有这个问题的，这个方法
![image](https://github.com/kongzue/DialogX/assets/2596436/cc0d2e07-e1d9-46fe-b9a8-6d7230fd563d)

**Comment by kongzue** [comment]
好的收到，但在最新版本中不会直接获取TopActivity了，而是在启动每一个对话框时为其指定了ownActivity，本身能够一定程度上避免问题，关于TopActivity的问题将在下一个版本处理，感谢反馈

**Comment by kongzue** [comment]
请更新至最新版本 [0.0.48 正式版](https://github.com/kongzue/DialogX/releases/tag/0.0.48)
