### ISSUE TITLE
Duplicate class com.kongzue.dialogx.util.views.ProgressView$8 found in modules jetified-DialogX-0.0.47-runtime (com.github.kongzue.DialogX:DialogX:0.0.47) and jetified-DialogX-0.0.47-runtime (com.kongzue.dialogx:DialogX:0.0.47)

### ISSUE THREAD

**Issue by DavidMGT** [kongzue/DialogX#316]
## BUG 反馈

请先确认您已阅读[《常见问题》](https://github.com/kongzue/DialogX/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)

### 问题描述：
 二者只需要一个吗

### 设备信息：
请在此说明您使用的设备型号、Android 版本等信息以协助我们排查问题

### 是否在 Demo 中能复现此问题？
是/否/未尝试

### 问题截图/视频
请在此插入佐证问题的截图和视频。

**Comment by kongzue** [comment]
请更新至最新版本。针对旧版本的问题已不再处理

**Comment by DavidMGT** [comment]
Duplicate class com.kongzue.dialogx.util.views.ProgressView$9 found in modules jetified-DialogX-0.0.48-runtime (com.github.kongzue.DialogX:DialogX:0.0.48) and jetified-DialogX-0.0.48-runtime (com.kongzue.dialogx:DialogX:0.0.48)
也是一样 。
我引入了这两个库
    "dialogx"                              : "com.kongzue.dialogx:DialogX:0.0.48",
            "dialogx_theme"                        : "com.github.kongzue.DialogX:DialogXIOSStyle:0.0.48",

**Comment by kongzue** [comment]
看错误信息应该是重复依赖，我这边在已有项目中引入并没有发现相关问题，请检查你的依赖关系，是否重复引入了DialogX

**Comment by DavidMGT** [comment]
Duplicate class com.kongzue.dialogx.dialogs.WaitDialog$5 found in modules jetified-DialogX-0.0.48-runtime (com.github.kongzue.DialogX:DialogX:0.0.48) and jetified-DialogX-0.0.48-runtime (com.kongzue.dialogx:DialogX:0.0.48)
Duplicate class com.kongzue.dialogx.dialogs.WaitDialog$6 found in modules jetified-DialogX-0.0.48-runtime (com.github.kongzue.DialogX:DialogX:0.0.48) and jetified-DialogX-0.0.48-runtime (com.kongzue.dialogx:DialogX:0.0.48)
Duplicate class com.kongzue.dialogx.dialogs.WaitDialog$7 found in modules jetified-DialogX-0.0.48-runtime (com.github.kongzue.DialogX:DialogX:0.0.48) and jetified-DialogX-0.0.48-runtime (com.kongzue.dialogx:DialogX:0.0.48)
Duplicate class com.kongzue.dialogx.dialogs.WaitDialog$DialogImpl found in modules jetified-DialogX-0.0.48-runtime (com.github.kongzue.DialogX:DialogX:0.0.48) and jetified-DialogX-0.0.48-runtime (com.kongzue.dialogx:DialogX:0.0.48)
Duplicate class com.kongzue.dialogx.dialogs.WaitDialog$DialogImpl$1 found in modules jetified-DialogX-0.0.48-runtime (com.github.kongzue.DialogX:DialogX:0.0.48) and jetified-DialogX-0.0.48-runtime (com.kongzue.dialogx:DialogX:0.0.48)
Duplicate class com.kongzue.dialogx.dialogs.WaitDialog$DialogImpl$1$1 found in modules jetified-DialogX-0.0.48-runtime (com.github.kongzue.DialogX:DialogX:0.0.48) and jetified-DialogX-0.0.48-runtime (com.kongzue.dialogx:DialogX:0.0.48)
Duplicate class com.kongzue.dialogx.dialogs.WaitDialog$DialogImpl$2 found in modules jetified-DialogX-0.0.48-runtime (com.github.kongzue.DialogX:DialogX:0.0.48) and jetified-DialogX-0.0.48-runtime (com.kongzue.dialogx:DialogX:0.0.48)
Duplicate class com.kongzue.dialogx.dialogs.WaitDialog$DialogImpl$3 found in modules jetified-DialogX-0.0.48-runtime (com.github.kongzue.DialogX:DialogX:0.0.48) and jetified-DialogX-0.0.48-runtime (com.kongzue.dialogx:DialogX:0.0.48)
Duplicate class com.kongzue.dialogx.dialogs.WaitDialog$DialogImpl$4 found in modules jetified-DialogX-0.0.48-runtime (com.github.kongzue.DialogX:DialogX:0.0.48) and jetified-DialogX-0.0.48-runtime (com.kongzue.dialogx:DialogX:0.0.48)
Duplicate class com.kongzue.dialogx.dialogs.WaitDialog$DialogImpl$5 found in modules jetified-DialogX-0.0.48-runtime (com.github.kongzue.DialogX:DialogX:0.0.48) and jetified-DialogX-0.0.48-runtime (com.kongzue.dialogx:DialogX:0.0.48)
Duplicate class com.kongzue.dialogx.dialogs.WaitDialog$DialogImpl$6 found in modules jetified-DialogX-0.0.48-runtime (com.github.kongzue.DialogX:DialogX:0.0.48) and jetified-DialogX-0.0.48-runtime (com.kongzue.dialogx:DialogX:0.0.48)
Duplicate class com.kongzue.dialogx.dialogs.WaitDialog$DialogImpl$6$1 found in modules jetified-DialogX-0.0.48-runtime (com.github.kongzue.DialogX:DialogX:0.0.48) and jetified-DialogX-0.0.48-runtime (com.kongzue.dialogx:DialogX:0.0.48)
Duplicate class com.kongzue.dialogx.dialogs.WaitDialog$DialogImpl$7 found in modules jetified-DialogX-0.0.48-runtime (com.github.kongzue.DialogX:DialogX:0.0.48) and jetified-DialogX-0.0.48-runtime (com.kongzue.dialogx:DialogX:0.0.48)
Duplicate class com.kongzue.dialogx.dialogs.WaitDialog$DialogImpl$7$1 found in modules jetified-DialogX-0.0.48-runtime (com.github.kongzue.DialogX:DialogX:0.0.48) and jetified-DialogX-0.0.48-runtime (com.kongzue.dialogx:DialogX:0.0.48)
Duplicate class com.kongzue.dialogx.dialogs.WaitDialog$DialogImpl$7$2 found in modules jetified-DialogX-0.0.48-runtime (com.github.kongzue.DialogX:DialogX:0.0.48) and jetified-DialogX-0.0.48-runtime (com.kongzue.dialogx:DialogX:0.0.48)
Duplicate class com.kongzue.dialogx.dialogs.WaitDialog$DialogImpl$8 found in modules jetified-DialogX-0.0.48-runtime (com.github.kongzue.DialogX:DialogX:0.0.48) and jetified-DialogX-0.0.48-runtime (com.kongzue.dialogx:DialogX:0.0.48)
Duplicate class com.kongzue.dialogx.dialogs.WaitDialog$DialogImpl$8$1 found in modules jetified-DialogX-0.0.48-runtime (com.github.kongzue.DialogX:DialogX:0.0.48) and jetified-DialogX-0.0.48-runtime (com.kongzue.dialogx:DialogX:0.0.48)
Duplicate class com.kongzue.dialogx.dialogs.WaitDialog$DialogImpl$8$1$1 found in modules jetified-DialogX-0.0.48-runtime (com.github.kongzue.DialogX:DialogX:0.0.48) and jetified-DialogX-0.0.48-runtime (com.kongzue.dialogx:DialogX:0.0.48)
Duplicate class com.kongzue.dialogx.dialogs.WaitDialog$DialogImpl$8$2 found in modules jetified-DialogX-0.0.48-runtime (com.github.kongzue.DialogX:DialogX:0.0.48) and jetified-DialogX-0.0.48-runtime (com.kongzue.dialogx:DialogX:0.0.48)
Duplicate class com.kongzue.dialogx.dialogs.WaitDialog$TYPE found in modules jetified-DialogX-0.0.48-runtime (com.github.kongzue.DialogX:DialogX:0.0.48) and jetified-DialogX-0.0.48-runtime (com.kongzue.dialogx:DialogX:0.0.48)
Duplicate class com.kongzue.dialogx.impl.ActivityLifecycleImpl found in modules jetified-DialogX-0.0.48-runtime (com.github.kongzue.DialogX:DialogX:0.0.48) and jetified-DialogX-0.0.48-runtime (com.kongzue.dialogx:DialogX:0.0.48)
Duplicate class com.kongzue.dialogx.impl.ActivityLifecycleImpl$onActivityResumeCallBack found in modules jetified-DialogX-0.0.48-runtime (com.github.kongzue.DialogX:DialogX:0.0.48) and jetified-DialogX-0.0.48-runtime (com.kongzue.dialogx:DialogX:0.0.48)
Duplicate class com.kongzue.dialogx.impl.AnimatorListenerEndCallBack found in modules jetified-DialogX-0.0.48-runtime (com.github.kongzue.DialogX:DialogX:0.0.48) and jetified-DialogX-0.0.48-runtime (com.kongzue.dialogx:DialogX:0.0.48)
Duplicate class com.kongzue.dialogx.impl.DialogFragmentImpl found in modules jetified-DialogX-0.0.48-runtime (com.github.kongzue.DialogX:DialogX:0.0.48) and jetified-DialogX-0.0.48-runtime (com.kongzue.dialogx:DialogX:0.0.48)
Duplicate class com.kongzue.dialogx.impl.DialogFragmentImpl$1 found in modules jetified-DialogX-0.0.48-runtime (com.github.kongzue.DialogX:DialogX:0.0.48) and jetified-DialogX-0.0.48-runtime (com.kongzue.dialogx:DialogX:0.0.48)
Duplicate class com.kongzue.dialogx.interfaces.BaseDialog found in modules jetified-DialogX-0.0.48-runtime (com.github.kongzue.DialogX:DialogX:0.0.48) and jetified-DialogX-0.0.48-runtime (com.kongzue.dialogx:DialogX:0.0.48)
Duplicate class com.kongzue.dialogx.interfaces.BaseDialog$1 found in modules jetified-DialogX-0.0.48-runtime (com.github.kongzue.DialogX:DialogX:0.0.48) and jetified-DialogX-0.0.48-runtime (com.kongzue.dialogx:DialogX:0.0.48)
Duplicate class com.kongzue.dialogx.interfaces.BaseDialog$2 found in modules jetified-DialogX-0.0.48-runtime (com.github.kongzue.DialogX:DialogX:0.0.48) and jetified-DialogX-0.0.48-runtime (com.kongzue.dialogx:DialogX:0.0.48)
Duplicate class com.kongzue.dialogx.interfaces.BaseDialog$2$1 found in modules jetified-DialogX-0.0.48-runtime (com.github.kongzue.DialogX:DialogX:0.0.48) and jetified-DialogX-0.0.48-runtime (com.kongzue.dialogx:DialogX:0.0.48)
Duplicate class com.kongzue.dialogx.interfaces.BaseDialog$3 found in modules jetified-DialogX-0.0.48-runtime (com.github.kongzue.DialogX:DialogX:0.0.48) and jetified-DialogX-0.0.48-runtime (com.kongzue.dialogx:DialogX:0.0.48)
Duplicate class com.kongzue.dialogx.interfaces.BaseDialog$4 found in modules jetified-DialogX-0.0.48-runtime (com.github.kongzue.DialogX:DialogX:0.0.48) and jetified-DialogX-0.0.48-runtime (com.kongzue.dialogx:DialogX:0.0.48)
Duplicate class com.kongzue.dialogx.interfaces.BaseDialog$4$1 found in modules jetified-DialogX-0.0.48-runtime (com.github.kongzue.DialogX:DialogX:0.0.48) and jetified-DialogX-0.0.48-runtime (com.kongzue.dialogx:DialogX:0.0.48)
Duplicate class com.kongzue.dialogx.interfaces.BaseDialog$5 found in modules jetified-DialogX-0.0.48-runtime (com.github.kongzue.DialogX:DialogX:0.0.48) and jetified-DialogX-0.0.48-runtime (com.kongzue.dialogx:DialogX:0.0.48)

**Comment by DavidMGT** [comment]
我引入了这两个库
"dialogx" : "com.kongzue.dialogx:DialogX:0.0.48",
"dialogx_theme" : "com.github.kongzue.DialogX:DialogXIOSStyle:0.0.48",

**Comment by kongzue** [comment]
仔细看发现，你是应该同时引入了MavenCentral版本的和Jitpack版本的，请注意包名是不同的。
请勿同时引入不同源的包。

**Comment by kongzue** [comment]
备注：
com.kongzue.dialogx是MavenCentral 源，
com.github.kongzue是Jitpack源。
