### ISSUE TITLE
【功能建议】DataBinding/ViewBinding for CustomDialog

### ISSUE THREAD

**Issue by jesse920524** [kongzue/DialogX#317]
### 需求描述：
When users use CustomDialog, they really need DataBinding or ViewBinding in their OnBindView() method.

Plz consider about support DB/VB for it, thank you !

**Comment by kongzue** [comment]
The instance root layout of the custom layout is provided in the OnBindView of CustomDialog, which is the parameter View of the onBind method, and you can bind internal components through it if needed.
For example:
```java
new OnBindView<BottomDialog>(R.layout.dialog_my_order_details) {
    private TextView textView;
  
    @Override
    public void onBind(BottomDialog dialog, View v) {
        textView = v.findViewById(R.id.textview);
    }
}
```
`OnBindView#onBind()` will be executed when the custom layout is instantiated and displayed to the interface.
