### ISSUE TITLE
多次调用同一个封装的Dialog方法展示Dialog 出现展示不出来，也没报错！

### ISSUE THREAD

**Issue by 1216845248** [kongzue/DialogX#318]
## BUG 反馈

请先确认您已阅读[《常见问题》](https://github.com/kongzue/DialogX/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)

### 问题描述：
多次调用同一个封装的Dialog方法展示Dialog 第一次能展示后面的展示不出来，也没报错！
![image](https://github.com/kongzue/DialogX/assets/101159837/c62cb730-6d62-4b63-80e0-9db5529cfffa)

在DialogLifecycleCallback onShow中打印Toast 显示能正常走onShow 方法，但是ui 没显示出来，调用refreshUI（）
还是显示不出来

![image](https://github.com/kongzue/DialogX/assets/101159837/f8123596-f940-47cc-bc45-3ed1d884a804)

### 设备信息：
请在此说明您使用的设备型号、Android 版本等信息以协助我们排查问题

设备Redmi Note 11T pro    mui 14.0.3  

### 是否在 Demo 中能复现此问题？
是/否/未尝试

### 问题截图/视频
请在此插入佐证问题的截图和视频。

**Comment by kongzue** [comment]
请先确认您已阅读[《常见问题》](https://github.com/kongzue/DialogX/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)
<img width="923" alt="image" src="https://github.com/kongzue/DialogX/assets/10115359/5b8a1c05-8acc-4c5f-8b14-e001c675e6b8">

**Comment by 1216845248** [comment]
我的场景应该不算是复用，我在一个Fragment 中做网络请求，在网络请求回来后展示弹窗，所有写了个扩展函数，不想每次些重复代码，但是我发现第一次网络请求可以正常展示，第二次网络请求回来后，这个自定义弹窗不展示出来，生命周期走了可show()方法

**Comment by kongzue** [comment]
那就不清楚了，我这边尚未收到过类似问题的反馈，且已知的在目前已上线的产品中没有遇到过对话框启动无效的情况，建议通过断点排查具体问题。

**Comment by 1216845248** [comment]
好吧，目前还没找到问题，断点也没发先问题，show（）都走了就是显示不出来

**Comment by wangkai9799** [comment]
我也是遇到了同样的问题，我看都走到show了，log也打印出来了SquareDialog(c317309).show

**Comment by 1216845248** [comment]
初始化调用DialogX.init(this) 会读取androidid  和应用进程？导致上架被拒

**Comment by kongzue** [comment]
请自行阅读源代码，本框架是开源的

**Comment by kongzue** [comment]
你需要的代码在：https://github.com/kongzue/DialogX/blob/master/DialogX/src/main/java/com/kongzue/dialogx/impl/ActivityLifecycleImpl.java
它只是一个 Application.ActivityLifecycleCallbacks 实现，如果你没有正确的初始化却要打开对话框会尝试反射android.app.ActivityThread获取Application对象自动完成初始化，我们目前已上线的应用产品在国内几乎所有应用商店都有上架，没有发现任何跟DialogX有关的问题。

**Comment by kongzue** [comment]
另外，关于 AndroidID 的使用，请自行检查你的程序代码，DialogX 所有源代码中都未读取和使用过这个标记。

**Comment by 1216845248** [comment]
好的，我看看，谢谢！
