### ISSUE TITLE
设置背景色有问题

### ISSUE THREAD

**Issue by libern** [kongzue/DialogX#32]
在com.kongzue.dialogx.dialogs.MessageDialog:491行
https://github.com/kongzue/DialogX/blob/2c681cc13d4a3eb990e630938ab667e5da045531/DialogX/src/main/java/com/kongzue/dialogx/dialogs/MessageDialog.java#L491

应该采用类似533行的：

https://github.com/kongzue/DialogX/blob/2c681cc13d4a3eb990e630938ab667e5da045531/DialogX/src/main/java/com/kongzue/dialogx/dialogs/MessageDialog.java#L533

结果应为：
在com.kongzue.dialogx.dialogs.MessageDialog:491行
```
splitHorizontal.setBackgroundColor(getResources().getColor(style.splitColorRes(isLightTheme())));
```

不然现在获取不到resource

**Comment by kongzue** [comment]
没区别啊...
![image](https://user-images.githubusercontent.com/10115359/112840862-6790b200-90d2-11eb-819c-fc4696cdd726.png)
getColor方法->BaseDialog中依然是取Res后获取颜色的

**Comment by libern** [comment]
但是我自定义的颜色只有这个没生效 在2021年03月29日 21:05，Kongzue 写道： 

没区别啊...



getColor方法->BaseDialog中依然是取Res后获取颜色的



—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

[

{

***@***.***": "http://schema.org",

***@***.***": "EmailMessage",

"potentialAction": {

***@***.***": "ViewAction",

"target": "https://github.com/kongzue/DialogX/issues/32#issuecomment-809360853",

"url": "https://github.com/kongzue/DialogX/issues/32#issuecomment-809360853",

"name": "View Issue"

},

"description": "View this Issue on GitHub",

"publisher": {

***@***.***": "Organization",

"name": "GitHub",

"url": "https://github.com"

}

}

]

**Comment by kongzue** [comment]
建议尝试更新至最新版本

**Comment by libern** [comment]
我再看看 在2021年03月29日 22:45，Kongzue 写道： 

已确认是有效的。





—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

[

{

***@***.***": "http://schema.org",

***@***.***": "EmailMessage",

"potentialAction": {

***@***.***": "ViewAction",

"target": "https://github.com/kongzue/DialogX/issues/32#issuecomment-809438758",

"url": "https://github.com/kongzue/DialogX/issues/32#issuecomment-809438758",

"name": "View Issue"

},

"description": "View this Issue on GitHub",

"publisher": {

***@***.***": "Organization",

"name": "GitHub",

"url": "https://github.com"

}

}

]

**Comment by libern** [comment]
> 建议尝试更新至最新版本

确实有用，我没升级版本导致。抱歉
