### ISSUE TITLE
【BUG反馈】显示一个自定义不消失的PopNotification ，然后显示WaitDialog，PopNotification 的顶部位置会不断改变

### ISSUE THREAD

**Issue by bananaCaptain** [kongzue/DialogX#320]
## BUG 反馈
显示一个自定义不消失的PopNotification ，然后显示WaitDialog，PopNotification 的顶部位置会不断改变

### 问题描述：
1.自定义一个PopNotification  并设置为noAutoDismiss。
2.显示一个WaitDialog，自动消失。
3.在WaitDialog显示时PopNotification  会向下移动大概是安全区的距离。
4.WaitDialog消失，PopNotification 回跳回原来的位置。
5.如果在PopNotification 的onBind方法中添加
dialog?.dialogImpl?.boxRoot?.isAutoUnsafePlacePadding = true 会 眺得更复杂。
希望PopNotification  不用突然改变位置。

### 是否在 Demo 中能复现此问题？
未尝试

**Comment by kongzue** [comment]
很抱歉未能在Demo中模拟出相关问题，测试视频如下：

https://github.com/kongzue/DialogX/assets/10115359/b8415b6b-dee3-4f41-93c4-9405aa2d54d1

测试环境：DialogX0.0.48，Google Pixel5(Android 14 beta2)
测试代码：
```java
PopNotification.show("这是一条消息 " + notificationIndex, "吃了没？\uD83E\uDD6A")
        .setButton("回复", new OnDialogButtonClickListener<PopNotification>() {
            @Override
            public boolean onClick(PopNotification baseDialog, View v) {
                toast("点击回复按钮");
                return false;
            }
        })
        .noAutoDismiss();
runDelayed(new Runnable() {
    @Override
    public void run() {
        WaitDialog.show("loading...");
        runDelayed(new Runnable() {
            @Override
            public void run() {
                WaitDialog.dismiss();
            }
        },1000);
    }
},1000);
```
