### ISSUE TITLE
【BUG反馈】运行apk文件点点就崩溃了

### ISSUE THREAD

**Issue by Jsondx** [kongzue/DialogX#321]
## BUG 反馈

请先确认您已阅读[《常见问题》](https://github.com/kongzue/DialogX/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)

### 问题描述：
崩溃了（我先下载你的apk文件）
apk version  0.0.48.beta24 (Build 47)

### 设备信息：
pixel 4

### 是否在 Demo 中能复现此问题？
是

### 问题截图/视频
![image](https://github.com/kongzue/DialogX/assets/23163675/24affa97-d3eb-4b68-b622-7e713b563c2f)

**Comment by kongzue** [comment]
请确保你使用的是最新版本：[0.0.48](https://github.com/kongzue/DialogX/releases/tag/0.0.48)
针对旧版的问题不再进行处理。
