### ISSUE TITLE
【BUG反馈】自定义customdialog在页面进入时弹出 设置遮罩后状态栏留空隙

### ISSUE THREAD

**Issue by kagurasansan** [kongzue/DialogX#322]
## BUG 反馈

请先确认您已阅读[《常见问题》](https://github.com/kongzue/DialogX/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)

### 问题描述：
在页面一进入就弹出dialog时顶部状态栏设置了setAutoUnsafePlacePadding(false)遮罩还是留出了空隙
![image](https://github.com/kongzue/DialogX/assets/31067094/190f112e-f122-47fc-b4fd-5e3e0a2010cb)
再页面点击弹出的弹窗就不会有空隙
![image](https://github.com/kongzue/DialogX/assets/31067094/18ed1b20-cd50-4c09-93ee-5ed20f4fdf6d)
  
Activity使用的主题为Theme.MaterialComponents.DayNight.NoActionBar

### 设备信息：
小米 12Pro  android13

### 是否在 Demo 中能复现此问题？
否

**Comment by kongzue** [comment]
安全区的判断依赖系统返回的WindowInsets，但倘若系统给出的WindowInsets是错误的则可能导致上述问题发生。
相关代码在：[DialogXBaseRelativeLayout.java](https://github.com/kongzue/DialogX/blob/8f73993d3595d27d0381a065dada55b30397cc57/DialogX/src/main/java/com/kongzue/dialogx/util/views/DialogXBaseRelativeLayout.java#L52)
另外可以尝试使用build()方法构建对话框，在指定完成所有设置之后再执行.show命令

**Comment by Wisdozzh** [comment]
> 安全区的判断依赖系统返回的WindowInsets，但倘若系统给出的WindowInsets是错误的则可能导致上述问题发生。 相关代码在：[DialogXBaseRelativeLayout.java](https://github.com/kongzue/DialogX/blob/8f73993d3595d27d0381a065dada55b30397cc57/DialogX/src/main/java/com/kongzue/dialogx/util/views/DialogXBaseRelativeLayout.java#L52) 另外可以尝试使用build()方法构建对话框，在指定完成所有设置之后再执行.show命令

能在详细一些吗？我比较了两次弹窗的WindowInsets值 都是一致的的。

**Comment by kagurasansan** [comment]
CustomDialog 中 show方法这么改了一下好使了 
![image](https://github.com/kongzue/DialogX/assets/31067094/54d77460-3b7a-46a7-8298-cffec4c10664)
