### ISSUE TITLE
【BUG反馈】底部弹框BottomMenu数量达到50多个时弹出有延迟

### ISSUE THREAD

**Issue by VoidAndNullity** [kongzue/DialogX#323]
## BUG 反馈

请先确认您已阅读[《常见问题》](https://github.com/kongzue/DialogX/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)

### 问题描述：
底部弹框BottomMenu数量达到50多个时弹出有延迟。主题我使用的是苹果主题。
以下是依赖的版本
implementation 'com.github.kongzue.DialogX:DialogX:0.0.47'
implementation 'com.github.kongzue.DialogX:DialogXIOSStyle:0.0.47'

### 设备信息：
荣耀V20 鸿蒙3.0

### 是否在 Demo 中能复现此问题？
未尝试

### 问题截图/视频
视频中数量小的弹出很流畅，但是数量多的时候感觉有点延迟

https://github.com/kongzue/DialogX/assets/94156250/90ddb319-c797-46c6-92bb-dfb471f3f8e3

**Comment by VoidAndNullity** [comment]
数据是已经通过接口获取到之后缓存起来的

**Comment by VoidAndNullity** [comment]
下面这个视频演示的是BottomMenu和WaitDialog一块使用时出现的问题，这里用到WaitDialog是因为请求接口有个等待的过程。

https://github.com/kongzue/DialogX/assets/94156250/4967b480-0be4-4937-8df4-fee03609b1ad

**Comment by kongzue** [comment]
是这样的，BottomMenu虽然允许但并不建议承载大量的选项，此时更建议使用BottomDialog或者FullScreenDialog配合RecycleView实现。

BottomMenu的应用场景更倾向于简单选择选项的使用场景，因为其内部构造是基于BottomDialog完成的，而BottomDialog因为需要计算内部元素高度，当高度大于可用范围时使用ScrollView承载内部布局，因此你可以理解为他是由一层ScrollView嵌套ListView实现的，因此在这种情况下ListView不能正确计算高度因此采用了满足最大高度计算的方案，也就意味着有多少选项就会渲染多少布局，再交由外层的ScrollView负责滚动逻辑，因而当选项特别多的时候会造成渲染压力，此时建议使用固定高度的BottomDialog/FullScreenDialog配合RecycleView作为自定义布局进行实现。

另外，当使用 IOS 主体且启用模糊效果时，因为 RenderScript 本身占用一定的计算资源可能会带来性能压力，如非必须也更推荐使用其它主题实现。

**Comment by VoidAndNullity** [comment]
好的，了解了
