### ISSUE TITLE
【BUG反馈】 在华为平板开启浮窗后，自定义布局均无法显示，有的甚至导致无法退出app

### ISSUE THREAD

**Issue by Li4526330** [kongzue/DialogX#325]
## BUG 反馈

请先确认您已阅读[《常见问题》](https://github.com/kongzue/DialogX/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)

### 问题描述：
请在此详细描述问题。

### 设备信息：
请在此说明您使用的设备型号、Android 版本等信息以协助我们排查问题

### 是否在 Demo 中能复现此问题？
是/否/未尝试

### 问题截图/视频
请在此插入佐证问题的截图和视频。

**Comment by kongzue** [comment]
猜测可能跟该系统的 WindowManager 有关，因无法复现暂无法排查故障原因，建议不要在华为设备上开启悬浮窗模式。
