### ISSUE TITLE
后台PopNotification通知，必须是全屏吗， 除了通知布局，其他界面无法点击，盲点能点到本app里的东西

### ISSUE THREAD

**Issue by Li4526330** [kongzue/DialogX#329]
## BUG 反馈

请先确认您已阅读[《常见问题》](https://github.com/kongzue/DialogX/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)

### 问题描述：
请在此详细描述问题。

### 设备信息：
请在此说明您使用的设备型号、Android 版本等信息以协助我们排查问题

### 是否在 Demo 中能复现此问题？
是/否/未尝试

### 问题截图/视频
请在此插入佐证问题的截图和视频。

**Comment by kongzue** [comment]
这个问题的原因是Google限制了悬浮窗不可以点击穿透，暂时没有合适的解决方案
