### ISSUE TITLE
【功能建议】InputDialog 为EditText增加InputFilter

### ISSUE THREAD

**Issue by Linnnnnn** [kongzue/DialogX#332]
## 功能建议
InputDialog 为EditText增加InputFilter
### 需求描述：
例如金钱输入的时候可以价格InputFilter验证输入的内容

**Comment by kongzue** [comment]
临时的可以通过以下方法获取EditText对象：
```java
.setDialogLifecycleCallback(new DialogLifecycleCallback<MessageDialog>() {
    @Override
    public void onShow(MessageDialog dialog) {
        EditText editText = dialog.getDialogImpl().txtInput;
    }
})
```
后续会考虑更新。

**Comment by Linnnnnn** [comment]
好的

**Comment by kongzue** [comment]
将在下一个版本中为InputInfo新增方法：`getInputFilters()`、`setInputFilters(InputFilter[] inputFilters)`、`addInputFilter(InputFilter inputFilter)` 和 `removeInputFilter(InputFilter inputFilter)`
相关代码已提交，将在下一个测试版本发布。
