### ISSUE TITLE
【BUG反馈】DialogFragment的内存泄漏问题

### ISSUE THREAD

**Issue by VoidAndNullity** [kongzue/DialogX#334]
## BUG 反馈

我的应用中使用了DialogFragment作为dialogx的实现方式，leakcanary提示有内存泄露，在0.0.47和0.0.49.beta1中都有这个问题

### 问题描述：

D/LeakCanary: ====================================
D/LeakCanary: 1 APPLICATION LEAKS
D/LeakCanary: 
D/LeakCanary: References underlined with "~~~" are likely causes.
D/LeakCanary: Learn more at https://squ.re/leaks.
D/LeakCanary: 
D/LeakCanary: 28831 bytes retained by leaking objects
D/LeakCanary: Signature: 9f57d2a3bafe58af085569d978386c97e223a0df
D/LeakCanary: ┬───
D/LeakCanary: │ GC Root: System class
D/LeakCanary: │
D/LeakCanary: ├─ android.app.ActivityThread class
D/LeakCanary: │    Leaking: NO (LoginActivity↓ is not leaking and a class is never leaking)
D/LeakCanary: │    ↓ static ActivityThread.sCurrentActivityThread
D/LeakCanary: ├─ android.app.ActivityThread instance
D/LeakCanary: │    Leaking: NO (LoginActivity↓ is not leaking)
D/LeakCanary: │    mInitialApplication instance of com.onegrid.app.npmn.NpmnApplication
D/LeakCanary: │    mSystemContext instance of android.app.ContextImpl
D/LeakCanary: │    mSystemUiContext instance of android.app.ContextImpl
D/LeakCanary: │    ↓ ActivityThread.mActivities
D/LeakCanary: ├─ android.util.ArrayMap instance
D/LeakCanary: │    Leaking: NO (LoginActivity↓ is not leaking)
D/LeakCanary: │    ↓ ArrayMap.mArray
D/LeakCanary: ├─ java.lang.Object[] array
D/LeakCanary: │    Leaking: NO (LoginActivity↓ is not leaking)
D/LeakCanary: │    ↓ Object[3]
D/LeakCanary: ├─ android.app.ActivityThread$ActivityClientRecord instance
D/LeakCanary: │    Leaking: NO (LoginActivity↓ is not leaking)
D/LeakCanary: │    activity instance of com.onegrid.app.npmn.LoginActivity with mDestroyed = false
D/LeakCanary: │    ↓ ActivityThread$ActivityClientRecord.activity
D/LeakCanary: ├─ com.onegrid.app.npmn.LoginActivity instance
D/LeakCanary: │    Leaking: NO (LifecycleRegistry↓ is not leaking and Activity#mDestroyed is false)
D/LeakCanary: │    mApplication instance of com.onegrid.app.npmn.NpmnApplication
D/LeakCanary: │    mBase instance of androidx.appcompat.view.ContextThemeWrapper
D/LeakCanary: │    ↓ ComponentActivity.mLifecycleRegistry
D/LeakCanary: ├─ androidx.lifecycle.LifecycleRegistry instance
D/LeakCanary: │    Leaking: NO (mState is not DESTROYED)
D/LeakCanary: │    mState = CREATED
D/LeakCanary: │    ↓ LifecycleRegistry.mObserverMap
D/LeakCanary: │                        ~~~~~~~~~~~~
D/LeakCanary: ├─ androidx.arch.core.internal.FastSafeIterableMap instance
D/LeakCanary: │    Leaking: UNKNOWN
D/LeakCanary: │    Retaining 75.7 kB in 834 objects
D/LeakCanary: │    ↓ FastSafeIterableMap[key()]
D/LeakCanary: │                         ~~~~~~~
D/LeakCanary: ├─ com.kongzue.dialogx.interfaces.BaseDialog$7 instance
D/LeakCanary: │    Leaking: UNKNOWN
D/LeakCanary: │    Retaining 74.8 kB in 803 objects
D/LeakCanary: │    Anonymous class implementing androidx.lifecycle.LifecycleEventObserver
D/LeakCanary: │    ↓ BaseDialog$7.this$0
D/LeakCanary: │                   ~~~~~~
D/LeakCanary: ├─ com.kongzue.dialogx.dialogs.WaitDialog instance
D/LeakCanary: │    Leaking: UNKNOWN
D/LeakCanary: │    Retaining 74.8 kB in 802 objects
D/LeakCanary: │    ↓ WaitDialog.dialogXAnimImpl
D/LeakCanary: │                 ~~~~~~~~~~~~~~~
D/LeakCanary: ├─ com.kongzue.dialogx.dialogs.WaitDialog$DialogImpl$7 instance
D/LeakCanary: │    Leaking: UNKNOWN
D/LeakCanary: │    Retaining 74.2 kB in 786 objects
D/LeakCanary: │    Anonymous subclass of com.kongzue.dialogx.interfaces.DialogXAnimInterface
D/LeakCanary: │    ↓ WaitDialog$DialogImpl$7.this$1
D/LeakCanary: │                              ~~~~~~
D/LeakCanary: ├─ com.kongzue.dialogx.dialogs.WaitDialog$DialogImpl instance
D/LeakCanary: │    Leaking: UNKNOWN
D/LeakCanary: │    Retaining 74.2 kB in 785 objects
D/LeakCanary: │    ↓ WaitDialog$DialogImpl.boxRoot
D/LeakCanary: │                            ~~~~~~~
D/LeakCanary: ╰→ com.kongzue.dialogx.util.views.DialogXBaseRelativeLayout instance
D/LeakCanary: ​     Leaking: YES (ObjectWatcher was watching this because com.kongzue.dialogx.impl.DialogFragmentImpl received
D/LeakCanary: ​     Fragment#onDestroyView() callback (references to its views should be cleared to prevent leaks) and View detached
D/LeakCanary: ​     yet still part of window view hierarchy)
D/LeakCanary: ​     Retaining 28.8 kB in 598 objects
D/LeakCanary: ​     key = b0c2d243-9234-4497-8070-4745718eb7c3
D/LeakCanary: ​     watchDurationMillis = 13065
D/LeakCanary: ​     retainedDurationMillis = 8059
D/LeakCanary: ​     View is part of a window view hierarchy
D/LeakCanary: ​     View.mAttachInfo is null (view detached)
D/LeakCanary: ​     View.mID = R.id.box_root
D/LeakCanary: ​     View.mWindowAttachCount = 1
D/LeakCanary: ​     mContext instance of com.onegrid.app.npmn.LoginActivity with mDestroyed = false
D/LeakCanary: ====================================

### 设备信息：
荣耀v20 鸿蒙3.0

### 是否在 Demo 中能复现此问题？
未尝试

**Comment by kongzue** [comment]
请更换为默认的View模式。
请注意，除了默认的View模式，其他模式都属于实验性，在wiki中有明确说明，如无必要不建议使用。

**Comment by kongzue** [comment]
尝试性修复代码已提交在：https://github.com/kongzue/DialogX/commit/0f804bb5a5281a2c9bf3161adac3f3d598bcc31b

**Comment by kongzue** [comment]
版本已更新：[0.0.49.beta2](https://github.com/kongzue/DialogX/releases/tag/0.0.49.beta2)

**Comment by VoidAndNullity** [comment]
更新后还是一样

D/LeakCanary: 1 APPLICATION LEAKS
D/LeakCanary: 
D/LeakCanary: References underlined with "~~~" are likely causes.
D/LeakCanary: Learn more at https://squ.re/leaks.
D/LeakCanary: 
D/LeakCanary: 28651 bytes retained by leaking objects
D/LeakCanary: Signature: 9f57d2a3bafe58af085569d978386c97e223a0df
D/LeakCanary: ┬───
D/LeakCanary: │ GC Root: System class
D/LeakCanary: │
D/LeakCanary: ├─ android.app.ActivityThread class
D/LeakCanary: │    Leaking: NO (LoginActivity↓ is not leaking and a class is never leaking)
D/LeakCanary: │    ↓ static ActivityThread.sCurrentActivityThread
D/LeakCanary: ├─ android.app.ActivityThread instance
D/LeakCanary: │    Leaking: NO (LoginActivity↓ is not leaking)
D/LeakCanary: │    mInitialApplication instance of com.onegrid.app.npmn.NpmnApplication
D/LeakCanary: │    mSystemContext instance of android.app.ContextImpl
D/LeakCanary: │    mSystemUiContext instance of android.app.ContextImpl
D/LeakCanary: │    ↓ ActivityThread.mActivities
D/LeakCanary: ├─ android.util.ArrayMap instance
D/LeakCanary: │    Leaking: NO (LoginActivity↓ is not leaking)
D/LeakCanary: │    ↓ ArrayMap.mArray
D/LeakCanary: ├─ java.lang.Object[] array
D/LeakCanary: │    Leaking: NO (LoginActivity↓ is not leaking)
D/LeakCanary: │    ↓ Object[3]
D/LeakCanary: ├─ android.app.ActivityThread$ActivityClientRecord instance
D/LeakCanary: │    Leaking: NO (LoginActivity↓ is not leaking)
D/LeakCanary: │    activity instance of com.onegrid.app.npmn.LoginActivity with mDestroyed = false
D/LeakCanary: │    ↓ ActivityThread$ActivityClientRecord.activity
D/LeakCanary: ├─ com.onegrid.app.npmn.LoginActivity instance
D/LeakCanary: │    Leaking: NO (LifecycleRegistry↓ is not leaking and Activity#mDestroyed is false)
D/LeakCanary: │    mApplication instance of com.onegrid.app.npmn.NpmnApplication
D/LeakCanary: │    mBase instance of androidx.appcompat.view.ContextThemeWrapper
D/LeakCanary: │    ↓ ComponentActivity.mLifecycleRegistry
D/LeakCanary: ├─ androidx.lifecycle.LifecycleRegistry instance
D/LeakCanary: │    Leaking: NO (mState is not DESTROYED)
D/LeakCanary: │    mState = CREATED
D/LeakCanary: │    ↓ LifecycleRegistry.mObserverMap
D/LeakCanary: │                        ~~~~~~~~~~~~
D/LeakCanary: ├─ androidx.arch.core.internal.FastSafeIterableMap instance
D/LeakCanary: │    Leaking: UNKNOWN
D/LeakCanary: │    Retaining 75.3 kB in 825 objects
D/LeakCanary: │    ↓ FastSafeIterableMap[key()]
D/LeakCanary: │                         ~~~~~~~
D/LeakCanary: ├─ com.kongzue.dialogx.interfaces.BaseDialog$7 instance
D/LeakCanary: │    Leaking: UNKNOWN
D/LeakCanary: │    Retaining 74.7 kB in 798 objects
D/LeakCanary: │    Anonymous class implementing androidx.lifecycle.LifecycleEventObserver
D/LeakCanary: │    ↓ BaseDialog$7.this$0
D/LeakCanary: │                   ~~~~~~
D/LeakCanary: ├─ com.kongzue.dialogx.dialogs.WaitDialog instance
D/LeakCanary: │    Leaking: UNKNOWN
D/LeakCanary: │    Retaining 74.6 kB in 797 objects
D/LeakCanary: │    ↓ WaitDialog.dialogXAnimImpl
D/LeakCanary: │                 ~~~~~~~~~~~~~~~
D/LeakCanary: ├─ com.kongzue.dialogx.dialogs.WaitDialog$DialogImpl$7 instance
D/LeakCanary: │    Leaking: UNKNOWN
D/LeakCanary: │    Retaining 74.1 kB in 781 objects
D/LeakCanary: │    Anonymous subclass of com.kongzue.dialogx.interfaces.DialogXAnimInterface
D/LeakCanary: │    ↓ WaitDialog$DialogImpl$7.this$1
D/LeakCanary: │                              ~~~~~~
D/LeakCanary: ├─ com.kongzue.dialogx.dialogs.WaitDialog$DialogImpl instance
D/LeakCanary: │    Leaking: UNKNOWN
D/LeakCanary: │    Retaining 74.1 kB in 780 objects
D/LeakCanary: │    ↓ WaitDialog$DialogImpl.boxRoot
D/LeakCanary: │                            ~~~~~~~
D/LeakCanary: ╰→ com.kongzue.dialogx.util.views.DialogXBaseRelativeLayout instance
D/LeakCanary: ​     Leaking: YES (ObjectWatcher was watching this because com.kongzue.dialogx.impl.DialogFragmentImpl received
D/LeakCanary: ​     Fragment#onDestroyView() callback (references to its views should be cleared to prevent leaks) and View detached
D/LeakCanary: ​     yet still part of window view hierarchy)
D/LeakCanary: ​     Retaining 28.7 kB in 593 objects
D/LeakCanary: ​     key = 2f485c74-eda0-4423-b92c-30d32c5d9cea
D/LeakCanary: ​     watchDurationMillis = 9189
D/LeakCanary: ​     retainedDurationMillis = 4188
D/LeakCanary: ​     View is part of a window view hierarchy
D/LeakCanary: ​     View.mAttachInfo is null (view detached)
D/LeakCanary: ​     View.mID = R.id.box_root
D/LeakCanary: ​     View.mWindowAttachCount = 1

**Comment by kongzue** [comment]
很抱歉无法确定原因。
在最新版本中，当 Activity 被回收时会依次触发：
```
com.kongzue.dialogx.impl.ActivityLifecycleImpl#onActivityPreDestroyed()
接着触发
com.kongzue.dialogx.interfaces.BaseDialog#recycleDialog()
接着触发
com.kongzue.dialogx.dialogs.WaitDialog#cleanInstance()
```
`WaitDialog#cleanInstance` 会对所有引用进行清理。此操作在使用 DIALOG_FRAGMENT 模式时有效，原因是在 View 实现模式情况下理论上随着 DialogXBaseRelativeLayout 被卸载，不应该还存在持续的引用，`DialogXBaseRelativeLayout#onDetachedFromWindow` 也会触发对话框的销毁操作。
