### ISSUE TITLE
【BUG反馈】FullScreenDialog0.0.48开始无法往上拉了

### ISSUE THREAD

**Issue by Matcha-xiaobin** [kongzue/DialogX#337]
### 问题描述：
1-> FullScreenDialog，里面放了个标题，然后下面是个recyclerView，上下滑动的，0.0.47是可以通过触摸弹窗内，RV以外的，比如标题部分往上拖伸展到全屏，但是0.0.48开始，到0.0.49.beta2都没有这个功能了，弹窗弹出来的时候是多高就是多高了，这个是就是这么做的，还是bug了？
2-> 0.0.48在win11安卓子系统上会高度异常，根本看不到，即使高度定死了好几百dp，依然看不到,，手机上没事。
有个建议：希望FullScreenDialog内是一个可以上下 滑动的控件时（例如RecyclerView），上下滑动时，可以把弹窗从半个窗口拉到整个窗口，或者从整个窗口拉下来半个窗口，或者拉下来关闭，最好是从全屏往下拉一下先回到半屏，在拉一下再关闭。

### 设备信息：
小米11，魅族20pro，模拟器，win11安卓子系统

### 是否在 Demo 中能复现此问题？
未尝试

### 问题截图/视频
请在此插入佐证问题的截图和视频。

**Comment by kongzue** [comment]
当内容界面接管适配触控事件后 DialogX 根布局是不会再拦截触控事件处理的。如果你的 RecycleView 有实现 ScrollController 接口滑动继承，那么当可以滑动时事件将完全交由 RecycleView 自身进行处理。这个问题会在后续版本尝试处理。
另外关于子系统，DialogX 暂时不确保对它完全支持，BottomDialog/FullScreenDialog的动画事件依赖屏幕高度的计算，如果运行过程中发生了变化可能导致位置出现问题，因此对于动态调整外部窗口宽高时确实可能存在问题。

**Comment by Matcha-xiaobin** [comment]
> 当内容界面接管适配触控事件后 DialogX 根布局是不会再拦截触控事件处理的。如果你的 RecycleView 有实现 ScrollController 接口滑动继承，那么当可以滑动时事件将完全交由 RecycleView 自身进行处理。这个问题会在后续版本尝试处理。 另外关于子系统，DialogX 暂时不确保对它完全支持，BottomDialog/FullScreenDialog的动画事件依赖屏幕高度的计算，如果运行过程中发生了变化可能导致位置出现问题，因此对于动态调整外部窗口宽高时确实可能存在问题。

了解了。但，0.0.49.beta2即使我拖动非RecyclerView的区域也无法往上拖动了，只能往下拖动关闭

**Comment by kongzue** [comment]
相关修复代码已提交：https://github.com/kongzue/DialogX/commit/6837bdc2834a2ebfb1b222e629834655e8c64cff 等待后续版本更新。

**Comment by Matcha-xiaobin** [comment]
@kongzue 0.0.49.beta3我尝试了下，似乎还是无法往上拉到全屏（即使我不是触摸在recyclerView上），是本来就这么设定的吗？但是0.0.47似乎不是这样的。

**Comment by kongzue** [comment]
提交的代码还未更新发布最新测试版本。
经过Demo测试是完美符合要求的，在打开一个拥有滚动布局（WebView）的全屏对话框后，滑动网页一段距离，下滑非WebView部分可以操作对话框的移动，测试视频如下：

**Comment by kongzue** [comment]
相关提交代码你可以在这里找到：https://github.com/kongzue/DialogX/commit/6837bdc2834a2ebfb1b222e629834655e8c64cff
最新版本的代码中，针对 BottomDialog、FullScreenDialog 的滑动操作判断不再仅限于 Scroll 布局是否处于顶端（滑动距离=0），而是综合判断了触摸区域是否不是在 Scroll 布局，如果触摸区域不在 Scroll 布局范围内那么会直接滑动对话框。

**Comment by kongzue** [comment]
请更新至最新版本 https://github.com/kongzue/DialogX/releases/tag/0.0.49.beta3

**Comment by Matcha-xiaobin** [comment]
@kongzue 我是用的你最新beta3 fork后在jetpack直接打包的，应该是同样的效果。
目前发现一个问题，Coil图片加载库，启用allowHardware(true)后，FullScreenDialog调起弹窗不再闪退，且没有看到报错，但弹窗弹出后，下沉的activity截图是一个纯白色的图，大概应该是没能截图到activity吧，关闭Coil的allowHardware即可恢复正常。
  然后，关于滑动判定，我觉得我需要详细解释下我的想法：
首先呢，0.0.47版本的时候，FullScreenDialog(没尝试过其它的弹窗，以下简称弹窗)弹出时，如果RecyclerView的高度不是很高的时候（RV的高度是warp_content，但还没有item），弹窗只占小半个屏幕，RV填充数据后，在RV上往上拉，是无法把弹窗拉起到全屏的高度，并且如果RV的内容总高度小于弹窗拉到全屏时的高度，则RV无法滑动，也就是RV上的超出弹窗目前高度的那部分item是无法看到和点击的，但可以通过滑动弹窗内非RV的部分把弹窗拉到全屏。
而从0.0.48开始，弹窗的高度在弹起时固定只有小半个屏幕之后，就无法通过滑动的方式拉到全屏了，并且目前0.0.49.beta3也是如此，不知大佬是否就是这么设计的。
关于我想要的效果：
弹窗弹出时默认一个最小高度，可以考虑自定义，按照百分比（activity或者屏幕高度的百分之多少）的那种，然后可以通过上滑拉到全屏，如果弹窗布局上包含RecyclerView或者NestedScrollView这类子控件时，那么在滑动时，优先判断这个方向是否子控件需要处理滑动，如果不需要，则直接滑动弹窗。
要做到这个，似乎只需要弹窗的顶层布局实现一下NestedScrollingParent接口即可？
大佬可以考虑下这个方案，也许可以做成一个开关，想要这个效果就打开，不想要就维持原来的。
感谢大佬！

**Comment by Matcha-xiaobin** [comment]
@kongzue 补充一下，用你的最新beta3，效果也是一样的。
![image](https://github.com/kongzue/DialogX/assets/5775066/838549b9-19c2-4cad-90e4-2e52e98da1c9)

**Comment by kongzue** [comment]
应该有历史版本更新的原因，DialogX是一个开源项目，更新过程中可能过有很多建议给到我这边，根据建议逐步进行调整，FullScreenDialog 现在的定位就是全屏对话框，逐渐不再考虑半屏的可能性，半屏呈现交由 BottomDialog，而 FullScreenDialog 负责更重的全屏操作。
DialogX 是从外层拦截触摸操作的，关于滑动接口 DialogX 提供了 ScrollController 接口，需要滑动的布局实现这个接口即可，主要需要获取滑动布局的滚动距离作为判断依据以及锁定滚动布局的触摸事件，暂时没有采用 NestedScrollingParent 是因为它过于臃肿。
另外关于 Coil 图片加载库的问题可能需要给 Coil 提交 issues，DialogX 这边只能尽可能的对可能引发问题的代码进行 try catch 来避免崩溃，但这个问题终归不是 DialogX 引发的，DialogX 所使用的所有 API 也都是 Android 的标准接口，因Coil导致运行环境发生变化我这边也无能为力，我这边也没有办法完全处理。

**Comment by Matcha-xiaobin** [comment]
> 应该有历史版本更新的原因，DialogX是一个开源项目，更新过程中可能过有很多建议给到我这边，根据建议逐步进行调整，FullScreenDialog 现在的定位就是全屏对话框，逐渐不再考虑半屏的可能性，半屏呈现交由 BottomDialog，而 FullScreenDialog 负责更重的全屏操作。 DialogX 是从外层拦截触摸操作的，关于滑动接口 DialogX 提供了 ScrollController 接口，需要滑动的布局实现这个接口即可，主要需要获取滑动布局的滚动距离作为判断依据以及锁定滚动布局的触摸事件，暂时没有采用 NestedScrollingParent 是因为它过于臃肿。 另外关于 Coil 图片加载库的问题可能需要给 Coil 提交 issues，DialogX 这边只能尽可能的对可能引发问题的代码进行 try catch 来避免崩溃，但这个问题终归不是 DialogX 引发的，DialogX 所使用的所有 API 也都是 Android 的标准接口，因Coil导致运行环境发生变化我这边也无能为力，我这边也没有办法完全处理。

OK，
其实之所以用FullScreenDialog主要是想要那个背景下沉效果，但既然设计就是如此，那就这样子好了。
