### ISSUE TITLE
【BUG反馈】横屏 dialog 位置不居中 可能隐藏虚拟键盘造成  (之前提交过 改bugs  目前使用0.0.48)

### ISSUE THREAD

**Issue by CPC-Coder** [kongzue/DialogX#338]
## BUG 反馈

请先确认您已阅读[《常见问题》](https://github.com/kongzue/DialogX/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)

### 问题描述：
横屏 dialog 位置不居中 可能隐藏虚拟键盘造成 (之前提交过 改bugs 目前使用0.0.48)

### 问题截图/视频
![微信图片_20230712161524](https://github.com/kongzue/DialogX/assets/26327598/317dcdc7-ffba-4a9a-8487-d9988908d94c)
![微信图片_20230712161529](https://github.com/kongzue/DialogX/assets/26327598/b69a4155-3109-49e7-8993-86f2ef91aa2e)

**Comment by kongzue** [comment]
并非bug。
DialogX的显示位置受限于系统WindowInsets返回的“安全区”，如果系统给定的右侧有非安全区那么DialogX的对话框位置是不会显示到非安全区范围的。
相关代码在：[DialogXBaseRelativeLayout.java:281](https://github.com/kongzue/DialogX/blob/17c61344515a47c3eca2e606a52160cb60128c90/DialogX/src/main/java/com/kongzue/dialogx/util/views/DialogXBaseRelativeLayout.java#L281)

**Comment by CPC-Coder** [comment]
框架外 要怎么处理

**Comment by kongzue** [comment]
我猜测你这个系统的隐藏导航栏的操作并非Android自身API实现，而是后期修改的，那么在修改这个逻辑的时候也要注意确保导航栏是真的去掉的而非“隐藏掉”了，请注意你的第一幅截图中，系统状态栏也依赖了相同的逻辑判断右侧电量图标的位置，很显然，导航栏造成的“非安全区”依然存在，请正确修改系统底层，确保导航栏完全去掉。
