### ISSUE TITLE
【BUG反馈】在Dialog主题的Activity弹出CustomDialog，Activity会偏移

### ISSUE THREAD

**Issue by wangkai9799** [kongzue/DialogX#339]
### 问题描述：
在一个Dialog主题的Activity上，弹出CustomDialog，Dialog主题的Activity会偏移
请在此详细描述问题。

### 设备信息：
任意设备

### 是否在 Demo 中能复现此问题？
是， 第一个页面是全屏的Activity，点击按钮之后弹出的弹窗是一个Dialog主题的Activity，点击Dialog主题的Activity之后弹出的是一个CustomDialog

### 问题截图/视频
请在此插入佐证问题的截图和视频。

https://github.com/kongzue/DialogX/assets/34116538/99116a47-20cf-4e2f-a53d-252071ced445

**Comment by kongzue** [comment]
看视频应该是系统返回了错误的“非安全区”范围，相关代码在：https://github.com/kongzue/DialogX/blob/9f3e2263f25bebecfce6b4d974a9c89ab90becf2/DialogX/src/main/java/com/kongzue/dialogx/util/views/DialogXBaseRelativeLayout.java
DialogX的对话框会根据系统返回的“非安全区”调整对话框的显示范围，如果使用的是CustomDialog，要关掉此功能可以尝试：
```java
.setAutoUnsafePlacePadding(false)
```

**Comment by wangkai9799** [comment]
设置了`setAutoUnsafePlacePadding(false)`还是一样

**Comment by kongzue** [comment]
请确认DialogX基于的activity的屏幕范围和位置正确，DialogX的对话框是依赖其父activity进行显示的，并非独立的window，如果父window出现位移或返回了错误的“非安全区”范围，可能导致DialogX的对话框显示位置出错。
