### ISSUE TITLE
使用IOSstyle后报错，默认样式没问题

### ISSUE THREAD

**Issue by Linnnnnn** [kongzue/DialogX#34]
java.lang.AbstractMethodError: abstract method "int com.kongzue.dialogx.interfaces.DialogXStyle$WaitTipRes.overrideWaitLayout(boolean)"

    private fun initDialogX() {
        DialogX.init(this)
        DialogX.globalStyle = IOSStyle()
    }
在Application.onCreate()中调用初始化方法

**Comment by kongzue** [comment]
请尽量确保style库和主库DialogX使用同一个版本

**Comment by kongzue** [comment]
长时间未收到回复，暂时关闭此问题，如有疑问可继续回复。
