### ISSUE TITLE
【BUG反馈】WaitingDialog在页面返回时未能够出现

### ISSUE THREAD

**Issue by stars-one** [kongzue/DialogX#343]
## BUG 反馈

请先确认您已阅读[《常见问题》](https://github.com/kongzue/DialogX/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)

### 问题描述：

有页面A和页面B,页面A中有个fragment,由fragment中的按钮点击触发进入到页面B,页面B会给回获得到一个返回的文本string

fragment接收返回的数据并会弹出WaitingDialog,但预期弹窗效果未能出现

**使用的是registerForActivityResult方法进行的页面跳转**

已确认数据是成功返回并执行了相关的处理逻辑,版本是最新版的0.0.49.beta4

```kotlin
 fun addNetworkBookNew(bookUrl: String) {
        WaitDialog.show("解析中,请稍候...")
        //下面逻辑会正常执行
        launch(Dispatchers.IO) {
         }
}
```

### 设备信息：
请在此说明您使用的设备型号、Android 版本等信息以协助我们排查问题

Android11

### 是否在 Demo 中能复现此问题？
未尝试

### 问题截图/视频
请在此插入佐证问题的截图和视频。

**Comment by kongzue** [comment]
请尝试 .show(activity, ...) 启动对话框。具体原因在 [常见问题](https://github.com/kongzue/DialogX/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98#q%E5%AF%B9%E8%AF%9D%E6%A1%86%E9%80%9A%E8%BF%87-log-%E5%8F%AF%E4%BB%A5%E7%9C%8B%E5%88%B0%E6%98%BE%E7%A4%BA%E4%BA%86%E4%BD%86%E5%AE%9E%E9%99%85%E4%B8%8A%E5%9C%A8%E7%95%8C%E9%9D%A2%E4%B8%8A%E4%B8%8D%E6%98%BE%E7%A4%BA) 中说的很清楚了

**Comment by stars-one** [comment]
尝试了下,现在对话框能出来了,但是无法关闭....

在fragment中使用的requireActivity()方法来获取activity

```kotlin

 fun addNetworkBookNew(bookUrl: String, action: ((Book) -> Unit)? = null) {
        WaitDialog.show(requireActivity(), "解析中,请稍候...")

        launch(Dispatchers.IO) {
            delay(1500)
            ThreadUtils.runOnUiThread{
                WaitDialog.dismiss(requireActivity())
            }
}
```

**Comment by kongzue** [comment]
因为WaitDialog是单例存在的，之所以这样做是为了方便和TipDialog进行衔接，fragment中可以获取其绑定的activity进行显示
