### ISSUE TITLE
【BUG反馈】BottomMenu的一些回调里的dialog类型为BottomDialog，导致需要强转一下才能用

### ISSUE THREAD

**Issue by Matcha-xiaobin** [kongzue/DialogX#344]
### 问题描述：
BottomMenu的一些回调里的dialog类型为BottomDialog，导致需要强转一下才能用
public BottomMenu setOkButton(OnDialogButtonClickListener<BottomDialog> OkButtonClickListener)
public BottomMenu setOtherButton(OnDialogButtonClickListener<BottomDialog> OtherButtonClickListener)
public BottomMenu setCustomView(OnBindView<BottomDialog> onBindView)
public BottomMenu setDialogLifecycleCallback(DialogLifecycleCallback<BottomDialog> dialogLifecycleCallback)
public BottomMenu setOnBackPressedListener(OnBackPressedListener<BottomDialog> onBackPressedListener)
虽然但是。。。能换成BottomMenu吗，省一行强转代码。
例如以下情况：
BottomMenu.build()
    .setMenuList(body.data)
    .setOnMenuItemClickListener(object :
         OnMenuItemSelectListener<BottomMenu>() {
    })
    .setMultiSelection()
    .setOkButton(getString(R.string.push_now)) { menu, _ ->
        //由于这个menu对象是个BottomDialog对象，这里需要拿的东西是BottomMenu才有的，需要强转一下
        menu as BottomMenu
        //已选中的
        val onSelectList = menu.selectTextArray
        if (onSelectList.isNullOrEmpty()) {
        } else {
        }
        true
    }
    .show()

### 问题截图/视频
![image](https://github.com/kongzue/DialogX/assets/5775066/9ddc26fb-6c93-40b2-bbdb-60598898d12a)

**Comment by kongzue** [comment]
这是Java的问题，重写方法是没办法调整参数包含的泛型的，这个确实没辙，比如BottomDialog和BottomMenu都具有相同名称的方法 `setOkButton(...)` 时，参数 `OnDialogButtonClickListener<BottomDialog>` 泛型必须相同，不然就会报错：
<img width="1311" alt="image" src="https://github.com/kongzue/DialogX/assets/10115359/1c3d4ec4-345e-4f1c-a9a0-c6ba930a21d3">
此问题之所以在 InputDialog 上不存在的原因是 InputDialog 的按钮回调采用了非相同的参数类型进行绑定：`setOkButton(OnInputDialogButtonClickListener<InputDialog> okButtonClickListener)`
其中，OnInputDialogButtonClickListener 和 OnDialogButtonClickListener 都是 BaseOnDialogClickCallback 接口的子类，而 BottomDialog 和 BottomMenu 的按钮参数实际上是一致的。
此问题依然会尝试改进，但不会对现有的参数进行修改以避免普遍使用的兼容性问题。

**Comment by kongzue** [comment]
最新提交的代码已经尝试做出如下调整：
- 对 BottomMenu 的 setOkButton、setCancelButton、setOtherButton 提供了单独的 OnBottomMenuButtonClickListener 参数接口，可直接提供 BottomMenu 参数的 onClick 回调事件；
具体修改可参考：https://github.com/kongzue/DialogX/commit/79f43297f4483e0a817fc04c0f7659f0c2fb4a9c
但对于尚未修改的 OnBindView、OnBackPressedListener 等，因为调整起来需要修改相当多的代码，且可能对现有已上线正在使用的用户产生影响，暂不考虑修改，这种修改主要涉及到需要将原有的接口抽象为一个通用接口，修改为 A extends I，B extends I，而对话框源代码中仅使用 I，在触发事件时又需要根据 I 的类型进行判断单独处理，而 OnBindView 的逻辑更加复杂，不太好调整，这种情况暂时建议还是强转一下。

**Comment by Matcha-xiaobin** [comment]
辛苦啦！
