### ISSUE TITLE
【功能建议】FullScreenDialog还是希望能实现一下NestedScrolling

### ISSUE THREAD

**Issue by Matcha-xiaobin** [kongzue/DialogX#347]
### 需求描述：
FullScreenDialog弹出时，内容是一个 顶部标题 + 列表的界面，列表上的数据是需要请求接口拿到，然后会有一个加载中的占位图，在拿到数据后，FullScreenDialog的高度依然维持在占位图显示的时候的高度，并且无法通过滑动列表把弹窗推上去，让用户看起来就像是弹窗只有这么高，内容只有这么多，实际上有一部分内容需要把弹窗拉上去才能看到，而且，列表已经滑动到顶部了，也无法通过继续下拉列表关闭弹窗，体验确实是差了那么一丢丢，希望能实现一下这个。

**Comment by kongzue** [comment]
尝试直接设置布局高度为match_parent
