### ISSUE TITLE
【BUG反馈】 BottomDialog内容的高度似乎没有固定，导致RecyclerView复用机制没有起作用

### ISSUE THREAD

**Issue by Matcha-xiaobin** [kongzue/DialogX#348]
### 问题描述

BottomDialog内容的高度似乎没有固定，导致RecyclerView复用机制没有起作用，内容几百条，会一次性加载出来，导致卡顿，也许，可以参考下：https://github.com/donkingliang/ConsecutiveScroller 这个库，限定每个子控件最大高度为弹窗容器的最大高度，实现一下NestedScrolling也许是个不错的选择。

### 设备信息

魅族20pro，android 13

### 是否在 Demo 中能复现此问题？

否

### 问题截图/视频

截屏/视频

**Comment by kongzue** [comment]
bottomdialog本身设定上就是按照布局高度去显示的，建议指定具体的布局内容高度，另外滑动管理是由外层布局接管实现的，这是为了保证衔接，具体的请参考wiki
________________________________
发件人: xiaobin ***@***.***>
发送时间: Friday, August 11, 2023 2:45:02 PM
收件人: kongzue/DialogX ***@***.***>
抄送: Subscribed ***@***.***>
主题: [kongzue/DialogX] 【BUG反馈】 BottomDialog内容的高度似乎没有固定，导致RecyclerView复用机制没有起作用 (Issue #348)


问题描述

BottomDialog内容的高度似乎没有固定，导致RecyclerView复用机制没有起作用，内容几百条，会一次性加载出来，导致卡顿，也许，可以参考下：https://github.com/donkingliang/ConsecutiveScroller 这个库，限定每个子控件最大高度为弹窗容器的最大高度，实现一下NestedScrolling也许是个不错的选择。

设备信息

魅族20pro，android 13

是否在 Demo 中能复现此问题？

否

问题截图/视频

截屏/视频

错误日志

No response

―
