### ISSUE TITLE
【BUG反馈】 WaitDialog背景设置

### ISSUE THREAD

**Issue by buxietiaodd** [kongzue/DialogX#349]
### 问题描述

WaitDialog设置背景为什么不生效呢，我想设置背景色为白色，更改进度条和文字颜色。但是设置却不生效。需要怎么设置呢？WaitDialog.show("123456").setBackgroundColor(Color.WHITE); 

### 设备信息

android 11

### 是否在 Demo 中能复现此问题？

是

### 问题截图/视频

![image](https://github.com/kongzue/DialogX/assets/24433035/616c0717-e40e-4bb0-b0f2-9545d831b705)

**Comment by kongzue** [comment]
很抱歉，经过确认这确实是一个bug，也感谢你的反馈帮助DialogX变得更好。
这个错误源于之前对iOS主题的修改，早期版本DialogX在WaitDialog/TipDialog对话框的背景中直接使用了BlurView作为基础组件进行背景渲染，在不启用模糊效果时使用染色来完成背景颜色的显示，但这存在一个问题，不使用模糊效果的主题下强行引入了BlurView造成了性能浪费，因此在后续版本中舍弃了默认集成BlurView的操作转为将模糊组件仅应用于iOS主题下，但未对其他主题模式下的背景颜色进行处理，这确实是遗漏。
最新提交的代码中修复了这一问题 https://github.com/kongzue/DialogX/commit/cdf68d7c71053b7392ede57e74abf2789e62c36d
并对所有对话框的 backgroundColor 属性进行了处理，由原先的值为 -1 不生效改为了值为 null 不生效，因为白色的ColorInt值确实为-1。

**Comment by kongzue** [comment]
[0.0.49.beta6](https://github.com/kongzue/DialogX/releases/tag/0.0.49.beta6) 版本已完成构建，请更新至最新版本。
