### ISSUE TITLE
WaitDialog 会在 BottomSheetDialogFragment下面

### ISSUE THREAD

**Issue by hyl87** [kongzue/DialogX#35]
WaitDialog 会在 BottomSheetDialogFragment下面,被遮挡看不见

**Comment by kongzue** [comment]
对的，因为DialogX并非Dialog实现，而是类似于View的实现方式，具体原因在Readme中有写，BottomSheetDialogFragment本质上还是Window实现，DialogX并不能覆盖在其之上

**Comment by kongzue** [comment]
DialogX有单独提供类似功能的BottomDialog，推荐使用

**Comment by kongzue** [comment]
长时间未收到回复暂时关闭此问题，如有疑问可继续留言
