### ISSUE TITLE
【PopTip在显示期间关闭页面，会产生内存泄漏】 

### ISSUE THREAD

**Issue by panzhusheng** [kongzue/DialogX#350]
### 问题描述

PopTip在显示期间关闭页面，会产生内存泄漏

### 设备信息

夜神模拟器Android 7.0

### 是否在 Demo 中能复现此问题？

未尝试

### 问题截图/视频

![image](https://github.com/kongzue/DialogX/assets/93423230/372c7f9d-2c95-4a0c-974f-a299af22bd86)

### 错误日志

```java
┬───
    │ GC Root: System class
    │
    ├─ com.kongzue.dialogx.interfaces.BaseDialog class
    │    Leaking: NO (a class is never leaking)
    │    ↓ static BaseDialog.runningDialogList
    │                        ~~~~~~~~~~~~~~~~~
    ├─ java.util.concurrent.CopyOnWriteArrayList instance
    │    Leaking: UNKNOWN
    │    Retaining 67.7 kB in 1398 objects
    │    ↓ CopyOnWriteArrayList[0]
    │                          ~~~
    ├─ com.kongzue.dialogx.dialogs.PopTip instance
    │    Leaking: UNKNOWN
    │    Retaining 67.7 kB in 1396 objects
    │    ↓ PopTip.dialogView
    │             ~~~~~~~~~~
    ├─ com.kongzue.dialogx.util.views.DialogXBaseRelativeLayout instance
    │    Leaking: YES (View.mContext references a destroyed activity)
    │    Retaining 1.7 kB in 41 objects
    │    View is part of a window view hierarchy
    │    View.mAttachInfo is null (view detached)
    │    View.mID = R.id.box_root
    │    View.mWindowAttachCount = 1
    │    mContext instance of com.example.titlebartest.MainActivity with mDestroyed = true
    │    ↓ View.mContext
```

**Comment by kongzue** [comment]
麻烦使用最新测试版本试一下？我这边无法确认问题的原因

**Comment by kongzue** [comment]
BaseDialog.runningDialogList的元素会在activity关闭时自动清除引用，相关代码执行过程：

[ActivityLifecycleImpl#onActivityPreDestroyed](https://github.com/kongzue/DialogX/blob/48829a9ac1d7cf36272731dcb4a46e9518a2b37d/DialogX/src/main/java/com/kongzue/dialogx/impl/ActivityLifecycleImpl.java)

⬇️

[BaseDialog#recycleDialog](https://github.com/kongzue/DialogX/blob/48829a9ac1d7cf36272731dcb4a46e9518a2b37d/DialogX/src/main/java/com/kongzue/dialogx/interfaces/BaseDialog.java)

不应该存在对话框被持有不回收的情况。

**Comment by panzhusheng** [comment]
更新到了0.0.49.beta6，还是会这样，我在真机上测试不会出现内存泄漏，真机是Android 11，但是在夜神模拟器7.0 和9.0 的Android版本上面都会出现这个情况

**Comment by kongzue** [comment]
我这边是使用的Google Pixel5 Android 14最新测试版系统测试的，没有发现问题，所以需要确认一下原因

**Comment by panzhusheng** [comment]
可能这个问题在较低版本才会出现

**Comment by kongzue** [comment]
我正在排查所有可能性，尝试直接删除掉 PopTip.dialogView 的引用，因为 BaseDialog.dialogView 是弱引用应该没有问题，稍后提交一版代码

**Comment by kongzue** [comment]
@panzhusheng 可否帮忙做一下测试，看看出现问题的设备的 ActivityLifecycleImpl.java#onActivityPreDestroyed 方法是否会执行？

**Comment by panzhusheng** [comment]
确实onActivityPreDestroyed没有执行

**Comment by kongzue** [comment]
了解了，应该是 ActivityLifecycleCallbacks 存在版本差异，那么可以再帮忙看一下 onActivityDestroyed 是否执行？

**Comment by panzhusheng** [comment]
onActivityDestroyed执行了，真机是先执行onActivityPreDestroyed，然后再执行onActivityDestroyed，模拟器就是直接执行onActivityDestroyed，但是都是里面的if (BaseDialog.getTopActivity() == activity) {
            BaseDialog.cleanContext();
        }没有进去，应该是页面跳转获取的activity不一致

**Comment by kongzue** [comment]
ok了解了，感谢，稍后发布新版本

**Comment by panzhusheng** [comment]
好的

**Comment by kongzue** [comment]
麻烦尝试更新到测试版本： 0.0.49.beta7

**Comment by panzhusheng** [comment]
┬───
    │ GC Root: System class
    │
    ├─ com.kongzue.dialogx.interfaces.BaseDialog class
    │    Leaking: NO (a class is never leaking)
    │    ↓ static BaseDialog.runningDialogList
    │                        ~~~~~~~~~~~~~~~~~
    ├─ java.util.concurrent.CopyOnWriteArrayList instance
    │    Leaking: UNKNOWN
    │    Retaining 67.7 kB in 1399 objects
    │    ↓ CopyOnWriteArrayList[0]
    │                          ~~~
    ├─ com.kongzue.dialogx.dialogs.PopTip instance
    │    Leaking: UNKNOWN
    │    Retaining 67.7 kB in 1397 objects
    │    ↓ PopTip.dialogXAnimImpl
    │             ~~~~~~~~~~~~~~~
    ├─ com.kongzue.dialogx.dialogs.PopTip$DialogImpl$9 instance
    │    Leaking: UNKNOWN
    │    Retaining 66.3 kB in 1370 objects
    │    Anonymous subclass of com.kongzue.dialogx.interfaces.DialogXAnimInterface
    │    ↓ PopTip$DialogImpl$9.this$1
    │                          ~~~~~~
    ├─ com.kongzue.dialogx.dialogs.PopTip$DialogImpl instance
    │    Leaking: UNKNOWN
    │    Retaining 66.3 kB in 1369 objects
    │    ↓ PopTip$DialogImpl.boxBody
    │                        ~~~~~~~
    ├─ android.widget.LinearLayout instance
    │    Leaking: YES (View.mContext references a destroyed activity)
    │    Retaining 1.7 kB in 23 objects
    │    View is part of a window view hierarchy
    │    View.mAttachInfo is null (view detached)
    │    View.mID = R.id.box_body
    │    View.mWindowAttachCount = 1
    │    mContext instance of com.example.titlebartest.MainActivity with mDestroyed = true
    │    ↓ View.mContext
    ╰→ com.example.titlebartest.MainActivity instance
    ​     Leaking: YES (ObjectWatcher was watching this because com.example.titlebartest.MainActivity received
    ​     Activity#onDestroy() callback and Activity#mDestroyed is true)
    ​     Retaining 7.6 kB in 215 objects
    ​     key = 2e1d750c-8d78-44ea-a672-55bdd5d9358c
    ​     watchDurationMillis = 12319
    ​     retainedDurationMillis = 7314
    ​     mApplication instance of android.app.Application
    ​     mBase instance of androidx.appcompat.view.ContextThemeWrapper
    ====================================
并且onActivityPreDestroyed没有执行，onActivityDestroyed新增的
if (android.os.Build.VERSION.SDK_INT < android.os.Build.VERSION_CODES.LOLLIPOP) {
            BaseDialog.recycleDialog(activity);
        }也没有执行进去，
这是我的测试代码
findViewById(R.id.button).setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View view) {
                PopTip.show("关闭页面");
                handler.postDelayed(new Runnable() {
                    @Override
                    public void run() {
                        Intent intent=new Intent(MainActivity.this,MainActivity2.class);
                        startActivity(intent);
                        finish();
                    }
                },500);
            }
        });

**Comment by kongzue** [comment]
抱歉这块代码貌似写错了，我重新提交一版

**Comment by kongzue** [comment]
请尝试更新至测试版本：0.0.49.beta8

**Comment by panzhusheng** [comment]
问题解决

**Comment by kongzue** [comment]
好的
