### ISSUE TITLE
【BUG反馈】 自定义弹窗中View.OnKeyListener()不能无法监听按钮事件

### ISSUE THREAD

**Issue by wxw-9527** [kongzue/DialogX#353]
### 问题描述

自定义弹窗中需要监听按钮点击事件，在demo的自定义弹窗示例中加入监听方法，未正确触发回调函数。
![image](https://github.com/kongzue/DialogX/assets/34825527/949aeda6-690b-4a2b-bc1e-a31808134f35)

### 设备信息

小米12

### 是否在 Demo 中能复现此问题？

是

### 问题截图/视频

截屏/视频

**Comment by kongzue** [comment]
可能存在焦点问题，DialogX 弹出对话框后会默认获得焦点以用于判断返回键事件，您可以为您的View设置一个focus状态样式来检查焦点是否获取到。

**Comment by wxw-9527** [comment]
我测试了一下，需要获取焦点的控件不能是根布局。使用自定义弹窗时，假如CustomRecycleView需要获取焦点，该控件外层需要再加一层父布局，需要焦点的控件作为子控件就可以获取到焦点执行其他操作了。
![image](https://github.com/kongzue/DialogX/assets/34825527/7b1821ec-8e77-47ea-9c2b-877cd1c33e82)

**Comment by wxw-9527** [comment]
感谢分享。^_^
