### ISSUE TITLE
【BUG反馈】 关于windows11安卓子系统不能正确弹窗，手机分屏模式下弹窗异常的问题

### ISSUE THREAD

**Issue by Matcha-xiaobin** [kongzue/DialogX#355]
### 问题描述

windows11安卓子系统不能正确弹窗的问题，可以看看能不能解决这个问题？
似乎是定位的问题？使用了屏幕宽高而不是app当前window的？
分屏模式下，处于下半屏幕时，弹窗高度异常，似乎是有个paddingTop，还有一个paddingBottom被错误的设置上去了，
看起来像是padding设置的不对，是不是没有使用WindowInsets来获取状态栏和虚拟导航条，虚拟导航栏的高度？

### 设备信息

oppo R17 (android 10)、windows 11 安卓子系统 (似乎是android 13)

### 是否在 Demo 中能复现此问题？

没有尝试demo

### 问题截图/视频

无

### 错误日志

无

**Comment by kongzue** [comment]
关于安全区的判定代码在：https://github.com/kongzue/DialogX/blob/c7329701d26b6c6c121be539a03b0844810ab79b/DialogX/src/main/java/com/kongzue/dialogx/util/views/DialogXBaseRelativeLayout.java

目前我这边没有测试条件，如果能够协助处理可以直接提交分支合并。

**Comment by Matcha-xiaobin** [comment]
我刚下载源码看了下，确实就是这个的问题，但还没细测，只是把DialogXBaseRelativeLayout 中的paddingView方法注释掉，目前在分屏和win11安卓子系统下都正确弹起了。

**Comment by Matcha-xiaobin** [comment]
提交了 @kongzue  搞了半天梯子才把代码给clone下来，Orz

**Comment by kongzue** [comment]
辛苦了，paddingView方法就是通过各种方式获取 windowInsets 来设置非安全区的，之所以要这样设计主要原因在于解决新版本的输入法弹出的动画支持，如果您可以解决此问题欢迎提交代码进行合并，一同为DialogX的发展做出贡献

**Comment by Matcha-xiaobin** [comment]
你说的输入法弹出动画，是指平滑推上去，而不是生硬的推上去是吗？其实，这个也能实现，只不过我只写了其中一个监听。

**Comment by kongzue** [comment]
感谢你的协助修改，已经合并更新至最新测试版本 [0.0.49.beta12](https://github.com/kongzue/DialogX/releases/tag/0.0.49.beta12)
