### ISSUE TITLE
【功能建议】CustomDialog自定义布局增加自动关闭功能

### ISSUE THREAD

**Issue by k3sc** [kongzue/DialogX#357]
### 需求描述：
在开发大屏应用时，首页需要有多个CustomDialog，是否可以增加一个自动关闭CustomDialog的功能，自定义显示时间，与WaitDialog一样，可以直接setShowDuration，或者现有是否有什么修改可以支持这样的需求？再此，非常感谢您对开源社区做出的贡献。

**Comment by kongzue** [comment]
你好，DialogX属于框架层，不会涉及业务层的功能，如有需要可以考虑使用以下代码进行延时处理：
```java
new Handler(Looper.getMainLooper()).postDelayed(new Runnable() {
    @Override
    public void run() {
        //Todo: 你的业务逻辑
        dialog.dismiss();
    }
},1000); //延迟1000毫秒执行
```

**Comment by k3sc** [comment]
好的，非常感谢
