### ISSUE TITLE
【BUG反馈】 

### ISSUE THREAD

**Issue by septemb22errrr** [kongzue/DialogX#363]
### setBackgroundColor在最新版本0.0.48无效， 在最新beta0.0.49也无效，经过排查， 问题发生在 **0.0.48.beta27 -> 0.0.48.beta28**过程中

MessageDialog messageDialog = MessageDialog.build(IOSStyle.style())
                .setTheme(DialogX.THEME.DARK)
                .setBackgroundColor(ColorUtils.getColor(R.color.gold_color))
                .setTitle(title)
                .setMessage(msg)
                .setCancelTextInfo(new TextInfo().setFontColor(
                        ColorUtils.getColor(R.color.color_dialog_cancel_btn)))
                .setOkTextInfo(new TextInfo().setFontColor(ColorUtils.getColor(R.color.gold_color)))
                .setCancelButton(left, (baseDialog, v) -> listener.onNegativeClick())
                .setOkButton(right, (baseDialog, v) -> listener.onPositiveClick())
                .setCancelable(true);
        messageDialog.show();

### DialogX 版本

0.0.48

### 设备信息

android11

### 是否在 Demo 中能复现此问题？

否

### 问题截图/视频

截屏/视频

**Comment by kongzue** [comment]
已查证此问题仅针对 IOSStyle 主题存在问题，将在下一个测试版本修复
