### ISSUE TITLE
【BUG反馈】 CustomDialog.setAlign在横屏模式下无效

### ISSUE THREAD

**Issue by Linnnnnn** [kongzue/DialogX#364]
### 问题描述

我遇到了... CustomDialog.setAlign在横屏模式下不生效

### DialogX 版本

v0.0.48

### 设备信息

android7.1

### 是否在 Demo 中能复现此问题？

否

### 问题截图/视频

截屏/视频

**Comment by kongzue** [comment]
很抱歉基于最新的beta测试版本未能在 GooglePixel5(Android14)上复现你所描述的问题，请尝试更新到测试版本看看效果，如果无效欢迎继续反馈。
![image](https://github.com/kongzue/DialogX/assets/10115359/937aea7d-db63-4961-a335-bcc6002569ff)

**Comment by Linnnnnn** [comment]
我是在那种定制平板上开发的，现在没弄那个项目，等有空更新测试版试一下
