### ISSUE TITLE
【BUG反馈】 CustomDialog中子布局setOnKeyListener无法触发

### ISSUE THREAD

**Issue by shaoweijie** [kongzue/DialogX#365]
### 问题描述

CustomDialog中子布局setOnKeyListener无法触发

### DialogX 版本

0.0.48

### 设备信息

Android7

### 是否在 Demo 中能复现此问题？

否

### 问题截图/视频

截屏/视频

**Comment by shaoweijie** [comment]
sorry

**Comment by shaoweijie** [comment]
可能是我的原因

**Comment by kongzue** [comment]
问题重复：https://github.com/kongzue/DialogX/issues/353
