### ISSUE TITLE
【BUG反馈】 横屏且隐藏标题栏状态下，弹窗位置偏移

### ISSUE THREAD

**Issue by wxw-9527** [kongzue/DialogX#366]
### 问题描述

调用`getWindow().getDecorView().setSystemUiVisibility(View.SYSTEM_UI_FLAG_FULLSCREEN);`隐藏状态栏，Activity设置为横屏，弹窗位置会发生偏移

### DialogX 版本

0.0.49.beta9

### 设备信息

OPPO K1

### 是否在 Demo 中能复现此问题？

是

### 问题截图/视频

![image](https://github.com/kongzue/DialogX/assets/34825527/a1f44e76-b72b-4e46-a987-869109c13d81)
![image](https://github.com/kongzue/DialogX/assets/34825527/8c731dc1-e60a-427e-8f16-8b615fdae541)

**Comment by kongzue** [comment]
很抱歉未能在最新测试版中复现你所描述的问题，您可以尝试升级至最新测试版本后再试：
图为基于最新beta版本的测试：
![image](https://github.com/kongzue/DialogX/assets/10115359/a1b7e0f4-1379-44f0-9d53-0e3f207a6fd6)
![image](https://github.com/kongzue/DialogX/assets/10115359/0e06a1c6-f756-4639-8ef6-b4d6785547f9)

**Comment by wxw-9527** [comment]
我尝试更新过最新版到0.0.49.beta13版本，但是这个版本使用ViewBinging时，自定义布局的父布局如果不是RelativeLayout会报错。
![image](https://github.com/kongzue/DialogX/assets/34825527/f6d6202b-a163-4159-a234-5b5bc32e2316)
![image](https://github.com/kongzue/DialogX/assets/34825527/ed55a3af-e978-42c1-ac3b-f404d803db16)
![image](https://github.com/kongzue/DialogX/assets/34825527/e1424126-3fe2-4cba-92cf-2a61acfcda00)

**Comment by wxw-9527** [comment]
不使用ViewBinding时，父布局可以是任何非RelativeLayout的ViewGroup

**Comment by kongzue** [comment]
您的堆栈错误并未指向dialogx，它并不是dialogx的错误，因此我无法进行修改和处理
________________________________
发件人: Saxxhw ***@***.***>
发送时间: Monday, September 4, 2023 11:30:45 PM
收件人: kongzue/DialogX ***@***.***>
抄送: Kongzue ***@***.***>; Comment ***@***.***>
主题: Re: [kongzue/DialogX] 【BUG反馈】 横屏且隐藏标题栏状态下，弹窗位置偏移 (Issue #366)


不使用ViewBinding时，父布局可以是任何非RelativeLayout的ViewGroup

―
