### ISSUE TITLE
【BUG反馈】 发送网络请求前使用WaitDialog.show(this,"xxx");提示框没有显示出来

### ISSUE THREAD

**Issue by dengzibo504** [kongzue/DialogX#367]
### 问题描述

我在登陆界面的activity执行WaitDialog.show(this,"登录中，请稍后");
用okhttp发起网络请求（非主线程）的结果回调方法执行WaitDialog.dismiss();
但网络请求不成功时，WaitDialog也无法在界面上显示。

### DialogX 版本

0.0.48

### 设备信息

Android 10

### 是否在 Demo 中能复现此问题？

未尝试

### 问题截图/视频

截屏/视频
![截图20230902170939](https://github.com/kongzue/DialogX/assets/83030669/fb09f91d-c153-4a1a-8f6b-3ad6ac9638b4)

**Comment by kongzue** [comment]
无法复现你所描述的问题，在现有已上线的产品中存在大量的基于okHttp的网络请求且正常使用WaitDialog和TipDialog进行提示的操作，并没有发现任何问题。
请更新至最新的beta版本在DEBUGMODE开启情况下检查你的Logcat是否正常的提示了WaitDialog的show和dismiss过程，如果没有请确认代码被正确的执行，如果有，检查下一步：
尝试确认WaitDialog所呈现的Activity是否正确，例如：
<img width="867" alt="image" src="https://github.com/kongzue/DialogX/assets/10115359/13ec1d8e-adde-4acf-9d50-9f8336388daa">
日志中会打印所呈现的activity，如果有，请尝试在WaitDialog.dismiss指令前的异步线程插入一个Thread.sleep(1000)试试看能不能显示出WaitDialog，因为DialogX的对话框启动过程需要等待主线程响应且存在入场动画，排查是否因为数据返回速度过快导致未能可见就被关闭的情况。

**Comment by dengzibo504** [comment]
确实是，因为数据返回速度过快导致的未能可见就被关闭，太厉害了，感谢
