### ISSUE TITLE
【BUG反馈】 输入对话框点击背景后关闭键盘，再点击背景无法关闭弹窗

### ISSUE THREAD

**Issue by Sunxyao** [kongzue/DialogX#369]
### 问题描述

demo中的输入对话框和其他类型弹窗也会有此问题

### DialogX 版本

0.0.49.beta11

### 设备信息

华为 mate40

### 是否在 Demo 中能复现此问题？

是

**Comment by kongzue** [comment]
此问题将在下一个测试版本被修复。
已确认引发问题的原因是输入框会被绑定获得焦点导致背景层无法触发click，相关修复代码已提交。
