### ISSUE TITLE
底部输入框，点击发布按钮后，软键盘么有关闭

### ISSUE THREAD

**Issue by xiaoerMr** [kongzue/DialogX#37]
使用的是官方dome，华为mate20x  Android10

**Comment by kongzue** [comment]
您好，我这边在Pixel5（Android 12）上进行测试是正常关闭输入法的，不清楚是否是华为修改了输入法的显示或关闭逻辑，我会对此问题继续关注，并寻找解决方案

________________________________
发件人: xiaoerMr ***@***.***>
发送时间: Friday, April 16, 2021 10:36:49 AM
收件人: kongzue/DialogX ***@***.***>
抄送: Subscribed ***@***.***>
主题: [kongzue/DialogX] 底部输入框，点击发布按钮后，软键盘么有关闭 (#37)


使用的是官方dome，华为mate20x

―

**Comment by xiaoerMr** [comment]
其他几个输入框是正常关闭的，是不是你少写了关闭代码

**Comment by kongzue** [comment]
底部对话框并不存在输入框的逻辑，请确认，在Demo中演示的是自定义布局的底部对话框，DialogX并没有提供原生支持的底部输入框功能。
理论上当EditText组件失去焦点或被卸载后，输入法应当关闭。

________________________________
发件人: xiaoerMr ***@***.***>
发送时间: Friday, April 16, 2021 10:43:30 AM
收件人: kongzue/DialogX ***@***.***>
抄送: Kongzue ***@***.***>; Comment ***@***.***>
主题: Re: [kongzue/DialogX] 底部输入框，点击发布按钮后，软键盘么有关闭 (#37)


其他几个输入框是正常关闭的，是不是你少写了关闭代码

―

**Comment by xiaoerMr** [comment]
clone 最新代码看，没有这个问题了
