### ISSUE TITLE
请问可以设置弹窗高度吗

### ISSUE THREAD

**Issue by 1825492258** [kongzue/DialogX#372]
可以设置弹窗的最大的高度的，从底部弹窗的弹窗 根据数据源会变

**Comment by kongzue** [comment]
你可以使用：
```java
.setMaxHeight(dip2px(100))  //限制高度为100dp
```
来限制最大高度，底部对话框的高度本身就是依据内容进行扩展的，具体效果请运行Demo尝试。

**Comment by 1825492258** [comment]
ok，我想问下怎么设置 PopTip.show("刷新成功").iconSuccess(); 从顶部弹出来？？
![image](https://github.com/kongzue/DialogX/assets/16134482/203ee5af-3f8e-4886-91ce-f467f6ecfbe3)
这样不行吗

**Comment by kongzue** [comment]
@1825492258 现在这个已经不可以设置了，顶部弹出的职能已经交给PopNotification实现。
