### ISSUE TITLE
【功能建议】动态更更新自定义Dialog里面的View

### ISSUE THREAD

**Issue by Android-wangmeng** [kongzue/DialogX#374]
## 功能建议
动态更更新自定义Dialog里面的View
### 需求描述：
使用CustomDialog.show()自定义界面，请问怎么动态更新里面的UI呢？

**Comment by kongzue** [comment]
OnBindView的回调onBind中给到你的View就是你自己的自定义布局，View有一个神奇的方法叫做findViewById()传入布局的id就可以获得子布局的实例了。

**Comment by kongzue** [comment]
如果实在不明白可以拉取项目试着在本地打开看看，Demo app里头全都是范例代码
