### ISSUE TITLE
【BUG反馈】 

### ISSUE THREAD

**Issue by Valpha** [kongzue/DialogX#376]
### 问题描述

DialogFragment 实现下，弹出的对话框点击空白区域无法 dismiss，box_root 收不到点击事件

### DialogX 版本

0.0.48

### 设备信息

Android 通用

### 是否在 Demo 中能复现此问题？

是

### 问题截图/视频

截屏/视频

**Comment by Valpha** [comment]
已提 PR @kongzue

**Comment by kongzue** [comment]
已同意合并，感谢你的反馈和贡献🎉
