### ISSUE TITLE
[BUG]底部导航适配问题

### ISSUE THREAD

**Issue by qq380791741** [kongzue/DialogX#38]
![1](https://user-images.githubusercontent.com/31462155/115662328-679e6d80-a371-11eb-8f19-6ed877f60d6a.jpg)
![Uploading 2.jpg…]()

手机开启底部三键导航就会有适配问题

**Comment by kongzue** [comment]
请更新至最新测试版本已修复此问题
https://github.com/kongzue/DialogX/releases/tag/0.0.38.beta5
