### ISSUE TITLE
【BUG反馈】 BottomMenu 点击其余背景地方弹框不会消失

### ISSUE THREAD

**Issue by protectedMan** [kongzue/DialogX#380]
### 问题描述

全局设置了
  //设置为IOS主题
        DialogX.globalStyle =  IOSStyle.style();
        //设置亮色/暗色（在启动下一个对话框时生效）
        DialogX.globalTheme = DialogX.THEME.LIGHT;
        DialogX.tipTheme = DialogX.THEME.LIGHT;
        //开启调试模式，在部分情况下会使用 Log 输出日志信息
        DialogX.DEBUGMODE = isDebug;
        //设置默认提示框及等待框（WaitDialog、TipDialog）默认是否可以关闭
        DialogX.cancelable = false;
        //设置对话框默认标题文字样式
        DialogX.titleTextInfo = new TextInfo().setFontSize(16);
        DialogX.titleTextInfo.setBold(false);
        //设置对话框默认内容文字样式
        DialogX.messageTextInfo  = new TextInfo().setFontSize(15);
        DialogX.backgroundColor = getResources().getColor(R.color.white);
        DialogX.cancelButtonText = "取消";
        //初始化
        DialogX.init(this);
在使用BottomMenu时候设置了setCancelable(true) 底部弹框点击其他区域不会消失

        BottomMenu.show(new String[]{"拍摄", "从手机相册选择"}, new OnMenuItemClickListener<BottomMenu>() {
            @Override
            public boolean onClick(BottomMenu dialog, CharSequence text, int index) {
return false;
            }

        }).setCancelable(true);

### DialogX 版本

正式版0.0.48 和0.0.49.beta17都不能取消

### 设备信息

OPPO K7X Android版本12

### 是否在 Demo 中能复现此问题？

否

### 问题截图/视频

截屏/视频

https://github.com/kongzue/DialogX/assets/17565737/1cdb42b8-3da2-4ce1-9f0c-f6ac39734bbb

**Comment by kongzue** [comment]
很抱歉暂未能在Demo中复现此问题，请先尝试排查背景点击事件是否正常触发：
```java
.setOnBackgroundMaskClickListener(new OnBackgroundMaskClickListener<MessageDialog>() {
    @Override
    public boolean onClick(MessageDialog dialog, View v) {
        //print logs here
        return false;
    }
})
```
如果未能触发，然后可以尝试断点排查 [DialogXBaseRelativeLayout.java:199](https://github.com/kongzue/DialogX/blob/9573f3c5f555e38d8534ac8280ea7f6486d996be/DialogX/src/main/java/com/kongzue/dialogx/util/views/DialogXBaseRelativeLayout.java#L199)的 touch 事件是否正常触发。

**Comment by protectedMan** [comment]
背景点击事件试了未能触发打印

**Comment by protectedMan** [comment]
debug昨天试了 touch没反应   刚刚debug背景又可以打印出 但是运行时候点击又没反应

**Comment by kongzue** [comment]
不清楚原因，确认一下点击事件被什么组件拦截掉导致了此问题，理论上，[DialogXBaseRelativeLayout](https://github.com/kongzue/DialogX/blob/9573f3c5f555e38d8534ac8280ea7f6486d996be/DialogX/src/main/java/com/kongzue/dialogx/util/views/DialogXBaseRelativeLayout.java#L199) 应当能够接收到触摸事件来完成点击关闭的行为，但如你所说猜测应当是有布局或其他因素拦截掉了。
