### ISSUE TITLE
【功能建议】依赖的三方库使用固定版本号，避免使用“2.0.4+”这种动态依赖

### ISSUE THREAD

**Issue by Valpha** [kongzue/DialogX#383]
## 功能建议

> 不推荐使用动态版本号 , 因为在编译程序时 , 不同版本的依赖 , 可能有不同的表现 , 如果后期依赖库更新 , 可能导致之前的版本无法使用 

framework 项目中有依赖此项目的，但 AOSP 编译时无法根据动态依赖解决对应的依赖链。

### 需求：

去掉动态依赖，使用固定版本依赖。在后续有大更新时再升级适配最新的依赖包

**Comment by kongzue** [comment]
可以使用 MavenCental分支，该分支属于稳定版本更新引用组件是非+表示的
