### ISSUE TITLE
一个空指针异常【BUG反馈】 

### ISSUE THREAD

**Issue by a2012s** [kongzue/DialogX#385]
### 问题描述

java.lang.NullPointerException
Attempt to read from field 'com.kongzue.dialogx.util.views.MaxRelativeLayout com.kongzue.dialogx.dialogs.CustomDialog$DialogImpl.boxCustom' on a null object reference
com.kongzue.dialogx.dialogs.CustomDialog$DialogImpl$3.run(CustomDialog.java:225)

### DialogX 版本

0.0.48

### 设备信息

Android 8.1.0,level 27 ROM  vivo/FUNTOUCH CPU架构  arm64-v8a

### 是否在 Demo 中能复现此问题？

这是firebase捕捉到的，手头没有这设备。

### 问题截图/视频

截屏/视频

### 错误日志

```java
java.lang.NullPointerException
Attempt to read from field 'com.kongzue.dialogx.util.views.MaxRelativeLayout com.kongzue.dialogx.dialogs.CustomDialog$DialogImpl.boxCustom' on a null object reference
解析原始
1
com.kongzue.dialogx.dialogs.CustomDialog$DialogImpl$3.run(CustomDialog.java:225)
2
android.os.Handler.handleCallback(Handler.java:790)
3
android.os.Handler.dispatchMessage(Handler.java:99)
4
android.os.Looper.loop(Looper.java:192)
5
android.app.ActivityThread.main(ActivityThread.java:6702)
6
java.lang.reflect.Method.invoke(Native Method)
7
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:549)
8
com.android.internal.os.ZygoteInit.main(ZygoteInit.java:826)
```

**Comment by kongzue** [comment]
请更新至最新测试版本（Jitpack分支）看看问题是否已被解决
