### ISSUE TITLE
【BUG反馈】 BottomDialog与 RecycleView滑动冲突问题

### ISSUE THREAD

**Issue by lsCoding666** [kongzue/DialogX#386]
### 问题描述

关联 https://github.com/kongzue/DialogX/issues/285
<img width="734" alt="image" src="https://github.com/kongzue/DialogX/assets/73888354/cc48dd78-4fad-44ac-a12a-a36aefdfd3a8">
似乎获得 scrollView就三种方法，如果是自定义的 bottomDialog有多个 view，其中一个 view是 recyclerview的话，这个DialogImpl.scrollView就获得不正确，导致调用不到自定义的getScrollDistance。
常见的布局就是一个过滤框+下面一个 recyclerview，在recyclerview实现getScrollDistance不会被调用，简单来说如果xml根布局不是 scrollview就有问题
比如说这个布局 已经在 demo中验证不行
```
<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:id="@+id/dialog_ll"
    android:layout_width="match_parent"
    android:layout_height="wrap_content"
    android:layout_alignParentBottom="true"
    android:background="@color/white"
    android:orientation="vertical">

    <RelativeLayout
        android:id="@+id/dialog_header_rl"
        android:layout_width="match_parent"
        android:layout_height="48dp">

        <TextView
            android:id="@+id/dialog_title_tv"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:layout_centerInParent="true"
            android:text="标题" />

    </RelativeLayout>

    <View
        android:layout_width="match_parent"
        android:layout_height="1dp"
        android:background="#FFF1F2F2" />

    <EditText
        android:id="@+id/etFilter"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:layout_marginHorizontal="8dp"
        android:layout_marginTop="8dp" />

    <com.kongzue.dialogxdemo.custom.recycleview.CustomRecycleView
        android:id="@+id/recycleView"
        android:tag="ScrollController"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:layout_marginHorizontal="1dp"
        android:layout_marginTop="8dp" />


</LinearLayout>
```

### DialogX 版本

0.0.49beta16

### 设备信息

华为平板M6 android 10 红米手机也会有问题Android13

### 是否在 Demo 中能复现此问题？

是

### 问题截图/视频

截屏/视频

**Comment by kongzue** [comment]
请参考 [Q：在 BottomDialog 和 FullScreenDialog 对话框中让自己的滑动布局支持滑动继承](https://github.com/kongzue/DialogX/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98#q%E5%9C%A8-bottomdialog-%E5%92%8C-fullscreendialog-%E5%AF%B9%E8%AF%9D%E6%A1%86%E4%B8%AD%E8%AE%A9%E8%87%AA%E5%B7%B1%E7%9A%84%E6%BB%91%E5%8A%A8%E5%B8%83%E5%B1%80%E6%94%AF%E6%8C%81%E6%BB%91%E5%8A%A8%E7%BB%A7%E6%89%BF)
另外可以通过设置 `.setScrollableWhenContentLargeThanVisibleRange(false)` 来让自定义布局位于DialogX对话框自带的ScrollView外。

**Comment by lsCoding666** [comment]
更新到最新版本确实可以解决这个问题，但是最新版本弹起键盘似乎有问题，还是用的0.48版本，看来只能再等等了

**Comment by kongzue** [comment]
0.0.49.beta19有键盘弹起问题么？可以给一份测试代码么，我这边暂时没有复现问题？

**Comment by lsCoding666** [comment]
晚一点会提供 这周内

**Comment by lsCoding666** [comment]
> 0.0.49.beta19有键盘弹起问题么？可以给一份测试代码么，我这边暂时没有复现问题？

参考代码https://github.com/lsCoding666/DialogxTest/

**Comment by lsCoding666** [comment]
@Matcha-xiaobin 也可以看看

**Comment by lsCoding666** [comment]
androd studio虚拟机 Pixel C平板也会复现问题 所以估计和机型没啥关系

**Comment by lsCoding666** [comment]
![image](https://github.com/kongzue/DialogX/assets/73888354/c664cfc2-eea6-4849-9c9d-38eb6bdf19ad)
![image](https://github.com/kongzue/DialogX/assets/73888354/0fe22084-d085-49f5-9c46-82594cf5544f)

**Comment by Matcha-xiaobin** [comment]
@lsCoding666  大概看了下，没有开启沉浸式，所以顶不起来。这个确实是个问题， @kongzue  我之前有提到过的一点，就是这个问题，如果没有开启沉浸式的话，那个windowInsets回调是不会被系统回调的，所以需要想个办法判断下是否设置了沉浸式。也许可以给个设置项，如果没开沉浸式，就不监听那些回调，直接获取系统栏高度去设置padding好了。

**Comment by kongzue** [comment]
> @lsCoding666 大概看了下，没有开启沉浸式，所以顶不起来。这个确实是个问题， @kongzue 我之前有提到过的一点，就是这个问题，如果没有开启沉浸式的话，那个windowInsets回调是不会被系统回调的，所以需要想个办法判断下是否设置了沉浸式。也许可以给个设置项，如果没开沉浸式，就不监听那些回调，直接获取系统栏高度去设置padding好了。

收到，我明天做一下测试

**Comment by lsCoding666** [comment]
另外提供的代码还有一个宽度设置不生效的原因我也已经知道了并知道了如何正确设置位置和宽度和高度了。原因是
dialog.getDialogImpl().bkg.getChildAt(0);
这句有问题，因为这个获得的child为imgTab，就是那个手柄，导致设置不正确
![image](https://github.com/kongzue/DialogX/assets/73888354/e5eb9e71-39cc-4fed-bf27-0c8b247de8a2)
![image](https://github.com/kongzue/DialogX/assets/73888354/74a7597d-a83d-4fe1-8b3c-95dcbcbd35f4)
实际上我想要的效果是这样
![image](https://github.com/kongzue/DialogX/assets/73888354/49fd552a-4101-4e39-8ef5-925456d2f8fa)
代码r如下
```
    private void showSignDialog() {
        new BottomDialog(new OnBindView<BottomDialog>(R.layout.comit_dialog_addcase_dsr_sign_date) {
            @Override
            public void onBind(BottomDialog dialog, View v) {
                if (dialog.getDialogImpl().imgTab != null) {
                    ((ViewGroup) dialog.getDialogImpl().imgTab.getParent()).removeView(dialog.getDialogImpl().imgTab);
                }
            }
        }).setDialogLifecycleCallback(new BottomDialogSlideEventLifecycleCallback<BottomDialog>() {
            @Override
            public void onShow(BottomDialog dialog) {
                super.onShow(dialog);

                View view3 = dialog.getDialogImpl().boxRoot;
                // 获取视图的LayoutParams
                ViewGroup.LayoutParams params3 = view3.getLayoutParams();
                if (params3 instanceof FrameLayout.LayoutParams) {
                    FrameLayout.LayoutParams layoutParams = (FrameLayout.LayoutParams) params3;
                    int[] location = new int[2];
                    mContext.findViewById(R.id.func_fl).getLocationOnScreen(location);
                    layoutParams.leftMargin = (int) (mContext.findViewById(R.id.func_fl).getWidth()+location[0]);
                    layoutParams.topMargin = 0;
                }
            }
        }).show();
    }
```

**Comment by lsCoding666** [comment]
我刚刚测试了下，将customRecycleView的isLockScroll方法固定返回true，也就是说无论什么时候，在recycleview向下滑动都不混关闭dialog。但是测试下来实际上，弹出键盘后的表现是不对的

https://github.com/kongzue/DialogX/assets/73888354/4f95a65b-7f74-4515-a484-97b7c0ffde9b

**Comment by kongzue** [comment]
请更新至 [0.0.49.beta20测试版本更新](https://github.com/kongzue/DialogX/releases/tag/0.0.49.beta20)
