### ISSUE TITLE
MessageDialog自定义布局的宽度

### ISSUE THREAD

**Issue by LeeLulin** [kongzue/DialogX#39]
MessageDialog中设置自定义布局后，对话框的宽度如何设置呢？
我的应用是强制横屏的，对话框宽度过宽，且不会随自定义布局的宽度而变化，尝试设置 DialogX.dialogMaxWidth 没有效果

**Comment by kongzue** [comment]
稍后会进行测试

**Comment by LeeLulin** [comment]
自定义布局如图
![截屏2021-04-29 下午2 58 23](https://user-images.githubusercontent.com/27431274/116513162-bf058600-a8fb-11eb-9cf6-f357e235960d.png)
使用MessageDialog.setCustomView()设置自定义布局

自定义布局宽度设置成 match_parent ，则是下图效果
![device-2021-04-29-144926](https://user-images.githubusercontent.com/27431274/116513023-8c5b8d80-a8fb-11eb-8bf7-baa393f69dc1.png)

自定义布局设置成 wrap_content ，则是如下效果
![device-2021-04-29-145610副本](https://user-images.githubusercontent.com/27431274/116513107-aac18900-a8fb-11eb-9365-29097480c609.png)
可见对话框的宽度始终固定，不会随布局变化
Dialog最大宽度设置为 DialogX.dialogMaxWidth = 800; 没有效果

请问这是BUG，还是MessageDialog本身不支持这样设置呢？

**Comment by wrs13634194612** [comment]
直接用dialogfragment  自定义布局不就行了

**Comment by kongzue** [comment]
@wrs13634194612  为什么不使用 DialogFragment 文档里都写得很明白了，DialogFragment 依然无法避免 windowLeaked 问题以及一系列的，诸如底部导航栏沉浸式问题等，且 DialogFragment 实际上使用方式并不方便，我在DialogV3这个库中以已经做过了尝试。
若你坚持使用 DialogFragment 请放弃 DialogX 这个框架，它可能不适合你。

**Comment by kongzue** [comment]
很抱歉过了这么久，dialogMaxWidth不生效是一个遗留问题，将会在下一个测试版本修复。

**Comment by kongzue** [comment]
已在0.0.40.beta3版本修复此问题。
