### ISSUE TITLE
【功能建议】请填写标题

### ISSUE THREAD

**Issue by aacai** [kongzue/DialogX#391]
## 功能建议
希望模糊api从renderScript切换到vulkan
### 需求描述：
renderScript的so包过于庞大，希望可以使用更加小的代码库

**Comment by kongzue** [comment]
有相关Demo么？这边会尝试开发对应的解决方案

**Comment by aacai** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。
