### ISSUE TITLE
合规性建议

### ISSUE THREAD

**Issue by jiugeishere** [kongzue/DialogX#392]
### 需求描述：
对于com.kongzue.dialogx.interfaces 包名下的OnBindView 类 有使用java.util.Random作为随机数  涉及使用不安全的随机数生成器,建议使用SecureRandom进行替换 国家合规性有这个要求 麻烦大佬修改下啦！

**Comment by kongzue** [comment]
相关问题的处理代码已经提交，等待下一个测试版本合并更新 https://github.com/kongzue/DialogX/commit/4b7aa7603e5cb100f30b2ed097258bc1d07a8f04

**Comment by kongzue** [comment]
更新已提交，请尝试最新版本 [0.0.49.beta21](https://github.com/kongzue/DialogX/releases/tag/0.0.49.beta21)
