### ISSUE TITLE
【BUG反馈】FullScreenDialog 会被系统顶部状态栏遮盖

### ISSUE THREAD

**Issue by Sunxyao** [kongzue/DialogX#393]
### 问题描述

哈喽，升级到0.0.49.beta20后，FullScreenDialog 会被系统顶部状态栏遮盖，0.0.49.beta11没有问题，看了其他issues，是不是沉浸式的修改导致的

### DialogX 版本

0.0.49.beta20

### 设备信息

华为 mate40

### 是否在 Demo 中能复现此问题？

否

### 问题截图/视频

截屏/视频

**Comment by kongzue** [comment]
很抱歉暂未能在Demo中复现你所描述的问题，测试设备是Google Pixel5（Android 14），请尝试拉取Demo代码并在设备上运行常识，若可以复现，麻烦提供一下Android版本以便排查问题

**Comment by Bruce8hou** [comment]
我也遇到这个情况 FullScreenDialog 直接在屏幕最上面弹出  没有错开状态栏

**Comment by kongzue** [comment]
@Bruce8hou  这边在Google Pixel5（Android 14）、虚拟机（Android 10）测试都没有发现问题，请尝试运行Demo，并排查是否存在使Activity全屏以及其他情况？

**Comment by Sunxyao** [comment]
@kongzue 哈喽，安卓版本是12，可以在demo中复现
1. 修改demo中的targetSdkVersion 为29
2. 在demo中新建一个activity，继承自AppCompatActivity，实现一个FullScreenDialog 全屏对话框 显示一个网页

**Comment by kongzue** [comment]
@Sunxyao 经过测试，当 targetSdkVersion 设置为 29 而系统 API 版本为 31 时，某些新的 API 功能和行为变化可能不会被触发，因为你的应用没有明确告诉系统它已经适配了这些新特性，DialogX 处于 API-30 以上时会使用支持动画的非安全区适配回调方案，如果你将 app 的 targetSdkVersion 设置为 30 以下会导致无法触发此效果，目前的临时解决方案是将你的 app 的 targetSdkVersion 设置到 30 以上。
当然我这边也会尝试适配这种情况，如果可以修复，可能会在下一个测试版本合并更新。

**Comment by kongzue** [comment]
此问题已经在 https://github.com/kongzue/DialogX/releases/tag/0.0.49.beta21 中合并更新处理，当 targetSdkVersion 设置为 29 而系统 API 版本为 31 时采用旧版本兼容方案处理，即不支持动画的非安全区适配方案。

**Comment by Bruce8hou** [comment]
FullScreenDialog 最上端 依然会侵入状态栏,如果设置了maxHeight 下方还会出现很大的一块空白。(下方的空白尺寸和状态栏的宽度相近)

**Comment by Sunxyao** [comment]
@kongzue targetSDK升级到了30，使用bete21版本，FullScreenDialog设置maxHeight后会被键盘顶起，请问如何才能让FullScreenDialog不被键盘顶起呢，beta11版本没有此问题

**Comment by Sunxyao** [comment]
> @kongzue targetSDK升级到了30，使用bete21版本，FullScreenDialog设置maxHeight后会被键盘顶起，请问如何才能让FullScreenDialog不被键盘顶起呢，beta11版本没有此问题

还有设置maxHeight后，弹窗并没有居底部显示
![image](https://github.com/kongzue/DialogX/assets/25925000/f1ef76c2-60cc-482e-81e1-31d370ad2f1d)
