### ISSUE TITLE
【BUG反馈】 

### ISSUE THREAD

**Issue by zaceeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee** [kongzue/DialogX#394]
### 问题描述

比如有两个activity   A和B，从A跳转到B，这时A中弹出一个customdialog（设置了activity，只会在A中显示），然后关闭B回到A，这时候能看到customdialog已经显示了，调用customdialog的dismiss方法，不会触发onDismiss的回调。回调是通过setDialogLifecycleCallback设置的。

### DialogX 版本

0.0.49.beta18

### 设备信息

Android11

### 是否在 Demo 中能复现此问题？

否

### 问题截图/视频

截屏/视频

**Comment by kongzue** [comment]
相关问题的处理代码已经提交，等待下一个测试版本合并更新 https://github.com/kongzue/DialogX/commit/4b7aa7603e5cb100f30b2ed097258bc1d07a8f04

**Comment by kongzue** [comment]
更新已提交，请尝试最新版本 [0.0.49.beta21](https://github.com/kongzue/DialogX/releases/tag/0.0.49.beta21)
