### ISSUE TITLE
JitPack引用依赖下载失败

### ISSUE THREAD

**Issue by wxw-9527** [kongzue/DialogX#395]
### 问题描述

DialogX并没有发现什么bug，不过从JitPack上引用该依赖包的时候一直失败，有其他友友遇到这种情况吗
![image](https://github.com/kongzue/DialogX/assets/34825527/c0275b62-3279-49df-916d-4a68604a4b5a)

### DialogX 版本

0.0.49.beta19

### 设备信息

OPPO K1

### 是否在 Demo 中能复现此问题？

否

### 问题截图/视频

截屏/视频

**Comment by kongzue** [comment]
确认一下网络情况，jitpack仓库地址：https://jitpack.io/#kongzue/DialogX
也可以下载aar手动集成：https://jitpack.io/com/github/kongzue/DialogX/DialogX/0.0.49.beta20/DialogX-0.0.49.beta20.aar
**AAR 包引入方法：**

1) 将 AAR 放入 libs 目录。
2) 在 Module 的 build.gradle 里加入以下代码：
```
build.gradle
repositories{
    flatDir {
        dirs 'libs'
    }
}

implementation(name: 'AAR文件名', ext: 'aar')
```
3) sync即可。

图文详见：https://xiaozhuanlan.com/topic/0647532819

**Comment by wxw-9527** [comment]
感谢回复，我确认网络是没有问题的，下载aar手动集成也解决了DialogX引用的问题。

顺便问一句，大佬您那儿JitPack引用正常么？我自己有一些小工具也放在了JitPack上了，现在基本瘫痪了

**Comment by kongzue** [comment]
我这边网络是北京联通的，一切正常

**Comment by wxw-9527** [comment]
多谢，我再试试其他解决方案 ᕦ(･ㅂ･)ᕤ
