### ISSUE TITLE
【功能建议】BottomDialog 增加默认动画监听

### ISSUE THREAD

**Issue by Bruce8hou** [kongzue/DialogX#397]
## 功能建议
 能否增加show动画的默认监听。
### 需求描述：
在一个对话框内有很多数据 如果在onshow里面进行加载 会造成卡顿，如果能监听动画完成，可以在动画完成后再加载，不影响动画的流畅度。目前只能查找修改动画时间，动画变量是私有，不能添加监听

**Comment by kongzue** [comment]
你可以尝试通过 [完全自定义开启、关闭动画](https://github.com/kongzue/DialogX/wiki/%E9%AB%98%E9%98%B6%E6%89%A9%E5%B1%95%E7%94%A8%E6%B3%95#%E5%AE%8C%E5%85%A8%E8%87%AA%E5%AE%9A%E4%B9%89%E5%BC%80%E5%90%AF%E5%85%B3%E9%97%AD%E5%8A%A8%E7%94%BB) 来进行处理。

另外个人建议通过多线程来解决复杂数据的加载处理流程，对话框布局采用固定高度的占位布局进行实现，大量长数据可以采用RecycleView等方案进行实现，当数据完全加载完成并生成适配器后再转入主线程进行UI替换操作，您可以尝试参考一下我使用 DialogX 实现的 [给未来写封信](https://github.com/kongzue/DialogX/wiki/%E2%9D%A4%EF%B8%8FPowered-By-DialogX#%E7%BB%99%E6%9C%AA%E6%9D%A5%E5%86%99%E5%B0%81%E4%BF%A1) 其中的很多对话框布局实际上相当复杂但依然保证了流畅性。

**Comment by Bruce8hou** [comment]
目前我是按照您说的是这个方法处理的 但是在一些配置比较低的设备上 当数据渲染和动画在同一时间的时候 也会卡顿。目前我是用的延时 或者自定义动画处理的。

**Comment by kongzue** [comment]
默认情况下DialogX采用View模式，这种模式在应对activity本身界面就复杂且对话框内自定义界面也复杂的情况下确实会存在一定的性能问题，但却是问题最少的方案，根本在于生命周期的管理很轻松，作为一个布局可以跟随activity的关闭被卸载，如果实在无法通过我上述描述的方法去优化也可以尝试切换到[其他模式](https://github.com/kongzue/DialogX/wiki/%E9%AB%98%E9%98%B6%E6%89%A9%E5%B1%95%E7%94%A8%E6%B3%95#%E5%AE%9E%E7%8E%B0%E6%A8%A1%E5%BC%8F%E5%AE%9E%E9%AA%8C%E6%80%A7)，但请注意其他模式都是属于实验性的，不排除存在一些细节上的bug。
