### ISSUE TITLE
BottomDialog 自定义布局 中包含 recycleview   recycleview 移除item BottomDialog高度变化异常

### ISSUE THREAD

**Issue by SamSongShan** [kongzue/DialogX#40]
目前解决办法 在OnGlobalLayoutListener  中加入一下代码
 private ViewTreeObserver.OnGlobalLayoutListener onContentViewLayoutChangeListener = new ViewTreeObserver.OnGlobalLayoutListener() {
            @Override
            public void onGlobalLayout() {
                if (boxContent != null) {
                    if (bkg.isChildScrollViewCanScroll() && bottomDialogMaxHeight != 0) {
                        if (bottomDialogMaxHeight <= 1) {
                            bkgEnterAimY = boxBkg.getHeight() - bkg.getHeight() * bottomDialogMaxHeight;
                        } else {
                            bkgEnterAimY = boxBkg.getHeight() - bottomDialogMaxHeight;
                        }
                    } else {
                        bkgEnterAimY = boxBkg.getHeight() - bkg.getHeight();
                    }
                    long exitAnimDurationTemp = 300;

                    ObjectAnimator exitAnim = ObjectAnimator.ofFloat(bkg, "y", bkg.getY(), bkgEnterAimY);
                    exitAnim.setDuration(exitAnimDurationTemp);
                    exitAnim.start();
                 /*   long downTime = SystemClock.uptimeMillis();
                    long eventTime = SystemClock.uptimeMillis() + 100;
                    float x = 0.0f;
                    float y = 0.0f;
                    int metaState = 0;
                    MotionEvent motionEvent = MotionEvent.obtain(
                            downTime,
                            eventTime,
                            MotionEvent.ACTION_MOVE,
                            x,
                            y,
                            metaState
                    );

                    bkg.dispatchTouchEvent(motionEvent);*/

                }
            }
        };

**Comment by kongzue** [comment]
已提交最新代码尝试修复，感谢反馈

**Comment by SamSongShan** [comment]
放在子线程里面  页面感觉再跳动  过度不是很自然

**Comment by kongzue** [comment]
这个就需要联系Google处理了，因为本质上DialogX可以在异步线程执行是原理是post给了mainHandler去操作UI逻辑，若主线程出现卡顿可能造成动画卡顿
