### ISSUE TITLE
【功能建议】希望TipDialog可以设置取消动画的方法

### ISSUE THREAD

**Issue by tnngo** [kongzue/DialogX#401]
## 功能建议
希望TipDialog 类型为 `WaitDialog.TYPE.SUCCESS`、`WaitDialog.TYPE.ERROR`等的时候，可以设置取消动画的方法，虽然TipDialog可以设置进出时间，但是显示后打勾、打差等动画时间对于某些场景业务时间略长。

比如入库扫码后的提示。当所需入库物件入库多的时候，动画很累赘，因为有些扫码结果可能就提示几个字，比如 重复入库、已入库等。这时候操作员一眼就看到结果了，但结果看完后还要再等待打勾、打差等动画结束。
### 需求描述：
希望增加一个全局属性，能取消TipDialog 类型为 `WaitDialog.TYPE.SUCCESS`、`WaitDialog.TYPE.ERROR`等所有动画效果，直接展示打勾、打差等。

**Comment by kongzue** [comment]
衔接动画可以通过 wiki 提供的方案进行修改：
<img width="995" alt="image" src="https://github.com/kongzue/DialogX/assets/10115359/09b74302-129b-4d17-b4f5-6c7262ed2415">
https://github.com/kongzue/DialogX/wiki/%E7%AD%89%E5%BE%85%E6%A1%86-WaitDialog-%E5%92%8C%E6%8F%90%E7%A4%BA%E6%A1%86-TipDialog#%E5%8A%A8%E7%94%BB%E8%A1%94%E6%8E%A5
至于完全取消所有动画效果建议如下：
1. 自定义主题，自己实现 ProgressViewInterface 的实例。
2. 直接采用自定义布局实现，即 `.setCustomView(customImageView)` 其中 customImageView 传入自己需要的图像即可。

**Comment by tnngo** [comment]
@kongzue 非常感谢，效果很不错，虽然打勾、打差等动画还有，但是圈的动画没有了，加上其他设置，使其停留差不多1到1.5秒左右。实际扫码入库再加上提示，整体效率和感观上提高了不少。
