### ISSUE TITLE
【BUG反馈】使用bottomDialog关闭时会出现滚动Recyclerview item情况

### ISSUE THREAD

**Issue by chengzhuangjie** [kongzue/DialogX#402]
https://github.com/kongzue/DialogX/assets/55633807/2b1bb57c-ec01-43a8-9ed0-93aab5e86be7

我的xml布局
<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:background="@color/white"
    android:orientation="vertical">

    <com.hjq.bar.TitleBar
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        app:title="详情"
        app:titleStyle="bold" />

    <com.drake.statelayout.StateLayout
        android:id="@+id/loadview"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:layout_weight="1.0">

        <com.scwang.smart.refresh.layout.SmartRefreshLayout
            android:id="@+id/mSmartRefreshLayout"
            android:layout_width="match_parent"
            android:layout_height="match_parent">

            <LinearLayout
                android:layout_width="match_parent"
                android:layout_height="wrap_content">

                <cn.czj.bbs.widget.sticky.HeaderScrollView
                    android:id="@+id/mHeaderScrollView"
                    android:layout_width="match_parent"
                    android:layout_height="match_parent">

                    <LinearLayout
                        android:layout_width="match_parent"
                        android:layout_height="wrap_content"
                        android:orientation="vertical">

                        <cn.czj.bbs.widget.sticky.StickyLinearLayout
                            android:layout_width="match_parent"
                            android:layout_height="wrap_content"
                            android:orientation="vertical">

                            <cn.czj.bbs.widget.ThemeDetailsView
                                android:id="@+id/mThemeDetailsView"
                                android:layout_width="match_parent"
                                android:layout_height="wrap_content" />

                            <RelativeLayout
                                android:layout_width="match_parent"
                                android:layout_height="50dp"
                                android:background="@color/white"
                                android:gravity="center_vertical"
                                android:paddingHorizontal="20dp"
                                app:isSticky="true">

                                <LinearLayout
                                    android:id="@+id/tvRoot"
                                    android:layout_width="100dp"
                                    android:layout_height="match_parent"
                                    android:gravity="center_vertical"
                                    android:orientation="horizontal">

                                    <TextView
                                        android:id="@+id/tvSwich"
                                        android:layout_width="wrap_content"
                                        android:layout_height="wrap_content"
                                        android:text="最新评论"
                                        android:textColor="#FF17181A"
                                        android:textSize="16sp"
                                        android:textStyle="bold" />

                                    <ImageView
                                        android:layout_width="20dp"
                                        android:layout_height="20dp"
                                        android:layout_toRightOf="@+id/tvRoot"
                                        android:src="@mipmap/ic_xiala" />

                                </LinearLayout>

                                <LinearLayout
                                    android:layout_width="wrap_content"
                                    android:layout_height="match_parent"
                                    android:layout_alignParentRight="true"
                                    android:gravity="center">

                                    <com.hjq.shape.view.ShapeButton
                                        android:layout_width="68dp"
                                        android:layout_height="28dp"
                                        android:gravity="center"
                                        android:text="插眼"
                                        app:shape_radius="999dp"
                                        app:shape_strokeColor="@color/grey"
                                        app:shape_strokeSize="1dp" />

                                </LinearLayout>

                            </RelativeLayout>

                        </cn.czj.bbs.widget.sticky.StickyLinearLayout>

                        <me.jingbin.library.ByRecyclerView
                            android:id="@+id/mRecyclerView"
                            android:layout_width="match_parent"
                            android:layout_height="match_parent"
                            app:layoutManager="androidx.recyclerview.widget.LinearLayoutManager"
                            tools:listitem="@layout/item_comment" />

                    </LinearLayout>
                </cn.czj.bbs.widget.sticky.HeaderScrollView>

            </LinearLayout>

        </com.scwang.smart.refresh.layout.SmartRefreshLayout>

    </com.drake.statelayout.StateLayout>

    <cn.czj.bbs.widget.BaseCommentView
        android:id="@+id/baseCommentView"
        android:layout_width="match_parent"
        android:layout_height="wrap_content" />

</LinearLayout>

**Comment by kongzue** [comment]
DialogX 并没有滚动 activity 布局的相关代码，请检查是否是因为焦点变化引起的滚动布局 `setSelectionFromTop(...)` 相关方法被触发。
