### ISSUE TITLE
请问下 maven 仓库还没同步最新的 0.0.49版本吗【BUG反馈】 

### ISSUE THREAD

**Issue by qvitasoyq** [kongzue/DialogX#403]
### 问题描述

想从maven仓库中引入 但是无法下载0.0.49版本

### DialogX 版本

0.0.49

### 设备信息

samsung SM-G610F

### 是否在 Demo 中能复现此问题？

否

### 问题截图/视频

![image](https://github.com/kongzue/DialogX/assets/16370418/a1f43b18-006b-4bc4-9f0f-96575d431aae)

**Comment by kongzue** [comment]
后台已确认提交
![f5526db398bb1fb09fa700850588adc4](https://github.com/kongzue/DialogX/assets/10115359/8d09d8a6-6810-42f6-a9ea-e7c0233054ca)
可能需要联系 MavenCentral 询问原因。

**Comment by qvitasoyq** [comment]
1.Jitpack源实际引入路径是 implementation 'com.github.kongzue:DialogX:0.0.49' 和文档上的不同所以导致无法引入成功
<img width="1131" alt="image" src="https://github.com/kongzue/DialogX/assets/16370418/fcf82ac3-ff55-4609-b4cd-25992ecef7ff">
2.引入成功后提示重复依赖 在主包有个 DialogXInterface.jar 和其中一个模块重复了 请问要怎么解决呢 @kongzue 
<img width="521" alt="image" src="https://github.com/kongzue/DialogX/assets/16370418/60c46114-7d16-47e5-b49a-b4d29b3de622">

**Comment by kongzue** [comment]
文档是按照 jitpack 给出的引导包名编写的：
相关链接：https://jitpack.io/#kongzue/DialogX/0.0.49
另外不存在“com.github.kongzue:DialogX”这个库

**Comment by qvitasoyq** [comment]
@kongzue 奇怪了 我这边看到的和你发的链接不同 o(╥﹏╥)o  https://jitpack.io/#kongzue/DialogX 
<img width="851" alt="image" src="https://github.com/kongzue/DialogX/assets/16370418/bc2fd739-a310-43e2-835d-97f610d1630e">

**Comment by qvitasoyq** [comment]
<img width="790" alt="image" src="https://github.com/kongzue/DialogX/assets/16370418/431080b1-c8e2-47e5-bfbe-3ea06dc43ea4">

**Comment by kongzue** [comment]
你点一下这个 get 按钮
<img width="736" alt="image" src="https://github.com/kongzue/DialogX/assets/10115359/e8bad544-66ac-420e-81aa-8291ec51649a">

**Comment by qvitasoyq** [comment]
哦哦 这样子 现在正常了 谢谢

**Comment by kongzue** [comment]
实际上点击左侧的 log 日志也可以看到真正的包名
<img width="766" alt="image" src="https://github.com/kongzue/DialogX/assets/10115359/b74ce847-c0d9-44dc-9548-58a8122049eb">

**Comment by ikilobyte** [comment]
坑死了，下载文档的上面0.0.49版本，结果仓库没有，，，文档应该改一下啊！！

**Comment by kongzue** [comment]
不清楚 MavenCentral 什么情况
________________________________
发件人: Sunny ***@***.***>
发送时间: Friday, December 22, 2023 4:50:32 PM
收件人: kongzue/DialogX ***@***.***>
抄送: Kongzue ***@***.***>; Mention ***@***.***>
主题: Re: [kongzue/DialogX] 请问下 maven 仓库还没同步最新的 0.0.49版本吗【BUG反馈】 (Issue #403)


坑死了，下载文档的上面0.0.49版本，结果仓库没有，，，文档应该改一下啊！！

―

**Comment by ikilobyte** [comment]
@kongzue 现在下载了0.0.48版本，用了iOS主题，消息对话框感觉太透明了，能设置不那么透明吗？

**Comment by kongzue** [comment]
猜测是 MavenCentral 那边出啥 bug 了，我重新提交了一次应该是好了
<img width="1709" alt="image" src="https://github.com/kongzue/DialogX/assets/10115359/97656c93-58a5-48ee-810d-738be3f0c868">
@ikilobyte @qvitasoyq
