### ISSUE TITLE
【BUG反馈】 小米手机澎湃OS系统下，按钮点击区域发生错位

### ISSUE THREAD

**Issue by nanayashiki1215** [kongzue/DialogX#404]
### 问题描述

仅在小米澎湃OS系统系列的手机中存在点击按钮无响应的问题，经排查疑似是UI错位导致点击事件失效，点击文字上方能触发点击事件

### DialogX 版本

'com.kongzue.dialog_v3x:dialog:3.2.4'

### 设备信息

小米14pro 

### 是否在 Demo 中能复现此问题？

未尝试

### 问题截图/视频

 用的方法为MessageDialog.show，无论是确定还是取消按钮，点击区域均在文字上方，仅澎湃OS系统有这问题

**Comment by kongzue** [comment]
请确认你所使用的框架是 DialogX 而非 DialogV3，DialogV3 已于两年前停止维护和支持，dialog_v3x是DialogV3的 AndroidX 版本，已经停止更新和维护。
请尽快迁移至 DialogX，对于 V3 存在的问题已经不在提供支持和更新，感谢你的理解。
另可参考：[🔁从 DialogV3 迁移至 DialogX](https://github.com/kongzue/DialogX/wiki/%E4%BB%8E-DialogV3-%E8%BF%81%E7%A7%BB%E8%87%B3-DialogX)

**Comment by nanayashiki1215** [comment]
已将所有代码更新至DialogX，谢谢
