### ISSUE TITLE
【BUG反馈】 圆圈两边 有白线,(大屏幕设备) 急

### ISSUE THREAD

**Issue by CPC-Coder** [kongzue/DialogX#408]
### 问题描述

我遇到了...圆圈两边 有白线,  特别在大屏幕设备上明显

### DialogX 版本

0.0.48

### 设备信息

定制机

### 是否在 Demo 中能复现此问题？

未尝试

### 问题截图/视频

[截屏/视频](https://github.com/kongzue/DialogX/assets/26327598/dc0fc783-bf3f-43f5-ae7e-aa3011bfe6b7)

![微信图片_20231216165022](https://github.com/kongzue/DialogX/assets/26327598/691cf8ba-d45a-43dd-8178-a700f8f6ff39)

![微信图片_20231216165106](https://github.com/kongzue/DialogX/assets/26327598/f12c869a-d2ef-428e-8074-13a420c33893)

### 错误日志

```java
无日志
```

**Comment by kongzue** [comment]
不清楚，感觉是设备系统的 canvas 绘制存在问题。
相关代码在：[ProgressView.jav:182](https://github.com/kongzue/DialogX/blob/53d0c1a88d85c394d708fb2e0c1ef3d98625fda1/DialogX/src/main/java/com/kongzue/dialogx/util/views/ProgressView.java#L182) 是调用 `canvas.drawArc` 绘制的圆环，在我这边测试没有发现类似的问题。

**Comment by kongzue** [comment]
请排查硬件加速是否开启，尝试禁用硬件加速，看看问题是否得到解决：
```java
activityRootView.setLayerType(View.LAYER_TYPE_SOFTWARE, null);
```
或者：
```java
getWindow().setFlags(WindowManager.LayoutParams.FLAG_HARDWARE_ACCELERATED,
                     WindowManager.LayoutParams.FLAG_HARDWARE_ACCELERATED);
```
我这边已排查代码中 Paint 已开启抗锯齿：[ProgressView.java:102](https://github.com/kongzue/DialogX/blob/53d0c1a88d85c394d708fb2e0c1ef3d98625fda1/DialogX/src/main/java/com/kongzue/dialogx/util/views/ProgressView.java#L102) 且圆环是基于 View 的 min(宽,高)-线条粗细 进行绘制的，代码没有异常。
不排除设备系统问题，此代码的渲染显示依赖系统实现，我这边仅能确保代码是准确无误的，且在大部分设备上没有类似的问题反馈
