### ISSUE TITLE
【BUG反馈】弹框位置问题，Window模式，打开globalHoverWindow=true, OPPO 手机上对话框显示位置异常

### ISSUE THREAD

**Issue by nmzhangzg** [kongzue/DialogX#409]
### 问题描述

位置问题，Window模式，打开globalHoverWindow=true, OPPO 手机上对话框显示位置异常，手机为OPPO Reno2  ColorOS11.1 Android 11
0.0.48,0.049都可以再现，官网提供Demo也可以再现，再现流程：1.选择”实现方式“为Window 2.点击”跨界面测试“主要为了打开globalHoverWindow  3.此时点击”对话框“或其他提示框都有位置问题

### DialogX 版本

0.0.48

### 设备信息

OPPO Reno2  ColorOS11.1 Android 11

### 是否在 Demo 中能复现此问题？

是

### 问题截图/视频

截屏/视频
![WechatIMG1903](https://github.com/kongzue/DialogX/assets/5057790/e1ebffad-8ebf-4e60-9c7c-a92acfb59450)
![WechatIMG1902](https://github.com/kongzue/DialogX/assets/5057790/bc38a980-fd78-488b-afec-10fdbb2cca03)
![WechatIMG1901](https://github.com/kongzue/DialogX/assets/5057790/38af4015-ab24-4930-8099-8f63b8f75484)

**Comment by kongzue** [comment]
请先尝试更新到最新测试版本，因代码差异针对老版本的问题不再处理
