### ISSUE TITLE
请问CustomDialog怎么设置背景颜色，

### ISSUE THREAD

**Issue by gzw13999** [kongzue/DialogX#41]
我的视图文件有白色背景 用CustomDialog调用就变成透明了，请问怎么设置背景色呢？

**Comment by kongzue** [comment]
您所描述的问题不存在。
在Demo中进行的测试：
![68d7f28f8976f1ab0f67642f6db9d46](https://user-images.githubusercontent.com/10115359/116501627-de90b480-a8e3-11eb-9684-ddadb934294d.jpg)
如图所示背景颜色生效。
如果您需要全屏，请在布局中设置宽高为`match_parent`后在启动对话框时设置`.setFullScreen(true)`其运行效果如下：
![6879e8dd4354b50927058508abef704](https://user-images.githubusercontent.com/10115359/116501697-113aad00-a8e4-11eb-8851-c4478e49e23a.jpg)
CustomDialog中不存在修改用户自定义View背景的功能。

**Comment by gzw13999** [comment]
![11111111](https://user-images.githubusercontent.com/3364249/116502962-865bb180-a8e7-11eb-912a-84cdb781f528.png)
![2222222222](https://user-images.githubusercontent.com/3364249/116502972-8b206580-a8e7-11eb-9cdc-b0e14cc88d92.png)

很奇怪，前者是使用的AlertDialog

**Comment by kongzue** [comment]
DialogX并不是使用AlertDialog作为实现的，在DialogX的定义中CustomDialog是完全由用户选择并实现界面UI样式的对话框，包括对话框的基底。按照您所描述的，您应当选择MessageDialog设置title、message和按钮均为null后使用自定义布局来进行实现，参考范例：
```
MessageDialog.show(null,null)
        .setCustomView(new OnBindView<MessageDialog>(R.layout.layout_custom_view) {
            @Override
            public void onBind(MessageDialog dialog, View v) {
            
            }
        });
```

**Comment by gzw13999** [comment]
昨天我尝试的时候原本就想用MessageDialog实现，但是发现title无法去除。按照你的代码参考MessageDialog目前可以解决问题。

但是我还是有点好奇我的布局使用CustomDialog为什么会出现那种现象。

**Comment by kongzue** [comment]
这是因为DialogX的CustomDialog希望能够提供完全自定义的方案给开发者，例如异形的对话框，部分弹窗广告可能并不需要额外类似于AlertDialog的带阴影白色的背景实现，CustomDialog本质上是希望能提供一个简单易用的完全自定义对话框方案，也支持从屏幕各个方向弹出和自定义的动画效果

**Comment by gzw13999** [comment]
好的。谢谢。
