### ISSUE TITLE
【BUG反馈】 Android4.4设备上运行时在DialogX.init时崩溃

### ISSUE THREAD

**Issue by CFSB** [kongzue/DialogX#410]
### 问题描述

FATAL EXCEPTION: main
                                                                                                    Process: com.xx, PID: 2223
                                                                                                    java.lang.VerifyError: com/kongzue/dialogx/impl/ActivityLifecycleImpl
                                                                                                     at com.kongzue.dialogx.interfaces.BaseDialog.init(BaseDialog.java:88)
                                                                                                     at com.kongzue.dialogx.DialogX.init(DialogX.java:167)

### DialogX 版本

0.0.48

### 设备信息

C588 4.4.4

### 是否在 Demo 中能复现此问题？

是

### 问题截图/视频

<img width="1037" alt="截屏2023-12-21 16 10 48" src="https://github.com/kongzue/DialogX/assets/40222362/cbc6e29e-c818-4be9-9671-960f517c0cf0">

### 错误日志

```java
Process: com.kongzue.dialogxdemo, PID: 3747
                                                                                                    java.lang.VerifyError: com/kongzue/dialogx/impl/ActivityLifecycleImpl
                                                                                                    	at com.kongzue.dialogx.interfaces.BaseDialog.init(BaseDialog.java:91)
                                                                                                    	at com.kongzue.dialogx.DialogX.init(DialogX.java:167)
                                                                                                    	at com.kongzue.dialogxdemo.App.init(App.java:24)
```

**Comment by kongzue** [comment]
请先尝试更新到最新测试版本，因代码差异针对老版本的问题不再处理
https://github.com/kongzue/DialogX/releases/

**Comment by CFSB** [comment]
google()
        jcenter()
        maven { url "https://jitpack.io"}
        
implementation "om.github.kongzue.DialogX:DialogX:0.0.50.beta2"

Could not find om.github.kongzue.DialogX:DialogX:0.0.50.beta2   是我哪里搞错了吗

**Comment by kongzue** [comment]
这里应该是 com 而不是 om
<img width="187" alt="image" src="https://github.com/kongzue/DialogX/assets/10115359/a125521f-0b10-40dc-b99d-2e8ffe7eac84">

**Comment by CFSB** [comment]
@
![Uploading 截屏2023-12-21 16.46.16.png…]()

**Comment by CFSB** [comment]
已经升级成功了，但是还是一样的错误<img width="1226" alt="截屏2023-12-21 16 46 16" src="https://github.com/kongzue/DialogX/assets/40222362/e2a7a6c0-b7ea-4c4a-9b88-5ed09f4183e2">

**Comment by kongzue** [comment]
你用的是 AndroidX 么？尝试升级一下 appcompat 库的版本试试看？

**Comment by kongzue** [comment]
ActivityLifecycleImpl继承的是Application.ActivityLifecycleCallbacks，这个组件隶属于android.app包，来源于系统，如果系统中没有这个组件可能导致错误

**Comment by CFSB** [comment]
是AndroidX，我之前也升级过 appcompat 库，但是出问题了 就又改回去了
The minCompileSdk (31) specified in a
dependency's AAR metadata (META-INF/com/android/build/gradle/aar-metadata.properties)
is greater than this module's compileSdkVersion (android-28).
Dependency: androidx.appcompat:appcompat:1.4.1.

**Comment by kongzue** [comment]
我正在尝试构建一个4.4 的虚拟机看看能不能复现这个问题，请稍等

**Comment by kongzue** [comment]
emmm...这虚拟机完全跑不起来
<img width="326" alt="image" src="https://github.com/kongzue/DialogX/assets/10115359/73ed7657-a32e-4154-8967-32e828085395">
等跑起来了再做测试吧，现在没办法确定原因，这个错误不是 dialogx 内部代码的错误，应该还是系统版本兼容性的问题，根据最新的开发要求 DialogX 已经更新了 JDK 版本和 targetSdkVersion，不排除跟这其中哪一环节有关，这问题不一定能处理的了

**Comment by kongzue** [comment]
离谱了，删除掉 ActivityLifecycleImpl#init(...) 的所有代码执行竟然依然会蹦，那基本上说明 Application.ActivityLifecycleCallbacks 在 Android 4.4 上有兼容性问题了，这问题我没办法处理
<img width="1999" alt="image" src="https://github.com/kongzue/DialogX/assets/10115359/0ba013e3-22ba-4de5-83f4-f37f42b0c60f">

**Comment by kongzue** [comment]
一个好消息，已通过逐行排查定位原因，在 ActivityLifecycleImpl.java 的 162 行： 
```java
Application.ActivityLifecycleCallbacks.super.onActivityPreResumed(activity); 
```
在旧版本 Android 中可能因为没有onActivityPreResumed事件提供导致的这个类加载异常，删除即可，稍后更新一个测试版本修复此问题

**Comment by kongzue** [comment]
请更新至版本：[0.0.50.beta3](https://github.com/kongzue/DialogX/tree/0.0.50.beta3)

**Comment by CFSB** [comment]
卧槽，太牛逼了  居然真的搞定了！大佬果然是大佬

**Comment by CFSB** [comment]
已解决

**Comment by tokiii** [comment]
真行啊，啥APP还适配到4.4啊
