### ISSUE TITLE
可以设置Dialog为非阻断吗？

### ISSUE THREAD

**Issue by Alex-wen1995** [kongzue/DialogX#411]
我在尝试使用bottomDialog的时候，发现不能设置为非阻断的效果（我想在Dialog显示的时候，点击Dialog外部的控件也得到反馈）

**Comment by kongzue** [comment]
本身不支持，但你可以参考 DialogXSample 的 DrawerBoxDialog 的写法自行实现一个：[DrawerBoxDialog.java](https://github.com/kongzue/DialogXSample/blob/73e13d3083d8c420994777ff0eb9d02d1b3f0a8c/DrawerBox/src/main/java/com/kongzue/drawerbox/DrawerBoxDialog.java)
