### ISSUE TITLE
【BUG反馈】 dialog的宽度非安全区问题

### ISSUE THREAD

**Issue by manitozhang** [kongzue/DialogX#412]
### 问题描述

`WindowInsetsController controller = null;
                if (android.os.Build.VERSION.SDK_INT >= android.os.Build.VERSION_CODES.R) {
                    controller = ((ViewGroup)((ViewGroup)getWindow().getDecorView()).findViewById(android.R.id.content)).getWindowInsetsController();
                    controller.hide(WindowInsets.Type.statusBars());
                    controller.hide(WindowInsets.Type.navigationBars());
                }`

添加这段代码到demo的activity中就会导致dialog的宽度拉不满

### DialogX 版本

0.0.49.beta20

### 设备信息

华为mate30pro

### 是否在 Demo 中能复现此问题？

是

**Comment by kongzue** [comment]
请更新至测试版本：[0.0.50.beta4测试版本更新](https://github.com/kongzue/DialogX/releases/tag/0.0.50.beta4)

**Comment by manitozhang** [comment]
已解决
