### ISSUE TITLE
【BUG反馈】 

### ISSUE THREAD

**Issue by SillyBoy93** [kongzue/DialogX#413]
### 问题描述

将DialogX.onlyOnePopNotification设置成false后，
  PopNotification build = PopNotification.build();
  build.setOnPopNotificationClickListener(new OnDialogButtonClickListener<PopNotification>() {
      @Override
      public boolean onClick(PopNotification dialog, View v) {
          dialog.dismiss();
          return false;
      }
  });
  build.noAutoDismiss();
  build.setTitle(String.format("这是一个提示 %s", count++));
  build.show();

多次调用以上代码，只有最后一个能够响应点击事件

### DialogX 版本

0.0.50.beta3

### 设备信息

OPPO K7x Android12

### 是否在 Demo 中能复现此问题？

否

### 问题截图/视频

截屏/视频

**Comment by kongzue** [comment]
您代码中的count是否是一个全局变量？如果是，那么当事件触发时它的值将指向全局变量最后变化的值

**Comment by SillyBoy93** [comment]
> 您代码中的count是否是一个全局变量？如果是，那么当事件触发时它的值将指向全局变量最后变化的值

这个值是全局的，只是用于区分PopNotification，当上面的代码多次调用后，所有的PopNotification 会重叠在一起，并且只有最后一个PopNotification能响应点击事件

**Comment by kongzue** [comment]
明白了，主要是位置问题对吧，我看了下代码，应该是非安全区回调导致的对话框位置重置了

**Comment by kongzue** [comment]
请更新至测试版本：[0.0.50.beta4测试版本更新](https://github.com/kongzue/DialogX/releases/tag/0.0.50.beta4)
