### ISSUE TITLE
【BUG反馈】 华为p30，鸿蒙3.0.0，使用WaitDialog.show时不转动

### ISSUE THREAD

**Issue by mocn26169** [kongzue/DialogX#414]
### 问题描述

如标题

### DialogX 版本

0.0.50.beta4

### 设备信息

华为p30，鸿蒙3.0.0

### 是否在 Demo 中能复现此问题？

是

### 问题截图/视频

截屏/视频

**Comment by mocn26169** [comment]
卡在第一帧
![image](https://github.com/kongzue/DialogX/assets/4371661/8643938b-7909-4c69-95da-6bed31d211d9)

**Comment by kongzue** [comment]
尚不清楚原因，目前在 Google Pixel5(Android 14)上未能复现，可能需要你帮助排查问题，相关代码在 https://github.com/kongzue/DialogX/blob/master/DialogX/src/main/java/com/kongzue/dialogx/util/views/ProgressView.java，内部逻辑也很简单，通过 canvas 绘制圆弧并控制圆弧的首尾角度，没有复杂的逻辑，你可以通过断点调试以下看看是哪里出现了问题

**Comment by mocn26169** [comment]
> 尚不清楚原因，目前在 Google Pixel5(Android 14)上未能复现，可能需要你帮助排查问题，相关代码在 https://github.com/kongzue/DialogX/blob/master/DialogX/src/main/java/com/kongzue/dialogx/util/views/ProgressView.java ，内部逻辑也很简单，通过 canvas 绘制圆弧并控制圆弧的首尾角度，没有复杂的逻辑，你可以通过断点调试以下看看是哪里出现了问题

经我这边测试，华为p30，鸿蒙3.0.0，ProgressView使用ValueAnimator时不会转动，但是使用RotateAnimation正常转动。应该是系统的问题。

**Comment by kongzue** [comment]
很奇怪，那么是否可以帮忙看一下ValueAnimator返回的值正常么？确定一下是哪个阶段导致的问题。
1. ValueAnimator是否回报了正确的值；
2. 是否是回报后刷新存在问题；

**Comment by mocn26169** [comment]
> 很奇怪，那么是否可以帮忙看一下ValueAnimator返回的值正常么？确定一下是哪个阶段导致的问题。
> 
> 1. ValueAnimator是否回报了正确的值；
> 2. 是否是回报后刷新存在问题；
> 
> 另外，如果可以欢迎提交 PR👏成为合作贡献者

ProgressView在这段代码里面：
                rotateAnimator.addUpdateListener(new ValueAnimator.AnimatorUpdateListener() {
                    @Override
                    public void onAnimationUpdate(ValueAnimator animation) {
                        currentRotateDegrees = (float) animation.getAnimatedValue();
                        Log.e("ProgressView","currentRotateDegrees="+currentRotateDegrees);
                        invalidate();
                    }
                });
                
普通的手机currentRotateDegrees返回值正常：
13:43:29.075 ProgressView            E  currentRotateDegrees=0.0
13:43:29.088 ProgressView            E  currentRotateDegrees=6.2050004
13:43:29.102 ProgressView            E  currentRotateDegrees=12.410001
13:43:29.111 ProgressView            E  currentRotateDegrees=18.25
13:43:29.128 ProgressView            E  currentRotateDegrees=24.455
..................


华为p30，鸿蒙3.0.0的返回值不正常：
13:41:40.911 ProgressView            E  currentRotateDegrees=0.0
13:41:40.912 >>>                     I  styleValue=-1.0<=0 
13:41:40.912 >>>                     I  return defaultValue=45.0
13:41:40.913 >>>                     I  WaitDialog(25a688).show on com.kongzue.dialogxdemo.activity.MainActivity@110b907
13:41:40.915 ProgressView            E  currentRotateDegrees=365.0

**Comment by mocn26169** [comment]
> 很奇怪，那么是否可以帮忙看一下ValueAnimator返回的值正常么？确定一下是哪个阶段导致的问题。
> 
> 1. ValueAnimator是否回报了正确的值；
> 2. 是否是回报后刷新存在问题；
> 
> 另外，如果可以欢迎提交 PR👏成为合作贡献者

ProgressView在这段代码里面：
                rotateAnimator.addUpdateListener(new ValueAnimator.AnimatorUpdateListener() {
                    @Override
                    public void onAnimationUpdate(ValueAnimator animation) {
                        currentRotateDegrees = (float) animation.getAnimatedValue();
                        Log.e("ProgressView","currentRotateDegrees="+currentRotateDegrees);
                        invalidate();
                    }
                });
                
普通的手机currentRotateDegrees返回值正常：
13:43:29.075 ProgressView            E  currentRotateDegrees=0.0
13:43:29.088 ProgressView            E  currentRotateDegrees=6.2050004
13:43:29.102 ProgressView            E  currentRotateDegrees=12.410001
13:43:29.111 ProgressView            E  currentRotateDegrees=18.25
13:43:29.128 ProgressView            E  currentRotateDegrees=24.455
..................


华为p30，鸿蒙3.0.0的返回值不正常：
13:41:40.911 ProgressView            E  currentRotateDegrees=0.0
13:41:40.912 >>>                     I  styleValue=-1.0<=0 
13:41:40.912 >>>                     I  return defaultValue=45.0
13:41:40.913 >>>                     I  WaitDialog(25a688).show on com.kongzue.dialogxdemo.activity.MainActivity@110b907
13:41:40.915 ProgressView            E  currentRotateDegrees=365.0

**Comment by kongzue** [comment]
这就很奇怪了，有可能是系统内的故障，ValueAnimator是系统组件并非 DialogX 提供的，理论上不应该存在这样的问题，我先去查询一下可能引发问题的原因

**Comment by kongzue** [comment]
我尝试使用自定义 DialogXValueAnimator 替代系统的 ValueAnimator，相关代码已提交，你可以测试一下：
请更新版本至 [0.0.50.beta5测试版更新](https://github.com/kongzue/DialogX/releases/tag/0.0.50.beta5)

**Comment by mocn26169** [comment]
> 我尝试使用自定义 DialogXValueAnimator 替代系统的 ValueAnimator，相关代码已提交，你可以测试一下： 请更新版本至 [0.0.50.beta5测试版更新](https://github.com/kongzue/DialogX/releases/tag/0.0.50.beta5)

使用0.0.50.beta5之后可以转动了！
