### ISSUE TITLE
【BUG反馈】 

### ISSUE THREAD

**Issue by YoungNatty** [kongzue/DialogX#415]
### ⚠️ 重要阅读

- [X] 请确保你已升级至 [最新发布的测试版本](https://github.com/kongzue/DialogX/releases)，旧版本存在的问题不再处理。
- [X] 请确保你已在 [已有的issues](https://github.com/kongzue/DialogX/issues?q=is%3Aissue+is%3Aclosed) 中查询过没有类似的问题。
- [X] 请先确认您已阅读[《常见问题》](https://github.com/kongzue/DialogX/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)
- [ ] 如有条件建议尝试拉取整个项目，尝试运行 Demo app，并模拟在 Demo 环境中运行可能存在问题的代码，如果可以复现请提交 issues 并附上复现代码。

### 问题描述

BottomDialog在Android 14 横屏时水平方向不会铺满

### DialogX 版本

0.0.50.beta5

### 设备信息

Pixel 7 Pro API 34 模拟器

### 是否在 Demo 中能复现此问题？

是

### 问题截图/视频

![截屏2024-01-12 16 43 01](https://github.com/kongzue/DialogX/assets/44336595/3da14848-913f-4d07-a6d4-2a48c3247f31)

**Comment by kongzue** [comment]
对话框显示范围取决于“安全区”，这涉及到沉浸式适配相关，系统返回了左侧存在“非安全区”，对话框规避了非安全区来显示 UI，如需关闭，可通过以下代码进行处理：
```java
.setDialogLifecycleCallback(new DialogLifecycleCallback<BottomDialog>() {
    @Override
    public void onShow(BottomDialog dialog) {
        super.onShow(dialog);
        dialog.getDialogImpl().boxRoot.setAutoUnsafePlacePadding(false);
    }
})
```
设置 `setAutoUnsafePlacePadding(false)` 将关闭沉浸式适配，然后需要自行适配沉浸式相关逻辑。

**Comment by YoungNatty** [comment]
好的，谢谢，已成功解决

**Comment by kongzue** [comment]
我在考虑是否添加一个设置，以规避“屏幕左右两侧的非安全区”，如果顺利可能在稍晚提交一个新的测试版本

**Comment by kongzue** [comment]
测试看没问题了。
![IMG_2147](https://github.com/kongzue/DialogX/assets/10115359/a3a81aac-6139-4c35-bffd-f36cae7de5fc)
下个版本设置开启 `DialogX.ignoreUnsafeInsetsHorizontal = true;` 会忽略左右两侧的非安全区

**Comment by kongzue** [comment]
最新代码已提交，请更新至： [0.0.50.beta6测试版本更新](https://github.com/kongzue/DialogX/releases/tag/0.0.50.beta6)
