### ISSUE TITLE
【BUG反馈】 先后弹出两个DIALOG_FRAGMENT形式的CustomDialog，点击周围区域关闭时会引崩溃。

### ISSUE THREAD

**Issue by YaoHoHo** [kongzue/DialogX#416]
### ⚠️ 重要阅读

- [X] 请确保你已升级至 [最新发布的测试版本](https://github.com/kongzue/DialogX/releases)，旧版本存在的问题不再处理。
- [X] 请确保你已在 [已有的issues](https://github.com/kongzue/DialogX/issues?q=is%3Aissue+is%3Aclosed) 中查询过没有类似的问题。
- [X] 请先确认您已阅读[《常见问题》](https://github.com/kongzue/DialogX/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)
- [X] 如有条件建议尝试拉取整个项目，尝试运行 Demo app，并模拟在 Demo 环境中运行可能存在问题的代码，如果可以复现请提交 issues 并附上复现代码。

### 问题描述

先后弹出两个DIALOG_FRAGMENT形式的CustomDialog，点击周围区域关闭时会引崩溃。

### DialogX 版本

0.0.50.Bate7

### 设备信息

三星s23 android14

### 是否在 Demo 中能复现此问题？

否

### 问题截图/视频

![e00ac9d09d2f8750b5fd9014a16faf8d](https://github.com/kongzue/DialogX/assets/20201118/e3620ed3-e005-485a-9336-da3c887cf955)
在demo中复现如上，选择实现方式为DialogFragment，先后弹出两个CustomDialog，点击关闭时，出现崩溃现象。

### 错误日志

```java
java.lang.StackOverflowError
```

**Comment by kongzue** [comment]
不建议在非必要情况下切换到其他实现模式，除了 View 模式外的其他模式均属于实验性的
