### ISSUE TITLE
使用ios的风格时，标题居中没问题，信息没有居中

### ISSUE THREAD

**Issue by libern** [kongzue/DialogX#42]
一句话的时候是layout_gravity=”center“

但还缺少gravity=”center“

当字有好几行的时候，就是居左显示了。。。

**Comment by kongzue** [comment]
这是特性并不是bug。
原因是当多行显示时，若直接采用完全居中的方案，会非常的难看。
你可以在下边的截图进行对比：
![c7c28cd57a78e59058f578fec457f43](https://user-images.githubusercontent.com/10115359/117084166-12068f80-ad79-11eb-92c2-7669651c6438.jpg)
若你所使用的场景必须完全居中，可以暂时使用以下方案：
```
MessageDialog.show("标题", "这是一长段文字的内容。\n当他出现换行时。\n就会显得像\n一首诗。", "确定").setOkButton(new OnDialogButtonClickListener<MessageDialog>() {
    @Override
    public boolean onClick(MessageDialog baseDialog, View v) {
        PopTip.show("点击确定按钮");
        return false;
    }
}).setDialogLifecycleCallback(new DialogLifecycleCallback<MessageDialog>() {
    @Override
    public void onShow(MessageDialog dialog) {
        dialog.getDialogImpl().txtDialogTip.setGravity(Gravity.CENTER);
        super.onShow(dialog);
    }
});
```

**Comment by libern** [comment]
好的，谢谢 ---- 回复的原邮件 ***@***.***>发送日期2021年05月05日 08:09 ***@***.***> ***@***.******@***.***>主题Re: [kongzue/DialogX] 使用ios的风格时，标题居中没问题，信息没有居中 (#42)

这是特性并不是bug。

原因是当多行显示时，若直接采用完全居中的方案，会非常的难看。

你可以在下边的截图进行对比：



若你所使用的场景必须完全居中，可以暂时使用以下方案：

MessageDialog.show("标题", "这是一长段文字的内容。\n当他出现换行时。\n就会显得像\n一首诗。", "确定").setOkButton(new OnDialogButtonClickListener<MessageDialog>() {

    @Override

    public boolean onClick(MessageDialog baseDialog, View v) {

        PopTip.show("点击确定按钮");

        return false;

    }

}).setDialogLifecycleCallback(new DialogLifecycleCallback<MessageDialog>() {

    @Override

    public void onShow(MessageDialog dialog) {

        dialog.getDialogImpl().txtDialogTip.setGravity(Gravity.CENTER);

        super.onShow(dialog);

    }

});





—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

[

{

***@***.***": "http://schema.org",

***@***.***": "EmailMessage",

"potentialAction": {

***@***.***": "ViewAction",

"target": "https://github.com/kongzue/DialogX/issues/42#issuecomment-832334110",

"url": "https://github.com/kongzue/DialogX/issues/42#issuecomment-832334110",

"name": "View Issue"

},

"description": "View this Issue on GitHub",

"publisher": {

***@***.***": "Organization",

"name": "GitHub",

"url": "https://github.com"

}

}

]
