### ISSUE TITLE
【功能建议】关于MessageDialog的功能建议

### ISSUE THREAD

**Issue by Sky-JD** [kongzue/DialogX#422]
### 需求描述：
- MessageDialog的message控件可以添加一个appendMsg的方法用于直接在对话框追加字符
- MessageDialog也可以添加类似于BottomMenu的复选框实现
**(以上均为建议，不合理可不采纳)**

**Comment by kongzue** [comment]
需求 1 在下一个测试版本中已经添加，需求 2 目前还需要些时间。
使用方法：
```java
.appendMessage(CharSequence)
```
在BottomDialog、BottomMenu、InputDialog、MessageDialog、PopNotification、PopTip、TipDialog和WaitDialog中可用。
