### ISSUE TITLE
【BUG反馈】 在Fragmnet中使用BottomMenu.show，背景Mask直接变黑，没有找到设置FragmentManager的方法

### ISSUE THREAD

**Issue by xlk777** [kongzue/DialogX#425]
### ⚠️ 重要阅读

- [X] 请确保你已升级至 [最新发布的测试版本](https://github.com/kongzue/DialogX/releases)，旧版本存在的问题不再处理。
- [X] 请确保你已在 [已有的issues](https://github.com/kongzue/DialogX/issues?q=is%3Aissue+is%3Aclosed) 中查询过没有类似的问题。
- [X] 请先确认您已阅读[《常见问题》](https://github.com/kongzue/DialogX/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)
- [X] 如有条件建议尝试拉取整个项目，尝试运行 Demo app，并模拟在 Demo 环境中运行可能存在问题的代码，如果可以复现请提交 issues 并附上复现代码。

### 问题描述

我遇到了...
![Screenshot_2024-02-29-11-21-14-119_com xiaobei kk_player_app](https://github.com/kongzue/DialogX/assets/64134780/bf7bcfd1-6850-40b2-b63a-1cfa75046341)

### DialogX 版本

0.0.49

### 设备信息

Redmi K40Pro Android 13

### 是否在 Demo 中能复现此问题？

是

### 问题截图/视频

截屏/视频

**Comment by kongzue** [comment]
尚不清楚原因，DialogX 的对话框无论在哪里启动实际上承载对话框的容器默认都是在 activity 上，如果要修改对话框遮罩层的颜色可以通过 .setMaskColor(ColorInt) 来完成。

**Comment by xlk777** [comment]
...
