### ISSUE TITLE
【功能建议】BottomDialog向下滑动关闭灵敏度调整

### ISSUE THREAD

**Issue by syczuan** [kongzue/DialogX#426]
## 功能建议
目前向下滑动关闭灵敏度太高，希望能提供配置调整
### 需求描述：
BottomDialog向下滑动时，可见布局高度到达指定百分比时，松手才决定是否自动关闭还是回弹
如：设置50%，向下滑动时，可见布局高度在大于50%时，松手后不关闭；小于50%时，松手后自动关闭

**Comment by kongzue** [comment]
您可以看一下 `DialogX.touchSlideTriggerThreshold` 这个属性是目前就有的，触摸滑动触发阈值，影响 BottomDialog、FullScreenDialog 下滑关闭触发距离，单位：像素
