### ISSUE TITLE
BottomMenu在我的魅族魅蓝U20上，高度为全屏

### ISSUE THREAD

**Issue by Linnnnnn** [kongzue/DialogX#43]
BottomMenu.show(contractNameList as List<CharSequence>?)
                    .setCancelButton("取消")
                    .setSelection(contractSelectIndex)
                    .setOnMenuItemClickListener { _, text, index ->
                        btnContract.text = text
                        contractSelectIndex = index
                        return@setOnMenuItemClickListener false
                    }
            }

不知道是不是我的使用方式不对
但是在小米一款手机上正常得

**Comment by kongzue** [comment]
我刚刚更新了最新的版本：0.0.39.beta1
请尝试Demo：http://beta.kongzue.com/DialogXDemo
若Demo也无法正常运行，请告诉我系统版本我会进行测试，若无法复现，请更新至最新测试版后再试。

**Comment by kongzue** [comment]
您好，jCenter已经被bintray停止维护，请尽快切换至jitpack源，具体方法请查阅文档。

**Comment by Linnnnnn** [comment]
有些老旧得库依然依赖jCenter，先关闭吧

**Comment by kongzue** [comment]
加jitpack不影响jCenter啊，两个可以并存的，并没有让你去掉jCenter

**Comment by Linnnnnn** [comment]
Execution failed for task ':app:dataBindingMergeDependencyArtifactsDebug'.
> Could not resolve all files for configuration ':app:debugCompileClasspath'.
   > Could not find com.kongzue.dialogx:DialogX:0.0.39.beta1.
     Required by:
         project :app
   > Could not find com.kongzue.dialogx.style.ios:DialogXIOSStyle:0.0.35.
     Required by:
         project :app

Possible solution:
 - Declare repository providing the artifact, see the documentation at https://docs.gradle.org/current/userguide/declaring_repositories.html

allprojects {
    repositories {
        google()
        jcenter()
//        maven{
//            url 'https://dl.bintray.com/myzchh/maven'
//        }
        maven {
            url "https://maven.aliyun.com/repository/public"
        }
        maven { url 'https://jitpack.io' }
        mavenCentral()
    }
}

**Comment by kongzue** [comment]
请检查网络，猜测是网络原因。
我这边测试以及众多群友都是可以正常引入的。

**Comment by kongzue** [comment]
你可以在这里查看jitpack的包源：https://jitpack.io/#kongzue/DialogX
