### ISSUE TITLE
【功能建议】能否在对话框dismiss之前追加逻辑

### ISSUE THREAD

**Issue by stars-one** [kongzue/DialogX#435]
我想通过PopMenu实现一个下拉菜单选择效果,目前发现如果在生命周期里或onDismiss方法里回调,都会感觉慢一拍(即对话框关闭了才会触发我的后续逻辑)

但是如果我是在选项点击事件里触发,则不会有此问题

**在选项里点击的效果:**

![预览动图](https://github.com/kongzue/DialogX/assets/31400169/9cbb32ad-a189-4221-be4b-d11ee1bb5ab6)

**代码:**
```kotlin
llOption.setOnClickListener {
                iv.animate().rotation(180f).setDuration(200).start()
                PopMenu.show(tvOption, arrayOf("选项1", "选项2", "选项3"))
                    .onDismiss {
                        //这里好像执行似乎是在dismiss之后,如果我想要dismiss之前执行,有无办法?
                        //iv.animate().rotation(0f).setDuration(200).start()
                    }
                    .setOnMenuItemClickListener { dialog, text, index ->
                        //如果在这里,效果就比较好
                        iv.animate().rotation(0f).setDuration(200).start()
                        false
                    }
                    .setOverlayBaseView(false)
                    .alignGravity = Gravity.BOTTOM or Gravity.CENTER_HORIZONTAL
            }
```

如果我在onDismiss方法里执行动画效果,则是下面这个效果(感觉就是dismiss执行后才执行的回调) 

> 因为我需要点击空白处需要触发那个箭头还原的动画,所以才想着在dismiss之前触发我的动画逻辑

![预览动图](https://github.com/kongzue/DialogX/assets/31400169/4c85dd05-ad8d-4925-8eec-8f6a21f96198)

**Comment by kongzue** [comment]
这个目前暂时确实没有，可以当做新需求看待

**Comment by kongzue** [comment]
预计采用的写法如下：
<img width="1251" alt="image" src="https://github.com/kongzue/DialogX/assets/10115359/2e8dc1e2-9978-436d-b0d2-44a4b8cef074">

使用 new 构建对话框对象并复写其 `preDismiss` 方法即可处理刚触发关闭对话框时的事件，请注意，`return true` 表示拦截关闭操作。

相关代码已经提交 Github，等待下个测试版本合并更新，如果急需也可以自行拉取代码打包 aar 使用。
