### ISSUE TITLE
【功能建议】PopTip多个依次提示

### ISSUE THREAD

**Issue by mxdlsm** [kongzue/DialogX#436]
## 功能建议
是否考虑支持PopTip多个的情况依次提示

### 需求描述：
PopTip提示有时候网络请求也好，还是做其他操作的时候，没提示完下一个提示就会覆盖了，想要第一个提示完，在进行提示第二个这种

**Comment by kongzue** [comment]
<img width="1079" alt="image" src="https://github.com/kongzue/DialogX/assets/10115359/4991112a-86da-4cf6-8f4c-0d907b369386">
```java
//限制 PopTip 一次只显示一个实例（关闭后可以同时弹出多个 PopTip）
DialogX.onlyOnePopTip = false;
```

**Comment by mxdlsm** [comment]
谢谢，我找到了这个，他是都会出现在屏幕上，不能提示1彻底展示完再展示提示2对吧？

**Comment by kongzue** [comment]
你提到的是阻塞式显示方式，在 wiki 中有说明如何使用，DialogX.onlyOnePopTip并非阻塞对话框的使用方式，会同时触发多个对话框的同屏显示，之前已经显示的 PopTip 会自动以动画的形式移动位置让开新显示的PopTip，但这也可能导致屏幕被PopTip挤满，如果你需要高频的监看数据变化，实际上持有一个PopTip 对象，并通过修改其 message是更佳的解决方案：
```java
.setMessage("new message")
.showLong();
```

**Comment by kongzue** [comment]
demo 中有演示案例：
<img width="1080" alt="image" src="https://github.com/kongzue/DialogX/assets/10115359/f15dc0e8-3fc6-48ce-b206-975e799cae7b">

**Comment by mxdlsm** [comment]
好的谢谢您，了解了。
