### ISSUE TITLE
【BUG反馈】 BottomMenu设置最低高度没用

### ISSUE THREAD

**Issue by xlk777** [kongzue/DialogX#438]
### ⚠️ 重要阅读

- [X] 请确保你已升级至 [最新发布的测试版本](https://github.com/kongzue/DialogX/releases)，旧版本存在的问题不再处理。
- [X] 请确保你已在 [已有的issues](https://github.com/kongzue/DialogX/issues?q=is%3Aissue+is%3Aclosed) 中查询过没有类似的问题。
- [X] 请先确认您已阅读[《常见问题》](https://github.com/kongzue/DialogX/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)
- [X] 如有条件建议尝试拉取整个项目，尝试运行 Demo app，并模拟在 Demo 环境中运行可能存在问题的代码，如果可以复现请提交 issues 并附上复现代码。

### 问题描述

设置了最低高度弹出还是默认内容的高度

### DialogX 版本

0.0.49

### 设备信息

Redmi K40Pro Android 13

### 是否在 Demo 中能复现此问题？

是

### 问题截图/视频

[
<img width="593" alt="屏幕截图 2024-04-05 032001" src="https://github.com/kongzue/DialogX/assets/64134780/7742f74f-6010-4a45-a6ed-0cdeda120fbc">
](url)
![Screenshot_2024-04-05-03-22-25-662_com xiaobei kk](https://github.com/kongzue/DialogX/assets/64134780/6c14c9d6-96cf-4220-a347-6faf4d6e86ed)

**Comment by kongzue** [comment]
该操作应用于对话框布局的 `setMinimumHeight(int)` 方法，该方法属于 view 的自带方法，至于为何不生效还需调查

**Comment by kongzue** [comment]
请更新至最新版本尝试问题已修复 [0.0.50.beta21](https://github.com/kongzue/DialogX/releases/tag/0.0.50.beta21)
