### ISSUE TITLE
【功能建议】对于同时发起多个网络请求的情况下，有没有适合场景的waitdialog

### ISSUE THREAD

**Issue by lsCoding666** [kongzue/DialogX#439]
进入一个界面时需要同时发起多个网络请求，但是谁先结束是不一定的。导致这种场景下如果一个网络请求跟waitdialog绑定的话，是不合适的（网络请求开始的时候显示dialog，结束的时候关闭是不合适的），因为一个网络请求结束的时候，会把dialog关闭后，其他的网络请求的加载动画就没了。我希望有一个组件，支持多实例，然后支持自定义抗打断，来满足这个场景。

如果用waitdialog的话，那就得自己管理请求，如果正在执行的请求空了才关闭dialog，一方面比较麻烦，另一方面因为不同网络请求的提示文本是不一样的，单例也不能满足这个场景。

**Comment by kongzue** [comment]
此问题属于 app 自身逻辑问题，并非 DialogX 框架的问题，请优化接口调用方式，不建议在每个接口中都启动和关闭 WaitDialog，即便 WaitDialog 不采用单例方案，频繁大量的显示带有遮罩的阻断性提醒也并非用户体验良好的操作，建议优化 app 逻辑以改善用户体验。
