### ISSUE TITLE
【BUG反馈】 空指针异常,非必现, 最新版本是否针对性解决

### ISSUE THREAD

**Issue by manitozhang** [kongzue/DialogX#441]
### ⚠️ 重要阅读

- [X] 请确保你已升级至 [最新发布的测试版本](https://github.com/kongzue/DialogX/releases)，旧版本存在的问题不再处理。
- [X] 请确保你已在 [已有的issues](https://github.com/kongzue/DialogX/issues?q=is%3Aissue+is%3Aclosed) 中查询过没有类似的问题。
- [X] 请先确认您已阅读[《常见问题》](https://github.com/kongzue/DialogX/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)
- [X] 如有条件建议尝试拉取整个项目，尝试运行 Demo app，并模拟在 Demo 环境中运行可能存在问题的代码，如果可以复现请提交 issues 并附上复现代码。

### 问题描述

bugly报错了一些空指针的异常
![image](https://github.com/kongzue/DialogX/assets/35214125/0c1db44d-e0e8-4692-9757-d01e8d09b12b)

### DialogX 版本

0.0.50.beta4

### 设备信息

vivo 系统版本  Android 12,level 31

### 是否在 Demo 中能复现此问题？

否

### 问题截图/视频

截屏/视频

### 错误日志

```java
`#145156 java.lang.NullPointerException
Attempt to invoke virtual method 'android.view.WindowInsetsController android.view.View.getWindowInsetsController()' on a null object reference

com.kongzue.dialogx.util.views.FitSystemBarUtils$5.void onGlobalLayout()(FitSystemBarUtils.java:544)`
```

**Comment by kongzue** [comment]
请更新至最新的测试版本，因代码更新相关代码在 FitSystemBarUtils.java:544 已经无法找到，针对旧版本存在的问题不再处理

**Comment by moguqxiong** [comment]
最新测试版同样会出现一样的问题，FitSystemBarUtils.java:586，这部分getDecorView().getWindowInsetsController()，这个getDecorView()确实可能出现空的情况

**Comment by kongzue** [comment]
getDecorView 为空可能的原因在于您在弹出对话框时并未完成初始化，请确保提前完成了初始化操作：
```java
DialogX.init(context)
```
DialogX 依赖于 activity 界面呈现界面内容，如果您正尝试使用其他实验性的实现方式（DialogX.implIMPLMode不为IMPL_MODE.VIEW）也可能存在影响。

**Comment by manitozhang** [comment]
> getDecorView 为空可能的原因在于您在弹出对话框时并未完成初始化，请确保提前完成了初始化操作：
> 
> ```java
> DialogX.init(context)
> ```
> 
> DialogX 依赖于 activity 界面呈现界面内容，如果您正尝试使用其他实验性的实现方式（DialogX.implIMPLMode不为IMPL_MODE.VIEW）也可能存在影响。

这个是在
