### ISSUE TITLE
【功能建议】可以为DialogX 加入优先级显示吗？

### ISSUE THREAD

**Issue by anypwx** [kongzue/DialogX#442]
## 功能建议
可以为DialogX 加入优先级显示吗？
### 需求描述：
有些需求在多个对话框弹出，需要有一定的先后顺序。比如存在 a b c  三个弹窗，他们显示的顺序是 b  a  c 。c 在最下面， b 在最上面

**Comment by kongzue** [comment]
默认情况下确实不支持，不过您可以尝试将要显示在最顶部的对话框使用 build() 方法构建，设置 dialogImplMode为其他模式来实现优先级的提升。
其原理是默认情况下 DialogX 是使用 View 模式插入到 activity 的界面前进行显示的，但若使用其他构建模式，例如 Window，是绝对优先于 activity 的界面层级显示的，就能实现最高优先级显示的效果。

**Comment by kongzue** [comment]
已在 [0.0.50.beta12](https://github.com/kongzue/DialogX/releases/tag/0.0.50.beta12) 提供。

### 相关更新日志：
- 新增各对话框支持 `get/setThisOrderIndex(int)` 来设置对话框层级，以及 `bringToFront()` 直接置顶对话框；
