### ISSUE TITLE
【BUG反馈】 

### ISSUE THREAD

**Issue by xiansenxuan** [kongzue/DialogX#443]
### ⚠️ 重要阅读

- [X] 请确保你已升级至 [最新发布的测试版本](https://github.com/kongzue/DialogX/releases)，旧版本存在的问题不再处理。
- [X] 请确保你已在 [已有的issues](https://github.com/kongzue/DialogX/issues?q=is%3Aissue+is%3Aclosed) 中查询过没有类似的问题。
- [X] 请先确认您已阅读[《常见问题》](https://github.com/kongzue/DialogX/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)
- [ ] 如有条件建议尝试拉取整个项目，尝试运行 Demo app，并模拟在 Demo 环境中运行可能存在问题的代码，如果可以复现请提交 issues 并附上复现代码。

### 问题描述

我遇到了...
CustomDialog.setAlignBaseViewGravity(view, Gravity.BOTTOM) 里面自定义布局 RecyclerView  
数据量超过界面可 显示高度以后 如30条数据 滑动到底部只能显示出来27条 有3条数据无法显示
（不可显示的数据高度应该刚刚好是弹窗到屏幕顶部的高度）

### DialogX 版本

0.0.49

### 设备信息

蓝叠模拟器

### 是否在 Demo 中能复现此问题？

未尝试

### 问题截图/视频

截屏/视频

### 错误日志

```java
无
```

**Comment by kongzue** [comment]
请尝试使用Layout Inspector来查看布局是否存在问题。
CustomDialog 本身只是一个容器，并不具备控制来自用户自定义布局内容的可显示项或滚动的相关代码，请自行排查可能存在的问题。
