### ISSUE TITLE
BottomMenu能否增加禁用选项的功能

### ISSUE THREAD

**Issue by wxw-9527** [kongzue/DialogX#444]
## 功能建议
BottomMenu能否增加禁用选项的功能

### 需求描述：
可以传入指定项的下标，禁止单项或多项选中/取消选中，参考material-dialogs

![image](https://github.com/kongzue/DialogX/assets/34825527/05f23af6-68ef-491c-a7a0-84893ffc4e43)

**Comment by kongzue** [comment]
会考虑。
临时替代方案是直接使用 dialog 对象重置选项，例如：
```java
BottomMenu dialog = BottomMenu.show("添加", "查看", "编辑")
        .setIconResIds(R.mipmap.img_dialogx_demo_add, 
                R.mipmap.img_dialogx_demo_view, 
                R.mipmap.img_dialogx_demo_edit);
//替换菜单选项
dialog.setMenus("选项 A", "选项 B");
```

**Comment by wxw-9527** [comment]
感谢回复

**Comment by kongzue** [comment]
相关代码已经提交，等待下一个测试版本合并更新。
0.0.50.beta13：
- BottomMenu/PopMenu 新增 `.enableMenu(int[])`、`.enableMenu(CharSequence[])`、.enableMenu(String[]) 以及 `.disableMenu(int[])`、`.disableMenu(CharSequence[])`、.disableMenu(String[]) 用于将控制菜单是否可用，不可用的菜单将以 40% 透明度显示且点击无效；额外的增加了 `.isMenuItemEnable(int)` 用于判段指定索引的菜单是否可用；

效果如图：
<img width="1078" alt="image" src="https://github.com/kongzue/DialogX/assets/10115359/ea972e8d-a51f-4b46-8450-98f8941d1f74">

使用范例：
```java
.disableMenu(1,3)    //禁用索引值为 1、3 的菜单
//或
.disableMenu("编辑", "删除")    //禁用名称为"编辑"、"删除"的菜单
```
