### ISSUE TITLE
【BUG反馈】 

### ISSUE THREAD

**Issue by xiansenxuan** [kongzue/DialogX#449]
### ⚠️ 重要阅读

- [X] 请确保你已升级至 [最新发布的测试版本](https://github.com/kongzue/DialogX/releases)，旧版本存在的问题不再处理。
- [X] 请确保你已在 [已有的issues](https://github.com/kongzue/DialogX/issues?q=is%3Aissue+is%3Aclosed) 中查询过没有类似的问题。
- [X] 请先确认您已阅读[《常见问题》](https://github.com/kongzue/DialogX/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)
- [X] 如有条件建议尝试拉取整个项目，尝试运行 Demo app，并模拟在 Demo 环境中运行可能存在问题的代码，如果可以复现请提交 issues 并附上复现代码。

### 问题描述

我遇到了...Gravity.BOTTOM 设置无效 

自定义VIEW中使用recycleView

VIEW永远都在顶部。并没有跟随点击的view显示在他底部

代码：
CustomDialog.build()
                .setAlignBaseViewGravity(view, Gravity.BOTTOM)
                .setCustomView(new OnBindView<CustomDialog>(R.layout.dialog_recycler) {
                    @Override
                    public void onBind(final CustomDialog dialog, View v) {
                        LRecyclerView recyclerView = v.findViewById(R.id.recyclerView);

                        LinearLayoutManager manager = new LinearLayoutManager(context);
                        recyclerView.setLayoutManager(manager);

                        MyRecyclerViewAdapter mAdapter = new MyRecyclerViewAdapter();
                        ViewUtils.addRecyclerViewAdapter(recyclerView, mAdapter);
                        ViewUtils.addItemDecoration(context,recyclerView);

                        mAdapter.addOnItemClickListener(new BaseRecyclerViewAdapter.OnItemClickListener() {
                            @Override
                            public void onItemClick(View view, int position) {

                                if(listener!=null){
                                    listener.onItemClick(view,position);
                                    dialog.dismiss();
                                }
                            }
                        });

                        mAdapter.clearNotify();
                        if(list!=null && list.size()>0){
                            mAdapter.addItemNotify(list);
                        }
                    }
                })
                .show();

<?xml version="1.0" encoding="utf-8"?>
<layout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools">

    <data></data>

        <com.xuan.view.recyclerview.LRecyclerView
            android:id="@+id/recyclerView"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:orientation="vertical"
            android:layout_gravity="center"
            android:scrollbars="none" />

</layout>

### DialogX 版本

0.0.49

### 设备信息

蓝叠模拟器

### 是否在 Demo 中能复现此问题？

否

### 问题截图/视频

截屏/视频

**Comment by kongzue** [comment]
很抱歉在 Demo 中未能复现您描述的问题，设置setAlignBaseViewGravity可以正常生效，请排查是否优于其他原因导致显示位置不正确。
截图如下：
<img width="1961" alt="image" src="https://github.com/kongzue/DialogX/assets/10115359/03a36d67-9aca-4f8f-a8f9-83e9c61197a4">
测试代码如下：
```java
CustomDialog.show(new OnBindView<CustomDialog>(R.layout.layout_custom_dialog_align) {
            private TextView btnSelectPositive;
            @Override
            public void onBind(final CustomDialog dialog, View v) {
                btnSelectPositive = v.findViewById(R.id.btn_selectPositive);
                btnSelectPositive.setOnClickListener(new View.OnClickListener() {
                    @Override
                    public void onClick(View v) {
                        PopTip.show("我知道了");
                        dialog.dismiss();
                    }
                });
            }
        })
        .setCancelable(false)
        .setMaskColor(getResources().getColor(com.kongzue.dialogx.iostheme.R.color.black30))
        .setEnterAnimResId(R.anim.anim_custom_pop_enter)
        .setExitAnimResId(R.anim.anim_custom_pop_exit)
        .setAlignBaseViewGravity(btnCustomDialogAlign, Gravity.BOTTOM | Gravity.CENTER_HORIZONTAL)
        .setBaseViewMarginBottom(-dip2px(45))
        .show();
```
相关测试在 Google Pixel5 Android 14 下调试通过。

**Comment by kongzue** [comment]
另外根据您提交的信息，您并未更新至[最新的测试版本](https://github.com/kongzue/DialogX/releases)进行尝试，旧版本存在的问题不再处理，其次建议在 Demo 代码中尝试调试，如果能够复现此问题请再与我联系

**Comment by xiansenxuan** [comment]
我换成了com.github.kongzue.DialogX:DialogX:0.0.50.beta14 版本也是如此 自定义VIEW里面一个 
        <com.xuan.view.recyclerview.LRecyclerView
            android:id="@+id/recyclerView"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:orientation="vertical"
            android:scrollbars="none" />

显示在顶部并没有在控件下方。

但是我换成0.0.47版本 自定义界面弹出来就是正常显示在下方
但是RecyclerView显示不全了。

**Comment by kongzue** [comment]
目前无法定位问题原因，我这边测试无法复现，如果属于普遍问题等待更多类似问题的反馈

**Comment by xiansenxuan** [comment]
CUSTOMDIALOG 里面 自定义layout放一个 RecyclerView 然后随便加几十个item
展示在某个按钮下面 你试试 就会出现我说的这种问题

**Comment by xiansenxuan** [comment]
![1](https://github.com/kongzue/DialogX/assets/11705011/4638c7f4-9a7f-4dd7-91f8-d90b9cf02b51)


btnCustomDialogAlign.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                CustomDialog.show(new OnBindView<CustomDialog>(R.layout.layout_custom_dialog_align) {

                            private TextView btnSelectPositive;

                            @Override
                            public void onBind(final CustomDialog dialog, View v) {
                                List<CustomRecycleViewAdapter.Data> dataArrayList = new ArrayList<>();
                                dataArrayList.add(new CustomRecycleViewAdapter.Data("Item Text 1"));
                                dataArrayList.add(new CustomRecycleViewAdapter.Data("Item Text 2"));
                                dataArrayList.add(new CustomRecycleViewAdapter.Data("Item Text 3"));
                                dataArrayList.add(new CustomRecycleViewAdapter.Data("Item Text 4"));
                                dataArrayList.add(new CustomRecycleViewAdapter.Data("Item Text 5"));
                                dataArrayList.add(new CustomRecycleViewAdapter.Data("Item Text 6"));
                                dataArrayList.add(new CustomRecycleViewAdapter.Data("Item Text 7"));
                                dataArrayList.add(new CustomRecycleViewAdapter.Data("Item Text 8"));
                                dataArrayList.add(new CustomRecycleViewAdapter.Data("Item Text 9"));
                                dataArrayList.add(new CustomRecycleViewAdapter.Data("Item Text 10"));
                                dataArrayList.add(new CustomRecycleViewAdapter.Data("Item Text 11"));
                                dataArrayList.add(new CustomRecycleViewAdapter.Data("Item Text 12"));
                                dataArrayList.add(new CustomRecycleViewAdapter.Data("Item Text 13"));
                                dataArrayList.add(new CustomRecycleViewAdapter.Data("Item Text 14"));
                                RecyclerView recyclerView = (RecyclerView) v.findViewById(R.id.recyclerView);
                                LinearLayoutManager layoutManager = new LinearLayoutManager(me);
                                recyclerView.setLayoutManager(layoutManager);
                                CustomRecycleViewAdapter adapter = new CustomRecycleViewAdapter(dataArrayList);
                                adapter.setOnItemClickListener(new AdapterView.OnItemClickListener() {
                                    @Override
                                    public void onItemClick(AdapterView<?> parent, View view, int position, long id) {
                                        PopTip.show(dataArrayList.get(position).getText());
                                        dialog.dismiss();
                                    }
                                });
                                recyclerView.setAdapter(adapter);

                         /*       btnSelectPositive = v.findViewById(R.id.btn_selectPositive);
                                btnSelectPositive.setOnClickListener(new View.OnClickListener() {
                                    @Override
                                    public void onClick(View v) {
                                        PopTip.show("我知道了");
                                        dialog.dismiss();
                                    }
                                });*/
                            }
                        })
                        .setCancelable(false)
                        .setMaskColor(getResources().getColor(com.kongzue.dialogx.iostheme.R.color.black30))
                        .setEnterAnimResId(R.anim.anim_custom_pop_enter)
                        .setExitAnimResId(R.anim.anim_custom_pop_exit)
                        .setAlignBaseViewGravity(btnCustomDialogAlign, Gravity.TOP | Gravity.CENTER_HORIZONTAL)
                        .setBaseViewMarginBottom(-dip2px(45))
                        .show();
            }
        });


这个是改字最新demo里面的自定义的一段代码 我把之前的“我知道了“ 改成了 RecycleView 你看看效果 就是不对了

**Comment by kongzue** [comment]
很抱歉依然未能复现您所描述的问题，经过测试CustomDialog显示位置正确，测试代码如下：
```java
CustomDialog.show(new OnBindView<CustomDialog>(R.layout.layout_custom_recycleview) {
            @Override
            public void onBind(CustomDialog dialog, View v) {
                v.setBackgroundColor(Color.WHITE);
                List<CustomRecycleViewAdapter.Data> dataArrayList = new ArrayList<>();
                dataArrayList.add(new CustomRecycleViewAdapter.Data("Item Text 1"));
                dataArrayList.add(new CustomRecycleViewAdapter.Data("Item Text 2"));
                dataArrayList.add(new CustomRecycleViewAdapter.Data("Item Text 3"));
                dataArrayList.add(new CustomRecycleViewAdapter.Data("Item Text 4"));
                dataArrayList.add(new CustomRecycleViewAdapter.Data("Item Text 5"));
                dataArrayList.add(new CustomRecycleViewAdapter.Data("Item Text 6"));
                dataArrayList.add(new CustomRecycleViewAdapter.Data("Item Text 7"));
                dataArrayList.add(new CustomRecycleViewAdapter.Data("Item Text 8"));
                dataArrayList.add(new CustomRecycleViewAdapter.Data("Item Text 9"));
                dataArrayList.add(new CustomRecycleViewAdapter.Data("Item Text 10"));
                dataArrayList.add(new CustomRecycleViewAdapter.Data("Item Text 11"));
                dataArrayList.add(new CustomRecycleViewAdapter.Data("Item Text 12"));
                dataArrayList.add(new CustomRecycleViewAdapter.Data("Item Text 13"));
                dataArrayList.add(new CustomRecycleViewAdapter.Data("Item Text 14"));
                RecyclerView recyclerView = (RecyclerView) v;
                LinearLayoutManager layoutManager = new LinearLayoutManager(me);
                recyclerView.setLayoutManager(layoutManager);
                CustomRecycleViewAdapter adapter = new CustomRecycleViewAdapter(dataArrayList);
                adapter.setOnItemClickListener(new AdapterView.OnItemClickListener() {
                    @Override
                    public void onItemClick(AdapterView<?> parent, View view, int position, long id) {
                        PopTip.show("点击了第 " + position + " 个");
                    }
                });
                recyclerView.setAdapter(adapter);
            }
        })
        .setCancelable(false)
        .setMaskColor(getResources().getColor(com.kongzue.dialogx.iostheme.R.color.black30))
        .setEnterAnimResId(R.anim.anim_custom_pop_enter).setExitAnimResId(R.anim.anim_custom_pop_exit)
        .setAlignBaseViewGravity(btnCustomDialogAlign, Gravity.BOTTOM | Gravity.CENTER_HORIZONTAL)
        .setBaseViewMarginBottom(-dip2px(45))
        .show();
```
测试截图如下：
<img width="1419" alt="image" src="https://github.com/kongzue/DialogX/assets/10115359/01fb4a21-c4ff-4560-befb-451b5c319f42">
相关测试在 Google Pixel5 Android 14 下调试通过。

**Comment by xiansenxuan** [comment]
我知道问题了。
如果使用
CustomDialog.build().setCustomView(new OnBindView<CustomDialog>(R.layout.layout_custom_recycleview) { 会导致位置显示没有生效（包含0.0.47之前是可以生效，之后的无法生效需要使用.show）
直接使用CustomDialog.show()(new OnBindView<CustomDialog>(R.layout.layout_custom_recycleview) { 位置显示是生效的

另外还有一个问题就是上面那个例子 弹出来的列表过长会导致显示不全。
![2024-06-05_115144](https://github.com/kongzue/DialogX/assets/11705011/177a8554-fdaf-489b-9a6b-f4ba80b46c52)
![2](https://github.com/kongzue/DialogX/assets/11705011/9a1d2201-d8fb-4b80-ab08-e1ee15325c99)
![3](https://github.com/kongzue/DialogX/assets/11705011/03b5f16d-720d-4500-99e2-b9ab7dee338e)

**Comment by kongzue** [comment]
经过布局检查可以看到 DialogX 仅改变了自定义布局的位置而并不会修改自定义布局的大小：
<img width="573" alt="image" src="https://github.com/kongzue/DialogX/assets/10115359/29e73e0d-a33e-4ae6-b008-f2d193eaed0e">
可以通过指定自定义布局大小来实现目标需求。
