### ISSUE TITLE
MessageDialog遮罩颜色设置问题

### ISSUE THREAD

**Issue by dengzibo504** [kongzue/DialogX#451]
### 问题描述

 我就想要个深一点的遮罩颜色，设置了boxRoot和bkg的颜色，就是MessageDialog的背景有半透明遮罩而弹窗本身无遮罩，但总是给界面全部上了遮罩

 dialog.setDialogLifecycleCallback(new DialogLifecycleCallback<MessageDialog>() {
            @Override
            public void onShow(MessageDialog dialog) {
                super.onShow(dialog);
                dialog.getDialogImpl().boxButton.setVisibility(View.GONE);//没有确定取消按钮时布局会有多余边距，隐藏该布局
                dialog.setMaskColor(ContextCompat.getColor(activity, R.color.black));
                dialog.getDialogImpl().boxRoot.setAlpha(0.2f);//修改背景遮罩透明度
                dialog.getDialogImpl().bkg.setAlpha(1f);//修改内容透明度
            }

### DialogX 版本

0.0.49

### 设备信息

Android 10

### 是否在 Demo 中能复现此问题？

是

**Comment by kongzue** [comment]
很抱歉没能理解您的需求，如果需要调整遮罩颜色直接使用 `.setMaskColor()` 即可，例如：
```java
//较深的背景遮罩（75% 不透明度的黑）
MessageDialog.show("标题", "这里是正文内容。", "确定")
        .setMaskColor(getColor(R.color.black75));
```
其中颜色定义在 `res/xml/colors.xml` 中:
```xml
<color name="black75">#BF000000</color>
```
其运行效果如图：
<img width="581" alt="image" src="https://github.com/kongzue/DialogX/assets/10115359/76a12bd0-4637-41ba-81c4-ef2adce44a72">

**Comment by dengzibo504** [comment]
谢谢，才知道black75是指不透明度75...

**Comment by wsdydeni** [comment]
怎么去除掉MessageDialog的遮罩，全透明

**Comment by kongzue** [comment]
@wsdydeni `.setBackgroundColor(Color.TRANSPARENT)`
