### ISSUE TITLE
【BUG反馈】 

### ISSUE THREAD

**Issue by foreverTonight** [kongzue/DialogX#452]
### ⚠️ 重要阅读

- [X] 请确保你已升级至 [最新发布的测试版本](https://github.com/kongzue/DialogX/releases)，旧版本存在的问题不再处理。
- [X] 请确保你已在 [已有的issues](https://github.com/kongzue/DialogX/issues?q=is%3Aissue+is%3Aclosed) 中查询过没有类似的问题。
- [X] 请先确认您已阅读[《常见问题》](https://github.com/kongzue/DialogX/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)
- [X] 如有条件建议尝试拉取整个项目，尝试运行 Demo app，并模拟在 Demo 环境中运行可能存在问题的代码，如果可以复现请提交 issues 并附上复现代码。

### 问题描述

当我在一个BaseDialog 中调用显示 WaitDialog.show(R.string.loading_default_messsage) 的时候，加载框会出现在下面被我当前的BaseDialog 挡着

### DialogX 版本

0.0.48

### 设备信息

华为mate30 应该所有的机型都是

### 是否在 Demo 中能复现此问题？

否

**Comment by kongzue** [comment]
请确认您已阅读[《常见问题》](https://github.com/kongzue/DialogX/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)
其中的 [DialogX 无法覆盖在 DialogFragment、AlertDialog 之上](https://github.com/kongzue/DialogX/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98#qdialogx-%E6%97%A0%E6%B3%95%E8%A6%86%E7%9B%96%E5%9C%A8-dialogfragmentalertdialog-%E4%B9%8B%E4%B8%8A)
