### ISSUE TITLE
How  to apply Message dialog to IOS Style 

### ISSUE THREAD

**Issue by NavjotSinghSeraphic** [kongzue/DialogX#460]
fun showMessageDialog(
        context: Context,
        title: String? = null,
        message: String ?=null,
        okButtonText: String = "OK",
        cancelButtonText: String = "Cancel",
        isCancelable:Boolean=false,
        onOkClickListener: ((dialog: MessageDialog, view: View) -> Boolean)? = null,
        onCancelClickListener: ((dialog: MessageDialog, view: View) -> Boolean)? = null
    ) {
        val dialog = MessageDialog.build()
            .setTitle(title)
            .setMessage(message)
            .setOkButton(okButtonText)
            .setCancelable(isCancelable)
            .setCancelButton(cancelButtonText)
            .setStyle(DialogX.globalStyle)

        onOkClickListener?.let {
            dialog.setOkButtonClickListener(it)
        } ?: dialog.setOkButtonClickListener { dialog, view ->
            dialog.dismiss()
            true
        }

        onCancelClickListener?.let {
            dialog.setCancelButton(it)
        } ?: dialog.setCancelButton { dialog, view ->
            dialog.dismiss()
            true
        }

        dialog.show()
    }

 i am not found  ios style  for applying to dialog 
 
![image](https://github.com/user-attachments/assets/b30f0ce0-38ed-4256-ad05-bbbe6ab902cc)

**Comment by kongzue** [comment]
Please refer to the wiki: [Using Other DialogX Themes](https://github.com/kongzue/DialogX/wiki/Styles_en). If you need to use a specific theme style in a separate dialog, you need to build it with the `build()` method, using the ` setStyle(...) ` method to specify the theme style, for example:
```kotlin
val dialog = MessageDialog.build()
    .setStyle(IOSStyle.style())
    .show()
```

**Comment by NavjotSinghSeraphic** [comment]
thank you
