### ISSUE TITLE
【功能建议】Dismiss定义提升

### ISSUE THREAD

**Issue by WangHan2014** [kongzue/DialogX#461]
### 需求描述：
能否将Dismiss提升至BaseDialog实现或提供其他实现于基础类的关闭方式

例如：
`dialog.close()`
`((BaseDialog)dialog).dismiss()`

**Comment by kongzue** [comment]
事实上，BaseDialog 是一个基础类并不提供对外直接使用的实现，如果要实现一个自定义的对话框子类可以通过以下方法关掉对话框：
```java
dismiss(dialogView);
```
