### ISSUE TITLE
【功能建议】textview字体改为sp，目前为dp，谷歌商店上架会有警告

### ISSUE THREAD

**Issue by crazecoder** [kongzue/DialogX#462]
### 需求描述：
<img width="372" alt="image" src="https://github.com/user-attachments/assets/ae7e06cb-e5d9-4d09-9c5a-8dea89423a03">

<img width="811" alt="image" src="https://github.com/user-attachments/assets/c7900c45-8bdb-4386-b0b5-bab5295f7772">

**Comment by kongzue** [comment]
默认情况下，DialogX 的字号使用 dp 为单位，其目的是在不同分辨率的屏幕小保持与 UI 设计风格一致的文本显示样式，要调整样式，请参考 wiki 中关于各部分组件的字体样式调整说明，例如 MessgaeDialog 的文本样式调整你可以 [在这里](https://github.com/kongzue/DialogX/wiki/%E5%9F%BA%E7%A1%80%E5%AF%B9%E8%AF%9D%E6%A1%86-MessageDialog-%E5%92%8C-%E8%BE%93%E5%85%A5%E5%AF%B9%E8%AF%9D%E6%A1%86-InputDialog#%E5%85%B6%E4%BB%96%E9%A2%9D%E5%A4%96%E6%96%B9%E6%B3%95) 找到对应的方法，DialogX 也提供了全局调整的方法，你可以 [在这里](https://github.com/kongzue/DialogX/wiki#%E9%A2%9D%E5%A4%96%E9%85%8D%E7%BD%AE) 找到。

DialogX 的文本样式调整需要你构建一个 `TextInfo` 配置信息，其中可以通过 `.setFontSizeUnit(FONT_SIZE_UNIT)` 来指定文本大小的单位，其中 `FONT_SIZE_UNIT` 是一个枚举，提供 `DP`、`PX`、`SP` 可选。
