### ISSUE TITLE
【BUG反馈】 按键焦点操作逻辑存在问题

### ISSUE THREAD

**Issue by dengwhao** [kongzue/DialogX#464]
### ⚠️ 重要阅读

- [X] 请确保你已升级至 [最新发布的测试版本](https://github.com/kongzue/DialogX/releases)，旧版本存在的问题不再处理。
- [X] 请确保你已在 [已有的issues](https://github.com/kongzue/DialogX/issues?q=is%3Aissue+is%3Aclosed) 中查询过没有类似的问题。
- [X] 请先确认您已阅读[《常见问题》](https://github.com/kongzue/DialogX/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)
- [X] 如有条件建议尝试拉取整个项目，尝试运行 Demo app，并模拟在 Demo 环境中运行可能存在问题的代码，如果可以复现请提交 issues 并附上复现代码。

### 问题描述

在TV端启动任意一个非全屏显示的自定义对话框，比如显示在右半边区域的对话框，遥控器按导航栏往左，焦点会到下一级页面上面去，并且后续焦点无法回到对话框这里

### DialogX 版本

0.0.50.beta17.1

### 设备信息

任意Android TV设备

### 是否在 Demo 中能复现此问题？

是

### 问题截图/视频

截屏/视频

**Comment by kongzue** [comment]
请尝试更换为非 view 的实现模式，在 view 实现模式下，默认情况是在 Activity 界面前插入了对话框 view，并没有隐藏 Activity 原本的内容，因此会出现此问题
________________________________
发件人: dengwhao ***@***.***>
发送时间: Friday, August 30, 2024 11:13:44 AM
收件人: kongzue/DialogX ***@***.***>
抄送: Subscribed ***@***.***>
主题: [kongzue/DialogX] 【BUG反馈】 按键焦点操作逻辑存在问题 (Issue #464)


⚠️ 重要阅读

  *    请确保你已升级至 最新发布的测试版本<https://github.com/kongzue/DialogX/releases>，旧版本存在的问题不再处理。
  *    请确保你已在 已有的issues<https://github.com/kongzue/DialogX/issues?q=is%3Aissue+is%3Aclosed> 中查询过没有类似的问题。
  *    请先确认您已阅读《常见问题》<https://github.com/kongzue/DialogX/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98>
  *    如有条件建议尝试拉取整个项目，尝试运行 Demo app，并模拟在 Demo 环境中运行可能存在问题的代码，如果可以复现请提交 issues 并附上复现代码。

问题描述

在TV端启动任意一个非全屏显示的自定义对话框，比如显示在右半边区域的对话框，遥控器按导航栏往左，焦点会到下一级页面上面去，并且后续焦点无法回到对话框这里

DialogX 版本

0.0.50.beta17.1

设备信息

任意Android TV设备

是否在 Demo 中能复现此问题？

是

问题截图/视频

截屏/视频

错误日志

No response

**Comment by dengwhao** [comment]
更换成fragment的方式会在启动对话框之后页面上没有焦点。之前用view的模式是我主动请求焦点的

**Comment by kongzue** [comment]
可以尝试在 [onShow 事件](https://github.com/kongzue/DialogX/wiki/%E5%9F%BA%E7%A1%80%E5%AF%B9%E8%AF%9D%E6%A1%86-MessageDialog-%E5%92%8C-%E8%BE%93%E5%85%A5%E5%AF%B9%E8%AF%9D%E6%A1%86-InputDialog#%E7%94%9F%E5%91%BD%E5%91%A8%E6%9C%9F%E5%9B%9E%E8%B0%83)中处理，这种情况比较特殊，我这边目前没有相关设备进行试验。

**Comment by dengwhao** [comment]
抱歉未能及时回复。
我试了在 onShow()事件中请求焦点，但是仍然没有效果。我目前将实现模式设置为了DialogX.implIMPLMode= DialogX.IMPL_MODE.WINDOW; 从我这边电视画面显示效果上看，怀疑似乎是焦点仍然停留在上一个页面的按钮处，因为此处的按键焦点水波纹效果仍然是按下去的状态。
context?.let {
            CustomDialog.show(onBindView).setAlign(CustomDialog.ALIGN.RIGHT_CENTER)
                .setEnableImmersiveMode(false)
                .setRootPadding(padding)
                .setCancelable(false)
                .setMaskColor(it.getColor(R.color.black_30))
                .setDialogLifecycleCallback(object : DialogLifecycleCallback<CustomDialog>() {
                    override fun onShow(dialog: CustomDialog) {
                        //dialog.dialogImpl.boxRoot.requestFocus()
                        dialogBinding.btnCancel.requestFocus()
                        //dialog.dialogImpl.boxCustom.requestFocus()
                        PopTip.show("onShow()")
                    }
                })
        }

**Comment by kongzue** [comment]
有没有尝试延迟？例如：
```java
view.post(new Runnable(){
    @Override
    public void run() {
        //try...
    }
})
```
或者指定时间延迟处理：
view.postDelayed(new Runnable() {
    @Override
    public void run() {
        //try...
    }
}, 300);
```
如果还是不行请检查是否能通过代码正确的使对象获得焦点。
我手头没有相关设备所以无法进行测试，希望建议能对你起到帮助

**Comment by dengwhao** [comment]
延迟处理是有效的，可以成功获取焦点，并且设置为WINDOW后并不会跑到底层页面了。但是这是否说明 onShow(dialog: CustomDialog) 回调方法触发时机存在问题
`override fun onShow(dialog: CustomDialog) {
                        dialogBinding.root.postDelayed({
                            //try...
                            dialogBinding.btnCancel.requestFocus()
                        }, 300)
                        PopTip.show("onShow()")
                    }`

**Comment by kongzue** [comment]
并没有问题，代码都是开源的你可以自己查阅，onShow执行后不代表着没有其他逻辑继续执行，可能会抢占焦点

**Comment by dengwhao** [comment]
行，那我这个问题找到解决办法了，问题关闭
