### ISSUE TITLE
【BUG反馈】 无法展示全局悬浮窗

### ISSUE THREAD

**Issue by izxyz** [kongzue/DialogX#466]
### ⚠️ 重要阅读

- [X] 请确保你已升级至 [最新发布的测试版本](https://github.com/kongzue/DialogX/releases)，旧版本存在的问题不再处理。
- [X] 请确保你已在 [已有的issues](https://github.com/kongzue/DialogX/issues?q=is%3Aissue+is%3Aclosed) 中查询过没有类似的问题。
- [X] 请先确认您已阅读[《常见问题》](https://github.com/kongzue/DialogX/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)
- [ ] 如有条件建议尝试拉取整个项目，尝试运行 Demo app，并模拟在 Demo 环境中运行可能存在问题的代码，如果可以复现请提交 issues 并附上复现代码。

### 问题描述

我遇到了...

### DialogX 版本

0.0.49

### 设备信息

Xiaomi10 

### 是否在 Demo 中能复现此问题？

未尝试

### 问题截图/视频

截屏/视频

### 错误日志

```java
无法展示全局悬浮窗
```

**Comment by kongzue** [comment]
DialogX默认采用View模式实现对话框的显示，其原理是在Activity的根布局插入一个前置的对话框view，这样做的目的在仓库主页有详细说明。
如有全局弹窗的需求，请尝试修改实现模式，例如改为Window模式，如果app具有悬浮窗权限，可以尝试开启悬浮窗模式：
```java
DialogX.globalHoverWindow = true;
```
此时使用window模式实现的弹窗可以在任意场景下弹出。
