### ISSUE TITLE
【BUG反馈】 打开弹窗太慢了

### ISSUE THREAD

**Issue by wsdydeni** [kongzue/DialogX#467]
### ⚠️ 重要阅读

- [X] 请确保你已升级至 [最新发布的测试版本](https://github.com/kongzue/DialogX/releases)，旧版本存在的问题不再处理。
- [X] 请确保你已在 [已有的issues](https://github.com/kongzue/DialogX/issues?q=is%3Aissue+is%3Aclosed) 中查询过没有类似的问题。
- [X] 请先确认您已阅读[《常见问题》](https://github.com/kongzue/DialogX/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)
- [ ] 如有条件建议尝试拉取整个项目，尝试运行 Demo app，并模拟在 Demo 环境中运行可能存在问题的代码，如果可以复现请提交 issues 并附上复现代码。

### 问题描述

调度不对啊，真的在一般性能机上跑过吗

### DialogX 版本

0.0.49

### 设备信息

vivo-V2327A-Android14

### 是否在 Demo 中能复现此问题？

否

### 问题截图/视频

截屏/视频

**Comment by kongzue** [comment]
Android14 设备上 debug 调试 app 出现卡顿的问题及临时修复办法 https://xiaozhuanlan.com/topic/1023694578
