### ISSUE TITLE
【BUG反馈】setCancelable不起作用

### ISSUE THREAD

**Issue by akai1203** [kongzue/DialogX#469]
### ⚠️ 重要阅读

- [X] 请确保你已升级至 [最新发布的测试版本](https://github.com/kongzue/DialogX/releases)，旧版本存在的问题不再处理。
- [X] 请确保你已在 [已有的issues](https://github.com/kongzue/DialogX/issues?q=is%3Aissue+is%3Aclosed) 中查询过没有类似的问题。
- [X] 请先确认您已阅读[《常见问题》](https://github.com/kongzue/DialogX/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)
- [X] 如有条件建议尝试拉取整个项目，尝试运行 Demo app，并模拟在 Demo 环境中运行可能存在问题的代码，如果可以复现请提交 issues 并附上复现代码。

### 问题描述

    用CustomDialog,show创建的对话框, 发现setCancelable函数无效

### DialogX 版本

0.0.49

### 设备信息

pda设备 android11

### 是否在 Demo 中能复现此问题？

否

### 问题截图/视频

截屏/视频

**Comment by akai1203** [comment]
CustomDialog.show(new OnBindView<CustomDialog>(R.layout.authcode) {

            private Button  btnOk ;
            private Button  btnCancle ;

            @Override
            public void onBind(final CustomDialog dialog, View v) {
                btnOk = v.findViewById(R.id.btn_ok);
                btnCancle = v.findViewById(R.id.btn_cancel);
                btnCancle.setOnClickListener(new View.OnClickListener() {
                    @Override
                    public void onClick(View v) {
                        dialog.dismiss();
                    }
                });
                btnOk.setOnClickListener(new View.OnClickListener() {
                    @Override
                    public void onClick(View v) {
                        PopTip.show("我知道了");
                        dialog.dismiss();
                    }
                });
            }
        })
                .setCancelable(true)
                .setMaskColor(getResources().getColor(com.kongzue.dialogx.iostheme.R.color.black30))
                .show();

**Comment by akai1203** [comment]
点击屏幕空白处 ,  无法关闭对话框

**Comment by kongzue** [comment]
请确认你的布局是否设置了宽高为match_parent，且是否有接收到或拦截触摸事件导致对话框的mask层没有接收到触摸事件。
另外测试mask层是否接收到点击事件的办法：
```java
.setOnBackgroundMaskClickListener(new OnBackgroundMaskClickListener() {
    @Override
    public boolean onClick(BaseDialog dialog, View v) {
        PopTip.show("点击到了对话框遮罩层");
        return false;
    }
})
```
