### ISSUE TITLE
InputDialog无法输入数据

### ISSUE THREAD

**Issue by Junpeng17** [kongzue/DialogX#47]
按照使用说明创建了一个输入对话框，不点击输入框就显示正常，然后点击输入框后显示出现问题，输入框及下半部分会不见，只剩下标题和按钮。
在AS 3.5的模拟器（安卓11）上和实体机（安卓11，类原生系统）上都有这个问题，App的API版本也是30
![1](https://user-images.githubusercontent.com/32558644/118382303-9a611c00-b626-11eb-88d8-99ed5536d35e.png)
![2](https://user-images.githubusercontent.com/32558644/118382360-10fe1980-b627-11eb-9101-1bc94003f316.png)

**Comment by kongzue** [comment]
请尝试[Demo](http://beta.kongzue.com/DialogXDemo)看看能否复现此问题。
尚未收到过类似的反馈，且当前应用DialogX组件的APP在各大应用商店已上架的软件，例如《给未来写封信》、《密码键盘》等均未收到过类似问题的反馈。
目前开发测试是基于Android 12(DP3)进行的，如有疑问可继续回复。

**Comment by Junpeng17** [comment]
demo里不会

new InputDialog("请输入密码", "设置文件的加密/解密的密码", "确定", "取消", null)
                .setCancelable(false)
                .setOkButton(new OnInputDialogButtonClickListener<InputDialog>() {
                    @Override
                    public boolean onClick(InputDialog baseDialog, View v, String inputStr) {
                        / ............... //
                        }
                        return false;
                    }
                })
                .show();
这段代码是哪里有问题啊
