### ISSUE TITLE
【功能建议】WaitDialog/TipDialog 默认文字设置+空参show()

### ISSUE THREAD

**Issue by XiaoRanLiu3119** [kongzue/DialogX#470]
## 功能建议
全局设置等待框/提示框文字,未设置,则WaitDialog.show()无文字提示
### 需求描述：
很多小项目,等待框无文字 或 都是"加载中..."，目前是到处WaitDialog.show("") 或 WaitDialog.build().show() 或 放到Base类/单独类调用。
期望提供类似于
//App
WaitDialog.typeNoneMsg= "加载中";
...
//Ui
WaitDialog.show() //加载中...
WaitDialog.show("正在上传...")

**Comment by kongzue** [comment]
请更新至最新版本：[0.0.50.beta22](https://github.com/kongzue/DialogX/releases/tag/0.0.50.beta22)
相关更新日志：
0.0.50.beta22
- 新增默认文本设置：
  
  // 默认消息对话框标题文本
  DialogX.defaultMessageDialogTitleText
  // 等待提示框默认文本
  DialogX.defaultWaitDialogWaitingText;
  // 成功提示框默认文本
  DialogX.defaultTipDialogSuccessText;
  // 错误提示框默认文本
  DialogX.defaultTipDialogErrorText;
  // 警告提示框默认文本
  DialogX.defaultTipDialogWarningText;
  
  设置文本后可以在不指定对应对话框的相关文本时直接使用默认文本；
  
  对应的对话框静态启动方法省略默认可设置文本的方法也已添加，比如 `MessageDialog.show(messageText)` 或者 `WaitDialog.showWaitWithDefaultText()` 以及 `TipDialog.showTipWithDefaultText(TYPE)`

- 修复 PopNotification 在允许同时显示多条通知时，关闭后依然能够接收到触摸事件的问题；
- 修复 PopNotification 在 DialogFragment 模式下默认顶部位置异常的问题

请注意为避免和非静态方法 `.show()` 的冲突，WaitDialog和TipDialog的默认更新后使用默认文本的启动方式使用了特定的方法。

**Comment by XiaoRanLiu3119** [comment]
大佬效率极高,这样舒服很多👍👍👍
