### ISSUE TITLE
【BUG反馈】 全屏界面中，横屏模式下底部输入弹窗在切换软键盘过程宽度会重新计算，导致界面闪一下

### ISSUE THREAD

**Issue by baiyinshi** [kongzue/DialogX#471]
### ⚠️ 重要阅读

- [X] 请确保你已升级至 [最新发布的测试版本](https://github.com/kongzue/DialogX/releases)，旧版本存在的问题不再处理。
- [X] 请确保你已在 [已有的issues](https://github.com/kongzue/DialogX/issues?q=is%3Aissue+is%3Aclosed) 中查询过没有类似的问题。
- [X] 请先确认您已阅读[《常见问题》](https://github.com/kongzue/DialogX/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)
- [X] 如有条件建议尝试拉取整个项目，尝试运行 Demo app，并模拟在 Demo 环境中运行可能存在问题的代码，如果可以复现请提交 issues 并附上复现代码。

### 问题描述

全屏界面中，横屏模式下底部输入弹窗在切换软键盘过程宽度会重新计算，导致界面闪一下

### DialogX 版本

0.0.50.beta20

### 设备信息

小米11Pro M2102K1AC Android 13

### 是否在 Demo 中能复现此问题？

否

### 问题截图/视频

截屏/视频

**Comment by kongzue** [comment]
不清楚是否跟您的沉浸式适配框架或者方案有关，若Demo中没有复现，请检查您的app是否存在沉浸式设置问题。
另可使用 `DialogXBaseRelativeLayout.debugMode=true` 开启沉浸式相关日志查看系统返回的“非安全区”大小是否存在问题，如果log数据异常请检查沉浸式框架，或更换适配方案。
