### ISSUE TITLE
【BUG反馈】 如何取消弹窗背景点击的涟漪效果？

### ISSUE THREAD

**Issue by Yetland** [kongzue/DialogX#473]
### ⚠️ 重要阅读

- [X] 请确保你已升级至 [最新发布的测试版本](https://github.com/kongzue/DialogX/releases)，旧版本存在的问题不再处理。
- [X] 请确保你已在 [已有的issues](https://github.com/kongzue/DialogX/issues?q=is%3Aissue+is%3Aclosed) 中查询过没有类似的问题。
- [X] 请先确认您已阅读[《常见问题》](https://github.com/kongzue/DialogX/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)
- [X] 如有条件建议尝试拉取整个项目，尝试运行 Demo app，并模拟在 Demo 环境中运行可能存在问题的代码，如果可以复现请提交 issues 并附上复现代码。

### 问题描述

点击弹窗背景一直有涟漪的效果，什么方法可以将点击效果去掉

### DialogX 版本

0.0.49

### 设备信息

Xiaomi 14 Android 15

### 是否在 Demo 中能复现此问题？

是

### 问题截图/视频

截屏/视频

**Comment by kongzue** [comment]
默认情况下是不会有的，未能在Pixel5上复现您描述的问题，且在红米K70上也未能复现。
不排除是新版本系统的bug，例如强制为可点击View配置了foreground，建议等待稳定版本后再进行测试。

**Comment by a296421914** [comment]
确实有这个问题
