### ISSUE TITLE
【BUG反馈】 PopMenu如何设置文字居中

### ISSUE THREAD

**Issue by Gxaasec** [kongzue/DialogX#474]
### ⚠️ 重要阅读

- [X] 请确保你已升级至 [最新发布的测试版本](https://github.com/kongzue/DialogX/releases)，旧版本存在的问题不再处理。
- [X] 请确保你已在 [已有的issues](https://github.com/kongzue/DialogX/issues?q=is%3Aissue+is%3Aclosed) 中查询过没有类似的问题。
- [X] 请先确认您已阅读[《常见问题》](https://github.com/kongzue/DialogX/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)
- [X] 如有条件建议尝试拉取整个项目，尝试运行 Demo app，并模拟在 Demo 环境中运行可能存在问题的代码，如果可以复现请提交 issues 并附上复现代码。

### 问题描述

想设置menulist的文字居中，然后使用.setAlignGravity( Gravity.CENTER_HORIZONTAL)
但是出现闪退。不加setAlignGravity就不会，以上操作在demo中进行操作的。版本是最新的

### DialogX 版本

0.0.50.beta23

### 设备信息

小米8 Android10

### 是否在 Demo 中能复现此问题？

是

### 问题截图/视频

截屏/视频
![image](https://github.com/user-attachments/assets/6172eced-7ef7-427b-b2a9-88da0410a723)

**Comment by kongzue** [comment]
请仔细阅读Wiki文档：[上下文菜单-PopMenu](https://github.com/kongzue/DialogX/wiki/%E4%B8%8A%E4%B8%8B%E6%96%87%E8%8F%9C%E5%8D%95-PopMenu)，setAlignGravity 操作的是 PopMenu 相对于 baseView 的位置而非 item 的居中方式，要调整 item 居中方式您可能需要自定义文本样式，您在未指定 baseView 时该选项不可用。
<img width="1583" alt="image" src="https://github.com/user-attachments/assets/d6d8382e-7746-497e-a282-228a1ac07d02">

要自定义文本样式，可以通过如下代码解决：
```java
.setMenuTextInfo(new TextInfo().setGravity(Gravity.CENTER))
```

相关代码我会在后续增加判断以避免空指针异常。

**Comment by Gxaasec** [comment]
好的。谢谢
