### ISSUE TITLE
【BUG反馈】 InputDialog输入类型问题

### ISSUE THREAD

**Issue by 690810892** [kongzue/DialogX#479]
### ⚠️ 重要阅读

- [X] 请确保你已升级至 [最新发布的测试版本](https://github.com/kongzue/DialogX/releases)，旧版本存在的问题不再处理。
- [X] 请确保你已在 [已有的issues](https://github.com/kongzue/DialogX/issues?q=is%3Aissue+is%3Aclosed) 中查询过没有类似的问题。
- [X] 请先确认您已阅读[《常见问题》](https://github.com/kongzue/DialogX/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)
- [X] 如有条件建议尝试拉取整个项目，尝试运行 Demo app，并模拟在 Demo 环境中运行可能存在问题的代码，如果可以复现请提交 issues 并附上复现代码。

### 问题描述

 new InputDialog("数量", "", "确定", "取消", "")
                    .setInputInfo(new InputInfo().setInputType(InputType.TYPE_CLASS_NUMBER) 
设置之后输入框依然能输入小数点，TYPE_CLASS_NUMBER应该只能数字才对

### DialogX 版本

0.0.50.beta24

### 设备信息

Redmi k60Pro  Android14

### 是否在 Demo 中能复现此问题？

是

### 问题截图/视频

截屏/视频

**Comment by kongzue** [comment]
感谢你的反馈，此问题系默认情况下内部额外增加了InputType.TYPE_CLASS_TEXT导致的，已在最新的代码提交中撤销了这个行为，相关代码位于[MessageDialog.java#L685](https://github.com/kongzue/DialogX/blob/e89ab3bf8e6c86c9e880010a592af9de9763c48d/DialogX/src/main/java/com/kongzue/dialogx/dialogs/MessageDialog.java#L685)
将合并在下一个测试版本更新。
