### ISSUE TITLE
自定义弹窗的奇怪现象

### ISSUE THREAD

**Issue by libern** [kongzue/DialogX#48]
在最新的AS 4.2.1和com.gyf.immersionbar:immersionbar:3.0.0，但是demo项目没问题

```
CustomDialog.build()
            .setCustomView(object : OnBindView<CustomDialog>(R.layout.dialog_popup_custom) {

                override fun onBind(dialog: CustomDialog?, v: View?) {

                }

            })
            .setMaskColor(CoreApplication.instance.color(R.color.backgroundAlertMaskTransparent))
            .setFullScreen(true)
            .setAlign(CustomDialog.ALIGN.CENTER)
            .setAutoUnsafePlacePadding(false)
            .show()
```

![image](https://user-images.githubusercontent.com/1830640/118508547-e06eca80-b761-11eb-8b5b-e6567c33cedb.png)

center无效果，然后bottom直接看不见

**Comment by kongzue** [comment]
请确认你的自定义布局的根布局高度非match_parent，如果是，请改为wrap_content后再试。
另外不排除与其他可能涉及沉浸式适配的框架存在冲突，我们只能保证在绝大部分情况下是正常的，且无法确定第三方框架的逻辑。

**Comment by libern** [comment]
![image](https://user-images.githubusercontent.com/1830640/118659635-12defd00-b820-11eb-8bd2-a20b2a82e229.png)

开了全新项目测试了，也是一样。版本是：0.0.36

**Comment by libern** [comment]
![image](https://user-images.githubusercontent.com/1830640/118659733-2a1dea80-b820-11eb-8474-caf0249c4df3.png)

0.0.38 就没问题了。感谢

**Comment by kongzue** [comment]
请尽量保证更新至最新版本，如有疑问可继续回复，也可以在Wiki中找到我们的讨论群加群交流。
