### ISSUE TITLE
CustomDialog中如何使用ViewPager2或FrameLayout加载Fragment？

### ISSUE THREAD

**Issue by wxw-9527** [kongzue/DialogX#480]
### 需求描述：
项目需要在dialog中使用ViewPager2展示多个Fragment，因为Dialogx无法获取FragmentManager的实例，所以改为使用DialogFragment实现弹窗效果，但是使用了DialogFragment又会导致PopTips被覆盖无法展示，请问有其他解决方案么?

**Comment by kongzue** [comment]
实际上你把DialogX的对话框理解成插入在activity的DecorView前的一个View就好，要使用FragmentManager直接拿对应显示的activity的FragmentManager即可，如果不好获取也可以这样：
```java
//这里拿CustomDialog举例
.onShow(new DialogXRunnable< CustomDialog >() {
    @Override
    public void run(CustomDialog dialog) {
        dialog.getOwnActivity()     //do something...
    }
})
```
