### ISSUE TITLE
使用WaitDialog.show界面中如果有输入框的焦点，择会被去掉

### ISSUE THREAD

**Issue by FrankHnb** [kongzue/DialogX#483]
WaitDialog.show（）无法实现弹窗和键盘共存

**Comment by kongzue** [comment]
建议您调整代码逻辑，在合适的场景使用合适的弹窗。
Waitdialog 作为阻断式弹窗，本身肯定是要避免用户的一切操作的，如果您有特殊需求，请定制开发。
