### ISSUE TITLE
一个页面多个接口时的混乱

### ISSUE THREAD

**Issue by CileCile** [kongzue/DialogX#49]
在同一个Fragment里，同时加载多个接口，每个接口都调用了WaitDialog，结果WaitDialog一直存在，不会消失
        mModel.getTaskList( pageNo, pageSize)
                .subscribeOn(Schedulers.io())
                //遇到错误时重试,第一个参数为重试几次,第二个参数为重试的间隔
                .retryWhen(new RetryWithDelay(3, 2))
                .doOnSubscribe(disposable -> {
                  WaitDialog.show( "请稍候222...");
                })
                .subscribeOn(AndroidSchedulers.mainThread())
                .observeOn(AndroidSchedulers.mainThread())
                .doFinally(() -> {
                    WaitDialog.dismiss();
                })
                //使用 Rxlifecycle,使 Disposable 和 Activity 一起销毁
                .compose(RxLifecycleUtils.bindToLifecycle(mRootView))
                .subscribe(new ErrorHandleSubscriber<GetTaskEntity>(mErrorHandler) {
                    @Override
                    public void onNext(GetTaskEntity response) {
                    }
                `});`

**Comment by kongzue** [comment]
请优化你的程序逻辑，这不是DialogX该帮你处理的事情。

**Comment by CileCile** [comment]
程序逻辑是没有问题的，之前同样的场景用普通的dialog和dialogV3都是没有问题的，现在做了升级就出现WaitDialog关不掉的情况了

**Comment by kongzue** [comment]
因为DialogV3和DialogX的实现逻辑不同。
DialogX采用了自动获取当前Activity的模式，且会post到主线程去执行，但频繁的启停对话框会造成主线程卡住，不建议这样操作。
目前有提供Window的实现方式，和以往的DialogV3基本一致，但存在一些未解决的bug，详情请参阅Wiki。

**Comment by kongzue** [comment]
我所说的建议优化逻辑是建议你将同时多个加载的逻辑合并起来，不要出现频繁启停对话框的方法去提示用户，频繁启停对话框的逻辑肯定是不合理的，同一时间只显示一个持续的阻止用户操作的提示才是正确方案。

**Comment by CileCile** [comment]
刚发现在Activity里面，有一个接口且只调用一次的情况下，WaitDialog同样不会消失

**Comment by kongzue** [comment]
您好，暂时未收到类似的问题报告，且在目前已经上线的应用反馈来看也未收到类似问题的反馈，请确保您使用的是最新的版本，我会持续关注此问题。
你也可以在README首页看到我们的讨论群加群与我直接讨论。

**Comment by kongzue** [comment]
请更新至最新版本，此问题已经得到修复。
