### ISSUE TITLE
崩溃：Attempt to read from field 'int android.view.View.mViewFlags' on a null object reference  android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4496)

### ISSUE THREAD

**Issue by feisher** [kongzue/DialogX#50]
稳定复现代码如下：
CustomDialog.show(object : OnBindView<CustomDialog>(R.layout.alert_coustom) {
                override fun onBind(dialog: CustomDialog, v: View) {
                    v.findViewById<TextView>(R.id.tv_cancel).click { dialog.dismiss() }
                    v.findViewById<TextView>(R.id.tv_ok).click {
                        dialog.dismiss()
                        TipDialog.show("崩溃点",WaitDialog.TYPE.SUCCESS)
                    }
                }
            })
CustomDialog中执行相关逻辑后，只要有TipDialog弹窗提示和就会崩溃报空指针，报错内容：
java.lang.NullPointerException
Attempt to invoke virtual method 'java.lang.Object android.content.Context.getSystemService(java.lang.String)' on a null object reference
com.kongzue.dialogx.interfaces.BaseDialog.createView(BaseDialog.java:131)

**Comment by kongzue** [comment]
请确认您正在使用最新的版本。
未能在BaseDialog.java:131找到createView(...)方法的使用。

**Comment by feisher** [comment]
使用的0.0.33 版本




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年5月19日(星期三) 下午2:51
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [kongzue/DialogX] 崩溃：Attempt to read from field &#39;int android.view.View.mViewFlags&#39; on a null object reference  android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4496) (#50)





 
请确认您正在使用最新的版本。
 未能在BaseDialog.java:131找到createView(...)方法的使用。

**Comment by kongzue** [comment]
请更新至最新版本，在README页可以看到版本号，我无法对老版本的代码进行处理。

**Comment by feisher** [comment]
好吧，0.0.38版确实没这个问题，但是之前我升级到0.0.38版本时候有出现部分弹窗报错又回退了




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年5月19日(星期三) 下午2:54
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [kongzue/DialogX] 崩溃：Attempt to read from field &#39;int android.view.View.mViewFlags&#39; on a null object reference  android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4496) (#50)





 
请更新至最新版本，在README页可以看到版本号，我无法对老版本的代码进行处理。

**Comment by kongzue** [comment]
最新的版本是0.0.39.beta3，可以尝试以下，如果遇到问题可以随时问我。

**Comment by feisher** [comment]
相对38版本有修复bug吗，还是增加了新特性？




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年5月19日(星期三) 下午3:05
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [kongzue/DialogX] 崩溃：Attempt to read from field &#39;int android.view.View.mViewFlags&#39; on a null object reference  android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4496) (#50)





 
最新的版本是0.0.39.beta3，可以尝试以下，如果遇到问题可以随时问我。

**Comment by kongzue** [comment]
具体就得对比差异了，我这边现在很忙暂时没办法维护编写每个版本的日志，一般都是bug修复或者新功能的扩展
