### ISSUE TITLE
PopTip 被 BottomSheetDialog 遮蔽

### ISSUE THREAD

**Issue by wizos** [kongzue/DialogX#51]
PopTip 在 BottomSheetDialog 的下一层，会被遮住

**Comment by kongzue** [comment]
您好，这并不是bug。DialogX是基于View实现的方案并不是Window方案，目前也提供了Window实现方案，但存在相当多的bug，详情请查看wiki。
我认为Window方案并不理想，目前相对于View方案没有任何优势，也建议使用BottomDialog替换BottomSheetDialog使用。

**Comment by kongzue** [comment]
另外补充文章[《DialogX为什么放弃传统Window体系去使用View体系制作对话框的讨论和探究》](https://xiaozhuanlan.com/topic/9478530612)
