### ISSUE TITLE
最新版使用IOS主题，BottomMenu有出现背景透明情况，而使用默认或MIUI主题就没有

### ISSUE THREAD

**Issue by feisher** [kongzue/DialogX#52]

**Comment by kongzue** [comment]
请确认您正在使用最新的版本：0.0.39.debug4
在0.0.39.debug4版本未能复现您所描述的情况。

**Comment by feisher** [comment]
使用的bate3,,debug4版本有修复这个情况？




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年5月24日(星期一) 晚上7:44
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [kongzue/DialogX] 最新版使用IOS主题，BottomMenu有出现背景透明情况，而使用默认或MIUI主题就没有 (#52)





 
请确认您正在使用最新的版本：0.0.39.debug4
 在0.0.39.debug4版本未能复现您所描述的情况。

**Comment by kongzue** [comment]
beta3->debug4未修改这块的逻辑。
请[下载Demo](http://beta.kongzue.com/DialogXDemo)查看是否能复现此问题，若能，请告知测试机型和系统版本，若不能，应该不是DialogX的问题，请检查设备是否支持renderScript库运行以及是否以及进行renderScript的配置（详情参考wiki）。

**Comment by feisher** [comment]
试了好几个机型都是一样，有华为mate40,小米5s,荣耀magic2,,,,仅BottomMenu有出现卡片背景消失问题，点击条目能显示被透明了的条目背景，再acitivity嵌套fragment里面更奇葩activity上的按钮点击正常，切换了activity里面fragment 再点击下面按钮BottomMenu弹窗竟然透明了，切回初始化哪个fragment 又可以显示背景了



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年5月24日(星期一) 晚上7:49
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [kongzue/DialogX] 最新版使用IOS主题，BottomMenu有出现背景透明情况，而使用默认或MIUI主题就没有 (#52)





 
beta3-&gt;debug4未修改这块的逻辑。
 请下载Demo查看是否能复现此问题，若能，请告知测试机型和系统版本，若不能，应该不是DialogX的问题，请检查设备是否支持renderScript库运行以及是否以及进行renderScript的配置（详情参考wiki）。

**Comment by kongzue** [comment]
Demo也是这样么？

**Comment by feisher** [comment]
------------------&nbsp;原始邮件&nbsp;------------------发件人:                                                                                                                        "kongzue/DialogX"                                                                                    ***@***.***&gt;;





发送时间:&nbsp;2021年5月24日(星期一) 晚上7:49
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [kongzue/DialogX] 最新版使用IOS主题，BottomMenu有出现背景透明情况，而使用默认或MIUI主题就没有 (#52)





 
beta3-&gt;debug4未修改这块的逻辑。
 请下载Demo查看是否能复现此问题，若能，请告知测试机型和系统版本，若不能，应该不是DialogX的问题，请检查设备是否支持renderScript库运行以及是否以及进行renderScript的配置（详情参考wiki）。

**Comment by feisher** [comment]
使用readme中的beta1和debug4,没有这个问题，集成已经更新为debug4

**Comment by beiger** [comment]
用的0.0.38确实有这个问题，时而有，时而没有，
![image](https://user-images.githubusercontent.com/18483100/119782495-d76abf80-befe-11eb-8860-0a40f1c57f49.png)

**Comment by kongzue** [comment]
@beiger  请更新版本后再试。
