### ISSUE TITLE
iOSStyle BottomMenu取消按钮背景透明

### ISSUE THREAD

**Issue by beiger** [kongzue/DialogX#56]
iOSStyle BottomMenu的取消按钮正常应该是白色背景，但是有时会变成透明背景，有时是正常的。

**Comment by beiger** [comment]
![image](https://user-images.githubusercontent.com/18483100/119782248-82c74480-befe-11eb-88cc-f637fe030d64.png)

**Comment by kongzue** [comment]
请更新至最新版本。
