### ISSUE TITLE
显示弹窗的时候null异常

### ISSUE THREAD

**Issue by HarrisonShen** [kongzue/DialogX#58]
WaitDialog.show(content)显示弹框的时候个别机型报空指针，由于BaseDialog这个类中protected void beforeShow() {        if (getContext() == null) {
这一步没拦截，导致BaseDialog.createView()  里面  public View createView(int layoutId) {
        return LayoutInflater.from(getContext()).inflate(layoutId, null);
    }
getContext空指针了，contextWeakReference 引起的空指针，希望能改进一下

**Comment by kongzue** [comment]
请确保根据文档要求，在您的Application#onCreate方法中完成了初始化操作。

**Comment by HarrisonShen** [comment]
> 请确保根据文档要求，在您的Application#onCreate方法中完成了初始化操作。

完成初始化了，你这边用的弱应用，应该是回收到了所以空了

**Comment by kongzue** [comment]
嗯，是被内存泄漏整怕了，下个版本修复

**Comment by kongzue** [comment]
查了下源代码，Application在DialogX中并未持有。
是从Context取出Application并为其设置了ActivityLifecycleCallbacks并从中获取Activity做了弱引用，具体请参考 `ActivityLifecycleImpl#init` 的代码。[(ActivityLifecycleImpl.java:34)](https://github.com/kongzue/DialogX/blob/07e06c8642cf6379c69cf3d1e52be0de44c31ccc/DialogX/src/main/java/com/kongzue/dialogx/impl/ActivityLifecycleImpl.java#L34)
因为Application被回收，这时就可能导致Application的内存指针发生了变化，致使初始化失效。

**Comment by kongzue** [comment]
请尝试测试版本：0.0.40.beta1
此版本尝试使用了反射来获取当前处于堆栈顶端的Activity以及ApplicationContext，不需要再进行初始化操作也可以使用Dialog。

**Comment by HarrisonShen** [comment]
> 请尝试测试版本：0.0.40.beta1
> 此版本尝试使用了反射来获取当前处于堆栈顶端的Activity以及ApplicationContext，不需要再进行初始化操作也可以使用Dialog。

好的
