### ISSUE TITLE
底部对话框菜单按下后移动手指到其他区域无法取消

### ISSUE THREAD

**Issue by fengyuecanzhu** [kongzue/DialogX#59]
底部对话框菜单按下后移动手指到其他区域无法取消，仍然会触发单击事件

我看了下源码是BottomDialogListView的dispatchTouchEvent方法拦截有问题

**Comment by kongzue** [comment]
是存在问题，但没找到解决办法......本质上是为了保证Material主题时可以允许下滑关闭BottomMenu，所以从父布局入手进行了事件拦截，但目前无法做到非下滑的逻辑处理，如果有办法的话我会进行尝试。

**Comment by kongzue** [comment]
请尝试最新的测试版本：0.0.40.beta13
