### ISSUE TITLE
配合RXjava使用，个别情况下，MessageDialog弹出后，WaitDialog无法dissmiss

### ISSUE THREAD

**Issue by z2700589** [kongzue/DialogX#6]
在doOnSubscribe()中show出WaitDialog，在doFinally()中dissmiss，然后再doOnComplete或者onError中展示MessageDialog。
个别情况下，MessageDialog显示后，WaitDialog会伴随MessageDialog一起显示且无法消失。

**Comment by kongzue** [comment]
请在恰当的时候执行WaitDialog.dismiss();
MessageDialog并不会自动关闭WaitDialog。

**Comment by z2700589** [comment]
```java
xxxxxxxxxx.doOnSubscribe(disposable -> WaitDialog.show("正在上传照片数据,请稍后..."))
                .doOnComplete(() -> MessageDialog.build()
                        .setCancelable(false)
                        .setTitle("提示")
                        .setMessage("上传成功")
                        .setOkButton("确定")
                        .show())
                .doOnError(throwable -> {
                    WaitDialog.dismiss();
                    MessageDialog.build()
                                .setCancelable(false)
                                .setTitle("提示")
                                .setMessage(throwable.getMessage())
                                .setOkButton("确定")
                                .show();
                    })
                .doFinally(WaitDialog::dismiss)
                .subcribe();
```
第一次运行没问题。再调一次该方法，进行到onError()时  waitDialog无法关闭。

**Comment by z2700589** [comment]
补充问题：当请求相应速度足够快的情况下，WaitDialog消失后，会使页面无法触摸

**Comment by z2700589** [comment]
> ```java
> xxxxxxxxxx.doOnSubscribe(disposable -> WaitDialog.show("正在上传照片数据,请稍后..."))
>                 .doOnComplete(() -> MessageDialog.build()
>                         .setCancelable(false)
>                         .setTitle("提示")
>                         .setMessage("上传成功")
>                         .setOkButton("确定")
>                         .show())
>                 .doOnError(throwable -> {
>                     WaitDialog.dismiss();
>                     MessageDialog.build()
>                                 .setCancelable(false)
>                                 .setTitle("提示")
>                                 .setMessage(throwable.getMessage())
>                                 .setOkButton("确定")
>                                 .show();
>                     })
>                 .doFinally(WaitDialog::dismiss)
>                 .subcribe();
> ```
> 
> 第一次运行没问题。再调一次该方法，进行到onError()时 waitDialog无法关闭。

反复测试android5.1.1  有这个问题    android 10 就正常

**Comment by kongzue** [comment]
目前猜测是老版本系统执行逻辑存在问题，暂时没有定位到问题所在，会持续关注

**Comment by z2700589** [comment]
> 目前猜测是老版本系统执行逻辑存在问题，暂时没有定位到问题所在，会持续关注

补充的那个问题能定位到么？

**Comment by z2700589** [comment]
> > 目前猜测是老版本系统执行逻辑存在问题，暂时没有定位到问题所在，会持续关注
> 
> 补充的那个问题能定位到么？

测试应该是同样的问题，dissmiss方法不执行。

**Comment by kongzue** [comment]
dismiss方法会在主线程执行，DialogX的实现原理本质上是在Activity界面中插入一个View实现的，dismiss就是从根布局删除这个View，理论上不会执行失败

**Comment by z2700589** [comment]
> dismiss方法会在主线程执行，DialogX的实现原理本质上是在Activity界面中插入一个View实现的，dismiss就是从根布局删除这个View，理论上不会执行失败

那么是线程调度的问题？我正在测试

**Comment by kongzue** [comment]
请尝试最新版本看还有没有这个问题

**Comment by z2700589** [comment]
> 请尝试最新版本看还有没有这个问题

还是会有，但是比之前出现概率降低了

**Comment by QIMOU** [comment]
我也存在这个问题，WaitDialog消失后，无法与页面进行交互，手机返回键也不行 除非直接退回桌面

**Comment by kongzue** [comment]
@QIMOU 目前无法确定这个问题的原因，在我这边上线的几款软件中都没有能复现出这个问题

**Comment by kongzue** [comment]
暂时关闭了此问题，如有疑问可继续回复。

**Comment by appdev** [comment]
同样有这个问题。当请求足够快时，比如show 后立即调用 dismiss，无法关闭WaitDialog。

**Comment by kongzue** [comment]
DialogX之所以不需要考虑启动线程的原因是会自动将执行逻辑post给主线程运行，也就是说，在执行show指令后，若出现了主线程卡顿，对话框并不能立即启动，所以请勿在执行show后立即dismiss。
建议优化执行逻辑，避免大量重复频繁启停。

________________________________
发件人: appdev ***@***.***>
发送时间: Thursday, April 15, 2021 6:42:42 PM
收件人: kongzue/DialogX ***@***.***>
抄送: Kongzue ***@***.***>; State change ***@***.***>
主题: Re: [kongzue/DialogX] 配合RXjava使用，个别情况下，MessageDialog弹出后，WaitDialog无法dissmiss (#6)


同样有这个问题。当请求足够快时，比如show 后立即调用 dismiss，无法关闭WaitDialog。

―
