### ISSUE TITLE
加载框在进度回调的时候重复出现，这单例有瑕疵啊

### ISSUE THREAD

**Issue by MONGCHIAOHAY** [kongzue/DialogX#61]

**Comment by kongzue** [comment]
在最新的测试版未能复现你所描述的问题

**Comment by MONGCHIAOHAY** [comment]
![untitled](https://user-images.githubusercontent.com/51981062/121980904-5b59ee00-cdbf-11eb-8bbe-89557fc5dd5c.gif)

**Comment by MONGCHIAOHAY** [comment]
上传文件时回调的进度使得这个waitdialog加载多次

**Comment by kongzue** [comment]
不清楚你的开发逻辑，目前在我们实际使用过程，和已上线的诸多项目中均未出现此情况。
我这边采用的逻辑是，在请求发出时，显示WaitDialog，在完成任务后，直接显示TipDialog，TipDialog会衔接WatiDialog并关闭提示。

**Comment by MONGCHIAOHAY** [comment]
我的操作就是如此，但他在tipdialog之前就有多个waitdialog，tipdialog也仅能关闭代替一个waitdialog，出现多个waitdialog也会使得整个屏幕变黑，如果只有一个是置灰一点而已

**Comment by MONGCHIAOHAY** [comment]
您在我上传的gif图中可以看见，当他上传完成之后，是使用了tipdialog来显示已完成，但是关闭之后还有一个waitdialog

**Comment by kongzue** [comment]
如果你同时有多个请求要处理建议在事物开始前执行WaitDialog的显示，在所有事物完成后关闭，请不要频繁的启停，因为DialogX是UI组件，需要在主线程启动，并不能完整做到频繁启停

**Comment by kongzue** [comment]
建议优化程序逻辑，因为WaitDialog和TipDialog需要实现动画衔接实际上是共用同一个组件的，如果你认为是WaitDialog的单例存在瑕疵可以提交修改建议，感谢您的反馈。

**Comment by kongzue** [comment]
BaseDialog的底层需要将所有对话框的启动事物post给主线程（mainHandler），如果你频繁启停还可能造成主线程的卡顿，这是原理限制，WaitDialog和TipDialog的遵循如果存在已创建的组件，则对已存在的组件进行调整显示，如果不存在则创建并显示。

**Comment by MONGCHIAOHAY** [comment]
明白了，我已经在回调返回前显示waitdialog了，完美解决了这个问题，谢谢您提供的思路

**Comment by kongzue** [comment]
暂时关闭此问题，若有疑问可继续提问。
