### ISSUE TITLE
WaitDialog如果网络速度很快，show完之后立即dismiss 会报错

### ISSUE THREAD

**Issue by Linnnnnn** [kongzue/DialogX#62]
Attempt to invoke virtual method 'boolean com.kongzue.dialogx.util.views.DialogXBaseRelativeLayout.post(java.lang.Runnable)' on a null object reference

版本 40-beta1
39的时候没出现过这个问题
我在dismiss前sleep(100) 就不错报这个错了

class LoadingObserver :Observer<Boolean> {

    override fun onChanged(show: Boolean?) {
        if (show == null) return
        if (show && !WaitDialog.getInstance().isShow){
           WaitDialog.show("加载中")
        }else{
            Thread {
                Thread.sleep(100)
                WaitDialog.dismiss()
            }.start()
        }
    }
}

**Comment by kongzue** [comment]
此问题已在最新测试版修复，请更新至0.0.40.beta2
