### ISSUE TITLE
ios风格，弧度锯齿明显。

### ISSUE THREAD

**Issue by YRowis** [kongzue/DialogX#64]

**Comment by YRowis** [comment]
自定RelativeLayout实现圆角导致。建议修改方式，或者重新构建自定义后加上抗锯齿。如果强行

**Comment by kongzue** [comment]
未能在Pixel5(Android 12 DP3)上发现你所描述的问题。
iOS主题的圆角源代码于[DialogX/src/main/java/com/kongzue/dialogx/util/views/BlurView.java(346)](https://github.com/kongzue/DialogX/blob/b0fe84aa3af393b8865d16237339b59ed4b43a5c/DialogX/src/main/java/com/kongzue/dialogx/util/views/BlurView.java#L346)，在开启模糊后使用了路径裁剪：[DialogX/src/main/java/com/kongzue/dialogx/util/views/BlurView.java(360)](https://github.com/kongzue/DialogX/blob/b0fe84aa3af393b8865d16237339b59ed4b43a5c/DialogX/src/main/java/com/kongzue/dialogx/util/views/BlurView.java#L360)，前者使用了`Paint.setAntiAlias(true)`来保证处理锯齿，后者仅在暗色模式下存在一定的锯齿，但目前未能找到合适的解决方案。
![处于亮色模式时无锯齿情况](https://user-images.githubusercontent.com/10115359/121979594-0e751800-cdbd-11eb-9975-639bd21e475b.jpg)

**Comment by JadePeakPoet** [comment]
小米mix3(android9同样有次问题，暗色和亮色皆锯齿严重)

**Comment by JadePeakPoet** [comment]
> 未能在Pixel5(Android 12 DP3)上发现你所描述的问题。
> iOS主题的圆角源代码于[DialogX/src/main/java/com/kongzue/dialogx/util/views/BlurView.java(346)](https://github.com/kongzue/DialogX/blob/b0fe84aa3af393b8865d16237339b59ed4b43a5c/DialogX/src/main/java/com/kongzue/dialogx/util/views/BlurView.java#L346)，在开启模糊后使用了路径裁剪：[DialogX/src/main/java/com/kongzue/dialogx/util/views/BlurView.java(360)](https://github.com/kongzue/DialogX/blob/b0fe84aa3af393b8865d16237339b59ed4b43a5c/DialogX/src/main/java/com/kongzue/dialogx/util/views/BlurView.java#L360)，前者使用了`Paint.setAntiAlias(true)`来保证处理锯齿，后者仅在暗色模式下存在一定的锯齿，但目前未能找到合适的解决方案。
> ![处于亮色模式时无锯齿情况](https://user-images.githubusercontent.com/10115359/121979594-0e751800-cdbd-11eb-9975-639bd21e475b.jpg)

BlurView.java代码有问题，useBlur为true时，完全不会走到Paint.setAntiAlias(true)相关代码，所以抗锯齿代码就没走，同时创建的mPaint没有使用，除了锯齿的问题，也不该在draw方法里面去创建Paint，Rect和Path对象。

**Comment by kongzue** [comment]
会尝试别的方案进行处理

**Comment by kongzue** [comment]
@JadePeakPoet 已测试该方法不可行

**Comment by kongzue** [comment]
很抱歉目前依然未能找到合适的解决方案。Path.Op的方法对BlurView是无效的，而setOutlineProvider的办法也存在锯齿。目前无法找到更合理的处理方案，此问题暂时搁置。

**Comment by kongzue** [comment]
请更新至0.0.40.beta10测试版本，已修复此问题

**Comment by JadePeakPoet** [comment]
> @JadePeakPoet @YRowis 请更新至0.0.40.beta10测试版本，已修复此问题

👍
