### ISSUE TITLE
DialogX 创建的对话框 会显示在其他自定义dialog下面

### ISSUE THREAD

**Issue by zhangxyfs** [kongzue/DialogX#65]
如题, 我项目里有一些其他的自定义popup或者dialog 暂时还没办法进行统一代码, 我有页面需要从一个已有自定义Dialog中再弹出一个dialog, 在使用DialogX时候会显示在这个dialog下面, 我使用的测试机是 huawei p20 pro

**Comment by kongzue** [comment]
您好，默认情况下DialogX是使用View模式进行实现的，这主要目的是避免出现额外的需要处理的WindowLeaked问题，但这种实现方案是无法与基于Window实现模式的AlertDialog、DialogFragment等组件抢层级的，建议您将所有对话框组件迁移至DialogX，DialogX提供了丰富的自定义布局允许您实现各式各样的对话框效果。
若实在无法迁移，请尝试调整DialogX的默认实现模式为Window实现方案，但请注意该方案依然存在部分未解决的bug，方法请[参阅Wiki](https://github.com/kongzue/DialogX/wiki#%E5%AE%9E%E7%8E%B0%E6%A8%A1%E5%BC%8F)

**Comment by kongzue** [comment]
暂时关闭此问题，如有疑问欢迎继续回复。
