### ISSUE TITLE
WaitDialog关闭有问题

### ISSUE THREAD

**Issue by zhangji92** [kongzue/DialogX#67]
在Rxjava中使用时，WaitDialog.dimiss关闭等待框之后，有一层透明页面，当前页面不能进行任何操作
![image](https://user-images.githubusercontent.com/20961803/124061882-49847600-da62-11eb-8810-9f2779f37a5a.png)

**Comment by zhangji92** [comment]
![image](https://user-images.githubusercontent.com/20961803/124061850-38d40000-da62-11eb-8342-1b13e282063d.png)

**Comment by zhangji92** [comment]
![image](https://user-images.githubusercontent.com/20961803/124709264-dd0bea00-df2d-11eb-81fe-5f733cade116.png)

**Comment by kongzue** [comment]
请更新最新版本
