### ISSUE TITLE
BottomMenu出现滚动条，并且显示不完整

### ISSUE THREAD

**Issue by sceneren** [kongzue/DialogX#68]
使用的0.0.39和0.0.40.beta8都有这个问题
![image](https://user-images.githubusercontent.com/6612998/124101650-2a054180-da92-11eb-8519-7ec38f7c2093.png)
而且内容部分显示不完全
代码
![image](https://user-images.githubusercontent.com/6612998/124101867-5de06700-da92-11eb-9924-48cf32dfa83b.png)

**Comment by kongzue** [comment]
未能在Pixel5(Android 12 DP3)上复现此问题，且已上线的项目暂未收到类似的问题报告。是否有使用其他适配方案，例如autoSize，建议先尝试下载Demo运行看是否存在此问题，若依然存在请告知我系统版本和设备型号我会针对性进行测试。

**Comment by sceneren** [comment]
有使用AutoSize

**Comment by kongzue** [comment]
IOS主题下因为模糊区域是需要准确计算的，因此是根据单行列表去进行的整体高度计算，一般不会出现此问题，我们在原生模式下测试是完全没有问题的，此问题DialogX无法直接处理，建议查看下autoSize是否能豁免DialogX的布局。

**Comment by kongzue** [comment]
请更新至测试版本：0.0.41.beta1，已经尝试修复此问题。

**Comment by sceneren** [comment]
0.0.41.beta1,此bug修复了
