### ISSUE TITLE
BottomDialog显示时弹出PopTip，BottomDialog会跳动一下

### ISSUE THREAD

**Issue by YoungNatty** [kongzue/DialogX#69]

**Comment by YoungNatty** [comment]
view模式下有问题，window模式下就没有这个问题了

**Comment by kongzue** [comment]
很抱歉未能在Demo中发现此问题，能报告下您的使用环境么

________________________________
发件人: Natty ***@***.***>
发送时间: Friday, July 9, 2021 2:54:18 AM
收件人: kongzue/DialogX ***@***.***>
抄送: Subscribed ***@***.***>
主题: Re: [kongzue/DialogX] BottomDialog显示时弹出PopTip，BottomDialog会跳动一下 (#69)


view模式下有问题，window模式下就没有这个问题了

―

**Comment by YoungNatty** [comment]
https://user-images.githubusercontent.com/44336595/125217672-ce3d8280-e2f3-11eb-91bb-dd4c5eee8107.mp4

targetSdkVersion 30
DialogX:0.0.40.beta9
就是视频这种情况

**Comment by YoungNatty** [comment]
https://user-images.githubusercontent.com/44336595/125217827-32604680-e2f4-11eb-8b47-2176ad3f7d02.mp4

targetSdkVersion 30
DialogX:0.0.40.beta9
就是视频中的这种情况

**Comment by YoungNatty** [comment]
![微信截图_20210712093436](https://user-images.githubusercontent.com/44336595/125217921-650a3f00-e2f4-11eb-9e25-9c21336fb626.png)
有这些设置

**Comment by YoungNatty** [comment]
![微信截图_20210712093436](https://user-images.githubusercontent.com/44336595/125217996-879c5800-e2f4-11eb-84af-e1643f785ecc.png)
有这些设置

**Comment by kongzue** [comment]
很抱歉我依然无法复现你所描述的问题。
此问题跟全局设置没有关系，相关测试视频可以在这里下载（Pixel5 Android 12 DP3）：
链接：https://pan.baidu.com/s/1dBEn6LDdvBIS3F83l4sOzQ 
提取码：bgmn 
测试一开始采用开启动画缩放模式查看细节，后半段是关闭系统动画缩放的实际测试效果，均未出现弹跳的问题。
可能受到其他因素影响，这也许跟沉浸式实现方式有关，但DialogX在默认沉浸式适配方案下是正常工作的，尚不清楚是否为其他原因导致。

**Comment by kongzue** [comment]
因为存在一些自定义布局，在启动时无法准确计算内容高度的情况，所以BottomDialog实际上会根据内容动态调整弹出的高度位置（屏幕高度-实际内容高度），如果出现内容高度变化可能引发上述情况。
目前我也只能猜测原因，希望能找到复现的办法。

**Comment by YoungNatty** [comment]
在BottomDialog正在显示的时候弹出一下PopTip试一下，测试视频：https://user-images.githubusercontent.com/44336595/125222427-8b33dd00-e2fc-11eb-85a3-a0e01f0f6ad2.mp4

我用Pixel4 XL Android R测试也是同样的情况

**Comment by YoungNatty** [comment]
在BottomDialog正在显示的时候弹出一下PopTip试一下，测试视频：https://user-images.githubusercontent.com/44336595/125222427-8b33dd00-e2fc-11eb-85a3-a0e01f0f6ad2.mp4

我用Pixel 4 XL API S模拟器测试也是同样的情况

**Comment by kongzue** [comment]
依然未能复现此问题，在弹出PopTip时，并不会影响BottomDialog的显示，设置目前使用View模式：
![](https://user-images.githubusercontent.com/10115359/125222780-3e9cd180-e2fd-11eb-9d90-f084e207a428.png)

**Comment by YoungNatty** [comment]
你尝试一下不继承你baseframework中的BaseActivity，应该可以复现这个问题

**Comment by YoungNatty** [comment]
问题出现在沉浸式，我关闭了

**Comment by kongzue** [comment]
收到，已复现出此问题，在尝试寻找修改方案

**Comment by YoungNatty** [comment]
好的，如果找到修改方案，希望可以在公告告知

**Comment by kongzue** [comment]
会在此回复你

**Comment by kongzue** [comment]
目前检测到的是“非安全区”检测报告了异常的bottomPadding值。
在弹出其他DialogX时，触发了之前的对话框非安全区更新，正在查找原因。
![image](https://user-images.githubusercontent.com/10115359/125227122-dd78fc00-e304-11eb-9246-69bbf167f125.png)

**Comment by kongzue** [comment]
目前发现，系统通过 dispatchApplyWindowInsets 方法给出了错误的值，引发了此问题，正在查找解决方案。

**Comment by YoungNatty** [comment]
好的

**Comment by kongzue** [comment]
临时的方案解决了此问题，但有一些技术细节需要分享给你。

因为DialogX并不想“赖着不走”所以并不会持续向Activity插入一个长期的布局，而是在使用时插入对话框层布局，在关闭后卸载掉以避免占用资源，那么这意味着每次显示对话框事实上都是再建立一个新的布局添加到Activity。

在这个过程因不明原因，Activity会触发调用已显示布局的 dispatchApplyWindowInsets 方法且传入错误的值，根据错误值，会导致 BottomDialog 对屏幕底边的非安全区高度发生错误判断（就如上述日志截图所示，在PopTip显示时导致了BottomDialog接收到错误的底部非安全区高度为0）而 BottomDialog 因为是会持续对内容布局高度进行判断调整动画以适应内容布局高度可能发生变化的，在这个过程中出现外部根布局高度变化（由非安全区高度变化引发）导致对话框触发调整位置动画的过程，引发了此问题。

在我测试过程中发现，对于已适配底部沉浸式的界面是不存在此问题的，例如Demo中使用到了BaseFramework进行了沉浸式适配，而在默认不进行导航栏沉浸式适配时会出现此问题，目前根据各方案尝试后决定的处理方案是，当非安全区的left、top、right未发生变化时，bottom若被输入了0值则忽略本次沉浸式处理。

感谢你的反馈，此问题将在下一版本进行更新。

**Comment by kongzue** [comment]
请更新至0.0.40.beta10测试版本，已修复此问题

**Comment by YoungNatty** [comment]
好的，感谢

**Comment by YoungNatty** [comment]
又出现这个问题了

**Comment by YoungNatty** [comment]
又出现了这个问题

**Comment by kongzue** [comment]
长时间未收到回复，暂时关闭了此问题，如有疑问请继续回复。
