### ISSUE TITLE
Dialog Dissmiss后页面所有事件全部失效

### ISSUE THREAD

**Issue by z2700589** [kongzue/DialogX#7]
请求结束后会弹框，然后弹框点击确定后diss，但是页面上任何事件均无效果（无法滑动或者点击触摸），但是进程并没有被阻塞。

https://user-images.githubusercontent.com/22461898/103502301-c5bf4780-4e8b-11eb-8132-bf533d41c836.mp4

**Comment by kongzue** [comment]
新版本已更新修复
