### ISSUE TITLE
有NavigationBar属性吗？

### ISSUE THREAD

**Issue by 1825492258** [kongzue/DialogX#70]
我用BottomMenu 从底部弹出是白色的Bar，感觉很突兀。有NavigationBarColor属性吗？或者源码在哪里可以改成bar为自定义的颜色？？

**Comment by kongzue** [comment]
请使用setBackgroundColor修改。DialogX默认是支持沉浸式的，你只需要修改对话框背景颜色即可，如果你的Activity未进行导航栏沉浸式建议使其透明，你可以在Demo中看到运行效果。
________________________________
发件人: wuzongjie ***@***.***>
发送时间: Friday, July 9, 2021 1:56:55 PM
收件人: kongzue/DialogX ***@***.***>
抄送: Subscribed ***@***.***>
主题: [kongzue/DialogX] 有NavigationBar属性吗？ (#70)


我用BottomMenu 从底部弹出是白色的Bar，感觉很突兀。有NavigationBarColor属性吗？或者源码在哪里可以改成bar为自定义的颜色？？

―

**Comment by 1825492258** [comment]
这个属性setBackgroundColor不太满足。
我想再问下 我用InputDialog，代码跟demo一样的。为什么我弹的时候键盘把dialog挡住了？？ 有什么特别的属性处理吗？？

**Comment by kongzue** [comment]
请查看wiki常见问题
________________________________
发件人: wuzongjie ***@***.***>
发送时间: Wednesday, July 14, 2021 2:44:24 PM
收件人: kongzue/DialogX ***@***.***>
抄送: Kongzue ***@***.***>; Comment ***@***.***>
主题: Re: [kongzue/DialogX] 有NavigationBar属性吗？ (#70)


这个属性setBackgroundColor不太满足。
我想再问下 我用InputDialog，代码跟demo一样的。为什么我弹的时候键盘把dialog挡住了？？ 有什么特别的属性处理吗？？

―

**Comment by 1825492258** [comment]
可以了。android:windowSoftInputMode="adjustResize"
