### ISSUE TITLE
消息对话框仅设置标题或内容时，上下边距布局异常

### ISSUE THREAD

**Issue by JadePeakPoet** [kongzue/DialogX#71]
消息对话框仅设置标题或内容时，布局异常，当仅设置内容时，异常更为明显
应该把内容和标题视为统一的整体设置上下边距，同时内容与标题之间间隙通过margin来代替padding进行约束，否则其中之一隐藏时，上下边距会与预期不符

**Comment by kongzue** [comment]
当前设计的目的是为了方便使用自定义CustomView时，可以允许无外置边距的完全自定义整个对话框的内容区域。若您需要控制padding或margin，您可以使用 `getDialogImpl()`：
```
.setDialogLifecycleCallback(new DialogLifecycleCallback<MessageDialog>() {
    @Override
    public void onShow(MessageDialog dialog) {
        dialog.getDialogImpl().txtDialogTip    //To do
    }
});
```
来获取对话框的实例进行控制。

**Comment by JadePeakPoet** [comment]
> 当前设计的目的是为了方便使用自定义CustomView时，可以允许无外置边距的完全自定义整个对话框的内容区域。若您需要控制padding或margin，您可以使用 `getDialogImpl()`：
> 
> ```
> .setDialogLifecycleCallback(new DialogLifecycleCallback<MessageDialog>() {
>     @Override
>     public void onShow(MessageDialog dialog) {
>         dialog.getDialogImpl().txtDialogTip    //To do
>     }
> });
> ```
> 
> 来获取对话框的实例进行控制。

ok明白，我自己这边因为需求的情况所以采取了DialogFragment进行拓展（因为需要横竖屏切换保持dialog存在，目前本库不支持），参照了DialogX的一些思想，所以也是想帮助DialogX，提出一些自己的建议

边距异常这个行为，和原生的dialog不一致，自定义view区域完全操作这是一个合理的诉求，但个人认为，在使用material design风格时，预期最好是能默认与原生一致，至少不会出现原本简单的操作，变得非常复杂，不处理就觉得有些像是bug的情形。

同时仅设置title/内容的场景应该也远超过customView的场景，前者本身是简单使用的场景，对于这种基本场景自己实现dialog，就是一个非常重的操作，后者自定义view，本来就需要额外做很多工作，所以可以想办法针对自定义view提供功能让其进行自定义。

当采用自定义view的时候，怎么处理边距，我有几个思路可以探讨，可以单独或组合使用
1、自定义view与通用对话框内容组合同级，上下默认边距设置在通用对话框内容区域上（这种方法操作起来最简单）
2、如果有自定义view和tip同时显示的需求，那么在1的基础上，保留两个自定义view，外部整体自定义与内部部分自定义，但实际上这部分需求应该不强，1也可以包容2的需求
3、view inflate之后，对外回调暴露当前dialog view，用户可以对这些基础上做一些操作而不需要自定义实现DialogImpl（比如获取到内容区域root，设置其边距）

**Comment by kongzue** [comment]
感谢你的反馈。
DialogX是支持横竖屏切换的，但需要您自行配置Activity不要因为横竖屏切换自动重启即可，这点在Demo中也是有实现的。
关于上述所述的设计思路，我印象中也是有人提了相关建议所以这样做的，应该是在之前的V3库中，这个设计呗保留了下来。
另外因为需要照顾其他主题的缘故，对于布局的结构暂时不会进行修改，以防止出现未知的问题。

**Comment by JadePeakPoet** [comment]
> 感谢你的反馈。
> DialogX是支持横竖屏切换的，但需要您自行配置Activity不要因为横竖屏切换自动重启即可，这点在Demo中也是有实现的。
> 关于上述所述的设计思路，我印象中也是有人提了相关建议所以这样做的，应该是在之前的V3库中，这个设计呗保留了下来。
> 另外因为需要照顾其他主题的缘故，对于布局的结构暂时不会进行修改，以防止出现未知的问题。

ok
