### ISSUE TITLE
希望能给WaitDialog添加非单例的支持

### ISSUE THREAD

**Issue by Orienser** [kongzue/DialogX#72]
例如有这么个场景：
1. 需要进行一个耗时操作，在操作开始前显示一个WaitDialog。
2. 耗时操作的逻辑部分委托给他人实现，如果其他人也在代码中使用了WaitDialog并调用了dismiss()方法，那第1步中的WaitDialog也会一起消失。

因此希望能给WaitDialog添加非单例的支持，可创建多个实例，而非全局共享一个me变量。

**Comment by kongzue** [comment]
当前版本有以下方法提供独立的实现：
```
WaitDialog waitDialog = WaitDialog.build();
```
但请注意它会替换当前存在的单例实例。目前对 WaitDialog 进行单例设计的主要目的是为了保证其与 TipDialog 可以无缝衔接，若不这么做可能出现无法过度的情况。

**Comment by kongzue** [comment]
请尝试最新的测试版本：0.0.40.beta13
