### ISSUE TITLE
主题库是否可以改成public,否则调不到

### ISSUE THREAD

**Issue by 15114846648** [kongzue/DialogX#73]
/**
 * @author: Kongzue
 * @github: https://github.com/kongzue/
 * @homepage: http://kongzue.com/
 * @mail: myzcxhh@live.cn
 * @createTime: 2020/9/26 17:04
 */
public class MIUIStyle implements DialogXStyle {
    
    private MIUIStyle() {
    }
    
    public static MIUIStyle style() {
        return new MIUIStyle();
    }
    
    @Override
    public int layout(boolean light) {
        return light ? R.layout.layout_dialogx_miui : R.layout.layout_dialogx_miui_dark;
    }

**Comment by kongzue** [comment]
请更新版本

**Comment by kongzue** [comment]
主题库是需要和主库保持同一版本的
