### ISSUE TITLE
CustomDialog 在自定义布局中添加动画后如果调用setCancelable后动画失效

### ISSUE THREAD

**Issue by iiouoii** [kongzue/DialogX#77]
CustomDialog customDialog =
                CustomDialog.build().show(new OnBindView<CustomDialog>(com.pbase.R.layout.loading) {
            @Override
            public void onBind(CustomDialog dialog, View v) {
                ImageView loging = v.findViewById(com.pbase.R.id.img_loging);
                RotateAnimation animation = new RotateAnimation(0, 359,
                        Animation.RELATIVE_TO_SELF, 0.5f, Animation.RELATIVE_TO_SELF, 0.5f);
                animation.setDuration(2000);
                animation.setRepeatCount(-1);
                animation.setInterpolator(new LinearInterpolator());//旋转效果
                loging.setAnimation(animation);

            }
        }).setCancelable(false);

**Comment by kongzue** [comment]
您好，未能在最新的版本的Demo中复现您所描述的问题。
经过测试，`setCancelable(false);` 正常生效，对话框无法通过外部点击或返回键关闭。
测试代码：
```
CustomDialog customDialog =
        CustomDialog.build().show(new OnBindView<CustomDialog>(R.layout.layout_custom_dialog) {
            @Override
            public void onBind(CustomDialog dialog, View v) {
                View loging = v.findViewById(R.id.btn_ok);
                RotateAnimation animation = new RotateAnimation(0, 359,
                        Animation.RELATIVE_TO_SELF, 0.5f, Animation.RELATIVE_TO_SELF, 0.5f);
                animation.setDuration(2000);
                animation.setRepeatCount(-1);
                animation.setInterpolator(new LinearInterpolator());//旋转效果
                loging.setAnimation(animation);
    
            }
        }).setCancelable(false);
```
测试设备：Pixel5 Android 12 SPB3
测试截图：
![image](https://user-images.githubusercontent.com/10115359/125730780-f533942f-b7f8-4556-beaf-62c235f2a2ae.png)

**Comment by iiouoii** [comment]
> 您好，未能在最新的版本的Demo中复现您所描述的问题。
> 经过测试，`setCancelable(false);` 正常生效，对话框无法通过外部点击或返回键关闭。
> 测试代码：
> 
> ```
> CustomDialog customDialog =
>         CustomDialog.build().show(new OnBindView<CustomDialog>(R.layout.layout_custom_dialog) {
>             @Override
>             public void onBind(CustomDialog dialog, View v) {
>                 View loging = v.findViewById(R.id.btn_ok);
>                 RotateAnimation animation = new RotateAnimation(0, 359,
>                         Animation.RELATIVE_TO_SELF, 0.5f, Animation.RELATIVE_TO_SELF, 0.5f);
>                 animation.setDuration(2000);
>                 animation.setRepeatCount(-1);
>                 animation.setInterpolator(new LinearInterpolator());//旋转效果
>                 loging.setAnimation(animation);
>     
>             }
>         }).setCancelable(false);
> ```
> 
> 测试设备：Pixel5 Android 12 SPB3
> 测试截图：
> ![image](https://user-images.githubusercontent.com/10115359/125730780-f533942f-b7f8-4556-beaf-62c235f2a2ae.png)

您好可能是我没描述清，.setCancelable(false)是正常执行的，但是设置.setCancelable(false)后中间自定义布局添加的动画效果失效了

**Comment by kongzue** [comment]
但是上述代码我在Demo中尝试运行，就如截图一样是正常运行动画的，您也可以从Github拉取DialogX源代码，在Demo然后尝试运行上述代码进行尝试。

**Comment by iiouoii** [comment]
> 但是上述代码我在Demo中尝试运行，就如截图一样是正常运行动画的，您也可以从Github拉取DialogX源代码，在Demo然后尝试运行上述代码进行尝试。

找到问题了，我导包的时候使用latest.release拉取，改成0.0.40.beta13就正常了
