### ISSUE TITLE
是否可以开放下那三个按钮的使能？

### ISSUE THREAD

**Issue by phoebewow** [kongzue/DialogX#8]
有时候需要达到某个条件时，才允许那个按钮可以点击，比如在InputDialog，需要检查内容正确后才允许点击确定按钮。

**Comment by kongzue** [comment]
请查看wiki文档。
https://github.com/kongzue/DialogX/wiki/%E5%9F%BA%E7%A1%80%E5%AF%B9%E8%AF%9D%E6%A1%86-MessageDialog-%E5%92%8C-%E8%BE%93%E5%85%A5%E5%AF%B9%E8%AF%9D%E6%A1%86-InputDialog#%E6%8C%89%E9%92%AE%E7%82%B9%E5%87%BB%E5%9B%9E%E8%B0%83
回调中有一个返回值，若return true 则可以点击后不自动关闭对话框。

若您需要直接控制按钮的可点击性，也可以通过
```
.setDialogLifecycleCallback(new DialogLifecycleCallback<MessageDialog>() {
            @Override
            public void onShow(MessageDialog dialog) {
                //对话框启动时回调
                //控制“OK”按钮的可用性：
                dialog.getDialogImpl().btnSelectPositive.setEnabled(true);
                //控制“Cancel”按钮的可用性
                dialog.getDialogImpl().btnSelectNegative.setEnabled(true);
                //控制“Other”按钮的可用性
                dialog.getDialogImpl().btnSelectOther.setEnabled(true);
            }
   })
```
在对话框完全启动后，你可以通过控制`dialog.getDialogImpl()`来直接修改或处理对话框内部组件，DialogX的灵活性足够满足大部分应用场景的修改需要。

**Comment by phoebewow** [comment]
好的，明白了，谢谢

**Comment by phoebewow** [comment]
抱歉，关于这个按钮的使能还需要问下，当enabled为否的时候，按钮文字颜色需要变灰，有没比较快捷的修改方式？每个调用都去改的话，还真是比较麻烦耶。。。

**Comment by kongzue** [comment]
@phoebewow 这三个按钮本质上是TextView，需要的话得手动修改drawable或者textColor样式

**Comment by phoebewow** [comment]
好的，谢谢。。。我搞了个类来专门做这些操作。。
