### ISSUE TITLE
BottomMenu iOS风格， 这条黑线如何去除

### ISSUE THREAD

**Issue by xiechunjiang** [kongzue/DialogX#81]
<img width="267" alt="82b262ff48ebbe51393abf0a57ffb56" src="https://user-images.githubusercontent.com/12966578/126440260-d7859460-c2b2-4ceb-8c27-6f99018e0c11.png">

**Comment by kongzue** [comment]
抱歉，这个之前是没注意到的遗留问题，会在下一个版本中删掉。

**Comment by kongzue** [comment]
请更新至测试版本：0.0.41.beta1，已经尝试修复此问题。

**Comment by xiechunjiang** [comment]
hi,0.0.41.beta1版本,我这边测试了下，如果用BottomDialog，BottomMenu show中使用new OnBindView 还会存在（demo中底部对话框按钮功能），另外，底部多选菜单会报错如图
![1627024408(1)](https://user-images.githubusercontent.com/12966578/126748959-0a3cb8ac-ac63-45bb-badf-6bd039546473.jpg)
：

**Comment by kongzue** [comment]
请问您使用的Style版本是？请保持和DialogX主库版本一致后再试下

**Comment by xiechunjiang** [comment]
style版本是，这是最新的吧
![1627033392(1)](https://user-images.githubusercontent.com/12966578/126765009-e42b8bfd-9dd8-4339-b86c-01bfe02fc03c.jpg)

**Comment by kongzue** [comment]
不是

**Comment by kongzue** [comment]
![image](https://user-images.githubusercontent.com/10115359/126766579-949fd6fc-40c2-4341-a6a5-63cf09193751.png)
请按照上述的版本号，或与主库保持一致

**Comment by xiechunjiang** [comment]
Hi,错误不报了，不过黑线我这边，在使用自定义布局还有，不知道是啥问题

**Comment by kongzue** [comment]
我这边用demo看是没这问题了…
________________________________
发件人: xiechunjiang ***@***.***>
发送时间: Friday, July 23, 2021 6:16:15 PM
收件人: kongzue/DialogX ***@***.***>
抄送: Kongzue ***@***.***>; Comment ***@***.***>
主题: Re: [kongzue/DialogX] BottomMenu iOS风格， 这条黑线如何去除 (#81)


Hi,错误不报了，不过黑线我这边，在使用自定义布局还有，不知道是啥问题

―

**Comment by kongzue** [comment]
我这边再查一下吧

**Comment by xiechunjiang** [comment]
哦，好吧，我当时是因为issues68 问题，改的自定义列表，不过现在issues68也可以了正常显示了我就改为直接填入数据了。谢谢解答，辛苦
