### ISSUE TITLE
minSdkVersion

### ISSUE THREAD

**Issue by android-1995** [kongzue/DialogX#82]
大佬，你这个库的minSdkVersion是21，我的项目是19，直接覆盖到19会有问题吗？
库的ui很好看，扩展也自由，感谢开源

**Comment by kongzue** [comment]
应该没问题，我没测过。
但你需要自己引入代码修改gradle中的minSDKVersion配置

**Comment by JadePeakPoet** [comment]
> 大佬，你这个库的minSdkVersion是21，我的项目是19，直接覆盖到19会有问题吗？
> 库的ui很好看，扩展也自由，感谢开源

Android21现在用的其实很少了，微信minSDKVersion也早就已经改为21了（android5.0，而且我尝试了，微信在android5.0上运行已经灰常卡了），所以其实可以直接升级原项目minSdkVersion了

**Comment by android-1995** [comment]
> > 大佬，你这个库的minSdkVersion是21，我的项目是19，直接覆盖到19会有问题吗？
> > 库的ui很好看，扩展也自由，感谢开源
> 
> Android21以下现在用的其实很少了，几乎可以忽略不记，微信minSDKVersion也早就已经改为21了（android5.0，而且我尝试了，微信在android5.0上运行已经灰常卡了），所以其实可以直接升级原项目minSdkVersion了

话虽如此，但是作为三方库还是支持的minSDKVersion低一点会好点
![image](https://user-images.githubusercontent.com/35674533/126733173-59a39652-091d-4c9c-9ad3-09f7e3838009.png)
