### ISSUE TITLE
It frequently throw context null

### ISSUE THREAD

**Issue by hopnv94** [kongzue/DialogX#83]
com.kongzue.dialogx.dialogs.BottomDialog$DialogImpl$6.run (BottomDialog.java:409)

I think the reason is context is saved in WeakReference

**Comment by kongzue** [comment]
Please update your version, in the latest version [BottomDialog.java:409](https://github.com/kongzue/DialogX/blob/fce243d7ccfad9f47e727c31546616d69471ddf9/DialogX/src/main/java/com/kongzue/dialogx/dialogs/BottomDialog.java#L409), it no longer contains the code you mentioned

**Comment by kongzue** [comment]
This issue is temporarily closed due to a long period of time without receiving a response.
Please continue to reply if you have any questions.
