### ISSUE TITLE
0.0.39自定义PopTip设置ios style，会把返回键监听，导致我写的返回的方法失效，0.0.40依旧有问题，且默认style下，位置设置不生效

### ISSUE THREAD

**Issue by MONGCHIAOHAY** [kongzue/DialogX#84]

**Comment by kongzue** [comment]
您好，未能在Demo中复现您所描述的问题。
在正常情况下启动PopTip，然后使用返回键，Activity正常接收onBackPressed事件，未发现任何问题。
请尝试拉取源代码运行，如果能在Demo中复现此问题，可能是设备问题，请告知设备型号及系统版本。
若不能复现，请检查您的项目是否存在其他可能影响的因素。
祝您生活愉快。

**Comment by MONGCHIAOHAY** [comment]
并不是设备问题，我使用多个设备测试问题依旧，在这两个版本中poptip出现的时候，onBackPressed会失效，此情况出现在我双击退出程序时，弹出提示框出现此bug，您可以尝试使用您的自定义PopTip。
![image](https://user-images.githubusercontent.com/51981062/127093804-0ceb984b-258d-47ca-8b23-220f24e3087e.png)

**Comment by MONGCHIAOHAY** [comment]
且此自定义方法下，miuistyle显示也有问题

**Comment by kongzue** [comment]
您好，我无法完全模拟你的代码，但模拟了相似的逻辑：
```
PopTip.build()
        .setCustomView(new OnBindView<PopTip>(R.layout.layout_custom_view) {
            @Override
            public void onBind(PopTip dialog, View v) {
                dialog.setAutoTintIconInLightOrDarkMode(false);
                ImageView imgIco;
                imgIco = v.findViewById(R.id.img_ico);
                imgIco.setTag("A");
            }
        })
        .setStyle(IOSStyle.style())
        .setAlign(DialogXStyle.PopTipSettings.ALIGN.TOP)
        .show();
```
在Demo中运行，未发现会阻止返回键操作的情况发生。
另外关于`.setAlign`方法无效，原因是实际上会受到主题的影响，请参阅自定义主题章节，或参考库 [kongzue/DialogXStyle-Snackbar](https://github.com/kongzue/DialogXStyle-Snackbar) 的代码进行修改。

**Comment by kongzue** [comment]
另外附上测试环境：最新版本的代码（0.0.41.beta1）但已知的是近期未对PopTip组件进行任何更新。
测试机器：Pixel5 Android12 SPB3

**Comment by kongzue** [comment]
暂时关闭了此问题，如有疑问请继续回复
