### ISSUE TITLE
WaitDialog的软键盘相关问题

### ISSUE THREAD

**Issue by android-1995** [kongzue/DialogX#87]
复现流程：
1.demo的activity_main 增加EditText控件，并且设置android:inputType="number"
2.实现方式设置为View
3.运行并且用editText弹出键盘，然后弹出等待对话框
![image](https://user-images.githubusercontent.com/35674533/127725640-dfb64b29-8290-4a72-9891-8c97308428c2.png)
![image](https://user-images.githubusercontent.com/35674533/127725647-cde04e64-f2fc-4ea6-aca5-0fb4c752a0a8.png)

**Comment by android-1995** [comment]
补充一下：当布局中有多个editText的时候，还会导致editText的焦点错乱。
复现流程：
1.demo中加两个EditText
2.手动把焦点移动到第二个EditText
3.弹出等待对话框
对话框结束后焦点就移动到第一个EditText了

**Comment by kongzue** [comment]
收到，会想办法处理。
但此问题本质上还是Android自身的问题。
在布局出现新增和卸载的时候对焦点的继承转移存在问题，DialogX此前针对InputDialog在关闭时隐藏输入法已经进行了处理，但没有考虑到已弹出输入法时启动对话框的情况，下一版会针对性进行处理。
感谢反馈，祝开发顺利！

**Comment by android-1995** [comment]
> 收到，会想办法处理。
> 但此问题本质上还是Android自身的问题。
> 在布局出现新增和卸载的时候对焦点的继承转移存在问题，DialogX此前针对InputDialog在关闭时隐藏输入法已经进行了处理，但没有考虑到已弹出输入法时启动对话框的情况，下一版会针对性进行处理。
> 感谢反馈，祝开发顺利！

这种情况还是常见的，我发现的时候是在写登录页面，填写手机号后点击发送验证码。
第一个问题还是挺影响的，第二个问题倒还好点。

感谢开源

**Comment by kongzue** [comment]
请等待下一个测试版本，我会尽快完成修改并提交

**Comment by kongzue** [comment]
请升级至 0.0.41.beta7 版本已处理此问题。
以下是一些技术细节：
在 [BaseDialog.java:408](https://github.com/kongzue/DialogX/blob/5c77d7d34059882a02cf1f282552cec50731444d/DialogX/src/main/java/com/kongzue/dialogx/interfaces/BaseDialog.java#L408) 增加了关闭输入法的代码，此方法会自动执行，无需手动处理。
