### ISSUE TITLE
WaitDialog不显示message

### ISSUE THREAD

**Issue by android-1995** [kongzue/DialogX#88]
`WaitDialog.show(MainActivity.this,"Please Wait!")`
👆没有文字

**Comment by kongzue** [comment]
请确认您正在使用 DialogX 框架。
DialogX 中的 WaitDialog 构建方法并不包含 context 参数。

**Comment by android-1995** [comment]
![image](https://user-images.githubusercontent.com/35674533/127795379-2427404e-a959-423d-9bde-7429f13cb086.png)
![image](https://user-images.githubusercontent.com/35674533/127795396-5a20fb58-e16f-41cb-9441-08919b5202d7.png)

**Comment by kongzue** [comment]
好吧，我忘了，待查证

**Comment by kongzue** [comment]
请更新至测试版本 0.0.41.beta11，或者等待下一个测试版本。

**Comment by android-1995** [comment]
> 请更新至测试版本 0.0.41.beta11，或者等待下一个正式版本。

文字可以正常显示。发现
`WaitDialog.dismiss()` 不能关弹窗了，是否可以加个WaitDialog.dismiss(Activity activity)的方法？

**Comment by kongzue** [comment]
请更新至 0.0.41.beta12 版本。
但个人建议不要对非处于活动状态的 Activity 进行 WaitDialog 的显示或关闭，因为 所有对话框组件均需要 post 到 UI 线程执行。

**Comment by android-1995** [comment]
> 请更新至 0.0.41.beta12 版本。
> 但个人建议不要对非处于活动状态的 Activity 进行 WaitDialog 的显示或关闭，因为 所有对话框组件均需要 post 到 UI 线程执行。

我也觉得，但是有这个显示方法就还是要有对应的关闭方法

**Comment by kongzue** [comment]
稍等，请更新至 0.0.41.beta13，刚刚12代码没上传成功
