### ISSUE TITLE
底部对话框自定义布局问题

### ISSUE THREAD

**Issue by Forevery1** [kongzue/DialogX#89]
在自定义布局中用recyclerView。向下滑动一下就会关闭，而且会抖动。（recyclerView定高）
类似抖音评论哪个界面

**Comment by kongzue** [comment]
请更新至版本：0.0.41.beta14，但因为涉及到滑动布局相关操作，您需要自定义滑动布局并实现一个接口，建议参考最新 Demo 代码中关于 RecycleView 的处理方案。
请参考：[CustomRecycleView.java](https://github.com/kongzue/DialogX/blob/master/app/src/main/java/com/kongzue/dialogxdemo/custom/CustomRecycleView.java)
并且我已在最新的版本代码中提交了 Demo 相关示例，您也可以下载最新版本的 Demo 进行体验。
![image](https://user-images.githubusercontent.com/10115359/128279866-31af98d9-9d22-4e52-9a2d-c318aa9553a6.png)
Demo 已编译版本下载：http://beta.kongzue.com/DialogXDemo

**Comment by Forevery1** [comment]
非常感谢，我这边试试。
