### ISSUE TITLE
BaseDialog这类有点问题，当我在oncreate方法里面直接new MessageDialog（）时 无法真正移除MessageDialog布局（具体可以把动画去掉验证），以至于无法通过按返回键finish调activity，我在BaseDialog里面加了行代码，解决了  不知道合适不 麻烦看一下，具看图片，我不知道为什么之前不能移除，

### ISSUE THREAD

**Issue by SamSongShan** [kongzue/DialogX#9]
![image](https://user-images.githubusercontent.com/15811961/105860898-10665680-6029-11eb-91e7-050c7c6f331c.png)

**Comment by kongzue** [comment]
这里存在一个问题是，rootFrameLayout会跟随当前Activity变化而变化，这样做有可能存在，当切换了Activity后无法dismiss掉之前创建的对话框，而dislogView实际上只会跟随其父布局被卸载，dismiss方法的代码已经在最新版本中被修改：
```
if (rootFrameLayout == null || dialogView == null) return;
if (dialogView.getParent() == null || !(dialogView.getParent() instanceof ViewGroup)) {
    rootFrameLayout.get().removeView(dialogView);
} else {
    ((ViewGroup) dialogView.getParent()).removeView(dialogView);
}
```
这样是更合理的处理方式，正常情况下使用getParent()获取其父布局直接remove掉是应该能够保证绝对准确的。

**Comment by SamSongShan** [comment]
好的  感谢解惑

**Comment by SamSongShan** [comment]
Dialog Dissmiss后页面所有事件全部失效  和这里应该是一个问题吧

**Comment by kongzue** [comment]
不清楚，目前我未能复现类似的问题

**Comment by kongzue** [comment]
暂时关闭了此问题，若有疑问可以继续留言。
