### ISSUE TITLE
41版本影响了APP整体样式

### ISSUE THREAD

**Issue by gazerhuang** [kongzue/DialogX#91]
![截图](https://user-images.githubusercontent.com/26590208/128825118-dc4e880f-2bd4-4844-b54a-0a33d0165a41.png)
用了41整个APP变沉浸式了……

**Comment by kongzue** [comment]
很抱歉此问题暂时不会进行处理，原因是这是为了解决另一个问题：[issues:69](https://github.com/kongzue/DialogX/issues/69)，问题的根本原因在于非沉浸式的情况下 Android 会在根布局添加其他新布局时给已存在的根布局返回错误的 windowInsets，而这个值决定了沉浸式相关判断导致其他问题的发生。
个人建议尝试在Activity根布局加入`android:fitsSystemWindows="true"`来完成沉浸式适配。

**Comment by kongzue** [comment]
相关处理代码在[ActivityLifecycleImpl.java:113]：https://github.com/kongzue/DialogX/blob/1724afa2ef68c6b76b8bea4b6775d776e54945df/DialogX/src/main/java/com/kongzue/dialogx/impl/ActivityLifecycleImpl.java#L113

**Comment by gazerhuang** [comment]
适配问题不大的，可能要麻烦您在使用说明里加一句

**Comment by kongzue** [comment]
请更新至 0.0.43.beta2 版本，并在初始化时添加设置：
```
DialogX.useActivityLayoutTranslationNavigationBar = false;
```
将关闭对话框布局延伸至导航栏背后显示的 Flag；
