### ISSUE TITLE
请问有木有dialog弹出位置相对某个view的方法

### ISSUE THREAD

**Issue by youngzm** [kongzue/DialogX#92]
比如在某个控件上方 或者在屏幕的某个坐标上弹出 类似popwindow

**Comment by kongzue** [comment]
暂时没有，我们正在考虑增加类似于 PopMenu 的组件

**Comment by kongzue** [comment]
再最新的测试版本中已经增加了 PopMenu 组件，但建议还是等到正式版更新后使用，目前文档未完善。
PopMenu 支持在指定 View 上叠加/不叠加显示一个菜单，并设置相对位置，也支持自定义布局，但主要还是以显示菜单为主体功能。

**Comment by kongzue** [comment]
暂时关闭了此问题，如有需要请继续留言回复。
