### ISSUE TITLE
对话框区域外没有一层遮罩了

### ISSUE THREAD

**Issue by lumia1999** [kongzue/DialogX#93]
对话框区域外没有一层遮罩了

**Comment by kongzue** [comment]
请更新最新版本
________________________________
发件人: lumia1999 ***@***.***>
发送时间: Wednesday, August 11, 2021 6:01:34 PM
收件人: kongzue/DialogX ***@***.***>
抄送: Subscribed ***@***.***>
主题: [kongzue/DialogX] 对话框区域外没有一层遮罩了 (#93)


对话框区域外没有一层遮罩了

―

**Comment by lumia1999** [comment]
切换到0.0.43.beta1了  还是一样么  并没有解决啊？

**Comment by kongzue** [comment]
您好，在0.0.42版本的Demo中未能复现您所描述的问题
![测试截图](https://user-images.githubusercontent.com/10115359/129365054-a5dc9219-4d45-4708-899b-4888650604dd.png)

**Comment by lumia1999** [comment]
漏掉了这个方法导致的setMaskColor，确实不存在该问题了

**Comment by kongzue** [comment]
没理解您的意思
