### ISSUE TITLE
关于toolbar

### ISSUE THREAD

**Issue by kobayashi-is-god** [kongzue/DialogX#94]
有个奇怪的问题，我更新后toolbar被压没了一半

**Comment by kongzue** [comment]
目前猜测与 [issues:91](https://github.com/kongzue/DialogX/issues/91) 有关，建议进行沉浸式适配

**Comment by kongzue** [comment]
请更新至 0.0.43.beta2 版本，并在初始化时添加设置：
```
DialogX.useActivityLayoutTranslationNavigationBar = false;
```
将关闭对话框布局延伸至导航栏背后显示的 Flag；

**Comment by kobayashi-is-god** [comment]
好的

**Comment by kongzue** [comment]
暂时关闭了此问题，若有疑问请继续回复
