### ISSUE TITLE
很多问题,开发中没法使用

### ISSUE THREAD

**Issue by zhao-pf** [kongzue/DialogX#95]
![image](https://user-images.githubusercontent.com/27126222/129438743-a77e4134-aa74-4a5d-976a-3117f2342a96.png)
dialog不能关闭暗色背景等等问题,反正是用了几个实际开发中都不能用上

**Comment by kongzue** [comment]
请尝试Demo看是否能复现此问题，若能复现，请告知设备和系统版本以便于我们排查普遍性问题；若不能，请检查您的APP代码设计是否存在会导致冲突的组件。

**Comment by kongzue** [comment]
暂时关闭了此问题，如有疑问可继续回复
