### ISSUE TITLE
Dialog内容使用SpannableString时，颜色会异常

### ISSUE THREAD

**Issue by tiansan** [kongzue/DialogX#96]
![微信截图_20210816165009](https://user-images.githubusercontent.com/26215198/129537486-9a83a2b0-5026-4dc1-86bf-3cfab8d9c113.png)

代码：1、
MessageDialog.build()
            .setTitle("温馨提示")
            .setMessage(getMessage())
            .setOkButton("同意")
            .setCancelButton(
                "暂不使用"
            ) { _, _ ->
                PopTip.show("点击暂不使用按钮")
                false
            }
            .setOkButton { _, _ ->
                PopTip.show("点击确定按钮")
                false
            }
            .show(this)

代码：2、
 private fun getMessage(): CharSequence {
        val content = resources.getString(R.string.user_privacy2)
        val spanString = SpannableString(content)
        val colorSpan = ForegroundColorSpan(Color.parseColor("#0000ff"))
        val privacy: ClickableSpan = object : ClickableSpan() {
            override fun onClick(widget: View) {
                PopTip.show("隐私政策")
            }
        }
        val agreement: ClickableSpan = object : ClickableSpan() {
            override fun onClick(widget: View) {
                PopTip.show("服务协议")
            }
        }
        spanString.setSpan(agreement, 7, 13, Spannable.SPAN_EXCLUSIVE_EXCLUSIVE)
        spanString.setSpan(privacy, 14, 20, Spannable.SPAN_EXCLUSIVE_EXCLUSIVE)
        spanString.setSpan(colorSpan, 7, 13, Spannable.SPAN_EXCLUSIVE_EXCLUSIVE)
        spanString.setSpan(colorSpan, 14, 20, Spannable.SPAN_EXCLUSIVE_EXCLUSIVE)
        return spanString
    }

**Comment by tiansan** [comment]
服务协议颜色异常，隐私政策颜色正常。

**Comment by kongzue** [comment]
您好，DialogX内部仅进行了AppCompatTextView#setText方法，请自行检查代码逻辑。

**Comment by kongzue** [comment]
具体请参考：[BaseDialog.java:348](https://github.com/kongzue/DialogX/blob/93e3030e3190066112ea29bbb9d2bca96b70d9f2/DialogX/src/main/java/com/kongzue/dialogx/interfaces/BaseDialog.java#L348)
