### ISSUE TITLE
Title为空时，样式顶部需要加间隔

### ISSUE THREAD

**Issue by tiansan** [kongzue/DialogX#97]
![微信截图_20210817095838](https://user-images.githubusercontent.com/26215198/129651853-a0df6182-43a3-4e20-9f1d-b6a13f6ec2e0.png)
版本0.0.43.bate3

**Comment by kongzue** [comment]
您好，这种情况建议使用以下方法实现：
```
MessageDialog.show(null, "这里是正文内容。", "确定").setOkButton(new OnDialogButtonClickListener<MessageDialog>() {
    @Override
    public boolean onClick(MessageDialog baseDialog, View v) {
        PopTip.show("点击确定按钮");
        return false;
    }
}).setDialogLifecycleCallback(new DialogLifecycleCallback<MessageDialog>() {
    @Override
    public void onShow(MessageDialog dialog) {
        dialog.getDialogImpl().txtDialogTip.setPadding(0,dip2px(30),0,0);
    }
});
```
因为要考虑可定制性，所以 DialogX 并没有设置对话框额外的边距（例如在不设置任何标题、正文情况下单纯使用自定义布局的情况等），您可以手动实现这种效果，但我更建议标题采用“提示”等文案而不是完全忽略标题。

另外这种情况您也可以将标题设为正文内容，然后通过 `.setTitleTextInfo(new TextInfo().setBold(false))` 来关闭粗体显示。
