### ISSUE TITLE
底部弹出对话框挡住了虚拟导航键

### ISSUE THREAD

**Issue by lumia1999** [kongzue/DialogX#98]
底部弹出对话框挡住了虚拟导航键

**Comment by lumia1999** [comment]
> 底部弹出对话框挡住了虚拟导航键

demo也存在这个问题

**Comment by kongzue** [comment]
您好，首先虚拟导航键并不能被第三方APP遮盖，其次，DialogX中这个效果叫做沉浸式，并不是“挡住了虚拟导航键”，因此并不算bug。

**Comment by lumia1999** [comment]
可以加你联系方式吗？

**Comment by kongzue** [comment]
Readme中有反馈群号：590498789
![image](https://user-images.githubusercontent.com/10115359/129691077-d7c7767c-af58-4515-8822-40165d4be583.png)

**Comment by kongzue** [comment]
暂时关闭了此问题，如有疑问可继续回复

**Comment by AreYReady** [comment]
测试，在dialogfragment模式中会出现，在view模式中正常。
<img width="552" alt="image" src="https://user-images.githubusercontent.com/13625746/185078944-bccd2421-d3af-4ded-9edb-570717e718d7.png">

**Comment by kongzue** [comment]
不建议使用实验性功能，在文档中已经提示过了
________________________________
发件人: AreYReady ***@***.***>
发送时间: Wednesday, August 17, 2022 5:00:51 PM
收件人: kongzue/DialogX ***@***.***>
抄送: Kongzue ***@***.***>; State change ***@***.***>
主题: Re: [kongzue/DialogX] 底部弹出对话框挡住了虚拟导航键 (#98)


测试，在dialogfragment模式中会出现，在view模式中正常。
[image]<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F13625746%2F185078944-bccd2421-d3af-4ded-9edb-570717e718d7.png&data=05%7C01%7C%7Cf074c36400404cc7db4b08da802efc78%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637963236543990707%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=yyY3%2FsouKvaGPyx3xdtNlEw0C0mxqiVKQK2MzO9M930%3D&reserved=0>

―

**Comment by AreYReady** [comment]
ok。
