### ISSUE TITLE
向下滑动关闭的那个触发距离可以自定义么？

### ISSUE THREAD

**Issue by Forevery1** [kongzue/DialogX#99]

**Comment by kongzue** [comment]
暂时不可以，如果紧急需要，可以尝试拉取源代码进行修改打包 aar 使用：
相关代码位于`com.kongzue.dialogx.util.BottomDialogTouchEventInterceptor` 中，滑动触发距离可在 [(BottomDialogTouchEventInterceptor.java:103)](https://github.com/kongzue/DialogX/blob/4d91eb7841abc385a14a17f5dab6eec4e37084c3/DialogX/src/main/java/com/kongzue/dialogx/util/BottomDialogTouchEventInterceptor.java#L103) 修改

**Comment by kongzue** [comment]
暂时关闭了此问题，如有疑问可继续回复
